### ISSUE TITLE
Problem between vsVim and VisualAssist auto close brace

### ISSUE THREAD

**Issue by darkpotpot** [jaredpar/VsVim#1008]
When using vsVim Plugin, there is a problem with VisualAssist autoclose brace feature.

If in visual assist I activate the option advanced/corrections/Insert () and closing } ) ] and put the parameters to "closing brace is inserted after a blank line", there is something weird which is inserted between the brace.

For example, typing :

namespace Foo
{

put a } right after the { (instead of after a blank line) and, on top of that, something weird is inserted between { and }, producing an incorrect syntax.

**Comment by jaredpar** [comment]
Should be fixed by #1509
