### ISSUE TITLE
Support visual selection replacement

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#1020]
Support the `\%V` sequence in the `:substitute` command syntax 

http://vim.wikia.com/wiki/Search_and_replace_in_a_visual_selection

**Comment by chaitanyagurrapu** [comment]
+1. I was just about to request this as well as put the link to the same page. :-)

**Comment by ricksladkey** [comment]
This was implemented in PR #2160 and so this issue can be closed.
