### ISSUE TITLE
Block indentation does not advance to the left properly

### ISSUE THREAD

**Issue by AndrewFalanga** [jaredpar/VsVim#1062]
I did Ctrl-Q and went down to the end of the block that I was editing and pressed '<'.  This character moves the indentation to the left in Vim.  It moved my block to the right.  I tried this a few times to make sure I wasn't tripping on something.  The '>' character does move the block to the right accordingly.

I'm using Visual Studio 2010 Professional and VsVim version 1.3.3.3

**Comment by ricksladkey** [comment]
This works correctly at the head of master and can be closed.
