### ISSUE TITLE
Productivity Power Tools Quick Find/Replace overrides normal mode

### ISSUE THREAD

**Issue by arbrown** [jaredpar/VsVim#1067]
I use the [Productivity Power Tools](http://visualstudiogallery.msdn.microsoft.com/d0d33361-18e2-46c0-8ff2-4adea1e34fef/) extension, and have found that the quick find/replace feature of this extension causes weird behavior with VsVim.  Ideally, I would just use VsVim to search, but I am a creature of habit, so bear with me.

When I search the document (using Ctrl-F and Productivity Power Tools Quick Find) it brings up a small quick search box at the top.  Note that the quick search bar has focus, and VsVim is in normal mode, as indicated by the block cursor in the word "Bulgarian."

![quick search](https://f.cloud.github.com/assets/498727/278116/23bce754-90dd-11e2-9e77-38114cac3a80.png)

If I click out of the quick search box, but do not dismiss it, focus is returned to my VsVim enabled editor window.  VsVim is still in normal mode, and the block cursor has focus, however, as long as the quick find box is still visible (but not focused) VsVim behaves as if it were in insert mode.  The two screenshots below show me having pressed "jjj" to move the cursor down three lines in normal mode.  The first shows the behavior when the quick find box is visible, and the second when I have dismissed it.

![quick search visible but not active](https://f.cloud.github.com/assets/498727/278145/bf501394-90dd-11e2-9d60-1987dbfb325c.png)
Quick search is visible but not active.  VsVim looks like it is in normal mode (as it should be) but text is inserted as if in insert mode.

![quick search dismissed, normal mode behaves properly](https://f.cloud.github.com/assets/498727/278149/eb5a356e-90dd-11e2-96da-d580f8456341.png)
Quick Search has been dismissed from the screen, and VsVim properly behaves as if in normal mode.

This may or may not be related to [Issue 491](https://github.com/jaredpar/VsVim/issues/491) but I thought it was worth writing a new issue for it.  I'd love for this bug to get fixed.  It still throws me for a loop when I think I'm in normal mode and suddenly O's and J's just start appearing on my screen in places I didn't want them to!

Please let me know if there's any way I can help!

**Comment by jaredpar** [comment]
Closing as quick find replace is no longer in power tools. Should work fine with the VS version of the feature.
