### ISSUE TITLE
CTRL-V, paste when searching with /

### ISSUE THREAD

**Issue by laughdat** [jaredpar/VsVim#1069]
For starters, I GREATLY appreciate all the work you've done for this project. I use VsVim daily and thankful for this project.

Awhile ago, issue #623 was opened but it was said it works as designed. The latest update allowed CTRL-V on the executable line, even if Visual Studio was set to handle CTRL-V. I was wondering if there were plans to allow CTRL-V from the search line as well? Or even Shift+Insert would be great.

Thanks again!

**Comment by jaredpar** [comment]
Going to let #623 track as it is now expanded to include this.
