### ISSUE TITLE
jk movement broken in visual mode

### ISSUE THREAD

**Issue by Flawe** [jaredpar/VsVim#1087]
Hi Jared,

I'm on 1.3.3.3 and going into visual mode (shift v) and moving up (k) exits visual mode and moves one line down instead. Going down (j) in visual mode exits visual mode and goes down 3 lines instead.

I think i stumbled upon this before and it was a bad .vimrc before. Here is the current one: https://dl.dropboxusercontent.com/u/285908/.vimrc

extras.vim is empty.

Thanks!

Flav

**Comment by lejboua** [comment]
Hi @jaredpar, I think I'm having the same bug: Visual Studio Community 2013 Version 12.0.31101.00 Update 4 and installed the extension from the Gallery, version 1.8.0.0.

When I hit 'j' or 'k' in Normal mode, it replaces what I have in that line and writes 'creenMovement("j")':
![image](https://cloud.githubusercontent.com/assets/557562/8466036/8f570b16-2046-11e5-9be3-65153245eb4b.png)

In Visual mode the 'j' or 'k' work as expected.

If you need any other detail, please let me know.
Extensions and other details:
Microsoft Visual Studio Community 2013
Version 12.0.31101.00 Update 4
Microsoft .NET Framework
Version 4.5.51650

Installed Version: Professional

Team Explorer for Visual Studio 2013   06177-004-0444002-02937
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06177-004-0444002-02937
Microsoft Visual Basic 2013

Visual C# 2013   06177-004-0444002-02937
Microsoft Visual C# 2013

Visual C++ 2013   06177-004-0444002-02937
Microsoft Visual C++ 2013

Visual F# 2013   06177-004-0444002-02937
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06177-004-0444002-02937
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06177-004-0444002-02937
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   12.4.60425.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Web Apps
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.21010.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.4
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure HDInsight HQL Service   2.0.1000.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.1000.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.3
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.6
Microsoft Azure Tools for Microsoft Visual Studio 2013 - v2.6.30508.1601

NuGet Package Manager   2.8.60318.734
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   12.0.41012.0
Microsoft SQL Server Data Tools

VsVim   1.8.0.0
VsVim is a Vim emulator for Visual Studio

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

**Comment by lejboua** [comment]
Update: My problem was related with my .vimrc. After enabling only the VsVimRc loading, everything working as expected. Thanks for the great extension.
