### ISSUE TITLE
Provide a way to copy word under cursor to build search and replace string

### ISSUE THREAD

**Issue by bradphelan** [jaredpar/VsVim#1099]
Under VIM we can do

```
:nnoremap ;s :%s/\<<C-r><C-w>\>/
```

to enable search and replace of the word under the cursor by pressing `;` key when over a word. However this doesn't work in VSVIM.

**Comment by sqlkoala** [comment]
Btw, it is already possible to do this: you yank into a register and then access this register in the commandline. Should be something like this.
`nnoremap ;s "ryiw:%s/<C-r>r/`

I even used this to build a mapping that searches the current word (in a regex) within my visual studio project :D

**Comment by shmup** [comment]
> Btw, it is already possible to do this: you yank into a register and then access this register in the commandline. Should be something like this. `nnoremap ;s "ryiw:%s/<C-r>r/`
> 
> I even used this to build a mapping that searches the current word (in a regex) within my visual studio project :D

This is what my vimrc uses for similar things, and I will try to adjust to something working from this thread. But I wanted to point out the technique:

```
nnoremap <space>s :'{,'}s/\<<C-r>=expand('<cword>')<cr>\>/
nnoremap <space>% :%s/\<<C-r>=expand('<cword>')<cr>\>/
```

It is a lovely mapping that I use often, hoping a variant here satisfies.
