### ISSUE TITLE
Always show cursor in "ex" command line

### ISSUE THREAD

**Issue by roryokane** [jaredpar/VsVim#1102]
#360 added support for editing the "ex" command line. To move the cursor, you currently have to press the left arrow key once to create a cursor inside the command line's text field, and then you can move the cursor with standard Windows commands.

Instead, the command line text field should always be in focus, and the cursor should always be visible (starting at the end of the field). If someone wants to type or paste text into the end of the command line, they can do that equally well whether there is a cursor at the end of it or not. Keeping the cursor there will save time if the user wants to move it, because they don't have to press Left first. And focusing the command line (which draws a light blue border) will help users remember what mode they are in if they leave the editor and come back.

**Comment by jaredpar** [comment]
After reflection decided to leave as is because it matches the gVim experience.
