### ISSUE TITLE
Setting default clipboard in vimrc not working

### ISSUE THREAD

**Issue by nkrosschell** [jaredpar/VsVim#1105]
In my vimrc I have:

" Set the clipboard to be the default buffer
set clipboard=unnamed

This makes it so that I can use the vi copy and paste commands to move text from VS to other programs. This worked in older versions of VsVim, and it still works in Vim. If I issue the set clipboard-unnamed in studio after it has been opened, then it correctly uses the global clipboard.

I'm running Win7 x64 and VS 2012 Premium Update 2. VsVim 1.4.0.1

**Comment by jaredpar** [comment]
Forgot to close out this bug when I fixed this behavior.  Should be working in the latest source code.

**Comment by nkrosschell** [comment]
Thank you very much. I love this tool.

**Comment by martin-braun** [comment]
@jaredpar I wonder why this behavior is not the default behavior though. The most popular Vim extension for VSCode uses the default clipboard buffer and I could imagine most people would want the same. It would also be nice to have an option for that in the VsVim settings.

I'm curious about the reason for that decision, thank you.

**Comment by jaredpar** [comment]
@martin-braun this can be chosen through the settings today though. If you pick the modern vim profiles in the options, used when you don't have a vimrc, then you get defaults like system clipboard. 

System clipboard though is becoming more and more problematic. The system clipboard is a shared resource and it can be locked by other processes. Had an increasing number of complaints  about "VsVim is slow to type" coming down to using the system clipboard by default and another process on the machine locking it. Gotten enough complaints that I'm trying to find time to effectively detect the lock and disable system clipboard when it happens 😦

**Comment by martin-braun** [comment]
@jaredpar thanks for your reply. I miss the option for the modern profile. Do you mean "Default settings" which can be set to `GVim74`? For me this has no effect, even when there is no `.vimrc`. I also tried `set clipboard=unnamed` but it's not sharing my clipboard as well.

Thanks for sharing the reason for why this is not enabled by default, it makes sense. I have no solution to that either, but it would be nice to at least being able to enable system clipboard. I would appreciate your assistance. Thanks in advance! 🙏🏻
