### ISSUE TITLE
Shift-A doesn't work in visual block mode

### ISSUE THREAD

**Issue by Kazark** [jaredpar/VsVim#1107]
In Vim, when you have some text and want to add some text to the end of every line, you can do this with visual block mode, even if the line endings are jagged (if they don't all end in the same column.)

![initial](https://f.cloud.github.com/assets/3661051/614657/3bafc7f0-ce22-11e2-904b-7399a47f9695.png)

<kbd>CTRL</kbd>-<kbd>V</kbd> <kbd>4</kbd> <kbd>k</kbd> <kbd>$</kbd>

![selected](https://f.cloud.github.com/assets/3661051/614659/3bb4e460-ce22-11e2-8110-7a13a4d0951c.png)

<kbd>SHIFT</kbd>-<kbd>A</kbd> <kbd>"</kbd><kbd> </kbd><kbd>+</kbd><kbd> </kbd><kbd>\</kbd><kbd>ESC</kbd>

![added](https://f.cloud.github.com/assets/3661051/614658/3baff1f8-ce22-11e2-89bc-cf16db6a4e50.png)

This does not work in VsVim 14.0.1. Instead, the visual block stays rectangular (does not select to the jagged edges, the the cursor goes to the end of the current line), and it just makes a "bing" sound when I press <kbd>SHIFT</kbd>-<kbd>A</kbd>. (I would attach a screenshot but my current theme doesn't make selected text show up very clearly.)

**Comment by lebster** [comment]
+1

I am trying to insert some text after every line of a file and it looks like the Shift-A part is failing for me also.

The following is the commands i'm trying.
1) ggVG<C-v>$A 
2) enter appending text
3) hit esc

**Comment by pedrofernandesfilho** [comment]
+1

**Comment by and-rej** [comment]
+1

I'm using a work-around from [here](https://stackoverflow.com/questions/11303032/how-to-add-text-at-the-end-of-each-line-in-vim?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa). You (v)isually select part of the target lines, press ":" to get the range filled in for you, then (s)ubstitute the end of the line ($) with your text.

E.g. if you have this text and your cursor is on the first line:

`aaaa`
`bbbbb`
`cc`

Type "vjj:s/$/123/" and hit enter and you get this:

`aaaa123`
`bbbbb123`
`cc123`

**Comment by ricksladkey** [comment]
I was fixing a bug in block insert and it was easy to add block append, so I included it in PR #2211.
