### ISSUE TITLE
Indenting C# object initializers with = does not work as in regular Vim

### ISSUE THREAD

**Issue by Kazark** [jaredpar/VsVim#1114]
Given this fragmented C# code in Vim:

![initial](https://f.cloud.github.com/assets/3661051/633779/255c8886-d209-11e2-88d8-d3cfa3fc8b32.png)

When I try to reformat the indentation of the object intializer with <kbd>=</kbd>, then I get this result:

![final](https://f.cloud.github.com/assets/3661051/633778/253389d6-d209-11e2-8a6f-ce3173241d6b.png)

However, in VsVim <kbd>=</kbd> does nothing in this case.

**Comment by jaredpar** [comment]
This behavior is "by design". VsVim uses VS's internal formatting rules over Vim's. What you are seeing here is C#'s decision on formatting playing out.
