### ISSUE TITLE
Selection focus changed after Introduce Variable refactoring with Resharper 7/8

### ISSUE THREAD

**Issue by pckujawa** [jaredpar/VsVim#1118]
I am writing VB code and when I do Resharper's Introduce Variable refactoring, the newly-extracted variable declaration has focus and can be changed. Nothing happens when I tab from the type declaration to the name, but once the name has focus, Resharper's renaming boxes disappear and only the declaration is selected (so if I type a different name, the references to it are no longer changed in sync).

This may be happening with other refactorings; I'll post if I notice it. I can't test with older R# versions, but I may be able to pull up some C# code to see if it's just a VB issue. (EDIT: Same issue in R# 8 beta.)

**Comment by jaredpar** [comment]
This should be addressed now. Fixed a number of bugs here.
