### ISSUE TITLE
Ranges with search

### ISSUE THREAD

**Issue by ElliottBignell** [jaredpar/VsVim#1120]
Trying to do a search and replace using vim-style searched ranges, in the general form as shown here, but not restricted to this exact format (i.e. with various combinations of spaces):

:/begin/,/end/s/first/second/g

Error issued: "Invalid range".

Reproducibility: Ineradicable. Absolutely will not work. I can search numeric ranges and bookmarks fine, but not using the "search" range-syntax.

Version: 1.4.0.1

**Comment by jaredpar** [comment]
This behavior is implemented now.  I can't remember the exact change but verified search is supported as a range value now.
