### ISSUE TITLE
Cases again

### ISSUE THREAD

**Issue by ElliottBignell** [jaredpar/VsVim#1121]
Trying to do a search and replace with case-switching, in the general form as shown here, but not restricted to this exact format (i.e. with various combinations of spaces and slashes):

:%s/\([a-z]\)/\U\1/g

Input: "it looks like this"

Result: UiUt UlUoUoUkUs UlUiUkUe UtUhUiUs

Reproducibility: Ineradicable. Absolutely will not work.

Version: 1.4.0.1

I understand that this issue had been raised and closed, but I loaded VsVim today (date of ticket) and it definitely ain't working. Which is a shame, because it's a lovely innovation and eases the pain of having to go back to Windows, and this was the first productive thing I planned to do with it.

**Comment by ricksladkey** [comment]
This was fixed in PR #1478, and so this issue can be closed.
