### ISSUE TITLE
Home key should be "smart" and alternate between hard and soft BOL

### ISSUE THREAD

**Issue by pckujawa** [jaredpar/VsVim#1130]
The normal behavior in VS is that <kbd>Home</kbd> goes to the soft beginning of line (BOL) unless the cursor is already there, in which case it brings you to the hard BOL (all the way left). Then, if the cursor is at hard BOL, hitting Home again brings you to soft BOL and so on.

In my vimrc file, I have

```
set vsvim_useeditordefaults
" Make hard BOL into soft BOL
map 0 ^
```

Neither setting causes the desire Home behavior, unfortunately (although I can use `0` to get to soft BOL if I remember).

**Comment by jaredpar** [comment]
This should now match the vim behavior.
