### ISSUE TITLE
Support highlight

### ISSUE THREAD

**Issue by tomfulton** [jaredpar/VsVim#1132]
I'm wanting to use the following commands in my vimrc file to highlight extra/trailing whitespace:

```
" Highlight EOL whitespace, http://vim.wikia.com/wiki/Highlight_unwanted_spaces
highlight ExtraWhitespace ctermbg=darkred guibg=#ff0000
highlight clear SignColumn

autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$/
autocmd InsertLeave * match ExtraWhitespace /\s\+$/
autocmd InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
```

I'm newish to Vim, so I'm not sure exactly which part isn't working, but I think the highlight command isn't supported as typing the first line gives me a parse error.

**Comment by orand** [comment]
In the meantime you can use Mads Kristensen's [Trailing Whitespace Visualizer](https://visualstudiogallery.msdn.microsoft.com/a204e29b-1778-4dae-affd-209bea658a59).  It also includes a keyboard shortcut to remove trailing whitespace from the current file. Ctrl+K, Ctrl+\

**Comment by tomfulton** [comment]
@orand that's awesome - thanks! :+1:

**Comment by jaredpar** [comment]
Closing as `autocmd` is no longer a goal of VsVim.
