### ISSUE TITLE
Dynamics Ax 2012 code editor

### ISSUE THREAD

**Issue by min2sia** [jaredpar/VsVim#1141]
Hi,
Thanks for the fantastic plugin!

My main development environment is not VS, but another MS product - Dynamics Ax 2012 (MS flagship ERP product). Ax has it's own custom IDE, which embeds VS 10.0 editor as a X++ code editor.

I was wondering if there are any chances to inject VsVim into it (which would be FANTASTIC)?

By examining Ax's bin directory I can see EditorComponents dir with the following:
Microsoft.Dynamics.AX.Editor.CodeRendering.dll
Microsoft.Dynamics.AX.Editor.Intellisense.dll
Microsoft.Dynamics.AX.Editor.XppParser.dll
Microsoft.VisualStudio.CoreUtility.dll
Microsoft.VisualStudio.ExtensibilityHosting.dll
Microsoft.VisualStudio.Language.Intellisense.dll
Microsoft.VisualStudio.Language.StandardClassification.dll
Microsoft.VisualStudio.Platform.VSEditor.dll
Microsoft.VisualStudio.Platform.VSEditor.Interop.dll
Microsoft.VisualStudio.Text.Data.dll
Microsoft.VisualStudio.Text.Internal.dll
Microsoft.VisualStudio.Text.Logic.dll
Microsoft.VisualStudio.Text.UI.dll
Microsoft.VisualStudio.Text.UI.Wpf.dll
Microsoft.VisualStudio.UI.Text.Wpf.KeyProcessor.Implementation.dll
Microsoft.VisualStudio.UI.Undo.Implementation.dll

Thanks!

**Comment by rawdhamab** [comment]
**it works for me thank you**
