### ISSUE TITLE
Anomalous "last operation"

### ISSUE THREAD

**Issue by ElliottBignell** [jaredpar/VsVim#1142]
Select a word and do "ciw". Type `set<Ctrl-R>"`  Now to yield "setWordNow". Proceed to next word using "w" or whatever. Hit "." in the expectation of getting "setNextWordNow". Result: "NowNextWord".

This is inconsistent with my expectations, at least based on other Windows ports. I would expect "last operation" to subsume everything since "ciw". It appears as though VsVim has terminated one operation at the paste and then started a new insert operation rather than treating the "change" as atomic.

**Comment by ricksladkey** [comment]
At the head of master, this behaves the same way in VsVim as it does in vim, i.e. the resulting buffer is:

```
runtest1Now();
runtest1Now();
runtest1Now();
runtest1Now();
runtest1Now();
```

which is not what @ElliottBignell was hoping for, but it is the way vim behaves. In other words, when repeats an insert mode change during which `<C-r>` was used to paste a register, the contents of that register are "baked into" the command that gets repeated.

In any case, there is no longer any bug, so this issue can be closed.
