### ISSUE TITLE
Add support for more regular expression pattern items ( \_x \ze \zs etc)

### ISSUE THREAD

**Issue by jwest591** [jaredpar/VsVim#1150]
It would be great to see the subset of regular expressions expanded.

From gVim
`:help pattern-overview`
lists a lot of options that aren't yet available in VsVim.

In particular it would be useful to be able to use `\ze` and `\zs` in patterns.

Thanks.

**Comment by AppFzx** [comment]
Actually just came here to ask for '\zs'
Awesome that it's implemented!
Anyone know how far Visual Studio extension updates lag behind the newest build?

**Comment by ricksladkey** [comment]
@AppFzx This feature is present in the current version of VsVim 2.6.0. Please give it a try!

**Comment by jayhill** [comment]
It looks like this has only been partially implemented -- only for replace scenarios, not pattern searches.
For example, searching `/foo\zs` should place the caret _after_ the sequence `foo`, but the caret is instead placed at the `f`.
I'll try to take a stab at this in the week or two, but if anyone with more familiarity wants to jump on it, that would be great too.

**Comment by ricksladkey** [comment]
@jayhill Thanks for offering to contribute! Please open a new issue covering the specific use case you described, i.e. the caret position during incremental search and at search completion for patterns containing `\zs` or `\ze`.
