### ISSUE TITLE
Can search but cannot search and replace for multi-line pattern

### ISSUE THREAD

**Issue by Kazark** [jaredpar/VsVim#1155]
I have a C# file with some autogenerated (by ReSharper) properties. I want to convert the getters and setters _en masse_ from throwing exceptions to having a compiler-generated implementation.

I define my search with the `/` command (I have `:set hlsearch` and `:set incsearch`) so I get feedback on whether it works before I try to replace. My search command is:

```
/\n\s\{8\}{\n.*\n.*\n\s\{8\}}
```

which works in Vim:

![aftersearch](https://f.cloud.github.com/assets/3661051/1003748/dc0fcad0-0a93-11e3-98e8-29034a401cdd.png)

and also in VsVim.

I then execute my substitute (replace) command:

```
:%s// { get; set; }
```

which works in Vim:

![substituted](https://f.cloud.github.com/assets/3661051/1003808/feb3c784-0a94-11e3-9e6b-576198d25bde.png)

and fails in an ironic way in VsVim:

![ironic](https://f.cloud.github.com/assets/3661051/1003807/f6cdb07a-0a94-11e3-9d33-08f16f99d3c8.png)

VsVim says it cannot find the pattern, whereas you can clearly see in the background, since `hlsearch` is on, that it has already found the same pattern (thus the `//` in the substitute command) when I used the `/` command shown above.

**Comment by ricksladkey** [comment]
This appears to be caused by `CommonOperations.Substitute` acting on individual lines as opposed to searching for matches in the actual buffer.

**Comment by ricksladkey** [comment]
I just tested this scenario by hand with #2160 and it works!

![image](https://user-images.githubusercontent.com/2680524/40469028-3d2f454e-5efd-11e8-9184-ecb47542b613.png)
