### ISSUE TITLE
VsVim fails to fully parse .vimrc

### ISSUE THREAD

**Issue by ljani** [jaredpar/VsVim#1188]
I'm using [spf13-vim](https://github.com/spf13/spf13-vim) as my vim configuration. I just updated to [this commit](https://github.com/spf13/spf13-vim/commit/28673c047d803d7407b9d29cbf6c4ba0f9e39648) and VsVim now fails to read at least following settings from the `.vimrc` resulting in using tabs instead of spaces and not showing line numbers:

```
set nu                          " Line numbers on
set shiftwidth=4                " Use indents of 4 spaces
set expandtab                   " Tabs are spaces, not tabs
set tabstop=4                   " An indentation every four columns
```

It used to work when I was using an earlier version of `spf13-vim`, but now there seems to be a bug with VsVim parsing the  `.vimrc`, because Vim 7.4 doesn't give any errors. VS2012u3 on Windows 7 x64.

EDIT: typo

**Comment by jaredpar** [comment]
This should be fixed now.
