### ISSUE TITLE
Any Way to turn off auto Visual Mode

### ISSUE THREAD

**Issue by x-xy-y** [jaredpar/VsVim#1231]
Hi. I'm new to this add-on. It is great and works flawlessly most of the time. But I don't like the auto Visual Mode behavior that whenever I select anything, sometimes I just want to stay in insert mode(or normal vs mode). Google says with
  set mouse-=a
or
 set mouse=
the auto Visual Mode, but "mouse" does not seem to be a valid option according to the setting reference. I've tried to add it to _vsvimrc. It do not work at all. So any way to turn off auto Visual Mode? Or disable Visual Mode completely?

**Comment by eruci** [comment]
Recent Amazon Linux update made visual mode the default and none of the methods described on various help forums work.
