### ISSUE TITLE
Some substitution patters disappears from the command history in some circumstances

### ISSUE THREAD

**Issue by poizan42** [jaredpar/VsVim#1241]
Open a file. Select a whole line with VISUAL LINE mode. Now execute:

```
:'<,'>s/\v([0-9]+)/abc
```

It does not matter whether it matched anything or not. Now select a line again, press ':', then up to edit the last command, and then _change_ that to

```
:'<,'>s/\v([0-9]+)1/abc
```

And press enter. Now select a line again, press ':' and up. Now the line showing up in the editor is

```
:'<,'>s/\v([0-9]+)/abc
```
- that is the second command has disappeared. This seems to work for some variations of the regexes, but not others.

**Comment by ricksladkey** [comment]
This works correctly at the head of VsVim master, and so this issue can be closed.
