### ISSUE TITLE
Selecting multiple lines with ctrl+v,I,Tab doesn't convert tabs to spaces

### ISSUE THREAD

**Issue by MaikKlein** [jaredpar/VsVim#1267]
When you hit ctrl+v , I and Tab it doesn't convert tabs to spaces.

For example
```
Line 1
Line 2
Line 3
```
to
```
    Line 1 // here are spaces
    Line 2 // here are tabs
    Line 3 // here are tabs
```

**Comment by SimonGustavsson** [comment]
Keep running into this issue, and doing F#, it's a real issue as TABs are not valid for indentation.
Any news on this? :-)

**Comment by jaredpar** [comment]
@SimonGustavsson I will try and get this into the next release.
