### ISSUE TITLE
Vimscript support

### ISSUE THREAD

**Issue by kri4er** [jaredpar/VsVim#1284]
Hi, first of all, thanks for this amazing addon, it makes life better)
I have VsVim Version 1.5.0.0, and my own vimrc file, where i try to add some function(from wiki), but when i call this function nothing happens, or i got Parse error. Can you give me any suitable example, what i am doing wrong? Sorry for my english. Thanks a lot.

```
 function! InsertTabWrapper(direction)
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<tab>"
    elseif "backward" == a:direction
        return "\<c-p>"
    else
        return "\<c-n>"
    endif
 endfunction
 inoremap \<tab\> \<c-r\>=InsertTabWrapper ("forward")\<cr\>
 inoremap \<s-tab\> \<c-r\>=InsertTabWrapper ("backward")\<cr\>
```

**Comment by jaredpar** [comment]
Closing out as full vim script support is not a goal of this project.
