### ISSUE TITLE
'v' and 'V' should obey the supplied count

### ISSUE THREAD

**Issue by ricksladkey** [jaredpar/VsVim#1336]
In vim, the `v` and `V` commands interpret the supplied count to mean the number of characters/lines to include in the initial selection.

**Comment by jaredpar** [comment]
Couple of notes about this bug I found out experimentally: 

- The count is not a direct count but rather a multiple of the extent of the previous visual selection. Hence if your previous character selection was 2 characters then `2v` will select 4 characters.
- The previous visual selection is not considered if it was canceled via `<Esc>`
- The previous visual selection is global to vim, not specific to a buffer.
- When `v` or `V` is supplied a count then it will take the mode of the previous selection, not the one specified. Example if you last did a visual character mode to yank 3 characters (`v3y`) and then typed `2V`, this would put you into visual character, not visual line. 

The last point is quite simply weird.

**Comment by ricksladkey** [comment]
Thanks, @jaredpar!
