### ISSUE TITLE
viB selects too much

### ISSUE THREAD

**Issue by MartinRykfors** [jaredpar/VsVim#1357]
Start out with the following text:

```
int foo (bar b)
{
    if (true)
    {
        int a;
        int b;
    }
}
```

Position the cursor on the ```int a;``` line and do ```viB```. In gVim, this selects just the two lines inside the if block. In VsVim, this also selects the newline after the ```{```, as well as the whitespace leading up to the ```}```.

**Comment by dshook** [comment]
+1 for this, I was going to report as well.  This also happens using `vi{` which is my preferred way and whether or not your braces are on the same line.

**Comment by MartinRykfors** [comment]
`viB` and `vi{` both behave the same in VsVim and gVim now. One difference that remains is that `ciB` respects indentation in gVim, but VsVim puts the cursor at line start. Should that be a new issue?

**Comment by jaredpar** [comment]
@MartinRykfors yes that should be a new issue.  Should be easy to fix though.
