### ISSUE TITLE
searches with multiline regexes don't find all matches, but do highlight them

### ISSUE THREAD

**Issue by adamtomjack** [jaredpar/VsVim#1365]
When I try to do a regex search with a multiline pattern, it correctly highlights all the multiline matches, but only moves among the single line matches.

I'm using VsVim Version 1.6.0.2

Consider the following HTML fragment:

```
    <tr class="something">
        <td>foo</td>
        <td>bar</td>
        <td>
            baz
        </td>
    </tr>
```

I put my cursor at the beginning of the text and search for

```
    /<\(\w\+\)\_.*<\/\1>
```

I expect it to capture all the tags: the `<tr>` and all three `<td>`s.  It highlights everything, but using "n" to cycle through the matches only gives me the two one-line `<td>` tags.  If you remove those, it will still highlight everything, but will say "Pattern not found".  If you remove the line breaks in the original example, it will find all the tags.

What I really want is "it" and "at" xml tag text-objects.  Lacking those, I'm trying to do a vnoremap that's close, but searching isn't working like I'd expect.  My simple example pattern above wouldn't handle nested tags with the same name, but I would expect it to handle nested tags with different names.

**Comment by ricksladkey** [comment]
I have a fix for this but the PR depends on another PR that hasn't been merged yet.
