### ISSUE TITLE
vsvim adds 0x8D after a autocompleted curly brackets when used together with visual assist

### ISSUE THREAD

**Issue by michalbrzozowski** [jaredpar/VsVim#1390]
I noticed that my struct failed compilation due to the following errors:
C2144: syntax error : 'int' should be preceded by ';'
C4430: missing type specifier - int assumed. Note: C++ does not support default-int

Looking at the code i couldt see anything wrong with the code;

struct Foo
{
  char var;
};

Then i wrote the same struct in notepad and copied it in and it compiled perfectly. 

So i saved the file and opened it in a hex editor and noticed a small difference.

The struct that didn't compile had a extra byte(0x8D) added between the opening bracket and the carriage return + line feed. 
E.g:
0x7B, 0x8D, 0x0D, 0x0A
~~~~~~~^ error

While the correct line not using (auto complete bracket) gave the following:
0x7B, 0x0D, 0x0A

This char does not show up in the editor, so its impossible to find it, without opening the file in a hex editor.

Disabling the vmvim plugin makes autocomplete of brackets work properly again.

Im using visual studio 2012, haven't tried to repro on any other versions.

**Comment by jaredpar** [comment]
This should be fixed with the associated PR.
