### ISSUE TITLE
Macro recording with `q`, `Ctrl+n`, `Ctrl+p` and IntelliSense do not work together

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#1393]
I had following macro to be recorded:
1. go to the first non-whitespace column (`^`)
2. change the complete line (`C`)
3. Enter `UpdateToolBar();`
4. quit macro recording

In step 3 I used IntelliSense to auto complete `UpdateToolBar` and entered the paranthesis and the semicolon manually.

Using the macro inserted `UpdateTool`, not the chosen `UpdateToolBar`!

So I re-recorded the macro using `Ctrl+n`, the Vim auto completion, but the result was not better at all.
With using the macro `UpdateTol` was inserted, instead of `UpdateToolBar`, because I mistyped the character `l` after hitting `Ctrl+n`, used `Back` to delete the mistyped character `l` letting VsVim auto complete to the correct text.

**Comment by dshook** [comment]
+1 for disabling intellisense and auto formatting while recording macros.

**Comment by damianpowell** [comment]
+1 for disabling Intellisense and auto formatting while recording macros.

I had used VsVim on and off for years but the final clincher that made me switch to it was when MS removed macros from Visual Studio. Vim macros are better than VS' old ones anyway, but fighting with Intellisense and auto formatting is a pain.
