### ISSUE TITLE
Switching from Visual to Visual Line moves end of selection

### ISSUE THREAD

**Issue by MartinRykfors** [jaredpar/VsVim#1395]
Start out with a block of text with at least two lines.

Move the cursor to the middle of the first line. Do `vj` to select a bit of both lines. Hit `o` to move the cursor to the beginning of the selection and then do `V` to switch to Visual Line.

In gVim, this results in both lines being selected. In VsVim only the first line is selected. If the `o` part is left out, they both behave the same.

**Comment by jaredpar** [comment]
Bug is in SwitchModeVisual (inside CommandUtil.fs). When switching from visual character to visual line we need to consider the anchor points only, not the caret position.
