### ISSUE TITLE
Handle IME issue with command window

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#1422]
https://twitter.com/gegogi/status/503695138406010880

The underlying bug here is that VsVim is just not handling IME input correctly.  The `IOleCommandTarget` implementation is just handling every IME input as a complete input.  This means the command window eventually holds all of the characters which were a part of the IME sequence instead of the final one.  

The `KeyProcessor` implementation needs to be adjusted to fix this.  It needs to recognize IME sequences via `TextInputStart` and `TextInputUpdate` when building up the command text

**Comment by ricksladkey** [comment]
I think this is probably fixed now that the command margin actually gets the focus.
