### ISSUE TITLE
Assiging Ctrl+A to VsVim should only be valid for editing

### ISSUE THREAD

**Issue by chaitanyagurrapu** [jaredpar/VsVim#1433]
I am a ViEmu user migrating over to VsVim. Before, I could assign ctrl+A to viemu and while editing text, it behaved like vim (i.e incremented the number under the cursor). But I could still copy/paste files under solution explorer using ctrl+A, ctrl+V. 

Assigning ctrl+A to VsVim gives me Vim behavior while editing, but takes away the ability to copy paste in solution explorer. 

I think it would be nice if VsVim let you use the windows ctrl+a / ctrl+v behavior in the solution explorer, or alternately use Vim yank and paste keys (y,p) to copy and paste files in the solution. Or provide an option for the user to pick one or the other.

As it is, if you give Ctrl+A to VsVim, then you seem to end up with no way to copy paste files in the solution explorer.

**Comment by ricksladkey** [comment]
This bug was fixed in PR #2325 and so this issue can be closed.
