### ISSUE TITLE
Cannot insert spaces after latest update

### ISSUE THREAD

**Issue by ghost** [jaredpar/VsVim#1437]
Been using this for awhile in VS 2012 and it's been great!  Thank you.  

After the recent update when I go to insert mode and start typing text when I get to a space and hit the spacebar instead of a space I now get:

pumvisible() ? "\" : "\ "

If I keep hitting space, it keeps adding this command:

pumvisible() ? "\" : "\ "pumvisible() ? "\" : "\ "pumvisible() ? "\" : "\ "

I am using the same .vimrc as earlier versions.  Here are some of my mappings that include pumvisible in it:
""""""""

" auto close omnicomplete options when exiting insert mode
autocmd InsertLeave \* if pumvisible() == 0|pclose|endif
" makes enter select item
inoremap <expr> <CR>    pumvisible() ? "<C-y>" : "<CR>"
inoremap <expr> <Space> pumvisible() ? "<C-y>" : "<Space>"
inoremap <expr> <.> pumvisible() ? "<C-y>" : "<.>"
inoremap <expr> <S-CR>  pumvisible() ? "<C-n><C-y>" : ""
"manual up/down with tab & shift+tab
inoremap <expr> <Tab>   pumvisible() ? "<C-n>" : "<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "<C-p>" : ""
"allows for autoselect of first item in user complete list
inoremap <expr> <C-n> pumvisible() ? '<C-n>' : '<C-n><C-r>=pumvisible() ? "<lt>Down>" : ""<CR>'
"allows autoselect of first item for omni complete
inoremap <expr> <leader>' pumvisible() ? '<C-n>' : '<C-x><C-o><C-n><C-p><C-r>=pumvisible() ? "<lt>Down>" : ""<CR>'
" open omni completion menu closing previous if open and opening new menu without changing the text
inoremap <expr> <C-Space> (pumvisible() ? (col('.') > 1 ? '<Esc>i<Right>' : '<Esc>i') : '') .
            \ '<C-x><C-o><C-r>=pumvisible() ? "<lt>C-n><lt>C-p><lt>Down>" : ""<CR>'
" open user completion menu closing previous if open and opening new menu without changing the text
inoremap <expr> <S-Space> (pumvisible() ? (col('.') > 1 ? '<Esc>i<Right>' : '<Esc>i') : '') .
            \ '<C-x><C-n><C-r>=pumvisible() ? "<lt>C-n><lt>C-p><lt>Down>" : ""<CR>'

""""""""""

Commenting out this shortcut fixes it (but I didn't have to do that in earlier versions of VsVIM):
inoremap <expr> <Space> pumvisible() ? "<C-y>" : "<Space>"

**Comment by jaredpar** [comment]
Closing due to staleness.
