### ISSUE TITLE
Feature request: gn/gN motions

### ISSUE THREAD

**Issue by academician** [jaredpar/VsVim#1449]
I recently learned about a pair of motions that Vim [added in patch 7.3.610](http://ftp.vim.org/vim/patches/7.3/7.3.610) (gn and gN) which reference the last used search pattern. This allows you do do things like "dgn" to delete the next match, or cgn to change the next match. If used on their own, they visually select the next match.

Since many of these types of things can technically be done with ":s", they may not be strictly necessary, but it does seem like it could make some of my editing patterns more efficient.

**Comment by ricksladkey** [comment]
I have a working version of this. I'll submit a PR when I am finished.
