### ISSUE TITLE
"vap" only selects text after cursor

### ISSUE THREAD

**Issue by j201** [jaredpar/VsVim#1456]
`vap` (visual a paragraph) doesn't select the entire paragraph, but only from the cursor to the end of the paragraph.

If the cursor is at the | in

```
foo
b|ar
baz
```

Then pressing `vap` selects the following:

```
foo
b<ar
baz
>
```

Whereas in vim it selects the following:

```
<foo
bar
baz
>
```

(`ip` doesn't work either, but that seems to be tracked by #1332.)

**Comment by jaredpar** [comment]
This is fixed now.
