### ISSUE TITLE
<C-o> in Insert mode

### ISSUE THREAD

**Issue by digitalcosmos** [jaredpar/VsVim#1462]
Typing `<C-o>$` in insert mode moves the cursor before the last character on the current line.
Also, using the `<C-o>A` alternative exhibits weird behavior if you try to exit insert mode with `<Esc>` right after(without typing anything) because it toggles `<C-o>` mode again.

I'm using version 1.7.0.0 on VS 2012 Professional (Update 4)

**Comment by jaredpar** [comment]
This should all be fixed now.
