### ISSUE TITLE
Support multipliers in operator-pending mappings (:omap)

### ISSUE THREAD

**Issue by Kazark** [jaredpar/VsVim#1481]
Given this operator-pending mapping:

```
:omap u t_
```

and given a line like this:

```
public void This_*is_my_NUnit_test_name()
```

where `*` represents the cursor position, when I do `cu`, I get:

```
public void This_*_my_NUnit_test_name()
```

which is correct and expected. Also `du` works as expected. However, when I do `c3u`, starting with the same line, nothing happens, and `d3u` also does not work. In Vim, the result would be

```
public void This_*_test_name()
```

**Comment by ricksladkey** [comment]
I cannot reproduce this at the head of VsVim master. That is to say, the stated repro case works as expected. Perhaps it was fixed at some point in the last four years!

**Comment by ricksladkey** [comment]
This issue is no longer present at the head of VsVim master and so this issue can be closed.
