### ISSUE TITLE
Error: The supplied SnapshotPoint is on an incorrect snapshot [VS2012/1.7.1.1]

### ISSUE THREAD

**Issue by obaterspok** [jaredpar/VsVim#1485]
Since 1.7-ish I've been getting the below error message while editing markups (like aspx pages)
      The supplied SnapshotPoint is on an incorrect snapshot.
      Parameter name: bufferPosition"

It happens rather seldom, perhaps once a week and I see no pattern for why it happens.
Sorry for crappy report :(

**Comment by obaterspok** [comment]
Hello Jared,

Attached is a test case for this bug. I can trigger this very easy with VS
2012 Ultimate.
Open the solution and then Default2.aspx (in the markup editor)

Once the highlighting and errors are shown, then select exactly this:
      <%=TR("HERE YOU CAN SE CRASH", "")%><

using mouse and then hit backspace or delete

Then "SnapshotPoint is on..." error pops up.

-- john

2014-11-08 11:09 GMT+01:00 John Obaterspok <john.obaterspok@gmail.com>:

**Comment by jaredpar** [comment]
@obaterspok where is the attachment at that I can look at?

**Comment by obaterspok** [comment]
It seems github won't let me attach files to a issue. Can I send it
somewhere else?

-- john

2015-02-14 21:20 GMT+01:00 Jared Parsons <notifications@github.com>:
