### ISSUE TITLE
Can't select last character without line break

### ISSUE THREAD

**Issue by visubesy** [jaredpar/VsVim#1507]
Let's say you have the following C# snippet:

```
public interface IWithStatus : IWithStatusGetter
{
    /// <remarks>
    /// Without "new" there is a warning. The alternative solution "IWithStatus :
    /// IWithStatusGetter, IWithStatusSetter" would cause compiler warnings because of ambigious
    /// type references. Disadvantage of this solution: If one *explicitly* implements
    /// IWithStatus.Status, one must also implicitly or explicitly implement
    /// IWithStatusGetter.Status.
    /// </remarks>
    new eStatus Status { get; set; }
}
```

When I visually select (with lower case v) the sentence "Disadvantage of this solution: If one .... IWithStatusGetter.Status.", VsVim (1.7.1.1) also selects the line break (CR LF). This is different from the behaviour of Vim (7.4).

In the example, deleting the visual selection in VsVim with d or x would also delete the line break after "IWithStatusGetter.Status" which is irritating if you only want to delete the sentence itself.

**Comment by visubesy** [comment]
Unfortunately, this problem still exists in VsVim 1.8.0.0.

I manually tested it with the code sample of my initial report. The lines use Windows line endings and the idented lines begin with a single tab if that mattered.

**Comment by jaredpar** [comment]
@visubesy hmm, I'm not seeing that.  I just tried the following on 1.8.0.0:

1. Pasted the sample code into a console application.
2. Put the cursor on the D of Disadvantage.
3. Executed: `v$x`

That deleted the sentence without including the line break.  Is there something you are doing differently here?

**Comment by visubesy** [comment]
@jaredpar v$x works as expected but vjj$x also deletes the line break after "IWithStatusGetter.Status." in VsVim.

**Comment by jaredpar** [comment]
@visubesy interesting.  Will update to support that scenario as well.

**Comment by ricksladkey** [comment]
The root problem here seems to be the setting `:set selection=exclusive`, which is implied by `:behave mswin` and which is the default for all users without an rc file. I believe @jaredpar's daily use environment includes `:set selection=inclusive virtualedit=onemore`.

In any case, with exclusive selection, there are many, many cases where VsVim incorrectly selects the linebreak, which is clearly past the caret.  The simplest example is typing just `v` on an empty line which should result in an empty selection but incorrectly selects the linebreak.

I've fixed these cases in a branch I am working on and will submit it in an upcoming PR.

**Comment by jaredpar** [comment]
> I  believe @jaredpar's daily use environment includes :set selection=inclusive virtualedit=onemore.

I think that is likely the case here. My daily environment usually doesn't have this but I often have local edits when I'm trying to track down bugs that I forget to revert. Probably what was happening here.
