### ISSUE TITLE
On VS 2015, integrate better with Refactoring > Rename tool

### ISSUE THREAD

**Issue by giggio** [jaredpar/VsVim#1515]
When we try to rename a variable (Ctrl+R Ctrl+R) VsVim does not work as expected.
Example:
If the variable name is `variable` and I issue the rename command, and then position the cursor over the `r` letter in `variable` and press `s`, instead of deleting only the letter `r` it deletes everything from the beginning of the work until `r`, leaving me with `iable`. Other commands, like `a` also don't work.

**Comment by jaredpar** [comment]
This is fixed now.
