### ISSUE TITLE
Increment / Decrement Breaks formatting

### ISSUE THREAD

**Issue by mrkanaly** [jaredpar/VsVim#1533]
When using the auto increment / Decrement hotkeys, they can break formatting.

For example, pressing CTRL-a on this statement (cursor on the digit portion):

"enum_val_00"

Results in the following:

"enum_val_1"

Instead of the standard vim behavior of resulting in

"enum_val_01"

The same is observed with using decrement (CTRL-x)

"enum_val_02" -> "enum_val_1"

**Comment by jaredpar** [comment]
Thanks for reporting this issue.  This is a duplicate of #876.
