### ISSUE TITLE
ReSharper rename variable fails when VsVim active

### ISSUE THREAD

**Issue by pramin** [jaredpar/VsVim#1536]
ReSharper 9.0 Update 1
VsVim 1.7.1.1

Given this code:

public void SomeMethod()
{
var myObject = new object();
}

1. Place the cursor on myObject
2. Press F2 (rename in R# IntelliJ keyboard mapping)
3. myObject his redbox highlighted by R#.
4. Typing myNewObjectName does not type over the name as expected (the cursor jumps around depending on what you type :)

Looks like bug #635 is back in ReSharper 9 Update 1

**Comment by jaredpar** [comment]
Thanks for reporting!

This has already been fixed in source and will be a part of the next release.

**Comment by jaredpar** [comment]
Commit 98b4136a39aeac5cf7f7f5c72209 added support for R# 9.0

**Comment by fakhrulhilal** [comment]
I go the same issue as above. Using the same version for R#. Another installed jetbrains product is only DotPeek 1.3 update 1. I'm using the latest version of VsVim as today. I think the actual problem is when VsVim entering in visual mode. I can't do anything when refactoring using R# while VsVim force the mode to visual. I think adding option to disable visual mode when refactoring would be helpful.

**Comment by jaredpar** [comment]
@fakhrulhilal hmm, I wonder if they DotPeek interfaces changed again to be different than the standard live templates.

**Comment by fakhrulhilal** [comment]
I don't think so. I've installed VsVim in two visual studio version, in the community version is working well, but not in pro version. Both two visual studio has update 4, R# v9 update 1 and DotPeek 1.3 update 1, using the latest version VsVim 1.7.1.1. Any idea how to troubleshoot this?

**Comment by jaredpar** [comment]
@fakhrulhilal that is strange.  VsVim 1.7.1.1 has no support for R# 9.0 at all.  I'm surprised it worked in either case.  

I'm actually going to be looking at some R# issues today.  Will test the DotPeek scenario while I am doing that.

**Comment by fakhrulhilal** [comment]
@jaredpar Most used features: moving by line (combined with relative number), visual mode for copy paste certain line, move by word, copy paste and work seamlessly. I've not tested another features. Currently, I disabled VsVim. Perhaps, waiting for this issue until it solved.

**Comment by jaredpar** [comment]
@fakhrulhilal are you using VsVim 1.8.0?

I have my machine with the same setup as yours:

- Visual Studio 2013 Update 4
- ReSharper 9.0 Update 1
- dotPeek 1.3 Update 1

I'm able to rename locals without problem in that setup.  VsVim sees the R# rename and backs off until it completes.  I checked with a few other users and they report that it is working for them as well. 

Note: It's expected that operations like line move, visual selection, etc ... would work prior to 1.8.0.  The particular problem with rename is specific to the rename operation.  The vast majority of other functions don't really have any conflicts with R# (other than the occasional keyboard clash).

**Comment by benrhughes** [comment]
Hi,
I have vsvim 1.8 installed, but this still seems to be occurring. Setup is:

Microsoft Visual Studio Ultimate 2013 Version 12.0.30501.00 Update 2
JetBrains ReSharper Ultimate 2015.1   Build 102.0.20150408.145317
VisualHG   1.1.6 
VsVim   1.8.0.0

Any ideas?

Cheers,

Ben

**Comment by jaredpar** [comment]
@benrhughes 

This is just a temporary issue.  The support for R# 9.0 is present in the latest sources but not the latest release of VsVim.  The next release of VsVim (a week or so away) will contain the fixes. 

Short term you can install the latest build from the Open Gallery and it will have R# 9.0 support.

https://github.com/jaredpar/VsVim/wiki/FAQ#how-can-i-install-a-build-with-the-latest-sources

**Comment by benrhughes** [comment]
Excellent, thanks!

**Comment by BradKnowles** [comment]
I'm experiencing a similar problem, but only in Razor views.  Shall I open a new issue or add to this one?

VS Version 14.0.25123.00 Update 2
VsVim 2.0.1.0
