### ISSUE TITLE
Feature request: filter text through an external program using !

### ISSUE THREAD

**Issue by QuadrupleA** [jaredpar/VsVim#1540]
Recently installed GOW, a nice little directory of precompiled unix utilitites for windows (like awk, sed, sort, wc, etc.). Would be really cool to be able to send text from VsVim to one of those utilities, reading its output back into the file (ala VIM, as described in section 10.9 of its help (usr_11.txt)). 

E.g. do a visual select of some lines of text and sort them using:

:'<,'>!sort

In VsVim I get a "No range allowed" message.

**Comment by jaredpar** [comment]
I agree, this would be a nice feature to add

**Comment by Voxellence** [comment]
Yeah, Python would be another goody for this purpose.
