### ISSUE TITLE
vw selects too much

### ISSUE THREAD

**Issue by Kantis** [jaredpar/VsVim#1541]
Using the sample text:
```
the brown
dog
```

Put cursor at start of 2nd word of first line and use `vwy`. the d character from the following line will be yanked as well. In gVim 7.4 the linebreak is included, but the d character is not.

**Comment by Kantis** [comment]
Seems to be an issue even when not at line end

**Comment by jaredpar** [comment]
I believe what you are seeing here is an effect of the `selection` setting.  

- `inclusive`: this is the default and when set the `'d'` character will be selected.
- `exclusive`: when this is set the `'d'` character will not be selected.  

VsVim mimics the gVim behavior for this scenario.

**Comment by Kantis** [comment]
Thanks @jaredpar. This "issue" came up while I was working on more unit tests for #1538 . I was doing this to attempt setting special marks:
```
Create("the brown dog");
_textView.MoveCaretTo(1);
_vimBuffer.Process("v2wy");
```

I came across this now though, which seems much more appropriate.

```
var visualSelection = VisualSelection.NewCharacter(new CharacterSpan(span), Path.Forward);
_vimTextBuffer.LastVisualSelection = FSharpOption.Create(visualSelection);
_vimBuffer.Process("y");
```
