### ISSUE TITLE
Repeat "." repeats the last step of the macro instead of the whole thing

### ISSUE THREAD

**Issue by FarmerBob** [jaredpar/VsVim#1544]
After recording a macro it's much more convenient to just press "." instead of "@a".  VsVim only repeats the last step of the macro, but vim repeats the whole thing.

**Comment by jaredpar** [comment]
Can you go into a bit more detail here?  Experimentally <kbd>.</kbd> repeats the last action of the macro in gVim, not the macro itself.  

Consider the following macro contents:

```
ia cat<Esc>bdog<Esc>
```

Executes
- Start insert mode
- type "a cat"
- Leave insert mode
- Go back a word
- Execute the change word (<kbd>cw</kbd>) command
- Type dog
- Leave insert mode 

If I run this macro and then immediately type <kbd>.</kbd> gVim will execute the <kbd>cw</kbd> portion only.  If I record this macro and then immediately type <kbd>.</kbd> the same will happen.  

Am I missing a part of the scenario here?

**Comment by FarmerBob** [comment]
You're right.  For some reason I thought I tested vim and saw that it repeated the macro when you press ".", but I now I see that I was wrong.  Vintage in Sublime Text does it, but of course that's not canon.

Oh well, at least at my searching I found that @@ repeats the last macro.  Sorry and thanks for looking into it!

**Comment by jaredpar** [comment]
@FarmerBob No problem.  Glad that it wasn't a bug in VsVim ;)
