### ISSUE TITLE
Interacts badly with R# rename variable refactoring

### ISSUE THREAD

**Issue by Porges** [jaredpar/VsVim#1547]
e.g. I hit Ctrl+R,R, I get this dropdown:

![image](https://cloud.githubusercontent.com/assets/12575/5731613/75403f76-9bea-11e4-9798-f2f291bffbd1.png)

I push arrow-down to get to "metadataPath", then hit Enter, but this just moves the cursor down one line and doesn't select the dropdown item.

**Comment by jaredpar** [comment]
@Porges what version of R# are you using?

**Comment by Porges** [comment]
R# is 9.0 Update 1 Build 9.0.20141219.130142.
VsVIm is 1.7.1.1.

**Comment by jaredpar** [comment]
@Porges 

This behavior is expected at the moment.  Support is present in the VsVim source code for R# 9.0 but it's not in the latest release.  It won't come online until 1.8.0.  I'm hoping to get this drop out this weekend.  

In the mean time though you can grab one of the recent builds off of AppVeyor and it will include the R# 9.0 support.  

https://ci.appveyor.com/project/jaredpar/vsvim/build/artifacts

**Comment by Porges** [comment]
Okay, thanks for the quick response :+1:
