### ISSUE TITLE
Command 's' not working and broke undo system

### ISSUE THREAD

**Issue by learning** [jaredpar/VsVim#1554]
This is my xaml file below,
```
<Page
    x:Class="TipCalculator.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TipCalculator"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="50"></RowDefinition>
            <RowDefinition Height="100"></RowDefinition>
            <RowDefinition Height="*"></RowDefinition>
        </Grid.RowDefinitions>

        <TextBlock Margin="20,0,20,0" Grid.Row="0">Tip Calculator</TextBlock>
    </Grid>
</Page>
```
When I edit it, move the block cursor on the space character between `TextBlock` and `Margin` at line 18, and press `s`, line 18 will change to:
```
<TextBlockargin="20,0,20,0" Grid.Row="0">Tip Calculator</TextBlockargin>
```
And it still at **COMMAND MODE**, not **INSERT MODE**, and **I CAN'T** undo it with `u` or `Ctrl+Z`, if I do that, the code change to:
```
<!-- undo -->
<TextBlockgin="20,0,20,0" Grid.Row="0">Tip Calculator</TeTextBlockargingin>

<!-- undo again -->
<TextBlockn="20,0,20,0" Grid.Row="0">Tip Calculator</TeTeTextBlockargingingin>

<!-- and again -->
<TextBlock"20,0,20,0" Grid.Row="0">Tip Calculator</TeTeTeTextBlockargingingingin>
```

Now the code become more and more unreadable, and it **CANNOT** undo!

After I try a few more times about this, I found one message comes out at the bottom of edit area:

> Undo linked chain broken. Falling back to Visual Studio undo

**Comment by jaredpar** [comment]
@learning 

Thanks for reporting.  I will take a look at this.  I believe this is a bug I've already fixed in the source but isn't present in the most recent release.  Will check.
