### ISSUE TITLE
Repeat last insert operation ('.') loses backspaces unless you don't use a vimrc

### ISSUE THREAD

**Issue by joshcameron** [jaredpar/VsVim#1555]
Type `o` to insert a new line, and type:
bad`<backspace><backspace><backspace>`good`<ESC>`
Then hit `.` to repeat the last operation.

Expected result: another line that says "good".
What I'm seeing: a new line that says "badgood".

If I set "VimRc File Loading" to "No vsvimrc or vimrc" files, the problem goes away. If I use a vsvimrc, even an empty one, the problem happens.

This problem is new as of a recent update (to 1.7.1.1) I did in November 2014. I'm not sure what version I was using before that.

**Comment by MartinRykfors** [comment]
I had the same problem, but Jared provided a way of fixing it in issue #1532. Give it a go and see if it works for you as well!

**Comment by joshcameron** [comment]
Yes. The workaround works. Thanks!
