### ISSUE TITLE
Use % to move between matchpairs of <> (ala HTML, XML)

### ISSUE THREAD

**Issue by jpolfer** [jaredpar/VsVim#1556]
I was using vim 7.4 and I noticed they supported using % to move between matchpairs of < and > in HTML files.

Is there a way to add this feature to VsVim?  It would be helpful when working with HTML and XML.

**Comment by jnothstine** [comment]
This is a duplicate of #1255

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue.  

As @jnothstine reported though this is a duplicate of #1255, going to let that be the primary tracker.
