### ISSUE TITLE
Options menu missing

### ISSUE THREAD

**Issue by lebster** [jaredpar/VsVim#1557]
I cant seem to find the vsvim options menu in tools -> options. I just switched to windows 8.1 and installed VS 2013 update 4 and vsvim. 

![image](https://cloud.githubusercontent.com/assets/914433/6070432/18ff7c00-ad41-11e4-8772-4bf6ddff7ef7.png)

**Comment by jaredpar** [comment]
Huh, I'm not sure how that is possible.  The registration of the Options page is declarative and nearly impossible to break.  I can't imagine how this would happen besides a corrupt piece of data in Visual Studio.

Can you try the following:

> devenv /resetSettings

**Comment by lebster** [comment]
I reset the settings and re-installed vsvim but still no luck. I also tried re-installing gvim to make sure I didn't install the vsvim bundled with it in case that makes any difference.

**Comment by jaredpar** [comment]
@jasonmalinowski can you think of any reason that an Options page wouldn't display?  I'm stumped if resetSettings doesn't fix it.  Should we go to reset user data?

**Comment by lebster** [comment]
It doesn't show up in VS 2012 either. It does show up in VS 2010 though.

**Comment by jasonmalinowski** [comment]
No idea. Do you have any version handling or explicit references to some 10.0 binary that doesn't ship in later versions?

**Comment by jaredpar** [comment]
@jasonmalinowski no.  I can use VsVim on machines with only 2012 or 2013 installed on a regular basis.

**Comment by lebster** [comment]
Is there anyway to modify the options outside of the options menu? I want to make ctrl + d scroll down. Right now it doesn't do anything.

**Comment by jaredpar** [comment]
@lebster try opening a command window and typing the following

> VsVim.Options

To open the command window go to View -> Other Windows -> Command Window

**Comment by lebster** [comment]
Just did a repair with VS 2013 and the options menu is there now! What is weird is that i checked 2012 and the options menu is there too now. Anyways thanks for the help!

**Comment by jaredpar** [comment]
@lebster 

Really glad that worked.  I was drawing a blank on next steps :)
