### ISSUE TITLE
Switched to the dark theme, now incremental search hits are very hard to read

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#1558]
Switching to the dark theme in VS2013 makes all incremental search hits very hard to read.

The default color for the background combined with the not changable light grey foreground color is not a good combination.
Any chances to change the two related "Font and color" settings?

**Comment by jaredpar** [comment]
The incremental search color can be changed by doing the following:

- Tools -> Options -> VsVim
- Item Colors -> Incremental Search

**Comment by MartinLemburg** [comment]
Yes - I know. Second place is "Environment/Fonts and Colors".
But - I only can change the background color, not the foreground/font color. Is this intentionally?

**Comment by jaredpar** [comment]
@MartinLemburg 

Yes.  The design at the moment is to simply highlight the area around the text with a specific color.  The code doesn't attempt to change the text color at all.

**Comment by MartinL0815** [comment]
The horrible is, that the highlighted characters are often colored using a color scheme, too.
So it is really hard to select a usable and useful highlighting color!

No chance for a change?
A change to override the "default" font color by a specific?

**Comment by jaredpar** [comment]
@MartinL0815 

The problem here is the VS theming and color support just make this difficult to implement correctly.  Or really in a definable way.   

Thus far I've kept the support to changing the background only because it has a simple story.  Once theming, overriding defaults, and mimicing existing colors come into play the problem gets quickly untennable.  

Will chat with the editor team and see if there is an easier way of doing this now ...

**Comment by ip** [comment]
Still not fixed in VS2015

**Comment by jaredpar** [comment]
@ip what are you expecting to be fixed?  The search colors can all be individually changed.

**Comment by ip** [comment]
@jaredpar It seems to me that they should change when I switch themes. At the moment, everyone who want to use non-default theme have to fix that manually.

**Comment by jaredpar** [comment]
Closing as VS doesn't really provide a way to do this. Essentially special case a color default by theme. If it existed I'd be happy to do the work here.

**Comment by jnothstine** [comment]
Doesn’t this do the trick?  Settings for colors.

[cid:image001.png@01D38941.59C77600]
