### ISSUE TITLE
Add alternate move cursor commands

### ISSUE THREAD

**Issue by pierremoreau** [jaredpar/VsVim#1565]
See `:help window-move-cursor` for more details.
Some of them have a different behaviour from stated in the documentation, like 1 Ctlr+W Ctrl+L which deletes the current line rather than moving the cursor to one window right of the current one.

(Btw, thanks a ton for this plugin! :+1: )

**Comment by jaredpar** [comment]
Thanks for reporting!

The <kbd>Ctrl+W Ctrl+L</kbd> command is implemented in the vim engine.  The Visual Studio layer is just failing to switch the <kbd>Ctrl+L</kbd> key to VsVim for handling.  Hence it ends up deleting a line when it sees that key stroke.  

Will fix.
