### ISSUE TITLE
$ position is forgotten when moving up and down

### ISSUE THREAD

**Issue by andmatand** [jaredpar/VsVim#1567]
(I'm not sure if this should be considered part of #283 but since that is closed, I thought it might be better to open a new issue)
## Steps to reproduce:
1. Use $ to go to the end of the current line
2. Move up or down (with k or j) to lines of different lengths
## Expected (vim) behavior

The cursor goes to the end of every line, regardless of length
## VsVim behavior

I'm not quite sure what the behavior is, but moving up/down often results in the cursor not being at the end of the line (often even the original line, when the cursor is moved back to that line)

**Comment by jaredpar** [comment]
Thanks for reporting!

That's interesting.  The VsVim implementation is simply remembering the column number when going up and down lines.  It appears that it needs to understand the `$` case separately and always move to the end of the line.

**Comment by jaredpar** [comment]
Turns out this behavior was implemented but it doesn't handle consecutive j or k commands correctly. Have a fix.

**Comment by jaredpar** [comment]
This is fixed now.
