### ISSUE TITLE
Remove whitespace at the end of each line

### ISSUE THREAD

**Issue by e2del** [jaredpar/VsVim#1570]
Tu erase whitespace in vim, i use : 
`:%s/\s\+$//`

But in vsvim, all whitespace are removed but also the the EOL symbol.

It's a bug or may i use a other command to erase whitespace ?

Eddy

**Comment by jaredpar** [comment]
That looks like a bug.  I have a couple of issues with replacing and `$` characters.  There are some odd corner cases that need to be handled.  I will take a look at this.

**Comment by rcorre** [comment]
possibly related:
If I run `/\s\+` the search will get stuck at the end of whatever line I'm on.
However, `/ \+` will progress through the whole file (using a literal whitespace instead of '\s')

**Comment by ricksladkey** [comment]
I have a fix for this and will submit a PR.
