### ISSUE TITLE
Tag parsing does not recognize non alphanumeric characters in tag/attribute names

### ISSUE THREAD

**Issue by leafgarland** [jaredpar/VsVim#1574]
The tag parser fails to handle tag names with `:` and `.`, this is a pain when working with namespaces and Xaml.

I had a quick look at making a fix, [see here](https://github.com/leafgarland/VsVim/commit/803dc0a289c256337be622913f6121d3d172a409), I can put that in a PR if you want. It just adds some extra chars to what is considered a valid name.

Looking at vim's behaviour, I think it parses any characters until whitespace as the tag name and then anything until the closing `>` is skipped. That might be a better fix.

**Comment by jaredpar** [comment]
I'd love it if you sent that along as a PR.

**Comment by jaredpar** [comment]
Closing as PR addressed this.
