### ISSUE TITLE
Feature Request - Show VsVim "Used By" in Keyboard Settings

### ISSUE THREAD

**Issue by flyfishMT** [jaredpar/VsVim#1576]
In the key mappings in Options, VsVim, Key, when you select the dropdown, it tells you what Visual Studio used the keymapping for. Example, Ctrl+F: Visual Studio "Used By Edit.Find".  It would be handy if it showed the same thing for VsVim; Ctrl+F: VsVim "Move forward one full screen"

**Comment by jaredpar** [comment]
Thanks for the request.  

VsVim will fill up that page for both vim commands and user defined key mappings.  In the case of user defined key mappings what would you expect to be displayed?  I was thinking "user defined key mappings".

**Comment by flyfishMT** [comment]
"user defined key mappings" would work for me.  Thanks for the great work.

**Comment by friedroman** [comment]
Maybe to make it even clearer, show the actual mapping command as text, if that is at all possible.
Something like `User defined: "nmap ..."`

**Comment by gwojan** [comment]
I agree with @friedroman, the more information provided the better. I also seem to recall discussion of providing the ability to export the key assignments. That would work for me too.

The one thing I have noticed is there are quite a few mappings that don't show up in the mapping dialog. They are keys that I've assigned to VsVim. The first time I noticed this behavior was when I allowed VS to sync my settings between two different VS installs, however, that might just be coincidence. :wink:

**Comment by jaredpar** [comment]
Decided against this after some thought. In the simple case it's easy to describe what a command maps to. But once you consider key mappings, leaders, modes, etc ... it becomes quite difficult. If done correctly in many cases it would result in 10+ commands per keybindings (think how many commands begin with <kbd>g</kbd> for example). 

Keeping current behavior for now.
