### ISSUE TITLE
M movement takes Outlines into account

### ISSUE THREAD

**Issue by trismarck** [jaredpar/VsVim#1581]
Hello,

when there is a collapsed Outline visible in the current buffer, `M` seems to take the text in the Outline into account when calculating where the middle of the buffer is:

![20150322-vsvim-m movement takes outlines into account](https://cloud.githubusercontent.com/assets/4901124/6767398/7a61974e-d02d-11e4-8174-4f5022756081.png)

Regards.

**Comment by jaredpar** [comment]
Good catch.  Will get that fixed.

**Comment by jaredpar** [comment]
Ha, looks like I knew about this some time ago and forgot to file a bug to track it.

https://github.com/jaredpar/VsVim/blob/master/Src/VimCore/MotionUtil.fs#L2252

**Comment by trismarck** [comment]
Worked, thanks.
