### ISSUE TITLE
Holding the del key crashes VS

### ISSUE THREAD

**Issue by Banger** [jaredpar/VsVim#1584]
In VS2012, while editing xaml files (it does not seem to do it for other files?), if I hold the del key for too long (in my brain "x" and the del key are the same so it might be either), it will sometimes deadlock VS (it becomes unresponsive) and I have no choice but to close and restart it (I have waited many minutes the first times it happened, and even left it overnight once).
It is hard to confirm 100% because after I disabled VSVim it stopped doing it, but it still hasn't done it after I re-enabled VSVim.  I thought I would report it anyway since it is critical and you might see something in the code.

It can't be easily reproduced, it seems to happen after I let my guards down :(
In most cases that I remember I was in "Insert" mode and had just pasted something (that's when I'll get lazy and delete some stuff by holding the del key).
Note that I am developing in 64 bits and so don't have an associated preview of the page.

**Comment by jaredpar** [comment]
Thanks for reporting!

That does seem to be a hard one to track down.  Going to keep trying it to see if I can get it to repo.

**Comment by Banger** [comment]
Update.
It still happens (after I disabled and re-enabled VSVim).  This time though I just deleted 5 characters on one line, moved to another line, typed something, and when I tried to delete it locked up.  So, 2 observations (in the hopes that it helps):
1. A large number of deletes is not necessary
2. I start deleting right after typing.  I.e. I type the replacement text in place then hold delete to remove the previous text.  This is a very typical pattern for me when I use the mouse to position the cursor for editing.

**Comment by jaredpar** [comment]
@Banger is there any chance you can get a stack trace of the exception?  Essentially attach to VS, hit the exception and send me the stack?  I'm still having trouble reproducing this on my machine.  I feel like this will be a relatively easy bug to fix once I can see where the error is.

**Comment by Banger** [comment]
There is no exception, it just hangs.  But Here is the stack if I break the hung VS (I doubt it will help you much though):

 	[Managed to Native Transition]	
>	Microsoft.Expression.DesignHost.dll!Microsoft.Expression.DesignHost.Isolation.Remoting.STAMarshaler.BlockingCall.PumpingWaitAny(System.Threading.WaitHandle[] handles = {System.Threading.WaitHandle[2]}, System.IntPtr[] nativeHandles = {System.IntPtr[2]})	
 	Microsoft.Expression.DesignHost.dll!Microsoft.Expression.DesignHost.Isolation.Remoting.STAMarshaler.BlockingCall.Wait(System.Threading.WaitHandle interrupt, System.Threading.WaitHandle timeoutSignal)	
 	Microsoft.Expression.DesignHost.dll!Microsoft.Expression.DesignHost.Isolation.Remoting.STAMarshaler.WaitForCompletion(Microsoft.Expression.DesignHost.Isolation.Remoting.STAMarshaler.NestedCallContext nestedCallContext, Microsoft.Expression.DesignHost.Isolation.Remoting.STAMarshaler.BlockingCall call = {Microsoft.Expression.DesignHost.Isolation.Remoting.STAMarshaler.BlockingCall}, System.Threading.WaitHandle timeoutSignal)	
 	Microsoft.Expression.DesignHost.dll!Microsoft.Expression.DesignHost.Isolation.Remoting.STAMarshaler.MarshalIn(System.Action action, int targetApartmentId)	
 	Microsoft.Expression.DesignHost.dll!Microsoft.Expression.DesignHost.Isolation.Remoting.ThreadMarshaler.MarshalIn(Microsoft.Expression.DesignHost.Isolation.Remoting.IRemoteObject targetObject, System.Action action)	
 	Microsoft.Expression.DesignHost.dll!Microsoft.Expression.DesignHost.Isolation.Remoting.LocalEvent<Microsoft.Expression.DesignHost.Isolation.Remoting.IRemoteDesignerUndoService,Microsoft.Expression.DesignHost.Isolation.Remoting.IRemoteDesignerUndoServiceCallback,Microsoft.Expression.DesignHost.HostUndoEventArgs>.Invoke(object sender, Microsoft.Expression.DesignHost.HostUndoEventArgs args)	
 	Microsoft.Expression.DesignHost.dll!Microsoft.Expression.DesignHost.Isolation.Remoting.LocalDesignerUndoService.Microsoft.Expression.DesignHost.Isolation.Remoting.IRemoteDesignerUndoServiceCallback.OnUndoUnitOpened(Microsoft.Expression.DesignHost.HostUndoEventArgs args = {Microsoft.Expression.DesignHost.HostUndoEventArgs})	
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage msg)	
 	mscorlib.dll!System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	
 	mscorlib.dll!System.Runtime.Remoting.Lifetime.LeaseSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage msg)	
 	mscorlib.dll!System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage(System.Runtime.Remoting.Messaging.IMessage reqMsg)	
 	mscorlib.dll!System.Runtime.Remoting.Channels.CrossContextChannel.SyncProcessMessageCallback(object[] args)	
 	mscorlib.dll!System.Runtime.Remoting.Channels.ChannelServices.DispatchMessage(System.Runtime.Remoting.Channels.IServerChannelSinkStack sinkStack, System.Runtime.Remoting.Messaging.IMessage msg = {System.Runtime.Remoting.Messaging.MethodCall}, out System.Runtime.Remoting.Messaging.IMessage replyMsg = null)	
 	mscorlib.dll!System.Runtime.Remoting.Channels.DispatchChannelSink.ProcessMessage(System.Runtime.Remoting.Channels.IServerChannelSinkStack sinkStack, System.Runtime.Remoting.Messaging.IMessage requestMsg, System.Runtime.Remoting.Channels.ITransportHeaders requestHeaders, System.IO.Stream requestStream, out System.Runtime.Remoting.Messaging.IMessage responseMsg, out System.Runtime.Remoting.Channels.ITransportHeaders responseHeaders, out System.IO.Stream responseStream)	
 	System.Runtime.Remoting.dll!System.Runtime.Remoting.Channels.BinaryServerFormatterSink.ProcessMessage(System.Runtime.Remoting.Channels.IServerChannelSinkStack sinkStack = {System.Runtime.Remoting.Channels.ServerChannelSinkStack}, System.Runtime.Remoting.Messaging.IMessage requestMsg = {System.Runtime.Remoting.Messaging.MethodCall}, System.Runtime.Remoting.Channels.ITransportHeaders requestHeaders, System.IO.Stream requestStream, out System.Runtime.Remoting.Messaging.IMessage responseMsg = null, out System.Runtime.Remoting.Channels.ITransportHeaders responseHeaders = null, out System.IO.Stream responseStream = null)	
 	System.Runtime.Remoting.dll!System.Runtime.Remoting.Channels.Ipc.IpcServerTransportSink.ServiceRequest(object state)	
 	System.Runtime.Remoting.dll!System.Runtime.Remoting.Channels.SocketHandler.ProcessRequestNow()	
 	System.Runtime.Remoting.dll!System.Runtime.Remoting.Channels.RequestQueue.ProcessNextRequest(System.Runtime.Remoting.Channels.SocketHandler sh)	
 	System.Runtime.Remoting.dll!System.Runtime.Remoting.Channels.SocketHandler.BeginReadMessageCallback(System.IAsyncResult ar)	
 	System.Runtime.Remoting.dll!System.Runtime.Remoting.Channels.Ipc.IpcPort.AsyncFSCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOverlapped)	
 	mscorlib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pOVERLAP)	
 	[Native to Managed Transition]

**Comment by jaredpar** [comment]
Thanks for getting that trace.  It actually does give me a small clue as to what the problem could be.  

I just noticed that you hit this using VS 2012, I've only been testing on VS 2013.  I wonder if there is a bug in the 2012 version of the XAML designer that you are hitting here.  Either way, will try this out on a 2012 machine this weekend to see if I can repro now.

**Comment by jaredpar** [comment]
This appears to be a WPF designer issue. Not a lot I can do about it.
