### ISSUE TITLE
Support Resharper EAP

### ISSUE THREAD

**Issue by d0nk3y** [jaredpar/VsVim#1585]
VsVim isn't recognizing the latest Resharper EAP release.  I'd suggest making the code that identifies Reshaper a bit more lenient to future proof it.  I tried modifying it myself but I haven't been successful in building VsVim for VS 2013.  I don't know if this will actually work, but my first attempt was going to be changing ResharperVersionUtility.cs:27 from

```csharp
internal const string ResharperPlatform6AssemblyName = "JetBrains.Platform.VisualStudio.SinceVs10";
```

to

```csharp
internal const string ResharperPlatform6AssemblyName = "JetBrains.Platform.VisualStudio.SinceVs";
```

Perhaps it should be as short "JetBrains.Platform" though.  When a new version comes out that depends on having a different string, the old one could be made more specific again.

**Comment by jaredpar** [comment]
> I'd suggest making the code that identifies Reshaper a bit more lenient to future proof it.

This is the approach VsVim initially took and it ended up causing a lot of issues.  R# has a tendency to have similarly named DLLs between R#, DotPeek, etc ... The lenient name mapping happily bound to those DLLs and ended up causing VsVim issues.  Additionally, as you can see, they rename their DLLs so often it's hard to keep even a lenient mapping in sync.

Eventually I decided it was better to do more strict matching and just plan on updating more often.  It's annoying but it produces more predictable results.

Which EAP are you using?

**Comment by d0nk3y** [comment]
Ah, that makes sense.  Thanks for the reply!  I'm using R# 9.1 EAP 7.

**Comment by vadimi** [comment]
I'm also using R# 9.1 EAP. They've updated file version of `JetBrains.Platform.VisualStudio.SinceVs10` assembly to `102`. So I ended up changing `ResharperVersionUtility` from `if (version.Major == 6)` to `if (version.Major == 6 || version.Major == 102)`. Works fine so far.

**Comment by jaredpar** [comment]
Looks like the changes to ReSharperVersionUtility have addressed this.
