### ISSUE TITLE
Visual select html tags does not work correctly when attributes has a "-" (dash)

### ISSUE THREAD

**Issue by kwokhou** [jaredpar/VsVim#1590]
The visual select tags feature does not work correctly when there's an attribute that has a "-" (dash).

When my cursor are within the `<tbody>`, pressing "vit" would would trigger the selection of the inner of the whole `<table>` tag, instead of the `<tbody>` tag. 

I notice this only happens if there-s a dash within the tag's attributes, e.g. below, I have a "data-bind" attributes, if I remove that attribute, everything works as expected.

Code samples:
```
<table class="table">
        <tbody data-bind="foreach: items">
            <tr>
                <td class="text-right"> <input class="text-right" /> </td>
                <td class="text-right"> <input class="text-right" /> </td>
            </tr>
        </tbody>
</table>
```

**Comment by jaredpar** [comment]
Thank for reporting. I think that may have gotten fixed in a recent PR. If
not I'll take care of this.

On Thursday, April 9, 2015, Andy Yong <notifications@github.com> wrote:

> The visual select tags feature does not work correctly when there's an
> attribute that has a "-" (dash).
>
> When my cursor are within the <tbody>, pressing "vit" would would trigger
> the selection of the inner of the whole <table> tag, instead of the
> <tbody> tag.
>
> I notice this only happens if there-s a dash within the tag's attributes,
> e.g. below, I have a "data-bind" attributes, if I remove that attribute,
> everything works as expected.
>
> Code samples:
>
> <table class="table">
>         <tbody data-bind="foreach: items">
>             <tr>
>                 <td class="text-right"> <input class="text-right" /> </td>
>                 <td class="text-right"> <input class="text-right" /> </td>
>             </tr>
>         </tbody>
> </table>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaredpar/VsVim/issues/1590>.
>


-- 
Jared Parsons
http://blog.paranoidcoding.com/
http://twitter.com/jaredpar
