### ISSUE TITLE
Build VsVim - Windows XP SP3 - missing System.ServiceModel.Internals - .NET Framework 4.5 | The value "" of the "Project" attribute in element <Import> is invalid.

### ISSUE THREAD

**Issue by trismarck** [jaredpar/VsVim#1591]
Hello,

when building VsVim on Windows XP SP3, the following warning is displayed (along with others and a few errors):

Warning 9   Could not resolve this reference. Could not locate the assembly "System.ServiceModel.Internals". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.    C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets  1360    9   VimCore

According to [this](http://stackoverflow.com/questions/7663199/system-servicemodel-internals-dll-where-does-it-come-from) StackOverflow question, that assembly seems to be part of .NET Framework 4.5, which can't be installed on Windows XP (latest that can be installed is .NET Framework 4.0). I've checked and there is no System.ServiceModel.Internals.dll file c:\WINDOWS\Microsoft.Net\Framework\v4.0.30319\ , gacutil also reports nothing upon doing `gacutil -l System.ServiceModel.Internals`

Windows XP SP3
Visual Studio 2010 SP1 SDK
VsVim 1.8.0.0 from branch 'master' latest as of 2015-04-12
.NET Framework 4.0

Regards.

tags: compile

**Comment by jaredpar** [comment]
That's strange.  That particular assembly should be installed as a part of installing Visual Studio 2010.  Machines with 2010 only are how I generally test my build system changes because it's the easiest scenario to get wrong.  

Does the build still complete even with the warning?  I would expect that it would.  That reference was just added to satisfy an issue with the F# build.  I don't actually depend on that assembly.

**Comment by trismarck** [comment]
No, there are some errors too.

Here are the logs:
Output:

    ------ Build started: Project: VimCore, Configuration: Debug Any CPU ------
    		"C:\VsVim-master\.nuget\nuget.exe" install "C:\VsVim-master\Src\VimCore\packages.config" -source "" -o "C:\VsVim-master\packages"
    		Successfully installed 'EditorUtils2010 1.4.1.0'.
    C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets(1360,9): warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.ServiceModel.Internals". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
    		C:\Program Files\Microsoft F#\v4.0\fsc.exe -o:obj\Debug\Vim.Core.dll -g --debug:full --noframework --define:DEBUG --define:TRACE --optimize- --tailcalls- -r:C:\VsVim-master\packages\EditorUtils2010.1.4.1.0\lib\net40\EditorUtils2010.dll -r:C:\VsVim-master\References\Vs2010\FSharp.Core.dll -r:C:\VsVim-master\References\Vs2010\Microsoft.VisualStudio.CoreUtility.dll -r:C:\VsVim-master\References\Vs2010\Microsoft.VisualStudio.Text.Data.dll -r:C:\VsVim-master\References\Vs2010\Microsoft.VisualStudio.Text.Logic.dll -r:C:\VsVim-master\References\Vs2010\Microsoft.VisualStudio.Text.UI.dll -r:C:\VsVim-master\References\Vs2010\Microsoft.VisualStudio.Text.UI.Wpf.dll -r:"C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\mscorlib.dll" -r:"C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\PresentationCore.dll" -r:"C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\PresentationFramework.dll" -r:C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationUI\v4.0_4.0.0.0__31bf3856ad364e35\PresentationUI.dll -r:C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll -r:"C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.ComponentModel.Composition.dll" -r:"C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Core.dll" -r:"C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.dll" -r:"C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\System.Numerics.dll" -r:"C:\Program Files\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\WindowsBase.dll" --lib:C:\VsVim-master\References\Vs2010,C:\VsVim-master\References\Vs2012,C:\VsVim-master\References\Vs2013 --target:library --warn:3 --warnaserror:76 --vserrors --LCID:1033 --utf8output --fullpaths --flaterrors --standalone "C:\Documents and Settings\ddd\Local Settings\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.fs" Resources.fs Constants.fs VimTrace.fs FSharpUtil.fs StringUtil.fs Util.fs VimKey.fs KeyInput.fsi KeyInput.fs CoreTypes.fs EditorUtil.fs Register.fs VimSettingsInterface.fs Interpreter_Expression.fs CoreInterfaces.fs CoreInternalInterfaces.fs TextUtil.fsi TextUtil.fs CountCapture.fs VimRegexOptions.fs VimRegex.fsi VimRegex.fs MefInterfaces.fs KeyNotationUtil.fsi KeyNotationUtil.fs MotionCapture.fs RegexUtil.fs HistoryUtil.fsi HistoryUtil.fs PatternUtil.fs CommonOperations.fsi CommonOperations.fs Interpreter_Tokens.fs Interpreter_Tokenizer.fsi Interpreter_Tokenizer.fs Interpreter_Parser.fsi Interpreter_Parser.fs Interpreter_Interpreter.fsi Interpreter_Interpreter.fs CommandFactory.fsi CommandFactory.fs Modes_Command_CommandMode.fsi Modes_Command_CommandMode.fs Modes_Normal_NormalMode.fsi Modes_Normal_NormalMode.fs Modes_Insert_InsertMode.fsi Modes_Insert_InsertMode.fs Modes_Visual_ISelectionTracker.fs Modes_Visual_SelectionTracker.fs Modes_Visual_VisualMode.fsi Modes_Visual_VisualMode.fs Modes_Visual_SelectMode.fsi Modes_Visual_SelectMode.fs Modes_SubstituteConfirm_SubstituteConfirmMode.fsi Modes_SubstituteConfirm_SubstituteConfirmMode.fs IncrementalSearch.fsi IncrementalSearch.fs CommandUtil.fsi CommandUtil.fs InsertUtil.fsi InsertUtil.fs Tagger.fsi Tagger.fs SelectionChangeTracker.fsi SelectionChangeTracker.fs FoldManager.fsi FoldManager.fs VimTextBuffer.fsi VimTextBuffer.fs VimBuffer.fsi VimBuffer.fs TextObjectUtil.fsi TextObjectUtil.fs MotionUtil.fsi MotionUtil.fs SearchService.fsi SearchService.fs RegisterMap.fsi RegisterMap.fs ExternalEdit.fs DisabledMode.fs MarkMap.fsi MarkMap.fs MacroRecorder.fsi MacroRecorder.fs KeyMap.fsi KeyMap.fs JumpList.fs VimSettings.fsi VimSettings.fs FileSystem.fs UndoRedoOperations.fsi UndoRedoOperations.fs CommandRunner.fsi CommandRunner.fs WordUtil.fsi WordUtil.fs AutoCommandRunner.fsi AutoCommandRunner.fs Vim.fs StatusUtil.fsi StatusUtil.fs TextChangeTracker.fsi TextChangeTracker.fs LineChangeTracker.fsi LineChangeTracker.fs MefComponents.fsi MefComponents.fs FSharpExtensions.fs AssemblyInfo.fs 
    		VimCore -> C:\VsVim-master\Src\VimCore\bin\Debug\Vim.Core.dll
    ------ Build started: Project: VsInterfaces, Configuration: Debug Any CPU ------
      VsInterfaces -> C:\VsVim-master\Src\VsInterfaces\bin\Debug\Vim.VisualStudio.Interfaces.dll
    ------ Build started: Project: VimWpf, Configuration: Debug Any CPU ------
      All packages listed in packages.config are already installed.
    C:\VsVim-master\Src\VimCore\VimCore.fsproj(54,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
    ------ Build started: Project: Vs2010, Configuration: Debug Any CPU ------
      Vs2010 -> C:\VsVim-master\Src\VsSpecific\Vs2010\bin\Debug\Vim.VisualStudio.Vs2010.dll
    ------ Build started: Project: VimCoreTest, Configuration: Debug Any CPU ------
      Successfully installed 'Moq 4.0.10827'.
      Successfully installed 'xunit 1.9.2'.
      Successfully installed 'xunit.extensions 1.9.2'.
    C:\VsVim-master\Src\VimCore\VimCore.fsproj(54,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
    ------ Build started: Project: VsVimShared, Configuration: Debug Any CPU ------
      All packages listed in packages.config are already installed.
    C:\VsVim-master\Src\VimCore\VimCore.fsproj(54,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
    ------ Build started: Project: VimWpfTest, Configuration: Debug Any CPU ------
      All packages listed in packages.config are already installed.
    C:\VsVim-master\Src\VimCore\VimCore.fsproj(54,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
    ------ Build started: Project: VsVim, Configuration: Debug Any CPU ------
      All packages listed in packages.config are already installed.
    C:\VsVim-master\Src\VimCore\VimCore.fsproj(54,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
    ------ Build started: Project: VsVimSharedTest, Configuration: Debug Any CPU ------
      All packages listed in packages.config are already installed.
    C:\VsVim-master\Src\VimCore\VimCore.fsproj(54,3): error MSB4102: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
    ========== Build: 3 succeeded or up-to-date, 6 failed, 0 skipped ==========
    




Error List:

    Warning	3	The referenced component 'Vs2012' could not be found. 	
    Warning	4	The referenced component 'Vs2013' could not be found. 	
    Warning	15	Could not resolve this reference. Could not locate the assembly "System.ServiceModel.Internals". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.Common.targets	1360	9	VimCore
    Error	1	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VsVim
    Warning	2	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VsVim
    Error	5	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VimCoreTest
    Warning	6	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VimCoreTest
    Error	7	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VsVimSharedTest
    Warning	8	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VsVimSharedTest
    Error	9	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VimWpf
    Warning	10	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VimWpf
    Error	11	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VimWpfTest
    Warning	12	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VimWpfTest
    Error	13	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VsVimShared
    Warning	14	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VsVimShared

MSBuild version:

    Microsoft (R) Build Engine Version 4.0.30319.1
    [Microsoft .NET Framework, Version 4.0.30319.239]
    Copyright (C) Microsoft Corporation 2007. All rights reserved.

Please note that I don't have the experience with C# / F# so there is a pretty high chance that I'm screwing something simple here. Besides of that, using Windows XP is archaic at this point in time.

**Comment by trismarck** [comment]
ok, I've managed to build it, thanks to your post.

So the story is like this: the warning about missing "System.ServiceModel.Internals.dll" file indeed is just a warning and lets the build process to continue. The cause of why the build failed was this error:

    Error	1	The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.	C:\VsVim-master\Src\VimCore\VimCore.fsproj	54	3	VsVim

After looking at the `VimCore.fsproj` file, the error is about `$(FSharpTargetsPath)` variable not being assigned a value. For VS 2010, this condition in the same file seems to trigger:

    <When Condition="'$(VisualStudioVersion)' == '11.0' or '$(VisualStudioVersion)' == '10.0'">
      <PropertyGroup Condition="Exists('$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets')">
        <FSharpTargetsPath>$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets</FSharpTargetsPath>
      </PropertyGroup>
    </When>

Visual Studio 2010 installs F# Runtime 2.0 (vs 3.0) by default. For F# Runtime 2.0, on Windows XP, the correct path to `Microsoft.FSharp.Targets` is: `c:\Program Files\Microsoft F#\v4.0\Microsoft.FSharp.targets`. `c:\Program Files\Microsoft SDKs\F#\` doesn't exist.

After replacing `$(MSBuildExtensionsPath32)\..\Microsoft SDKs\F#\3.0\Framework\v4.0\Microsoft.FSharp.Targets` with `c:\Program Files\Microsoft F#\v4.0\Microsoft.FSharp.targets` in that part of the code, the build process worked. There were still some errors about missing VS2012 dll file, but the `VsVim.vsix` file was successfully generated.

Thanks.

**Comment by jaredpar** [comment]
This project recently changed to require VS2017 to build the source tree. This bug won't repro with VS2017 installed. As such closing.
