### ISSUE TITLE
Repeating with "." is inaccurate for an insertion including a "."

### ISSUE THREAD

**Issue by jtomola** [jaredpar/VsVim#1592]
If I attempt to repeat an insertion that includes a period, only the text following the period will be inserted.

For example, if I insert "12345.6789" and then repeat it, only "6789" will actually be inserted.

**Comment by jaredpar** [comment]
@jtomola thanks for reporting.  I will look into that.

**Comment by ricksladkey** [comment]
This was fixed in PR #2230.
