### ISSUE TITLE
VC++: gd doesn't go to definition

### ISSUE THREAD

**Issue by obaterspok** [jaredpar/VsVim#1594]
I would expect gd to do the same as F12. Now it seems to do a find symbol.
For c# this works as it should.

**Comment by obaterspok** [comment]
Then perhaps gD could go to declaration (ctrl+f12)

**Comment by jaredpar** [comment]
Can you give an example where the behavior differs?

**Comment by obaterspok** [comment]
*> "**example where the behavior differs"*

What behavior are you referring to?

If I have a
     foo->bar();

and do a gd or gD on bar then some type of Find Symbol action occurs where
all possible bar() methods are listed from many files in my project.

-- john


2015-04-23 22:26 GMT+02:00 Jared Parsons <notifications@github.com>:

**Comment by jaredpar** [comment]
> What behavior are you referring to?

Essentially a case where VsVim and <kbd>gD<kbd> have one behavior and <kbd>F12</kbd> has another where everything else is the same.  The C++ implementation of go to def is significantly more complex than the C# one.  Having a repro for the difference is what will help me track down the problem / fix.
