### ISSUE TITLE
Issue loading VsVim solution in VS2013

### ISSUE THREAD

**Issue by gwojan** [jaredpar/VsVim#1597]
I was going to try and build the latest code locally and when VS2013 tries to convert the project files I get the following error in the Migration Report:

`Src\VsVim\VsVim.csproj: The application which this project type is based on was not found.`

**Comment by jaredpar** [comment]
@gwojan have you installed the VS SDK?  That is required to load / build VsVim.

**Comment by jaredpar** [comment]
Closing as development of VsVim now requires VS2017.
