### ISSUE TITLE
why i cannot find vsvim in tools>extensions and updates?

### ISSUE THREAD

**Issue by chapgaga** [jaredpar/VsVim#1598]
i know it is installed, but why i cannot find vsvim in tools> extensions and updates, i think all vs extension should be there , why not vsvim?
btw, i am using vs 2013

**Comment by tmajest** [comment]
Be sure to select the 'Online' tab before you search.  Otherwise, you'll be searching in the 'Installed' tab and you won't be able to find it.

**Comment by jaredpar** [comment]
@chapgaga it should be listed under the Installed tab of the `Extensions and Updates` dialog box.  Note that if you have a lot of extensions installed it won't appear on the first page.  There is a pagination tool at the bottom of the page that will go to later pages.  Do you see it now?
