### ISSUE TITLE
VS2015 RC appears to break "gt" tab switching

### ISSUE THREAD

**Issue by iandimayuga** [jaredpar/VsVim#1601]
In Visual Studio 2015 RC, `gt` does not switch tabs as expected.
It still works fine in VS2013.

**Comment by jaredpar** [comment]
Thanks for reporting.  This should be fixed when I merge the VS2015 branch back into master.  This will be a part of the next release.

**Comment by jaredpar** [comment]
This is fixed now in the master branch.

**Comment by orlandow** [comment]
still not working in v2.0.0.0

**Comment by mahinshaw** [comment]
Just updated.  I "g{t,T}" no longer works for me either.  Using VS 2013

**Comment by jaredpar** [comment]
Heard a couple of reports about this.  Going to debug into it tonight and see what is going on.

**Comment by jaredpar** [comment]
Yeah this is a regression in my deployment and build step.  I will get a fix out for this tomorrow in the AM.

**Comment by jaredpar** [comment]
This should be fixed now in the 2.0.1 release.

**Comment by mahinshaw** [comment]
Just updated.  Works great.  Thanks!
