### ISSUE TITLE
Cursor unresponsive when Source Control > Annotate enabled

### ISSUE THREAD

**Issue by patrickdillon** [jaredpar/VsVim#1605]
Using Visual Studio 2013. When I enable Source Control > Annotate the cursor becomes unresponsive. I can't even CTRL + SHIFT + F12 to disable VsVim. Closing the annotated tab returns everything to normal. 

This is not a big deal for me. I rarely use annotate. I'm just reporting in case it is helpful.

**Comment by jaredpar** [comment]
Interesting.  I will try that out and see if I can figure out what is going on here.

**Comment by jaredpar** [comment]
I tested this out today with a mix of F# and C# code base on a Git repo and was unable to reproduce the problem.  I turned on annotations for a couple of files navigated around in them and the none annotated files and everything worked as expected.  Moving around in the annotated file was a bit slower but it was functional.

Can you give me a bit more information about your setup?

**Comment by patrickdillon** [comment]
I just tested on my home setup, which is Windows 8, and had the same problem. My work computer is Windows 7 and that is where I had the problem originally. 

Let me know which info would be most helpful. Originally I had resharper installed but removed it. Here is a copy of the About VS from my home computer:

Microsoft Visual Studio Professional 2013
Version 12.0.30723.00 Update 3
Microsoft .NET Framework
Version 4.5.51641

Installed Version: Professional

Team Explorer for Visual Studio 2013   06177-004-0446025-02573
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06177-004-0446025-02573
Microsoft Visual Basic 2013

Visual C# 2013   06177-004-0446025-02573
Microsoft Visual C# 2013

Visual C++ 2013   06177-004-0446025-02573
Microsoft Visual C++ 2013

Visual F# 2013   06177-004-0446025-02573
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06177-004-0446025-02573
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Windows Phone SDK 8.0 - ENU   06177-004-0446025-02573
Windows Phone SDK 8.0 - ENU

ASP.NET and Web Tools   12.3.50717.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Websites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.20703.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.2
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Mobile Services Tools   1.2
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.4
Microsoft Azure Tools for Microsoft Visual Studio 2013 - v2.4.20730.1601

NuGet Package Manager   2.8.50313.46
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PowerShell Tools   1.2
Provides file classification services using PowerShell

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   12.0.40403.0
Microsoft SQL Server Data Tools

Telerik ASP.NET AJAX VSExtensions   2014.2.707.0
Telerik UI for ASP.NET AJAX VSExtensions

Telerik ASP.NET MVC VSExtensions   2014.6.1305.0
Telerik UI for ASP.NET MVC VSExtensions

VsVim   1.7.1.1
VsVim is a Vim emulator for Visual Studio

Windows Azure Tools   2.2
Windows Azure Tools for Microsoft Visual Studio 2013 - v2.2.11003.1601

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.
