### ISSUE TITLE
"Invalid Range" when using :t/:copy Ex command and pattern match /match/ or ?match?

### ISSUE THREAD

**Issue by Chris-E-J-Ellis** [jaredpar/VsVim#1608]
If I have some example text:

```
aLine

[cursor]

anotherLine
```

I'm trying to use a command of the form **:/another/t.** to copy the next matching line to the current cursor location (or changing . to the required address.) Currently this will result in an "Invalid range" error.

If I condense the command to **:/another/t** (not specifying a copyto address) I get the error "Invalid address" which is expected, but specifying the address again results in the "Invalid range" error.

**Comment by jaredpar** [comment]
Thanks for reporting. 

Looks like I'm just not handling that particular case well.  Need to fix it.

**Comment by Chris-E-J-Ellis** [comment]
Great, thanks! This is by far my favourite Visual Studio extension; thanks for the great work.

**Comment by ricksladkey** [comment]
All the pattern line specifiers are unimplemented. I'll take a look at this.
