### ISSUE TITLE
"Pattern not found" while matched text is highlighted

### ISSUE THREAD

**Issue by obaterspok** [jaredpar/VsVim#1611]
If you have a text file with this:
/******************************************************************************
- $Header: /SrcRoot/...
  *
  */

Then search for \/**._\n\s_*\s*$Header and it will say "Pattern not found" while the matched text is still highlighted. Substitute won't work either.

**Comment by jaredpar** [comment]
Thanks for reporting.  

I think this is related to the other issues I have about matching `$` in certain cases.  Hopefully it can just be merged into those.

**Comment by obaterspok** [comment]
Absolutely, I just wasn't aware of those.

2015-05-13 22:13 GMT+02:00 Jared Parsons <notifications@github.com>:

**Comment by rkhoury** [comment]
Hey @jaredpar 
I have a similar issue but not related to using '$' in the regex.
I have a search pattern:
/\(\w\+\)::\1
Which was matching simple c++ constructors, and this seems to work fine searching in the forwards direction, but the moment I press N (reverse search) it says Pattern no found (when there are highlighted matches above the cursor's current position).
If this is not the same issue I can make a new one.

Thanks.
