### ISSUE TITLE
VsVim always yanks at least 1 char from last line in visual mode

### ISSUE THREAD

**Issue by ecsousa** [jaredpar/VsVim#1612]
When you yank text in Visual Mode, VsVim always gets at least 1 char from last line. For instance, if you have the code:

```
{
    line1;
    line2;
}
```

If you are at the first beginning, and executes the following key strokes: `vjjjyP`, in VsVim you will get the following result (notice an extra space at 4th line):

```
{
    line1;
    line2;
 {
    line1;
    line2;
}
```

While Vim gives you:

```
{
    line1;
    line2;
{
    line1;
    line2;
}
```

**Comment by ricksladkey** [comment]
This bug was fixed in PR #2269.
