### ISSUE TITLE
Replace mode backspace doesn't work like Vim

### ISSUE THREAD

**Issue by jankner** [jaredpar/VsVim#1613]
Backspace in replace mode should "undo" replacing characters rather than removing characters.

For example, entering replace mode, typing one character, then typing a backspace should have no effect. In VsVim it has the effect of removing one character.

**Comment by jaredpar** [comment]
Thanks for reporting.  This looks like a duplicate of #653 though.

**Comment by jankner** [comment]
Oh, you're right. I don't know how i missed that.

**Comment by jaredpar** [comment]
It can be easy to miss in the search.
