### ISSUE TITLE
Block indentation doesn't work like Vim

### ISSUE THREAD

**Issue by ri-aje** [jaredpar/VsVim#1614]
>i} command in Vim indent the content within a {} block, excluding the closest enclosing {} though. the same command in VsVim also indents the enclosing {} pair, which is what >a} does in Vim. Moveover, >a} in VsVim has the same behavior as >i}. Please make >i} behavior identical as Vim.

**Comment by ChrisMiskowiec** [comment]
This is working correctly for me in VS 2013 and VsVim 1.8.0.0. (&gt;i} indents only contents and not braces, &gt;a} indents contents + braces)

**Comment by ri-aje** [comment]
just tried, worked for me as well. looks like it has been fixed?

**Comment by jaredpar** [comment]
@ri-aje it's possible as I recently fixed a few other bugs in this area.  Will look into coding up a unit test to verify this.

**Comment by jaredpar** [comment]
Hmm, can you all provide a code sample where this behavior was seen?  Want to make sure I craft a good test here.

**Comment by ri-aje** [comment]
1. copy paste the following into vim/vsvim.
if (condition)
{
statement;
}

2. place cursor on the statement line.

3. in command mode, type >i}
in vim, I get the following. note my tab == one space, so it may not be that obvious.
if (condition)
{
 statement;
}

in vsvim, I got
if (condition)
 {
 statement;
 }

note three consecutive lines right after if are all indented.
note that this is not the current behavior of vsvim as of 07/10/2015, but I remember it was this way when I opened the bug.

**Comment by ri-aje** [comment]
markdown messed up the format, so I am uploading a picture to show exactly what I want. I also increased my tab width to 4 to make it easier to see the effects.
![untitled](https://cloud.githubusercontent.com/assets/321429/8630738/69620bca-271e-11e5-846a-b00ec963493f.png)

**Comment by jaredpar** [comment]
@ri-aje I added some explicit code markers to your first comment and it seems to have fixed the formatting to show the problem.  The issue is pretty clear now.  Thanks for adding the sample!
