### ISSUE TITLE
ci" goes too far with C# literal strings

### ISSUE THREAD

**Issue by jasonmalinowski** [jaredpar/VsVim#1616]
Copy this into a C# buffer:

    string blah = string.Concat(@"hello\", "world");

Place your caret on hello, and ci". Observe it eats the " and the comma between the arguments.

**Comment by jaredpar** [comment]
This behavior appears to be By Design.  gVim proper has the same behavior of treating the escaped `"` value as a non-quote for the purposes of strings.

**Comment by jaredpar** [comment]
The root issue here is the `quoteescape` setting.  By default it treats `\"` as a quote escape.  If you want you could push on me to support that.  Wouldn't be too terrible.
