### ISSUE TITLE
C should not affect P

### ISSUE THREAD

**Issue by zanqi** [jaredpar/VsVim#1618]
If I do a CC to change a line, that line will currently go into the vim clipboard, causing my next P to put that line back in. This is different from standard Vim right?

I expect C is just change, not yank and change.

How do I resolve this?

**Comment by jaredpar** [comment]
@zanqi this is the standard vim behavior.  From `help cc`

```
Delete [count] lines [into register x] and start insert linewise
```

The way to work around this is to tell `cc` to put the deleted contents into the black hole register.

```
"_cc
```
