### ISSUE TITLE
Link to VS 2015 RC SDK - Its migration report gives the wrong link

### ISSUE THREAD

**Issue by darlingm** [jaredpar/VsVim#1619]
This ultimately isn't a VsVim error, but a link to the VS 2015 RC SDK could be helpful in the readme - the right link is http://go.microsoft.com/fwlink/?LinkId=517034

This is because VS 2015 RC's "Migration Report" is helpful to say a required package is needed, and gives you the link to the VS 2013 SDK, but nowhere does the link say it's only for 2013.  So, you install it, and if you're going fast through the installer, you miss it's for 2013.  Then you're confused why it still gives the error.

Without the SDK, most everything builds, but the VsVim project isn't included.  This means there's no "Src\VsVim\bin" directory with the VsVim.vsix file you need to install the extension.

(I did read the directions -- this time -- but thought I already had the SDK installed!)

**Comment by ricksladkey** [comment]
This issue is obsolete because VS2017 is now required to do VsVim development and so this issue can be closed.
