### ISSUE TITLE
Ctrl+ww switching between panes

### ISSUE THREAD

**Issue by aikeru** [jaredpar/VsVim#1623]
In vim if I do a `:vsplit`, I can switch between splits using `<C-ww>`. I think it would be great if VsVim could implement this functionality too!

**Comment by chaitanyagurrapu** [comment]
+1 for this feature.

**Comment by knatten** [comment]
Related: https://github.com/jaredpar/VsVim/issues/625

**Comment by sakari369** [comment]
+1 from here too.
