### ISSUE TITLE
Visual selection with mouse causes flickering and over-selection

### ISSUE THREAD

**Issue by debuuu** [jaredpar/VsVim#1628]
I'm currently using Visual Studio 2013 (12.0.31101.00 Update 4), and sometimes (quite often in fact) when editing larger files, if I select text with the mouse (which causes then displays Visual mode in the Vim status bar), the selection jumps as I move downwards and selects text underneath the mouse cursor. 

This only happens when dragging _down_, not up, and only happens during movement; if I stop moving the mouse the selection remains - but that means you might have a selection that includes text below the mouse cursor (for a downward drag selection). 

I searched the issues for something similar, but couldn't find anything listed. Apologies if this issue already exists!

**Comment by jaredpar** [comment]
@debuuu thanks for reporting.  I will take a look at that.  

In general with drag selection Visual Studio does most of the work.  VsVim just monitors the changes to adjust some internal state.  It's possible though that a bug is causing it to interfere here.  I will take a look at that.

**Comment by debuuu** [comment]
Thanks for the fast reply! I'm able to reproduce the issue pretty easily, so let me know if there's anything else I can do to help.

**Comment by Cakez0r** [comment]
Hi @jaredpar, I have this bug too. I am using visual studio 2013 professional, update 4 and can confirm that selection behaviour does return to normal if I disable VsVim. I recorded a gif of how selection behaves for me (see below). The position of the line on the screen seems to affect how erratic the overselection is. If I click on a line near the top of the page, then the selection goes nuts. As the line moves closer towards the center of the screen, it seems to behave less erratically. Let me know if you'd like any more information.

![Selection](https://i.imgur.com/Y98EgqU.gif)

**Comment by Cakez0r** [comment]
After doing some more investigation, this issue is caused by having 

    set so=7

in my .vimrc file (http://vim.wikia.com/wiki/Keep_your_cursor_centered_vertically_on_the_screen)

I guess there is still some bug here with the over selection, but the issue is resolved for me after removing this particular config entry.

**Comment by debuuu** [comment]
Stupid question: where is the .vimrc file? I know once before, when I installed Vim on a Windows machine, that I had a .vimrc file in My Documents, but I don't right now (as I don't have Vim installed). Does VsVim have its own .vimrc? 

I also just tried doing :set so=0 direction in VS, but, 1) I'm not sure if setting it inside VS would do anything, and 2) you said you removed the line, so maybe setting it to 0 wouldn't help anyway.

**Comment by Cakez0r** [comment]
My .vimrc was in %USERPROFILE%, but it could be in any one of these places
http://vim.wikia.com/wiki/Open_vimrc_file

On 11 August 2015 at 13:47, debuuu <notifications@github.com> wrote:

> Stupid question: where is the .vimrc file? I know once before, when I
> installed Vim on a Windows machine, that I had a .vimrc file in My
> Documents, but I don't right now (as I don't have Vim installed). Does
> VsVim have its own .vimrc?
>
> I also just tried doing :set so=0 direction in VS, but, 1) I'm not sure if
> setting it inside VS would do anything, and 2) you said you removed the
> line, so maybe setting it to 0 wouldn't help anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jaredpar/VsVim/issues/1628#issuecomment-129860097>.
>



-- 
Lewis

**Comment by jaredpar** [comment]
@Cakez0r thanks for the GIF explanation of the problem.  This being affected by the `so` setting makes sense.  I likely need to account for that in the selection update logic.

**Comment by jhamm** [comment]
Do you have the Extension "Productivity Power Tools" installed with the option for "Syntactic Line Compression" enabled? This shrinks lines that do not have a number or character by 25%.

When I have this enabled, the over-selection happens. When this is disabled, this behavior does not appear to happen. This will happen whether the "scrolloff" is set to 7 or 0. 

I was able to see this behavior in VS2013 and VS2015.

**Comment by debuuu** [comment]
Thanks for the tip @jhamm, I checked, but I don't have Productivity Power Tools installed. In fact I have very few plugins, only: RelativeLineNumbers, Visual Assist, and Recode. It can't be Recode or RelativeLineNumbers, because I had the problem before installing both. Will dig through the VIsual Assist settings I guess. Thanks for the idea anyway!

**Comment by jhamm** [comment]
You are right this doesn't have anything to do with any other extensions. I disabled all extensions except VsVim and was able to get this to happen consistently.

Repro steps: 
* (Start Visual Studio or start debugging Visual Studio Hive instance on the VsVim project)
* :set so=7   ' or have it in the _vsvimrc
* wait about 1 minute
* Test Case 1) open Test\VimCoreTest\CommandRunnerTest.cs
  * on line 23 where the Create(KeyRemapMode, params string[]), click on the space between private and void, the drag down but not far enough to cause the screen offset to start to scroll. Sometimes it takes a while and you may need to select most of the method. If this doesn't work, try with the private void Create(params string[]) method on line 18.
* Test Case 2) open Src\VimCore\SelectionChangeTracker.fs
  * on line 212 in the AdjustSelectionToCaret() method, click on the blank line above the match, then drag down. 
* There are probably others, but these were 2 I found that were pretty easy to cause the repro.

There was an issue in the SelectionChangeTracker. I am putting a PR together for the fix.

**Comment by debuuu** [comment]
Oh awesome, you submitted a fix already! Hopefully gets merged soon. :+1:

**Comment by kellyelton** [comment]
Yeah this has been an issue for a long time for me, I was just coming here to try and get to the bottom of it. I'm glad that there's active progress going on to fix this.

**Comment by jhamm** [comment]
@jaredpar Can you review this PR?
