### ISSUE TITLE
Disable Intellisense and auto formatting during macro recording

### ISSUE THREAD

**Issue by damianpowell** [jaredpar/VsVim#1629]
In issue #1393 Jared mentioned that it might be a good idea to disable Intellisense while recording Vim macros. I would very much like to see that! VsVim became my main editor when Visual Studio's own macros were removed. I prefer the Vim macro solution anyway, but it is often complicated by Visual Studio's Intellisense and auto formatting.

**Comment by jaredpar** [comment]
This is something I definitely would like to implement.  Part of the problem has been that it wasn't really feasible to disable intellisense + auto formatting.  It can be done in some languages but not all and plugins like R# complicate things a bit since they have their own implementations.  

I think I should start work on this though, at least as an experiment, to see how well it would work out in practice.  If I could at least get mainline scenarios working it would be a big improvement.

**Comment by damianpowell** [comment]
Fabulous! Thanks, Jared.

**Comment by fredizzimo** [comment]
One thing that I will probably try, is to add a similar option for macros as I did for normal dot repetitions here https://github.com/jaredpar/VsVim/pull/1552.

This would support using intellisense completion during the macro playback. However the auto formatting might still be a problem.

**Comment by cchamberlain** [comment]
This feature would be huge for me in C# (using R#).  I would use VS for a lot more of my general editing if it supported macros better than the alternatives (WebStorm does a pretty good job with them, zero support in Atom).

**Comment by jaredpar** [comment]
Just sent a PR to implement this behavior.  It's still a bit on the experimental side but playing around with it locally it seems to work well.

For now the clean macro recording behavior is off by default.  It is a bit of a behavior change and I suspect some will be a bit surprised if they accidentally trigger macro recording (i do it at least twice a day) and suddenly a lot of Visual Studio features stop working. May revisit this decision in a future release though.  

This behavior, dubbed Clean Macros, can be enabled through the Options page or by adding the following to your vsvimrc file:

```
set vsvim_cleanmacros
```

**Comment by cchamberlain** [comment]
Awesome!

**Comment by bradphelan** [comment]
This setting only works with visual studio intellisense but not resharper intellisense :(

**Comment by christianrondeau** [comment]
I second this; ReSharper does not play very nice with VsVim (e.g. <kbd>.</kbd> to repeat commands), but really macro recording is just not working most of the time; I'm usually switching to gVim to do macros of any kind, but multi-files macro become very difficult to do.

I see there was a discussion on this a few years back with JetBrains: https://resharper-support.jetbrains.com/hc/en-us/community/posts/206657885-Detecting-and-dismissing-Intellisense-from-an-extension - I was wondering if you finally found a way to disable ReSharper completely during macros, OR to actually replay ReSharper actions?
