### ISSUE TITLE
Command-Line mode not working correctly when cursor is in XML Doc Comments

### ISSUE THREAD

**Issue by ChrisMiskowiec** [jaredpar/VsVim#1632]
When entering command-line mode while text cursor is inside an XML Documentation Comment block, pressing enter will cause a new line instead of executing the command.

For example, using the following code sample:

``` c#
/// <summary>
/// Does stuff
/// </summary>
private void Foo()
{
}
```
1. In normal mode, move cursor over "D" in "Does stuff".
2. Type ":w&lt;CR&gt;".
3. Observe new line is created in comment block, file is not saved, and still in command-line mode.

**Comment by jaredpar** [comment]
Thanks for reporting! 

Do you have any other extensions installed on VS?  ReSharper for example?

**Comment by ChrisMiskowiec** [comment]
Nothing AFAIK that would be hijacking keystrokes. 

Here is my full list of extensions:

* .NET Memory Profiler
* Application Insights Tools for Visual Studio
* Behaviors SDK (XAML)
* Code Contracts Tools
* Microsoft Advertising pubCenter Service for Visual Studio
* Microsoft Advertising SDK for Windows 8.1
* Microsoft Advertising SDK for Windows Phone 8.1 XAML
* Microsoft ASP.NET and Web Tools
* Microsoft Visual Studio ASP.NET MVC 5 Scaffolding
* NuGet Package Manager for Visual Studio 2013
* PowerShell Tools for Visual Studio 2013
* Productivity Power Tools 2013
* ReAttach
* Release Management tools for Visual Studio 2013
* SlowCheetah - XML Transforms
* SpecFlow for Visual Studio 2013
* Team Foundation Server Power Tools 2013
* TFS Process Template Editor
* TFS Team Collaborator
* TFS Work Item Type Designer
* Visual F# 3.1.2
* Visual FSharp Tools Templates for VSPro
* Visual Studio 2013 Color Theme Editor
* Visual Studio Extensions for Windows Library for JavaScript
* VsVim
* Web Essentials 2013 for Update 4
* Windows Phone 8.1 SDK Integration
* Workflow Manager Activities

If you can't repro then I can try disabling certain things and see if I still get the issue.

**Comment by jaredpar** [comment]
@ChrisMiskowiec are you seeing this behavior in a web project?  Or does it repro with any type of project?

**Comment by ChrisMiskowiec** [comment]
Yesterday when I reported it, I was working in a web project. I could've sworn I'd seen it elsewhere previously, but I just tried again in several places, and found it only occurring with Javascript comment blocks. I was definitely seeing it in a CS file when I reported the issue, but I'm not sure what I've changed since yesterday.

I disabled Web Essentials 2013, and now it is no longer happening, so it seems like Web Essentials is intercepting the &lt;CR&gt; before VsVim can handle it.

**Comment by jaredpar** [comment]
> I disabled Web Essentials 2013, and now it is no longer happening, so it seems like Web Essentials is intercepting the <CR> before VsVim can handle it.

Thanks for digging into it.  I suspected this may be the case.  On occasion our extensions conflict and we end up competing for the same key stroke.  I will check and see if this is an issue I've previously fixed that just hasn't been released yet.

**Comment by jaredpar** [comment]
This should be fixed now. Several conflicts were found and resolved in the last few eyars.
