### ISSUE TITLE
Half page navigation using <C-D>,<C-U> is very slow

### ISSUE THREAD

**Issue by digitalcosmos** [jaredpar/VsVim#1633]
Using `Ctrl+D` or `Ctrl-U` to scroll half page is painfully slow (about 500ms) while scrolling a full page (either `Ctrl+F` or `Page Down`) is almost instant.

Many people use `Ctrl+D`/`Ctrl+U` to scroll through big files because you are still context aware. Having to wait for the page to scroll makes it annoying and breaks the flow.

I'm running on latest gen hardware which makes me believe that the delay is not a performance issue but it was put in intentionally. 
Vim/GVim behavior is to scroll without noticeable delay.

Thanks.

**Comment by jaredpar** [comment]
@digitalcosmos the behavior definitely isn't intentional.  I use this feature quite frequently and a delay would drive me crazy as well. 

Have you tried using normal <kbd>PageUp</kbd> and <kbd>PageDown</kbd> in the same scenarios where <kbd>Ctrl+D</kbd> is slow?  If <kbd>PageUp</kbd> is slow as well then it would speak to an underlying editor issue vs. a VsVim one.

**Comment by digitalcosmos** [comment]
Seeing that you don't experience this delay I took a moment to reflect on the scenario.
Turns out that I experience the delay only on my portrait monitor (1200x1920) and when I put VS on the other (landscape) monitor there is no delay.

In order to replicate either put the monitor in portrait mode and press `Ctrl+D` or even better, set the font to a small size so that you have about 100 lines in view ( `Consolas 6pt` seems to work well).
If I set a small font on my portrait monitor, the delay increases to ~1 second.

**Comment by jaredpar** [comment]
@digitalcosmos interesting.  I haven't really ever coded that way before.  

Do you experience the delay if you use <kbd>PageUp</kbd> and <kbd>PageDown</kbd>

**Comment by digitalcosmos** [comment]
@jaredpar I feel coding on a vertical screen is better when dealing with large files. 
For me `PageUp` and `PageDown` have no delay in scrolling.
I created a file with 1000 empty lines(`1000o<Esc>`) and scrolling through with `Ctrl+D` has the same delay as scrolling through a file with code. The size of the file is irrelevant, the delay only increases when lowering font size (thus having more lines on screen).

It seems that the delay is proportional to the number of lines on screen.

**Comment by jaredpar** [comment]
@digitalcosmos if <kbd>PageUp</kbd> doesn't have a delay then this is likely a bug in VsVim.  Which is strange because the algorithm here is pretty standard, nothing stands out at a glance.  Probably an odd perf characteristic of one of the APIs that I'm using.  Will profile and see what's going on.

**Comment by ricksladkey** [comment]
@sid-6581 Moving the discussion over here. Can you tell me if you use what Visual Studio calls "word wrap":

![image](https://user-images.githubusercontent.com/2680524/47956938-a662c200-df83-11e8-8ed4-f4d87b2514ec.png)

or what VsVim and vim call `:set wrap`? That is, if you have very long lines, does it take up multiple rows in the window?

**Comment by ricksladkey** [comment]
OK, I have a repro of sorts.

If I go to the beginning of a long text file, e.g. `CommonOperations.fs` (which is 2220 lines currently) and then press and hold `<PageDown>` until it reaches the end of the file, that procedure takes noticeably longer than the the same steps taken when VsVim is disabled with `<C-S-F12>`. On my laptop the former takes about 7 or 8 seconds and the latter takes about 2 or 3 seconds.

I mean, I don't notice that `<PageUp>`/`<PageDown>` is slow, but clearly it is slower. At least I now have an objective test to gauge roughly how slow it is.

**Comment by sid-6581** [comment]
@ricksladkey I have word wrap turned off for all file types.
