### ISSUE TITLE
Incomplete support for using High-Contrast desktop theme and VS2013 dark theme

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#1634]
Because of eye disabilities I needed to switch to a high contrast desktop theme, which is a kind override for most of the applications normally having an own visual representation.
Even VS2013 is completely different in its style after switchting to the high contrast desktop theme.

So - now I have problems reading the "command line and feedback area", which has still a white background and a black foreground color.

Is there a "quick" chance for help or a more continuous accessibility/disability  support of VsVim.

In this context I want to remind of the [issue 1558](1558), which is very problematic now, after the second eye causing troubles.

**Comment by jaredpar** [comment]
@MartinL0815 I will look into getting this done.  It's been awhile since I've implemented accessibility features though (almost 10 years) so it's going to take me a short bit to figure out how to hook into high contrast correctly.  Once that's done though I suspect it should be very doable as I don't have much in the way of complex WPF code here.  

I have a long upcoming trip this week.  Let's see if I can get it done on the plane flight.

**Comment by jaredpar** [comment]
@MartinL0815 also as a temporary work around it is possible to change the margin to match the current high contrast theme.  

- Tools -> Options -> VsVim -> Default
- Change Command Margin Background / Foreground Color 

These settings will persist across sessions of Visual Studio.  Using this I was able to get the text in the command margin to match that of the editor (using High Contrast `#1).  

Wasn't sure if there was anything besides that I was missing.

**Comment by MartinL0815** [comment]
Thanks Jared!

I applied several color changes in the `Options/Environment/Fonts & Colors` section, where to find the VsVim settings, too!

Since high-contrast-theming issues are relevant for me, I write to most of the developers or companies with applications or application extensions not "*respecting*" high-contrast-theming overrides.

Your response gives hope, like the one from the Entrian Source Search Support, which provided a quick solution for the occurred problems!

Many thanks in advance!

Best regards,

Martin

**Comment by jaredpar** [comment]
This particular change is my first attempt at getting high contrast support going:

> 5625b72737d3afd64db011f120fdfd313364f6f2

On my machine at least this caused the command margin to match up the colors of the editor when I toggled into and out of high contrast mode.  

Note: This is an area that I am completely new at.  I've played around a bit and it works fine but I'm unsure if the fix goes far enough.  If there are other items that need to change (like for example the font size needing to be updated) please let me know.  

This will be a part of the release that comes out later today.

**Comment by MartinL0815** [comment]
Hi Jared,

Thanks for the support!

Since i'm new to this problem, too, I fear I must test and try a bit, too!

I only know about the override character of the high-contrast-mode and that 
I implemented the colors to be used to be mostly system colors.
If not I decided to use the W3C recommendations for minimum color contest 
in accessibility area, to demand a brightness contrast greater 125 and hue 
contrast greater 500.

brightness contrast = (299*(r1-r2) + 586*(g1-g2) + 114*(b1-b2))/1000
hue contrast = (r1-r2) + (g1-g2) + (b1-b2)

In the visual studio environment I me other colors to be more contrasting. 
But those aren't VsVim colors.

Thanks again for your support!

Best regards,

Martin

------- Original message -------

**Comment by ip** [comment]
Still isn't fixed in VS2015:
 - Wrong highlight colors when searching
 - Hard-coded status bar colors


![2015-11-10 15_27_07-greenshot](https://cloud.githubusercontent.com/assets/1111008/11062387/9aa9f5e2-87bf-11e5-8d9e-b85737917091.png)

**Comment by jaredpar** [comment]
@ip this issue concerns updating values when in high contrast mode.  The screen shot you supplied here isn't in high contrast.  What behavior are you expecting to work here?

**Comment by ip** [comment]
@jaredpar I expect light text on dark background, obviously.

**Comment by ip** [comment]
@jaredpar With search, the text should be distinct from background

**Comment by jaredpar** [comment]
@ip are you using high contrast though?  Your screen shot indicates you are not.

**Comment by ip** [comment]
No, I use dark theme in VS 2015 (can be set in Tools -> Options -> Environment -> General)

**Comment by MartinL0815** [comment]
After some time an add-on to this problem.

With high-contrast-mode and colors adapted the way you @jaredpar advised, the caret in the command line is invisible.

**Comment by jhamm** [comment]
This seems like the issue #1665. The PR #1748 has been merged with the fix.

**Comment by jaredpar** [comment]
This should be fixed now with #1748.
