### ISSUE TITLE
 Visual Assist 's Smartselect could not work in vsc

### ISSUE THREAD

**Issue by drinkmystery** [jaredpar/VsVim#1635]
I try to use this map:
nmap <leader>a :vsc VAssistX.SmartSelectExtend<CR>.
But it could not get work, when I foucs on a word and type <leader>a, it just jumps to the end of the word.
I guess this is similar to  #1377, but I am not sure.
If they are caused by same reason, did b6adb10 fix this ?
Using VS2013 and VsVim 1.8.0.0.

**Comment by jaredpar** [comment]
The referenced change was both 

1. A general hook for fixing this problem
2. A R# specific implementation

I'll need to add a VAssistX implementation for this issue.  Hopefully not a ton of work.  Mostly making sure I have the right VAssistX package GUID.
