### ISSUE TITLE
The 'H' command doesn't work properly when it's preceded with a number.

### ISSUE THREAD

**Issue by spiralsam** [jaredpar/VsVim#1637]
Something is wrong with the 'H' command.

For example if you type in '5H' while in normal mode, the cursor should jump to the 5th line from the top of the current editor's view. However, for me it almost always jumps to the 1st line, as though you didn't type the '5' - just ignoring the preceded number.

Interestingly, if you type '5H' followed by another '5H', the cursor first jumps to the first line, then jumps to the 5th line. So if you test, test from an initial cursor position near the middle or end of the view.

**Comment by jaredpar** [comment]
Thanks for reporting.  I will take a look at this.

**Comment by jaredpar** [comment]
I've played around with this and am unable to reproduce this behavior.  I've tried in a variety of settings and count + <kbd>H</kbd> behaves as expected.  Can you give me a bit more information about where you are seeing this behavior?  C, Javascript, etc ... and perhaps some sample code where it occurs? 

Also is it possible there are entries in your vimrc file which would effect the <kbd>H</kbd> command?
