### ISSUE TITLE
The 'H' and 'L' commands, when preceded with a number, won't jump to the proper line if that line is a blank line.

### ISSUE THREAD

**Issue by spiralsam** [jaredpar/VsVim#1638]
I've just submitted a bug #1637 that might prevent this bug here from being tested properly unless you are careful when testing it. But they are different issues.

If you type '5L', the cursor should jump to the 5th line from the bottom of the current view. This normally works, however, the problem is that if the 5th line from the bottom is an entirely blank line, it may not jump to the right line. I say 'may not' because while testing this, I tried with different starting positions for the initial cursor (before entering the '5H' command). If I had it placed somewhere above the 5th line from the bottom (near the top of the view), then it would end up actually jumping to the 6th line instead, jumping right over the blank line. However, if instead I had it placed initially somewhere below the 5th-from-bottom line (at bottom of the view), then it would actually end up landing on the line it was supposed to: the 5th line from the bottom that was blank.

I can't fully test this as a '5H' command because of #1637, but it looks like the 'H' command is also incorrectly skipping over blank lines as well.

**Comment by spiralsam** [comment]
I just noticed that this also happens with the 'M' command without any preceding number.

**Comment by jaredpar** [comment]
I'm unable to reproduce this behavior.  I can jump to blank lines in normal mode with <kbd>H</kbd> or <kbd>L</kbd>.  Can you give me a bit more info about where you are seeing this?  C, Javascript, etc ...

**Comment by spiralsam** [comment]
Well I've just updated VsVim to 2.0.1.0 from 1.8.0 a moment ago and I can no longer produce it any more either (had tested with.cpp files). Same goes for #1637 - can't reproduce any more!

**Comment by jaredpar** [comment]
@spiralsam good to hear.  We'll close them for now then.  Please post back if the issue comes up again.
