### ISSUE TITLE
Command bar is duplicated

### ISSUE THREAD

**Issue by sgrassie** [jaredpar/VsVim#1639]
![capture](https://cloud.githubusercontent.com/assets/194140/8734871/dcb4e698-2c04-11e5-89e5-8b431510b17f.PNG)

I get this on my home machine. On my machine at work, it's fine, there is only one.

I've tried uninstalling and reinstalling VsVim, and I'm running the latest of the VSIX gallery.

I don't think this is an issue with VsVim... but I can't make it go away, so I'm open to suggestions.

**Comment by idealist1508** [comment]
It depend on `set laststatus` value.
Please see #1350

**Comment by sgrassie** [comment]
:+1: 
I just tried that here at work and have been able to turn it on/off.

Thank you!
