### ISSUE TITLE
Error closing/saving VsVim keybindings dialog

### ISSUE THREAD

**Issue by kalebpederson** [jaredpar/VsVim#1641]
I loaded up VsVim for the first time in VS-2015 and it warned me of potential conflicts, so I pulled up the key bindings dialog by clicking the "Configure" button. At that point I looked through the potential conflicts and then clicked ok at which point I received an error in VS. Here's the error recorded in the activtiy log

> System.ArgumentException: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG)) at EnvDTE.Command.set_Bindings(Object pVar) at Vim.VisualStudio.Extensions.SafeSetBindings(Command command, IEnumerable`1 commandBindings) at Vim.VisualStudio.Implementation.OptionPages.KeyboardSettingsControl.UpdateKeyBindings() at Vim.VisualStudio.Implementation.OptionPages.KeyboardSettingsControl.Apply() 

Thank you for continuing to support and work on VsVim. It's truly greatly appreciated!

**Comment by jaredpar** [comment]
Thanks for reporting!  Every release we find a new way that API can fail :frowning:
