### ISSUE TITLE
VS 2015 RTM regression of #1601

### ISSUE THREAD

**Issue by digitalcosmos** [jaredpar/VsVim#1642]
Hi @jaredpar,
I've upgraded from 2015 community to RTM and installed version 2.0 of VsVim from Visual Studio Gallery, but I had to rollback to version 1.8.342 because the behavior in issue #1601 is still present. (`gt`/`gT` doesn't switch tab)

Thanks for developing and maintaining VsVim :+1:

**Comment by jaredpar** [comment]
@digitalcosmos can you try the 2.0.1 version of VsVim?  I had a deployment bug in the 2.0.0 version that caused <kbd>gt</kbd> to be broken.  The most recent drop should have fixed this.

**Comment by digitalcosmos** [comment]
Tab switching works as intended. Thanks :grin:
