### ISSUE TITLE
*it (cit, vit, dit, ...) don't work correctly if the tag includes a property that has a - in its name

### ISSUE THREAD

**Issue by ahmelsayed** [jaredpar/VsVim#1644]
Put the cursor on the text in the anchor below (`Click the link`)
``` html
<body>
    <div class="outer-div">
        <div class="inner-div">
            <h1>test</h1>
        </div>
        <a href="#" ng-click="click()">Click the link</a>
    </div>
</body>
```
hit `vit` or `cit`. I would expect the text `Click the link` to get highlighted or deleted, 
but actually everything in the `div.outer-div` gets highlighted\deleted.

VIM (7.4) handles it correctly

**Comment by ahmelsayed** [comment]
I forgot to mention. I think this is because of `ng-click` on the anchor. If you get rid of the `-`, *it commands work as expected.

**Comment by jaredpar** [comment]
Thanks for reporting the bug.  It does indeed appear to be the `-` in the attribute name that is causing the issue.  Will fix.
