### ISSUE TITLE
Sort completion list

### ISSUE THREAD

**Issue by philipmat** [jaredpar/VsVim#1645]
Please consider sorting the completion list that shows up on Ctrl-N/Ctrl-P. At a minimum, it would be nice if it was sorted alphabetically (case sensitive). It would be really nice if it was sorted by distance from insertion point: if the word is defined in the same file, it should show up before words defined in different files.

**Comment by jaredpar** [comment]
@philipmat do you know what the gVim behavior is here?

**Comment by philipmat** [comment]
Vim behavior is sorted by distance from the insertion point. Given a list of:
```
a11
a22
a33
a44

a55
a66
a77
a88
a99
```

Pressing `Ctrl-N` *after a44* yields a popup containing the items:
```
a55
a66
a77
a88
a99
a11
a22
a33
a44
```
and the first element *a55* is selected.

If `Ctrl-P` is pressed, the list is the same, but the selection cursor is placed at the bottom, thus selecting *a44*.

**Comment by dedowsdi** [comment]
This is broken in vs2019 16.7.5 . Completion is sorted alphabetically.
