### ISSUE TITLE
Cursor goes past end of line when clicking past the end of line in normal mode

### ISSUE THREAD

**Issue by jankner** [jaredpar/VsVim#1650]
In gVim, when clicking somwhere to right of the text on a line, the cursor is positioned on the last character of the line. In VsVim the cursor is positioned to the right of the last character. Placing the cursor past the end of the text on a line normally isn't possible in Vim and in VsVim it can only be placed there by using the mouse.

~~~
Some text.<EOL>
         ||               ^- click here.
         |^- the cursor is placed here.
         ^- it should go here.
~~~

**Comment by jaredpar** [comment]
Thanks for reporting.  I will take a look at that.

**Comment by jaredpar** [comment]
Note that the caret can be positioned at `<EOL>` when `ve=onemore` via a mouse click.

**Comment by jankner** [comment]
I didn't know that. That's not what's happening here, though, since using the mouse is the only way to position the caret at <EOL>.

**Comment by jaredpar** [comment]
@jankner yep in this case it repros no matter what the setting of `ve=onemore` is.

**Comment by jhamm** [comment]
I took a look at this one. 

I think this may be part of the VS editor. If you switch to VsVim disabled, and click after the line, the cursor is at the same position as the original report. Then switch back to VsVim enabled and click after the line, its at the same spot. My initial guess is we will need to move the cursor back one character if it was moved by the mouse in normal, insert, or replace mode. It should exit Visual mode if clicking unless you drag the selection.

I would like some advice on where to start with this one.

**Comment by jaredpar** [comment]
@jhamm I think the bug is here 

https://github.com/jaredpar/VsVim/blob/f711e222b249559aa9b5d00747cdf3f4820f0b66/Src/VimCore/SelectionChangeTracker.fs#L90

I **think** this should include the `VirtualEdit` flags as well to check for the caret being passed the EOL.

**Comment by jhamm** [comment]
Yup you are right. I have modified the PR with the updated fix. Thanks! :smile:

**Comment by jhamm** [comment]
Lets hold off on merging this PR. I think the tests should cover both with and without the ve=onemore setting.

**Comment by dsherret** [comment]
I'm glad I just had to add `set ve=onemore` to my vimrc to disable this fix and use the old behaviour. Thanks! :)

Kind of annoyed me because you can't select the last character on a line when going from right to left with the mouse:

![image](https://cloud.githubusercontent.com/assets/1609021/16363869/e26e978a-3ba5-11e6-9eff-18f0d6a89cb8.png)

**Comment by jankner** [comment]
That looks strange. I am able to select the entire line like that even without `ve=onemore`.

**Comment by dsherret** [comment]
@jankner weird. I'm getting the same behaviour not being able to select the entire line when going from right to left on my work computer too. I'm using VS2015 with VsVim 2.1.0.0 on both computers.

**Comment by jankner** [comment]
@dsherret Sorry, you're right. I was doing left to right. I get the same behaviour as you going right to left.
