### ISSUE TITLE
Command reference

### ISSUE THREAD

**Issue by iamkarlson** [jaredpar/VsVim#1651]
Hi, I'm newbie in Vim and I try to start using it directly in visual studio, skip using in vim. And due to this reason, I don't know all of commands of Vim. I've opened VsVim settings and saw a lot of key combinations without explanations. I printed a cheatsheet for vim, but it does not give me full understanding for VsVim functions. Can I use same cheatsheets for VsVim as well as cheatsheets for vim? Can I call visual studio commands (like expand region) from command mode? And how I can do it?

**Comment by Mharlin** [comment]
You can use the same cheatsheet for VsVim as you would for Vim if you set the shortcuts to be handled by VsVim in the settings. You can use the normal shortcuts for things like expanding regions and visual studio does executes it regardless of what mode you are in.

**Comment by jaredpar** [comment]
@iamkarlson in general I would try and use the vim cheat sheets for VsVim.  There are some more advanced commands that don't work much of the work that appears in tutorials will work in VsVim.
