### ISSUE TITLE
Ctrl-R keystroke for pasting register content replaces only one character in replace mode

### ISSUE THREAD

**Issue by Predelnik** [jaredpar/VsVim#1653]
As I checked in vim, Control-R and then register key, while being in replace mode should replace the same number of characters after cursor as in register, but VsVim replaces only one and inserts the rest.

Also looks like it should draw double quote under cursor as in insert mode, but that's minor thing.

**Comment by jaredpar** [comment]
@Predelnik thanks for reporting. I will get that fixed.

**Comment by jhamm** [comment]
PR #1742 should take care of this.
