### ISSUE TITLE
Multiline/multicursor edit in vs

### ISSUE THREAD

**Issue by iamkarlson** [jaredpar/VsVim#1655]
Hi, is it exist multiline mode for vsvim, like same in sublime text, or in vanila visual studio? I've found plugin for vim with same functionality (https://github.com/terryma/vim-multiple-cursors), but i don't know how i can use same functions in vsvim

**Comment by jaredpar** [comment]
Unfortunately that functionality doesn't exist for Visual Studio or VsVim.  In general VS itself doesn't support the concept of multiple cursors though so it's unclear how this would be implemented.

**Comment by exyi** [comment]
I'm using [MultiEditing](https://visualstudiogallery.msdn.microsoft.com/2beb9705-b568-45d1-8550-751e181e3aef) extension for Visual Studio and it works fine with VsVim in insert mode.
