### ISSUE TITLE
Problem with delete/change inside command (not always)

### ISSUE THREAD

**Issue by darkpotpot** [jaredpar/VsVim#1660]
Hi,
I'm a big fan of the "delete/change inside" command but sometimes it doesn't work. For example, with the following line:
`   boost::wregex l_OutlineFileNameRegex(DuplicateBackslash(L"^OutlineFileName:(.*\\.*\\\\).*$"));`
If the cursor is on DuplicateBackslash word, typing ***ci)*** does nothing. In Vim, it deletes everyting up to the last parenthesis.
It seems like VsVim is confused with the ***\\)*** and doesn't count this one as a closing parenthesis.

**Comment by jaredpar** [comment]
Thanks for reporting.  That does seem like a bug.
