### ISSUE TITLE
Copying hangs for a couple seconds, then throws exception

### ISSUE THREAD

**Issue by bmsullivan** [jaredpar/VsVim#1663]
The first time I copy something after opening Visual Studio, the IDE freezes for a couple of seconds, then I get an error dialog box that says "An exception has been encountered. This may be caused by an extension."

When I check the ActivityLog.xml file that it points me to, I find this error message at the bottom:

    <entry>
    <record>837</record>
    <time>2015/09/02 13:28:02.175</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>
       System.Runtime.InteropServices.COMException (0x800401D0): OpenClipboard Failed (Exception from HRESULT: 0x800401D0 (CLIPBRD_E_CANT_OPEN))&#x000D;&#x000A;   
        at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)&#x000D;&#x000A;   
        at System.Windows.Clipboard.CriticalSetDataObject(Object data, Boolean copy)&#x000D;&#x000A;   
        at System.Windows.Clipboard.SetDataInternal(String format, Object data)&#x000D;&#x000A;   
        at System.Windows.Clipboard.SetText(String text, TextDataFormat format)&#x000D;&#x000A;   
        at System.Windows.Clipboard.SetText(String text)&#x000D;&#x000A;   
        at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.&lt;&gt;c__DisplayClass4.&lt;SetText&gt;b__3()&#x000D;&#x000A;   
        at Vim.UI.Wpf.Implementation.Misc.ClipboardDevice.TryAccessClipboard(Action action, Int32 retryCount, Int32 pauseMilliseconds)
    </description>
    </entry>

The content still gets copied to the clipboard, and the dialog only shows up once per opening of VS, but the multiple second delay whenever I copy or delete something happens every time and really slows me down. I've tried uninstalling Resharper and disabling Git integration, but neither seemed to help.

If there's any other information I can provide that can help track this down, please don't hesitate to ask.

**Comment by bmsullivan** [comment]
Also of note, running VS2015 on Win 10, but I can reproduce in 2013 as well.

**Comment by jaredpar** [comment]
Unfortunately this is "by design of Windows".  The clipboard in Windows is shared amongst all processes and it's possible for other applications to lock it in such a way that it can't be used by other applications.  

That is what is occurring here.  Another app has locked the clipboard, VsVim tries to access it, and an exception occurs because it's locked.  There is really no recourse for me to take here (besides finding and killing the process that locked the clipboard).  

When I wrote this code I waffled a bit about whether or not to surface this error to Visual Studio.  Eventually I decided to because not surfacing it meant that developers would execute copy / paste commands to the clipboard and it would silently fail.

**Comment by bmsullivan** [comment]
Thanks, Jared! Your explanation pointed me to what I think was causing the problem. I was using a clipboard recording utility which was likely locking the clipboard.  I feel a bit silly for not having thought to try disabling that! That also explains why other people weren't running into this issue.

I appreciate your quick reply and the extra information!

**Comment by boydy12** [comment]
I seem to get this issue every time I open Visual Studio for the first time and highlight the word and press the change button 'c'. After the error has appeared once then it doesn't appear again, until I close down Visual Studio and reopen.

I can see it being a windows issue but why does it always error out only once, and only the when visual studio has been opened.
