### ISSUE TITLE
SetSite failed for package VsVim

### ISSUE THREAD

**Issue by TyOverby** [jaredpar/VsVim#1664]
The VsVim package doesn't load for me.  When looking in ActivityLog.xml, I found this:

```xml
  <entry>
    <record>198</record>
    <time>2015/09/06 00:53:19.907</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Vim.VisualStudio.VsVimPackage, VsVim, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null]</description>
    <guid>{A284D12C-1E96-451B-A3B0-5486A1BEB6CA}</guid>
  </entry>
  <entry>
    <record>199</record>
    <time>2015/09/06 00:53:19.939</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [Vim.VisualStudio.VsVimPackage, VsVim, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null]</description>
    <guid>{A284D12C-1E96-451B-A3B0-5486A1BEB6CA}</guid>
    <hr>80131500</hr>
    <errorinfo>No exports were found that match the constraint: 
	ContractName	Vim.IVim
	RequiredTypeIdentity	Vim.IVim</errorinfo>
  </entry>
  <entry>
    <record>200</record>
    <time>2015/09/06 00:53:19.941</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [Vim.VisualStudio.VsVimPackage, VsVim, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null]</description>
    <guid>{A284D12C-1E96-451B-A3B0-5486A1BEB6CA}</guid>
    <hr>80131500</hr>
    <errorinfo>No exports were found that match the constraint: 
	ContractName	Vim.IVim
	RequiredTypeIdentity	Vim.IVim</errorinfo>
  </entry>
```

**Comment by jaredpar** [comment]
Thanks for reporting this issue.  I'm pretty sure the line of code that is leading to this error is [this line](https://github.com/jaredpar/VsVim/blob/master/Src/VsVim/VsVimPackage.cs#L46): 

``` csharp
_vim = _exportProvider.GetExportedValue<IVim>();
``` 

That line should never fail unless there is an installation error, or some fatal exception during MEF composition.  The latter though should also lead to entries in the same log file though.  

Did you install VsVim from the gallery or did you build it by hand?

**Comment by TyOverby** [comment]
Looking in the log file I found this earlier:

```xml
  <entry>
    <record>185</record>
    <time>2015/09/06 00:53:14.919</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Performance warning: String load failed. Pkg:{A284D12C-1E96-451B-A3B0-5486A1BEB6CA} (Vim.VisualStudio.VsVimPackage, VsVim, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null) LANG:0409 ID:0&#x000D;&#x000A;</description>
  </entry>
  <entry>
    <record>186</record>
    <time>2015/09/06 00:53:14.919</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Performance warning: String load failed. Pkg:{A284D12C-1E96-451B-A3B0-5486A1BEB6CA} (Vim.VisualStudio.VsVimPackage, VsVim, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null) LANG:0409 ID:0&#x000D;&#x000A;</description>
  </entry>
  <entry>
    <record>187</record>
    <time>2015/09/06 00:53:14.920</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Performance warning: String load failed. Pkg:{A284D12C-1E96-451B-A3B0-5486A1BEB6CA} (Vim.VisualStudio.VsVimPackage, VsVim, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null) LANG:0409 ID:0&#x000D;&#x000A;</description>
  </entry>
```

I'm installing from the gallery.  Completely clean VS 2015 installation too.  VsVim was the first plugin that I tried installing.

**Comment by jaredpar** [comment]
Those string loads are the VsVim resource strings which Visual Studio queries to get items like a display name, description, etc ...  That also should never fail.  There is no real code involved here, it's a declarative operation on the package + embedding the strings.  :frowning: 

At this point it seems like either the download is corrupted or there was an issue with Visual Studio itself.  It's possible there is a latent bug that caused the original error but not this most recent issue.  That shouldn't ever fail (CC @jasonmalinowski in case he can think of something I'm missing).  

As a next step I would try reinstalling VsVim in the following manner:

- Uninstall VsVim.  
- From a VS command prompt run
    - devenv /updateconfiguration
    - devenv /clearcache
- Reinstall VsVim 

That should be as close to a clean install as possible without directly deleting files off of disk.  If that doesn't work the next step may be to repair the Visual Studio installation.  

Have you tried installing any other extensions and seeing if they work?

**Comment by TyOverby** [comment]
Thanks, those steps seemed to have fixed it!

**Comment by unix-bigot** [comment]
Sorry, I know this post is over a year old, but it was the closest one that I could find that seemed to be similar.

I have the issue with the SetSite failed message, except the package failing is Visual Studio Component Model Host Package. My company applied some .net updates this past weekend and now I have this error pop up and is in the log when I start visual studio. 

It appears to impact my ability to access extensions and updates as well as sql server object explorer.

If I clear the files from C:\Users\myuserid\AppData\Local\Microsoft\VisualStudio\12.0\Extensions it resolves the errors and access, but as soon as I go to the gallery, download vsvim and run it, the errors and no access isues come back. I also tried the /updateconfiguration and /clearcache commands but no joy.

We are using Visual Studio 2013 with all the latest updates, and I believe that the company just applied .NET 4.6.2

last entries in the Activity.xml log file:
  <entry>
    <record>327</record>
    <time>2016/12/20 19:25:52.744</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Visual Studio Component Model Host Package]</description>
    <guid>{49D12072-378B-4FFA-A09E-40E0B5D097CC}</guid>
  </entry>
  <entry>
    <record>328</record>
    <time>2016/12/20 19:25:52.745</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [Visual Studio Component Model Host Package]</description>
    <guid>{49D12072-378B-4FFA-A09E-40E0B5D097CC}</guid>
    <hr>80131509</hr>
    <errorinfo>The component has already been initialized.</errorinfo>
  </entry>
  <entry>
    <record>329</record>
    <time>2016/12/20 19:25:52.745</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [Visual Studio Component Model Host Package]</description>
    <guid>{49D12072-378B-4FFA-A09E-40E0B5D097CC}</guid>
    <hr>80131509</hr>
    <errorinfo>The component has already been initialized.</errorinfo>
  </entry>
</activity>

**Comment by jaredpar** [comment]
@unix-bigot have you tried just deleting the entire  `C:\Users\myuserid\AppData\Local\Microsoft\VisualStudio\12.0` directory?  Save it first of course.

**Comment by unix-bigot** [comment]
Brillant!
that worked.
thanks mucho for the quick response and the a resolution!
I love this editor. I have been using VI for over 20 years. I had to take a Windows position around 12 years ago and your vsvim has made my life SO much easier. thanks for a great product.
