### ISSUE TITLE
In High-Contrast-Mode the caret of the command line is invisible

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#1665]
To be able to use the command line in High-Contrast-Mode I changed the colors this way:
>![VS2013 options font&colors](https://cloud.githubusercontent.com/assets/525700/9756137/0f2b9bb4-56d8-11e5-9376-bd3e94675a02.png)

Since then I can see the caret anymore. It seems, that it is black on black background, even if the font color is yellow.

Any change or fix possible?

**Comment by jaredpar** [comment]
Have you tried changing the color through the `VsVim -> General` menu?  If you make it yellow there it should come up the same text.  

For the next version in high contrast mode I'll make it match the text color.

**Comment by MartinL0815** [comment]
Yes, I used today the VsVim options instead of "Tools/Options/Environment/Fonts and Colors", but nothing changed!

The caret is still invisible!

But there is another misbehavior:

1. use `Pos1` in the command line edit control
2. use `Del` to delete the first character

WIth my VsVim isntallation nothing happens! The first character won't be deleted. Even `Shift-Del` won't delete a character in the edit control.

**Comment by MartinL0815** [comment]
Sorry, but with 2.1.0.0 this issue is only partly solved - on my high-contrast-enabled system.

- Before using a caret moving key, the caret is invisible …

>>![caret-less command line](https://cloud.githubusercontent.com/assets/525700/16187456/b9bf80e4-36d0-11e6-9720-16fb5249d8b8.png)

- After moving the caret with the cursor keys, Pos1, etc., the caret becomes visible …

>>![command line with caret after moving it](https://cloud.githubusercontent.com/assets/525700/16187497/ea9ea5be-36d0-11e6-8c18-ab9618ab007f.png)

Additionally - may be I should create a new issue - pressing End does not move the caret to the end of the command line text, but inserts a square like …
>![End does not move the caret, but inserts a character](https://cloud.githubusercontent.com/assets/525700/16187516/0121412a-36d1-11e6-804d-0bcd89fb8c82.png)
