### ISSUE TITLE
Issues with HOME directory shortcut (~)

### ISSUE THREAD

**Issue by jamiehayes** [jaredpar/VsVim#1668]
I have a couple mappings in my _vimrc that make use of the HOME directory shortcut, and they aren't working in VsVim, but they work in gvim. Examples:

`:tabnew ~/_vimrc<CR>` (yields "The system cannot find the path specified. (Exception from HRESULT: 0x80070003)")
`:source ~/_vimrc<CR>` (yields "Missing quote")

Thanks!

**Comment by jaredpar** [comment]
Thanks for reporting.  I'll look at getting that implemented.  I have a few bugs in this area that I'm going to try and clean up at once.

**Comment by ricksladkey** [comment]
Both of these commands work properly at the head of VsVim master.
