### ISSUE TITLE
String substitution not working

### ISSUE THREAD

**Issue by tskillian** [jaredpar/VsVim#1672]
Lets say that searching for the string foo with /foo works with the plugin, I would expect substitution to work with :s/foo/bar/g to replace foo with bar in the whole file. However, this doesn't seem to work. I always get the "pattern not found" message. So, basically:

/foo => finds instance of foo
:s/foo/bar/g => Pattern not found: foo

**Comment by jaredpar** [comment]
VsVim is conforming to the standard vim behavior here.  The `:s` form of the substitute command will only act on the current line.  In order to replace in the entire file the `:%s` form of the substitute command needs to be used.

**Comment by tskillian** [comment]
Sorry, brain fart on my end. Forgot that you needed the %
