### ISSUE TITLE
IMapping jk to <Esc> moves down a line if cursor is at the end of a line 

### ISSUE THREAD

**Issue by otherdave** [jaredpar/VsVim#1673]
My _vsvimrc file has the line:

```
imap jk <Esc>
```

If I am in the middle of a line of text, in insert mode, and I press `jk` I leave insert mode. If I am at the end of the line and I press `jk` I leave insert mode and then move to the next line. I verified this happens with other escape mappings so it's likely not `jk` specific.

Is this intended behavior or is there a change to my _vsvimrc that would prevent this?

**Comment by jaredpar** [comment]
That seems like a bug. 

When this occurs is there a line below the one u are typing in that has text? Or is the line below blank?

**Comment by otherdave** [comment]
It fails in both cases you describe. I just verified a super-simple one: if I'm on line 1 and it's blank, and line 2 is also blank, hitting `jk` on line one (position 0, as it's blank) I move down a line. Pressing escape doesn't do this.

**Comment by otherdave** [comment]
If it helps ,here is my _vsvimrc file. I believe I got a super-duper vimrc file years ago and tweaked it, then pruned it down to the basics needed for vsvim. So maybe there's a setting here that's incompatible with what I'm trying to do and vsvim?

```
" Sets how many lines of history VIM has to remember
set history=300

" Go nocompatible
set nocompatible

" Set to auto read when a file is changed from the outside
set autoread

" <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","

imap jk <Esc> 

" Fast saving
nmap <leader>w :w!<cr>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => VIM user interface
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Set 7 lines to the curors - when moving vertical..
set so=7

set wildmenu "Turn on WiLd menu

set ruler "Always show current position

" Set backspace config
set backspace=indent,eol,start

" ignore case if search term is all lower case (smartcase)
" requires ignorecase too
set ignorecase
set smartcase 

set hlsearch "Highlight search things

set incsearch "Make search act like search in modern browsers

set magic "Set magic on, for regular expressions

set showmatch "Show matching bracets when text indicator is over them
set mat=2 "How many tenths of a second to blink

" Always have line numbers
set nu

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Colors and Fonts
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
syntax enable "Enable syntax hl

set vsvim_useeditordefaults
```

**Comment by gibwar** [comment]
> ```
> set so=7
> ```

Just for fun, does it still happen if you set `scrolloff` to `0`?

**Comment by otherdave** [comment]
@gibwar yep, still happens :(

**Comment by jaredpar** [comment]
Figured this out. The problem here is that at the end of the `imap` line there is an extra space. Hence the mapping is effectively `:imap jk <ESC><SPACE>`. Pressing <kbd>space</kbd>on an empty line will cause the caret to jump to the next line. 

I checked and gVim has the same behavior here.

**Comment by otherdave** [comment]
@jaredpar wow, thanks for checking this out and updating the issue. I just verified that the extra space was absolutely my problem :(

**Comment by halkoma** [comment]
> Figured this out. The problem here is that at the end of the `imap` line there is an extra space. Hence the mapping is effectively `:imap jk <ESC><SPACE>`. Pressing spaceon an empty line will cause the caret to jump to the next line.

I had the same problem without <space> and found out that you don't have to have a <space> and this behavior can still happen. For me the problem was an empty space, " ", after the mapping. To be clear: "`inoremap kj <esc>`" is correct; "`inoremap kj <esc> `" is incorrect.
