### ISSUE TITLE
Implement 'normal' command

### ISSUE THREAD

**Issue by ecsousa** [jaredpar/VsVim#1678]
One feature that a really miss in VsVim is the normal command. I find it very useful to record macros like this:

```
jVi{:g/public/normal O[DataMember]
```

With this marco, if I am in the first line of a POCO class, it would put a DataMember attribute to each property of that class.

normal command is a great combo with g command

**Comment by jaredpar** [comment]
That's interesting.  I've never seen this before.

**Comment by jhamm** [comment]
This is a useful feature. I verified it works by building from the source. Should this issue be closed?

**Comment by jaredpar** [comment]
@jhamm yep.  Closing.
