### ISSUE TITLE
Navigating between vertical split windows fails when both windows are viewing the same file.

### ISSUE THREAD

**Issue by mattrrichard** [jaredpar/VsVim#1679]
Reproduce Steps:
1. Open a single file
2. <kbd>CTRL</kbd>-<kbd>w</kbd> <kbd>v</kbd> to split file
3. <kbd>CTRL</kbd>-<kbd>w</kbd> <kbd>l</kbd> to move to the second column
4. Attempt <kbd>CTRL</kbd>-<kbd>w</kbd> <kbd>h</kbd> to move back. 

If you instead open two different files in the columns, it works as expected.

**Comment by mattrrichard** [comment]
Using VsVim version 2.0.370 in VS 2013

**Comment by mattrrichard** [comment]
Looks like it's due to [the way `MoveFocusHorizontally` finds the currently active window](https://github.com/jaredpar/VsVim/blob/f711e222b249559aa9b5d00747cdf3f4820f0b66/Src/VsVimShared/VsVimHost.cs#L580):

```
var indexOfActiveDoc = topLevelWindows.FindIndex(win => win.Document == _dte.ActiveDocument);
```

When there are two windows displaying the same document, the index returned from that might be wrong.  I'll try to look into it more deeply later today if I get time.  This is something I haven't done before so it'll be an adventure!

**Comment by idealist1508** [comment]
it's awesome.  I thought it is impossible, because of #1602

**Comment by jaredpar** [comment]
> When there are two windows displaying the same document, the index returned from that might be wrong.

That's likely the case.
