### ISSUE TITLE
ciB does not respect indentation

### ISSUE THREAD

**Issue by MartinRykfors** [jaredpar/VsVim#1683]
Start with the following with the cursor somewhere on the second line:

```
if (true){
    int a;
    int b;
}
```

In gVim, pressing `ciB` will delete the text between the braces and go into insert mode with the cursor indented one level. 
In VsVim, the cursor is left at the start of the line and not at the indentation level.

Edit: If `autoindent` is not set, then gVim and VsVim behave the same way.

**Comment by idealist1508** [comment]
This is really strange. I try it in gvim and it was like in vsvim.
![vimvib](https://cloud.githubusercontent.com/assets/4608274/10726310/327049b6-7bd2-11e5-97cd-53ec7dc1a119.gif)
Is there some option, that change this behavior?

**Comment by MartinRykfors** [comment]
My .vimrc has `autoindent` and `smartindent` set. Do you have the same settings?
(Not sure of those settings should affect this.)

**Comment by idealist1508** [comment]
Thanks, it depend on ```autoindent```.  This setting seems to be not fully supported in vsvim

**Comment by MartinRykfors** [comment]
Cool, I've updated the first post to clarify this.
