### ISSUE TITLE
Can't insert 'space' after disable vsvim ( ctrl+shift+f12)

### ISSUE THREAD

**Issue by GitMyCode** [jaredpar/VsVim#1688]
If i use the "disable vim feature with ctrl+shift+f12" i cannot insert space! The behavior seems like the ctrl key is stuck because it always open de auto-suggestion box whenever i press spacebar

**Comment by jaredpar** [comment]
That's very odd.  In disabled mode VsVim essentially steps out of the way and lets Visual Studio take over the keyboard handling.  So if items like auto-seggest are displaying it is because Visual Studio chose to do it. 

When you re-enable VsVim and go to insert mode do you see the same behavior?  Is this change only limited to space?  

Curious: can you check and see if you have any key mappings around space?  They shouldn't be running here but would be an interesting piece of data.

**Comment by GitMyCode** [comment]
I think there is a compatibility problem with Resharper. I tested with resharper uninstalled and it worked well.

**Comment by jaredpar** [comment]
Which version of ReSharper are you running?

**Comment by GitMyCode** [comment]
It doesn't work with the 8.2.1 and the 9.2 ( the two version i tested)

**Comment by idealist1508** [comment]
I have Resharper 8.2.1 too. It works as expected.

**Comment by GitMyCode** [comment]
I m on visual studio 2013 if that make a difference

**Comment by GitMyCode** [comment]
And the 2.0.1 version of VsVim

**Comment by GitMyCode** [comment]
I've been having this problem on three different computer. I tried uninstalling and reinstalling  vsvim or resharper without success. I also tried different keyboard scheme with resharper without success.

**Comment by elrob** [comment]
I'm having the same problem. :(
Resharper 9.1.3 
VsVim 2.0.1.0

**Comment by elrob** [comment]
Do you still need more data on this?

**Comment by jaredpar** [comment]
@elrob hopefully it will repro with this information.  Haven't tried yet (been out of town) but will be looking at it early this week.

**Comment by millionbonus** [comment]
I'm having the same problem.
However, It only happens when I edit .cs files while vsvim was disabled. If I switch to other kind of file(ex: .aspx, .js, .css) the problem gone. Then I switch back to .cs file. The problem comes back.



VsVim 2.0.1.0
Visual Studio 2012

**Comment by jaredpar** [comment]
Sorry for the delay on this.  We had some bad weather in Washington that knocked out power for a few days and I do my R# investigations on my home desktop.  Power back but my license has apparently expired.  Hopefully it gets renewed this weekend and I can finish out this bug.

**Comment by jaredpar** [comment]
For whatever reason I'm unable to reproduce this on my box.  I've applied all of the standard R# keyboard schemes, disabled VsVim and still been able to type spaces.  Been testing on R# 10.2 in VS 2012.

**Comment by jhamm** [comment]
This could be related to the fix in PR #1745.

**Comment by teddemunnik** [comment]
I am also hitting this issue after switching to VS2015, and I'm not using Resharper.
- Visual studio Profesional 2015: 14.0.23107.0 D14REL
- VsVim: 2.0.1.0

**Comment by idealist1508** [comment]
I had it also.  Only reset of keyboard sheme helped me:
Options -> Environment -> Keyboard -> Reset

**Comment by teddemunnik** [comment]
@idealist1508 Thank you for your help, sadly this solution did not help for me.

I did also notice that space doesn't work anymore in vs2012, so it might be related to changes in my vimrc. I'll investigate further..

**Comment by crzytrane** [comment]
It's happening for me as well is there any information I can provide for this issue? VsVim Version 2.0.1.0 no resharper and keyboard resets didn't work for me. Disabling the vsvim extension makes space work as expected. Having the vim bindings disabled triggers the issue(Ctrl+Shift+F12). Visual Studio 14.0.25123.00 Update 2

**Comment by darfink** [comment]
I experience this when I disable VsVim, but beyond this I also have this issue in the C# immediate window (with VsVim enabled). I have no custom .vimrc whatsoever

**Comment by crzytrane** [comment]
I tried reinstalling the extension but I can confirm this doesn't fix the issue. I found that after disabling VsVim I can actually still use the space key in .aspx files but in .vb and .sql files space bar does nothing. Hope this helps

**Comment by crzytrane** [comment]
After setting the VsVim Keyboard shortcuts back to being handled By Visual Studio with the exception of Ctrl+Shift+F12 it "fixed" the issue for me. I've narrowed down the cause on my particular machine to be Ctrl+Alt+Space being handled by VsVim causing this issue. Could someone else confirm this?

**Comment by Mattias1** [comment]
Confirmed. Setting everything but C-S-F12 to visual studio's shortcuts makes the spacebar work just fine after switching back to vs from vsvim. Then handling C-A-Space with vsvim stops the spacebar when switching back to vs.

Also, when going back to my own settings the space was not working again (in C-S-F12 mode), when Giving C-A-Space back to visual studio the space works like it should.

**Comment by crzytrane** [comment]
Thanks @Mattias1, Good to know it works for other people too! Should these Labels on this issue be swapped out for a Bug Label or is it too soon? At the very least I think the Resharper Label should be taken off unless I'm mistaken.

**Comment by GitMyCode** [comment]
Wow thanks! @crzytrane it worked for me too finally!

**Comment by Mattias1** [comment]
Errrm, why is this closed? Handling C-A-Space with visual studio is a workaround right? Not a fix.

Or am I mistaken.

**Comment by crzytrane** [comment]
I agree with you @Mattias1, I was suggesting the Need More Data and Resharper Labels could be taken off and swapped for a Bug Label.

**Comment by jhamm** [comment]
This looks similar to #1787 and that has been reported as fixed.

**Comment by Mattias1** [comment]
Confirmed, giving Ctrl-Alt space back to vsVim now doesn't give problems anymore. Looks like this issue is fixed, thanks @jhamm and @jaredpar!
