### ISSUE TITLE
CTRL+B does not work

### ISSUE THREAD

**Issue by makcakaya** [jaredpar/VsVim#1692]
I enabled CTRL+B and CTRL+F to page-up and down with VsVim. CTRL+B does not work, CTRL+F does.

(CTRL+B) was pressed. Waiting for second key of chord...

Visual Studio 2015 Pro 14.0.23107.0 D14REL
VsVim 2.0.1.0

**Comment by jaredpar** [comment]
@makcakaya sounds like <kbd>Ctrl+B</kbd> is still mapped to a Visual Studio command.  Have you used the VsVim options to switch control to VsVim for this keyboard entry? 

- Tools -> Options -> VsVim -> Keyboard
- Select VsVim for the relevant keys

**Comment by makcakaya** [comment]
Yes, CTRL+B and CTRL+F is set to be handled by VsVim.

![Screenshots](http://imgur.com/a/rBblB)

**Comment by jaredpar** [comment]
Hmm, seems like some command is still overriding those keys then even though VsVim tried to remove them.  Can you run the command `VsVim.DumpKeyboard` from the Command Window inside Visual Studio and paste the results here?   The output will be stored in `%LOCALAPPDATA\VsVim\keyboard.txt`

**Comment by ricksladkey** [comment]
@makcakaya That screenshot shows "(Ctrl+B) was pressed.  Waiting for second key of chord..."

I'm guessing it is relevant that `Ctrl+B` is the first key of a multi-key binding.

**Comment by makcakaya** [comment]
[keyboard.txt](https://github.com/jaredpar/VsVim/files/36767/keyboard.txt)

**Comment by jaredpar** [comment]
It looks like Edit ToggleBookmark, NextBookmark and PreviousBookmark are all using <kbd>Ctrl+B</kbd>.  Try manually removing those key bindings.

**Comment by makcakaya** [comment]
Yep, I removed those bindings and it works now. Thank you.

**Comment by Eternal21** [comment]
Had the same issue, but in my case it wasn't Bookmark chords, but Build.BatchBuild and Build.Buildfullprogramdatabasefile chords that were causing the issue (I'm guessing they're Resharper related).  An easy way to find out which chords are the culprits is by pressing the first chord inside Options > Environment > Keyboard.
