### ISSUE TITLE
a problem with visual assist x

### ISSUE THREAD

**Issue by nooberfsh** [jaredpar/VsVim#1694]
when i input something like: vector<>  when i finish typing , i enter ESC then i quickly, then the cursor is on the '<' and did not go into input mode. 
when i uninstall visual assist x , the problem is gone, but visual assist x and vim are both important for me.

 please fix the problem , thanks very much

**Comment by jaredpar** [comment]
Curious: have you enabled the registry flag that asks Visual Assist to work with VsVim?

**Comment by huadaxiang** [comment]
i had look through the all options in va, i did not see the registry flag you said, is it somewhere else?

**Comment by jaredpar** [comment]
Here is the information about the key

http://support.wholetomato.com/default.asp?W271
