### ISSUE TITLE
Tab and Shift Tab over multiple lines inserts gv characters

### ISSUE THREAD

**Issue by jakeday** [jaredpar/VsVim#1697]
For some reason, when tabbing or shift tabbing multiple lines of code, the gv characters are getting inserted. This is using the stock vsvimrc config on Visual Studio 2013.

**Comment by jaredpar** [comment]
Can you post the contents of your vimrc file?  It's possible VsVim is picking up a setting from that file it's misinterpreting which is causing this behavior.

**Comment by jakeday** [comment]
Where would I find the vsvimrc file? This is a clean install of Visual Studio 2013 and VsVim.

**Comment by jaredpar** [comment]
@jakeday typically it will be in the `%USERPROFILE%` directory. 

Note: a vsvimrc file will only be created if you created one yourself.  But VsVim will read a normal `.vimrc` file, used by gVim, if it finds one.

**Comment by jakeday** [comment]
I did not create one, and I enabled the option to ignore the .vimrc from gVim. Is something there interfering?

**Comment by jaredpar** [comment]
Try running `:set` with no arguments on the command line. Two of the options displayed should be vimrc and vimrcpaths. The vimrc value is the file which VsVim chose as the vimrc file and vimrcpaths is the set of paths it looked at for the vimrc.

Also you can run `:map` with no arguments as well.  That should list any mappings that were being incorrectly read here.
