### ISSUE TITLE
Comment out with "gcc" or "gc" 

### ISSUE THREAD

**Issue by JordanTHarris** [jaredpar/VsVim#1701]
It would be awesome to be able to comment out text with the <kbd>gcc</kbd> (current line) or <kbd>gc</kbd> (selection) key presses. I have to kind of fake this by using something like this:

```vim
    nnoremap gcc :vsc Edit.CommentSelection<CR>
    vnoremap gc :vsc Edit.CommentSelection<CR>
```

This only lets me comment text out though. I can't uncomment text with it. I use this vim feature quite a lot and it's quite surprising it isn't here yet. I hope to see it sometime soon!

**Comment by digitalcosmos** [comment]
I personally use the built in Visual Studio shortcuts:
`<C-K> <C-C>` - *K*omment *C*reate
`<C-K> <C-U>` - *K*omment *U*ndo

I would suggest to map Caps Lock to Control (maybe OS wide) as that makes this kind of shortcuts really quick and easy to hit.( Hold `caps` with left pinky, hit `kc/ku` )

**Comment by JordanTHarris** [comment]
@digitalcosmos I use that for undo because it's less common, but I find <kbd>gcc</kbd> quicker. Funny enough, I actually do use Caps Lock for Control, as well as Escape. When I press it on its own, it's Escape. When I press it in combination with another key, it's Control. I can do that, as well as many others great things, thanks to AutoHotKey. I agree, that makes a lot of things easier and faster to hit. 

I use some other editors too, with Vim emulation plugins, and its just really nice having Vim-like  behavior by default. I don't have to remember more key combinations than I have to.

**Comment by jaredpar** [comment]
Thanks for taking the time to file this request. 

Unfortunately I don't believe this is a vim command.  I believe it's a feature of the vim-commentary plugin.  Right now there are no plans in VsVim to support arbitrary plugins.

**Comment by JordanTHarris** [comment]
Interesting. I didn't even know that. I just know that every other Vim emulation plugin I use (IdeaVim,  Vintage out,  and I think Vim-Mode)  has this feature.  I guess those developers thought it was a good feature to add,  but I can understand if you don't want to add it.  It's a seriously useful feature to have though. I guess I could just use <leader> for uncommenting and get use to that.

**Comment by grobgl** [comment]
You can use the [Toggle Comment extension](https://marketplace.visualstudio.com/items?itemName=munyabe.ToggleComment) to achieve this behaviour. Install, then add the following to your .vsvimrc:
```
nnoremap gcc :vsc Edit.ToggleComment<CR>
vnoremap gc :vsc Edit.ToggleComment<CR>
```

**Comment by djalan** [comment]
> You can use the [Toggle Comment extension](https://marketplace.visualstudio.com/items?itemName=munyabe.ToggleComment) to achieve this behaviour. Install, then add the following to your .vsvimrc:
> 
> ```
> nnoremap gcc :vsc Edit.ToggleComment<CR>
> vnoremap gc :vsc Edit.ToggleComment<CR><Esc><Esc>
> ```

It works, but `gc` is very slow with the trailing `<Esc><Esc>`

After testing, it works very well/fast without the two Esc.

```
nnoremap gcc :vsc Edit.ToggleComment<CR>
vnoremap gc :vsc Edit.ToggleComment<CR>
```
