### ISSUE TITLE
Feature request: Repeat Last Command

### ISSUE THREAD

**Issue by digitalcosmos** [jaredpar/VsVim#1702]
Hi @jaredpar,
If you type `@:` in vim, it repeats the last ex command. In VsVim we have to do `:<Up-Arrow><CR>` for the same behavior, which moves the hand away from the home row.

An example where this feature is useful is when performing a substitution on 1 line and then wanting to repeat.

Thanks!

**Comment by jaredpar** [comment]
Thanks for filing this request.  It is already covered by issue #1115.  Hoping to get this into a future release.
