### ISSUE TITLE
VSVim crashing Dev Studio 2012

### ISSUE THREAD

**Issue by allender** [jaredpar/VsVim#1703]
Hi - I have been experiencing crashes of Dev Studio 2012 for a while.  I finally started it with extension logging and waited for a crash to see what might be happening.  I am not entirely sure that this is VsVim, but due to the small number of extensions that I'm running, and the callstack, I have a suspicion that it might be.

I can't give you any detailed repro case.  Only that I start moving my cursor and dev studio will stop responding.  The activitylog.xml contains this:

```
System.ArgumentNullException: Value cannot be null. Parameter name: targetSnapshot at
Microsoft.VisualStudio.Text.SnapshotSpan.TranslateTo(ITextSnapshot targetSnapshot, SpanTrackingMode spanTrackingMode) at
Microsoft.VisualC.CppOutliner.GetTags(NormalizedSnapshotSpanCollection spans) at
Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__16.MoveNext()
```

I have the following extensions installed:
* VsVim
* P4VS
* Solution Explorer Collapse and Sync (although this was installed after my crashes started)
* Several PS4 development extensions (that are not in use)
* Productivity Power Tools

Based on the callstack, it appears VsVim related, although I cannot be 100% certain.  Is this information helpful?  Is there something that I can do to provide more information?  Or do you think that this might not even be VsVim related?   Thanks.

**Comment by jaredpar** [comment]
Thanks for reporting but this is a known issue in the C++ language service in Visual Studio.  I'm pretty sure it was fixed in more recent versions of Visual Studio.
