### ISSUE TITLE
Wrong behavior with "substitute line" (S key)

### ISSUE THREAD

**Issue by JordanTHarris** [jaredpar/VsVim#1706]
In Vim, when you substitute the line using <kbd>S</kbd> or <kbd>cc</kbd>, the caret will return with the same indentation as the previous text.

In VsVim, the caret <strong>always</strong> returns to the very first column of the text editor.

**Comment by jaredpar** [comment]
Do you have `autoindent` set in your vsvimrc / vimrc file?  The <kbd>S</kbd> and <kbd>cc</kbd> command only go to the same indentation when `autoindent` is set.  When it is not set they reset to column 0.  VsVim emulates this behavior.

**Comment by JordanTHarris** [comment]
Wow, I feel dumb for that. No I didn't have `autoindent` turned on. It seems to work exactly as expected with it on. Sorry about that. I tried figuring out why it did that but came up dry. Thank you!

**Comment by JordanTHarris** [comment]
Wow, I feel dumb for that. No I didn't have `autoindent` turned on. It seems to work exactly as expected with it on. Sorry about that. I tried figuring out why it did that but came up dry. Thank you!

**Comment by jaredpar** [comment]
No problem.  It's a common mistake.

**Comment by Janiels** [comment]
I have the same problem, but I have autoindent set. What would be the best steps to track down what the problem is, or what might be misconfigured?
Here is a gif demonstrating the behavior:
![Here is a gif](http://i.imgur.com/dyTfiX8.gifv)
I am pressing S at all the normal -> insert mode transitions.

**Comment by jaredpar** [comment]
@Janiels right now `cindent` isn't supported.

**Comment by Janiels** [comment]
I see. Thanks for the response.
