### ISSUE TITLE
"Surround With..." and VsVim

### ISSUE THREAD

**Issue by S0und** [jaredpar/VsVim#1707]
After a Surround With command, VsVim keeps going into INSERT mode. After the surround i do not go into insert mode by my on choice, the only thing i do is pressing ESC furiously and 'hjkl'-ing.

https://youtu.be/XDR3p-H-rOM

**UPDATE: Paxxi's comment solved it, which is simply press Enter (multiple times, if needed).**

**Comment by jnothstine** [comment]
I have used Surround With... and it puts vsvim into a weird state.  I end up having to Visual Studio and restart it.  I quit trying because I never got any success with it.  I would love to see that work correctly.

**Comment by S0und** [comment]
As you can see, for me, it snaps out from this "wierd state" on it's own, but yeah, sometimes i have to restart VS.

**Comment by Paxxi** [comment]
Try hitting enter after the surround with. I've noticed the same issue when using other snippets like prop. Once you've hit enter to "close" the inputs that belong to the snippet everything is back to normal again.
