### ISSUE TITLE
Handle dead keys on key press

### ISSUE THREAD

**Issue by pescuma** [jaredpar/VsVim#1711]
Is it possible to handle dead keys in the keyboard on key press? Currently, to type `^` I need to type `^<space>` in my keyboard (because `^` is a dead key).

**Comment by jaredpar** [comment]
Dead keys is an area that I've frankly gotten wrong a number of times and only change with great care now.  Can you give me a bit more info here?  In particular what layout / language you use and where you are typing space at (normal mode, insert, etc ...).

**Comment by pescuma** [comment]
I use the Brazilian ABNT2 keyboard. I can also test it with the US International and UK international. I was talking about the normal mode.

IMHO, the best way to handle dead keys would be to accept them when the text would be sent to the document, and just use the key presses otherwise. (Please keep in mind that I'm a new vi user). For example, accept dead keys in insert mode, inside the text for search and replace strings, etc. And just use the key presses in other places.

But if this would complicate things too much, I'd suggest a simplification: accept dead keys only in command and insert mode. My reasons for this are:

  - In insert mode, because this is where I'm typing the document text, if I type `^a` I get an `â`
  - In command mode, because I assume that search and replace are the most common commands, they would be accepted too
  - Now, in normal mode, the only reason that I can think of for having the dead keys is to map commands to accented chars. I'll go on a limb here and say that this won't happen much. Generally, I think it would be better to type `^` once instead of having to type `^<Space>` or `^^` to trigger the go to start of line command. The other case where this might represent a problem is with the `r` command. If I understood correctly, `r` don't send you to insert mode, so just after an `r` it would make sense to accept dead keys (so that I could type `r^a` to replace the current char with `â`). But I'd gladly accept this not working in exchange for having to type only once `^`, `'` and `"`

**Comment by jaredpar** [comment]
Curious: how does gVim handle these cases?

**Comment by pescuma** [comment]
Just tested it: gvim does the same as VsVim: always uses the dead keys (so you need to type `^^`)

**Comment by jaredpar** [comment]
That's what I was suspecting here.  Keyboard handling is very tricky and VsVim tries to emulate gVim as much as possible.  Is there a way gVim provides to make this easier to type?

**Comment by Janiels** [comment]
In this particular case <kbd>_</kbd> is a good alternative to <kbd>^</kbd>, and is much simpler to type. The only other case of dead keys I use is <kbd>`</kbd> for going to a mark. Since VsVim already matches gVim in this behavior, I don't think it should be changed though.

**Comment by pescuma** [comment]
@jaredpar I found this in vim's repo: https://github.com/vim/vim/pull/399 (there are a few other issues related to this). Also found http://stackoverflow.com/questions/3937237/gvim-us-international-not-combining-dead-keys-with-space . I'd be glad if it would be possible to disable them in normal mode at least (maybe a flag to set?)

@Janiels Thanks for the `_`, I didn't knew that one. I'm having a lot of problems with `'` and `"` (and, to a lower level, `~`) which are all dead keys here. (` ` ` is also a dead key here)

**Comment by pescuma** [comment]
I've created issue #1759 as an alternate approach to fix this problem.

**Comment by ricksladkey** [comment]
@pescuma I am unclear on how implementing digraphs solves the dead key problem. Do you mean that with digraphs enabled, then VsVim could revive all dead keys or that the user could configure their keyboard so that there are no dead keys?

**Comment by pescuma** [comment]
The second option, the user could configure their keyboard so there are no dead keys. This is actually what I do. When I need to type some chars (like á) I change my keyboard layout and then change it back later. With digraphs I could just not change it at all.

**Comment by ricksladkey** [comment]
Thanks, I'll think about how hard digraphs would be.

**Comment by pescuma** [comment]
Thank you.

**Comment by pescuma** [comment]
@ricksladkey Thanks a lot for that! I'll test it when the new version is out. 

What do you mean by dead key suppression in normal mode?

**Comment by pescuma** [comment]
@ricksladkey Ok, got it. When you said suppression I thought you wanted to ignore the key completely, and not just treat it as a normal key.

In that case, afaik, vim does not do dead key suppression in normal mode. At least in my machine (using vim from mingw and gVim for windows) dead keys still work as dead keys in normal mode.

**Comment by ricksladkey** [comment]
@pescuma OK, my gvim 8.0 doesn't do it either (I thought I might not have enabled it somehow) and we have digraphs, so I'll close this issue.
