### ISSUE TITLE
VsVim conflicts with the new C# Interactive Window

### ISSUE THREAD

**Issue by ichpuchtli** [jaredpar/VsVim#1713]
Somehow VsVim prevents you adding a space in the C# interactive window. Disabling VsVim resolves the issue.

References
https://www.visualstudio.com/en-us/news/vs2015-update1-vs.aspx#Csharp

**Comment by jaredpar** [comment]
Thanks for reporting.  I will take a look at that.

**Comment by cogwheel** [comment]
In the meantime, `shift-space` seems to work as `space` should, or you can run `csi` in the VS developer command prompt (albeit without intellisense).
