### ISSUE TITLE
<C-r><C-w> does not put current word in status line

### ISSUE THREAD

**Issue by canro91** [jaredpar/VsVim#1714]
First, thanks for bringing vim to VS. Here it's the thing: `<C-r><C-w>` does not put the current word in status line. I tried it using VS 2013 and 2015 Pro, with no vsvimrc file.
- Steps:
	- Put cursor in any word
	- Type `:s/`
	- Hit `<C-r><C-w>`
	- When `<C-r>` is typed, a double quote (") is shown in the status line. But the word is not
	paste in status line.

**Comment by jaredpar** [comment]
Thanks for reporting.  I'll take a look at getting that implemented.  I thought I had done that when I did the general <kbd>Ctrl+R</kbd> support but looks like I missed that case.

**Comment by jhamm** [comment]
I am working on this one. I will add `<C-r><C-a>` with this PR.

**Comment by jhamm** [comment]
The referenced PR has the fix and tests for this issue.
