### ISSUE TITLE
Mapping crv doesn't work

### ISSUE THREAD

**Issue by pescuma** [jaredpar/VsVim#1716]
The mapping `nnoremap crv :vsc ReSharper.ReSharper_IntroVariable<CR>` does not work. Instead, it puts the editor in visual mode.

**Comment by mattrrichard** [comment]
What version are you running?  I cannot reproduce this issue in 2.0.401.  

Is it possible that your vsvimrc file isn't being loaded?  Have you tried running it directly in VS using <kbd>:</kbd>?

**Comment by pescuma** [comment]
You are right. I don't know what I did, probably I used the wrong file. It's working :)

**Comment by mattrrichard** [comment]
Glad to help :) :+1:
