### ISSUE TITLE
Completion Mode (Ctrl-X in insert mode)

### ISSUE THREAD

**Issue by ijcuevas2** [jaredpar/VsVim#1718]
I don't know if this is already supported. VsVim should support line completion as in regular vim. For example, using the Ctrl-X Ctrl-L shortcut in insert mode to autocomplete lines is quite useful.

**Comment by awojcik-lgnexera** [comment]
Yes, this would be very useful. Or maybe this is already implemented but some configuration is needed?

**Comment by farzadmf** [comment]
I like Ctrl-X feature in vim A LOT. It would be so nice if it would work here ...

**Comment by ricksladkey** [comment]
This is a duplicate of issue #1718 and so this issue can be closed.

**Comment by dtynewydd** [comment]
> This is a duplicate of issue #1718 and so this issue can be closed.

Am I crazy or is the lissue linked *this* issue? Did this ever get implemented?

**Comment by wayneforrest** [comment]
> This is a duplicate of issue #1718 and so this issue can be closed.

Perhaps that reference number is not correct, this issue itself is #1718 (a circular references)
