### ISSUE TITLE
Clipboard failure handling is broken

### ISSUE THREAD

**Issue by baldurk** [jaredpar/VsVim#1725]
Following up from #1675, I have the same problem if I install a recent build (for a long while I had a locally hacked build so I only just started seeing it). It seems the `_useTextMethods` backup case is never actually set to false when retrying fails in [ClipboardDevice.cs](https://github.com/jaredpar/VsVim/blob/master/Src/VimWpf/Implementation/Misc/ClipboardDevice.cs). I think you want to make the change below:

```diff
index 794ee74..6696850 100644
--- a/Src/VimWpf/Implementation/Misc/ClipboardDevice.cs
+++ b/Src/VimWpf/Implementation/Misc/ClipboardDevice.cs
@@ -83,7 +83,7 @@ namespace Vim.UI.Wpf.Implementation.Misc
                     if (i == 0)
                     {
                         _protectedOperations.Report(ex);
-                        _useTextMethods = true;
+                        _useTextMethods = false;
                         return false;
                     }
                 }
```

This seems to have been a typo introduced in the refactoring in d682bcc51, as the original catch-exception-and-backoff code was added way back from the original issue I reported #1430. 

For what it's worth I seem to have a 100% repro for the buggy behaviour on VS2010, VS2013, VS2015. *Every* time I do a `dw` then it hangs for a few seconds then throws an exception, so this backoff code is really needed :smile:.

If there's any investigation or logging you want to do to try and track down what's happening let me know, since I don't think the clipboard should be so reliably broken. As talked about there's nothing to be done about random errors - but even when I orignially reported it I remember it being quite intermittent which would fit more with the idea of clipboard synchronisation clashes than this consistently 100% broken state.

**Comment by jaredpar** [comment]
Good catch.  Will submit a fix for that shortly.
