### ISSUE TITLE
Recorder macro disappear after Visual Studio restart

### ISSUE THREAD

**Issue by kmorcinek** [jaredpar/VsVim#1726]
Every time I restart Visual Studio I need to record macros again. For example in gVim in my system I don't have this problem.

**Comment by jaredpar** [comment]
VsVim doesn't yet save registers (where Macros are stored) between restarts yet.  I'll look to get that added in a future release.

**Comment by kmorcinek** [comment]
Any ideas for current workarounds for that? It is limiting use of macros quite a lot.

**Comment by mattrrichard** [comment]
You can save them in your vsvimrc like this:

```
let @g="macrotexthere"
```

This can get somewhat tricky, though when your macros contain special keys like <kbd>Esc</kbd>.  You can still enter these by using <kbd>Ctrl+v Esc</kbd>.  

However, I'm not sure if it's possible to save a macro that contains <kbd>Enter</kbd> in this way as I wasn't able to find a way to encode that character.  Using actual vim, I was able to insert the special character `^M`, but VsVim treats this as an actual line break and fails to parse the file.  Bug?

example: 
VsVim treats this: ``` let @g="/search^MdwP" ```

as this:

``` 
let @g="/search
dwP"
```

**Comment by chrat7** [comment]
I tried the VsVim v2.2.522 . The macro is not replayed properly. May I know while storing the session when we close visual studio, what is the path of file that will store the registers(session)?

**Comment by kmorcinek** [comment]
Registers between restart are still not working for me. 

when I type ":reg" to see all of them I have some old code in some of them (ie. "c, "d, "x, and some are not shown). So I know that there were recorded at some point in the past. 
When I run as Admin nothing changes. I had for couple month version 2.2, now I have just installed 2.2.522. I restarted VS, restarted the system. Nothing happens.

**Comment by kmorcinek** [comment]
@mattrrichard where is located vsvimrc?

**Comment by mattrrichard** [comment]
That will depend on your OS, but you can open it directly in visual studio with vsvim by doing `:e ~/_vsvimrc`.
