### ISSUE TITLE
Is there any way to map jj as <ESC> in insert mode?

### ISSUE THREAD

**Issue by yifanchen** [jaredpar/VsVim#1732]

**Comment by jaredpar** [comment]
This can be done with a standard `imap` command:

```
:imap jj <ESC>
```

I just verified that works on VS 2015.  Is this not working for you?

**Comment by yifanchen** [comment]
How does this actuallly work? Do you just add this line in your windows .vimrc? I am using virtual machine with fusion windows 10 on macbook pro, trying not to do any command line thing in windows.

**Comment by jaredpar** [comment]
I usually just mappings like that to my vsvimrc file.

**Comment by mechoid9** [comment]
I know this is closed, so I hate to comment, but imap doesn't seem to work for my installation of VsVim on VisualStudios (2013).

None of the following works:
`imap jj <Esc>`
`:imap jj <Esc>`
`:imap jj <ESC>`

However, I can set 'jj' to `<Esc>` in command mode after startup.

**Comment by jaredpar** [comment]
@mechoid9 can you give me a bit more detail:

- What type of project are you working on: web, console app, etc ...? 
- What other extensions do you have installed?

**Comment by mechoid9** [comment]
I'm using VS to work on a console app (programmed in C# and C++), but it does the same thing for every project I open. Also, I checked that it's looking at the right vimrc:

`:set vimrc <ENTER>`
`vimrc="C:\Users\MY_REAL_NAME\_vimrc"`

Installed Extensions:
- Behaviors SDK (XAML)
- Microsoft Advertising pubCenter Service for Visual Studio
- Microsoft Advertising SDK for Windows 8.1
- Microsoft Visual Studio ASP.NET MVC 5 Scaffolding
- Microsoft Web Developer Tools
- NuGet Package Manager for Visual Studio 2013
- Visual F# 3.1
- Visual  Studio Extensions for Windows Library for JavaScript
- VsVim
- Workflow Manager Activities

**Comment by jaredpar** [comment]
@mechoid9 can you run `:map` and `:imap` and paste the results?

**Comment by mechoid9** [comment]
`:imap <ENTER>`
` `
`:map <ENTER>`
` `

Nothing shows up. After I do `:imap jj <Esc>` the output of `:imap` is:
`i    jj <Esc>`

**Comment by gibwar** [comment]
Just figured I'd chime in and mention it works for me, though I use `inoremap` rather than `imap`.

vsvim:
```
inoremap jk <Esc>
inoremap <C-Enter> <C-o>O
```

output:
```
i    jk <Esc>
i    <C-CR> <C-O>O
```

**Comment by mechoid9** [comment]
Thanks; I tried it. Having `inoremap jj <Esc>` in my vimrc file does nothing; however, running it from the command prompt inside of visual studio does work. 

I have a lot of stuff in my vimrc file (I use it on multiple computers/OSs). I wonder if something in it is preventing the file from being parsed correctly?

**Comment by mechoid9** [comment]
I've added my normal vimrc file (vimrc.bak) and a paired down vimrc. The paired down vimrc works as expected. 

[vimrc.zip](https://github.com/jaredpar/VsVim/files/341860/vimrc.zip)

**Comment by jaredpar** [comment]
> The paired down vimrc works as expected.

This combined with the other entries in this issue indicate the `vimrc` file you are using can't properly be handled by VsVim.  If there are simple issues in the parsing that can help I'm usually up for fixing them.  Generally though the recommendation is to use a separate `vsvimrc` file that holds the settings supported by VsVim.

**Comment by mechoid9** [comment]
Thank you for the help. I'll just use the separate vsvimrc.
