### ISSUE TITLE
Go back to the line just yanked `` is not working

### ISSUE THREAD

**Issue by jasjuang** [jaredpar/VsVim#1733]
After we yank a line, and lets say go down 5 lines to paste, `` should take the cursor back to the original line but it isn't

yy
5jp
`` ---> this is not working

Will appreciate if you can look into this.

**Comment by jaredpar** [comment]
Thanks for reporting that.  I will look at getting that implemented.

**Comment by jhamm** [comment]
Hi, I am not able to reproduce this behavior in vim/gvim.
in a buffer of:
````
1
2
3
4
5
6
7
8
9
0
````

from normal mode:
````
10G
m'
1G
yy
5jp
''
````

The cursor is on 11,1.

 If "yy" was overwriting the previous context mark, the cursor should be at position 1,1.

Can you provide more information about this please?

**Comment by jasjuang** [comment]
In this case it should be

```
10G
m'
1G
yy
5jp
`''
```

According to http://vim.wikia.com/wiki/Using_marks

''  jump back (to line in current buffer where jumped from)
`" jump to position where last exited current buffer

**Comment by jhamm** [comment]
Yup, you are right. I was reading ` as '.

**Comment by jhamm** [comment]
I have a working mark " at [jhamm/VsVim/fix-1733](https://github.com/jhamm/VsVim/tree/fix-1733).

I am now working on mark ``

When they are completed, I will create a PR.

**Comment by jhamm** [comment]
This one can be closed, the PR has been merged.

**Comment by jasjuang** [comment]
Thanks a lot for making this happen!

**Comment by jhamm** [comment]
Glad I can help :smile:
