### ISSUE TITLE
Double command margin

### ISSUE THREAD

**Issue by zolem** [jaredpar/VsVim#1734]
I am having a weird issue where I have a double command margin. It's not really a problem but does make the command margin appear very bulky. I tried just turning it off and using the status bar but you can't see the status bar when you pull tabs out to another monitor. I wonder if there is just a setting I broke or an extension conflict. Maybe this is expected behavior and I don't know what I am talking about. Thanks again!

![image](https://cloud.githubusercontent.com/assets/7129911/12332960/b02ef3a0-baae-11e5-84bc-955f402ba7cd.png)

**Comment by gibwar** [comment]
Based off your `.vimrc` in #1722 the double line is being caused by

```vim
set laststatus=2
```

(which you actually set more than once)

VsVim has a default of 0, so you'll need to change it to `0` to remove it.

**Comment by zolem** [comment]
Ok cool I will check it out thanks.
