### ISSUE TITLE
Add a command to build the solution

### ISSUE THREAD

**Issue by hmny** [jaredpar/VsVim#1735]
This is not a bug! Just a suggestion. That would be nice if you can build the solution using a shortcut like `:b` which I don't think is mapped to anything else.

**Comment by zolem** [comment]
This is a good way to do it. I don't know how to remap something to be a :command but the leader is my favorite thing to use to map visual studio specific commands.
noremap <leader>b :vsc Build.BuildSolution<cr>

**Comment by jtbm37** [comment]
As zolem mentioned above you can call most visual studio commands from the command line.

```
nmap ,c :vscmd Build.BuildSelection<CR>
nmap ,C :vscmd Build.BuildSolution<CR>
```

**Comment by hmny** [comment]
awesome! thanks for the tips
