### ISSUE TITLE
Yank with a setting clipboard=unnamed should be placed to the register 0 too.

### ISSUE THREAD

**Issue by idealist1508** [jaredpar/VsVim#1738]
How to reproduce:

```
:set clipboard=unnamed
yy
:reg 0 
  -> is empty
```

**Comment by idealist1508** [comment]
I was trying to fix it, but i got an Error
The type 'ClipboardOptions' is not defined in
https://github.com/idealist1508/VsVim/blob/CopyToUnnamedFix/Src/VimCore/Register.fs#L569

I don't understand why? 
@jaredpar: Can you help me with it.

**Comment by jaredpar** [comment]
@idealist1508 not sure why you would get that error as that type is defined in the project.  Are you sure nothing else changed which could have moved / deleted that type?

**Comment by idealist1508** [comment]
@jaredpar Yes, I am sure. I only add a new parameter to https://github.com/idealist1508/VsVim/commit/ffb4b1c685803af89bd0769ef2514542c716816e#diff-96e864afc9fb1f7f309e9318eb130074R569
Can you try to compile code from my branche https://github.com/idealist1508/VsVim/tree/CopyToUnnamedFix? Thanks

**Comment by jaredpar** [comment]
The reason you're getting that error is you're trying to use `ClipboardOptions` before it's been defined.  F# processes files in the order they appear in Solution explorer (top down).  In this case `ClipboardOptions` is defined in `VimSettingsInterface.fs` but you're using it in `Registers.fs`.  The latter file gets processed first hence the error.

**Comment by idealist1508** [comment]
You are right. I read about this (and forgot). Thanks.

**Comment by ernestobarros** [comment]
Missing this fix - to make everything work smoothly.

**Comment by idealist1508** [comment]
I can look at this again at weekends. But I am only the beginner in F#, so if somebody fix it i will not cry.

**Comment by idealist1508** [comment]
Hier is my Fix #1830
