### ISSUE TITLE
Intermittent VS hangs when used with Resharper

### ISSUE THREAD

**Issue by mattrrichard** [jaredpar/VsVim#1741]
Occasionally my visual studio hangs for 10-15 seconds, and it _seems_ to only happen when I have VsVim and ReSharper enabled together.  

I'm honestly not even sure this is something VsVim is doing, and I know this is unbelievably vague, but how can I even start to figure out what is happening?

**Comment by jaredpar** [comment]
Can you grab a dump of Visual Studio when this hang happens?  That shuold give me enough context to track this down.

[Instructinons for grabbing a dump](http://blogs.msdn.com/b/debugger/archive/2009/12/30/what-is-a-dump-and-how-do-i-create-one.aspx)

**Comment by WillemMali** [comment]
I experience this problem as well since I got ReSharper.

Sadly I don't have time to make a process dump and remove personal/work data from it. Is there any other way in which I could help?

**Comment by mattrrichard** [comment]
I've recently switched projects to a much, _much_ smaller project and this problem hasn't actually happened in weeks.  I still keep procdump handy in case it does....

**Comment by jaredpar** [comment]
> Sadly I don't have time to make a process dump and remove personal/work data from it. Is there any other way in which I could help?

If you create a mini-dump the amount of personal info is pretty constrained because it doesn't include anything from the heap. Mostly I'm just interested in the stack traces because that will give me the information I need to track this down.
