### ISSUE TITLE
';' interpreted as '.' on an azerty keyboard (french layout) with VisualAssist

### ISSUE THREAD

**Issue by smatcher** [jaredpar/VsVim#1751]
Hello.

I just installed VSVim and noticed that there is problem with the semicolon key in command mode.
On azerty keyboards the dot is on the semicolon key, you reach '.' by pressing shift + ';'
This issue only appears in command mode when the VisualAssist plugin is enabled.

Disabling VisualAssist solves this issue.
I didn't find a VisualAssist setting solving the issue (appart from disabling it entirely).
I didn't find an other key causing a similar issue.

I use the following configuration
Windows 7
VS 2015
VisualAssist plugin

**Comment by jaredpar** [comment]
Thanks for reporting this issue. 

Have you contacted Visual Assist about this?  VsVim in general won't interpret key strokes in this way anymore.  It will process the char as typed.  It's possible there is a bug here but it's been a while since we've seen an issue in this area.

**Comment by smatcher** [comment]
Hi,

I haven't contacted the Visual Assist team about this yet. I noticed that similar bugs were fixed in the past and wanted to see what you could do before contacting them.
I will file a bugreport to the Visual Assist team.

**Comment by jhamm** [comment]
Can you list the case# from Visual Assist? This way we can watch the release builds and notes to see if it is included in the [Archive of Visual Assist builds and release notes](http://support.wholetomato.com/default.asp?W422).

According to [Visual Assist Case Numbers page](http://support.wholetomato.com/default.asp?W318) there is no way of directly tracking, but they will list them in the release notes and one can request a status update in their forums.

**Comment by smatcher** [comment]
Hi,

The case number is 95429
