### ISSUE TITLE
gd does not feed the jump list

### ISSUE THREAD

**Issue by Chadehoc** [jaredpar/VsVim#1752]
Hi,
`gd` does not seem to be recorded as a jump, `''` does no work next ("mark not set").

**Comment by jaredpar** [comment]
The `gd` command does feed the jump list as seen below:

https://github.com/jaredpar/VsVim/blob/9548fd76d595e371c1a78043699ec49240d1329b/Src/VimCore/CommonOperations.fs#L710

The issue seems to be that the " mark is not supported.  Can you point me to some more information on this?

**Comment by Chadehoc** [comment]
> The issue seems to be that the " mark is not supported.
> Can you point me to some more information on this?

Do you mean the `'` (single quote) mark?  All I can notice is that `''` (doubled single quote) brings me back after most other jumps, but not after `gd`. The linked code seems to do the job, but in the end it doesn't work for me.

**Comment by ricksladkey** [comment]
@Chadehoc  Is it possible that `gd` navigated to a different buffer? Unfortunately, the jump list is local to a buffer.

**Comment by Chadehoc** [comment]
Ah, that must have been it!
I now use `Ctrl-O`to go back, it works fine.
I didn't remember this issue, I guess you can close it.
