### ISSUE TITLE
selection using mouse in VISUAL LINE mode selects parts of lines

### ISSUE THREAD

**Issue by jankner** [jaredpar/VsVim#1756]
Moving the selection by shift-clicking allows me to select partial lines when in Visual Line mode, which is not how vim behaves. In vim the entire line is selected when you shift-click in Visual Line mode.

**Comment by jankner** [comment]
Something I just realized: The partial line selection appears to be only visual. Commands still work as if entire lines have been selected.

**Comment by jhamm** [comment]
This could be related to #1628. There is an open PR that resolves similar issues.
