### ISSUE TITLE
Disable VsVim ctrl+shift+F12 goes to AssemblyInfo

### ISSUE THREAD

**Issue by eleijonmarck** [jaredpar/VsVim#1757]
Visual Studio 2015,
Windows Server 2012,

Ctrl+Shift+F12 goes to AsseblyInfo

**Comment by floatas** [comment]
I am using VS2015 on win8.1 and win10 and I don't have any issues. Did you checked Tools > Options > VsVim > Keyboard ? Maybe it is handled by Visual Studio and not VsVim

**Comment by jaredpar** [comment]
@floatas I'm guessing that in this case the key binding was used by Visual Studio.  Need to take that into account when I'm in disabled mode.

**Comment by eleijonmarck** [comment]
@floatas was right. It was used by visual studio for action : View.NextError.

Enterprise Version also.

**Comment by jhamm** [comment]
This may be related to the issues #1654 and #1713 that is fixed by PR #1745.

**Comment by jaredpar** [comment]
Looks like a dupe of #1685. This needs to be implemented as a global VS command so it can take precedence.
