### ISSUE TITLE
VS Code integration

### ISSUE THREAD

**Issue by skippermike** [jaredpar/VsVim#1758]
Would it be possible to adjust VsVim in order to provide the same, great vim functionality in VS Code editor exactly like it is already done in its bigger brother Visual Studio?

**Comment by jhamm** [comment]
The project owner may have a different idea, but I do not think that VsVim would be able to be quickly ported to VS Code. See the wiki article on this topic: [Porting VsVim to other applications](https://github.com/jaredpar/VsVim/wiki/Porting-VsVim-to-other-applications)

VS Code is a Node.js application, so it does not use WPF and the article indicates that porting to a non-WPF host would be a large undertaking.

**Comment by jhamm** [comment]
It does look like there are some other projects that have made some progress in providing vim functionality in VS Code:

https://github.com/VSCodeVim/Vim
https://github.com/74th/vscode-vim

**Comment by jaredpar** [comment]
Porting VsVim to VsCode is unfortunately not a realistic option.  Despite the name VS Code shares practically zero code with Visual Studio.  They have an entirely different model for extensions: both in API and underlying runtimes.  

VsVim relies heavily on the WPF editor and is portable anywhere that is hosted with little effort.  It cannot target non-WPF editor platforms though such as VS Code.  

As @jhamm pointed out there are several projects in the works right now.  I've met with the owner of https://github.com/VSCodeVim and they seem to have the right direction for the work.

**Comment by skippermike** [comment]
I understand. 
Thank you for all your help! 
The reason I asked for it is that I do love VsVim and I am addicted to it when using VS and I miss it very much in other editors - like VS Code which is in its early development stage.
