### ISSUE TITLE
Implement digraphs and Ctrl-K

### ISSUE THREAD

**Issue by pescuma** [jaredpar/VsVim#1759]
http://vimdoc.sourceforge.net/htmldoc/digraph.html

**Comment by jeffvandyke** [comment]
That documentation page has atrocious encoding issues - see this one: <https://vimhelp.appspot.com/digraph.txt.html>

**Comment by ricksladkey** [comment]
I have a basic implementation of digraphs working. I'll submit a PR when I'm finished.
