### ISSUE TITLE
VsVim breaks parenthesis highlighting

### ISSUE THREAD

**Issue by CodEFouR** [jaredpar/VsVim#1763]
I'm using Visual Studio 2015 Community with F# Power Tools installed. When I don't have VsVim installed the matching parenthesis are highlighted but not with VsVim installed and enabled. The parenthesis highlighting works after disabling VsVim.

**Comment by jaredpar** [comment]
I will take a look at this.  I wonder if we're using the same key for our colors.

**Comment by slav** [comment]
To add to this ticket. When I type the parenthesis or manually select parenthesis (Shift + arrow) the braces highlight while. But if i just move the cursor to it, the highlight doesn't work.

Any ideas on how to try and work around this?

**Comment by jeroldhaas** [comment]
I'm experiencing this as well. Enabling & disabling VsVim behaves the same for me as well.

This may or may not be relevant, however I noticed `Vim.VisualStudio.UnitTest.VsKeyProcessorTest.IVsTextView.HighlightMatchingBrace` is not implemented.

I've added an issue to F# Power Tools at fsprojects/VisualFSharpPowerTools#1494 as well referencing this issue. These issues are now cross-referenced.
