### ISSUE TITLE
Visual studio keybindings broken due to loading vimrc when starting from vim

### ISSUE THREAD

**Issue by Chiel92** [jaredpar/VsVim#1764]
Whenever I load Visual Studio from vim using `<F1>` with `<F1>` being

``` vim
nnoremap <F1> :!start "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe" /edit "%"<CR><CR>
```

many keys are broken, I assume due to having them remapped in vimrc, since the first time I did this, VsVim notified me that it found my regular .vimrc and decided to load it (instead of my .vsvimrc, which it loads normally).

Then I turned off the load .vimrc option in the VsVim options by explicitly restricting it to load vsvimrc only (in Options->VsVim->Defaults). However, this doesn't bring back the normal keybindings of Visual Studio when starting from inside Vim.  When starting visual studio the normal way, i.e. by clicking the sln file in explorer, all is fine.

Any idea what could be the cause of this?

Btw, the keys that are broken are also not listed in Options->VsVim->Keyboard.

**Comment by jaredpar** [comment]
That is really strange.  That should be the equivalent of just clicking on a solution file.  If you run `:set` it should display the paths that VsVim looked for the vimrc in.  Is it looking in the same places for both scenarios?  Also what does `:map` output in the incorrect case?

**Comment by Chiel92** [comment]
Thanks for you reply. After I changed VsVim to only look at vsvimrc, I was starting to think that VsVim has nothing to do with it, and looking at `:map` confirms that. The thing here is, opening a single file doesn't make Visual Studio aware of the solution, disabling many function keys. The fact that I had also remapped these in my vimrc is a coincidence.

However, when I set "VimRc File Loading" back to "vsvimrc or vimrc files", which is the default, there is a difference in behaviour. In this case Starting Visual Studio from Vim results in vimrc to be loaded, while starting Visual Studio from explorer causes vsvimrc to be loaded. Both are in the same directory.

Output of `:set`:
Starting from Vim:
```
vimrc="C:\Users\Chiel.tenBrinke\.vimrc"
vimrcpaths="C:\Users\Chiel.tenBrinke;C:\Program Files\Vim;C:\Users\Chiel.tenBrinke"
```
Starting from explorer:
```
vimrc="C:\Users\Chiel.tenBrinke\_vsvimrc"
vimrcpaths="C:\Users\Chiel.tenBrinke;C:\Users\Chiel.tenBrinke"
```

**Comment by jhamm** [comment]
When in GVIM, the MYVIMRC environment variable is set, `:ec $MYVIMRC` will be `C:\Users\Chiel.tenBrinke\.vimrc`. So when you launch Visual Studio by using `<F1>`, Visual Studio will use the environment variables from its context, in this case `MYVIMRC=C:\Users\Chiel.tenBrinke\.vimrc`.

The MYVIMRC environment variable takes precedence over the other locations when determining which RC file to load.

**Comment by jaredpar** [comment]
@jhamm seems to have tracked this down. Thanks!
