### ISSUE TITLE
VsVim support for SSMS 2016

### ISSUE THREAD

**Issue by gwojan** [jaredpar/VsVim#1766]
@jaredpar Is there any chance VsVim will support SSMS 2016? I found the link to an earlier blog article about making support work but that link appears to be offline.

**Comment by jaredpar** [comment]
The SSMS product uses the Visual Studio shell.  As such VsVim can in theory work just fine in it.  The problem is whether or not SSMS allows extensions to be installed.  Last I checked it wasn't supported but developers had found a way to ... convince extensions to work in that.  

This is the best article I could find on doing this:

> https://sqljudo.wordpress.com/31-days-of-sql-server-management-studio/ssms-day-30-vspackage-and-ssms/

Unfortunately there really isn't anything I can do on my end.  If there are bugs when VsVim is loaded in SSMS I'd be happy to look at them.

**Comment by voglster** [comment]
Just to add some color here...
I have the latest SSMS 2016 installed, firgure id try to get VsVIM working and see what error messages came up.

Only thing I did was add SSMS version 13 to the manifest

Upon loading you dont get any errors but if you goto into options and select VsVIM you see this:
![image](https://cloud.githubusercontent.com/assets/620205/21154568/714dc502-c134-11e6-8a67-d246e7be95ac.png)

and the associated log file:
[ActivityLog.txt](https://github.com/jaredpar/VsVim/files/649844/ActivityLog.txt)

if you want the xsl:
[ActivityLog.xsl.txt](https://github.com/jaredpar/VsVim/files/649845/ActivityLog.xsl.txt)


It does "kindof load" and I would be more than willing to debug this but I'd need some help know what to debug.

**Comment by jaredpar** [comment]
I looked through the log and there really wsan't anything in there about VsVim.  Just a performance warning about a failed string laod.  That shouldn't affect correctness though. 

Have you tried passing `/resetSkipPkgs` to the SSMS command line?  It's possible a previous failed load is causing a problem here.

**Comment by voglster** [comment]
unfortunately it doesn't look like ssms actually has that option... attempting to run it results in: 
![image](https://cloud.githubusercontent.com/assets/620205/21232401/1a00ce2e-c2b1-11e6-8d4c-549742e2ec89.png)

**Comment by clwalker85** [comment]
We're so close in SSMS 2017

https://trello.com/c/5mhYUt7m/87-enable-loading-of-vspackage-extensions-in-sql-server-management-studio

**Comment by NonlinearFruit** [comment]
I got this far. But the 3 VsVim options all say:
> An error occurred loading this property page

![image](https://user-images.githubusercontent.com/6962125/48880377-cee91980-edd5-11e8-9b1e-f08fa8229944.png)

---

**Steps to reproduce**

1. I copied the VsVim extension folder from Visual Studio 2015 to SSMS 2017
    - from: `C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Extensions`
    - to: `C:\Users\<username>\AppData\Local\Microsoft\VisualStudio\15.0_b1e1c6a3\Extensions`
2. Created a file `SkipLoading.2017.reg` with the package GUID in `VsVim.pkgdef`
```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\SQL Server Management Studio\14.0\Packages\{a284d12c-1e96-451b-a3b0-5486a1beb6ca}]
"SkipLoading"=dword:00000001
```
3. Double-clicked the reg file and updated the registry
4. Restarted SSMS
