### ISSUE TITLE
Problems with Supercharger

### ISSUE THREAD

**Issue by jnothstine** [jaredpar/VsVim#1772]
I have Supercharger installed.  I frequently use the Code Map feature to drag and drop methods to move them around in a file.  I also use the Code Map feature to delete methods.

These features work just fine with version 2.0.1.0 of VsVim.
When I install version 2.0.465 of VsVim, things break pretty bad.

Dragging a method or deleting one, using Code Map in Supercharger will cause the closing bracket of the method to be moved or deleted and nothing else.

I can easily just fall back to version 2.0.1.0 of VsVim so I can use both tools but, hopefully, this can be fixed so I can keep up to date with VsVim.

Thanks,

Jerry.

**Comment by jaredpar** [comment]
I've never used Supercharger before.  Can you point me at a demo to repro this?

**Comment by jnothstine** [comment]
Sorry I haven't gotten back on this.  Here is what I have:

1. Any C# project, I have tried it on two different computers with completely different projects.
2. Install VsVim, the latest build
3. Install the Visual Studio Extension named Supercharger (used to be VS10X Code Map).  Supercharger adds a panel to Visual Studio that shows the methods and properties in the class.  Right click in the window and choose Sort/As in code.  That will show the items in the order they are in the code.
4. You can then drag one method in the frame to a different location above or below where it is.  That should move the method in the file.

That works fine with the released version of VsVim.  If I grab the most recent version from http://vsixgallery.com/feed it causes this drag and drop to work incorrectly.  I originally wrote this up as a bug with Supercharger but he couldn't reproduce (before I realized that it was related to VsVim).  I uninstalled the latest build of VsVim and installed the most recent released version and the problem went away.  The guy at Supercharger said he would be glad to assist if you need him to.  You can go to http://supercharger.tools to see more about that tool.

**Comment by jnothstine** [comment]
Whatever caused this problem is gone now so this can be closed.
