### ISSUE TITLE
Autocmd file patterns containing path characters do not correctly match files in the path

### ISSUE THREAD

**Issue by patrickmoore** [jaredpar/VsVim#1774]
Given the following in a _vimrc
`au BufRead,BufEnter,BufNewFile,BufWinEnter */some/directory/* set noexpandtab`

VsVim's autocmd fails to correctly match any file in 'some/directory' due to the Visual Studio buffer file names using '\\'s for the directory separator.  

It appears that what needs to happen is either the autocmd pattern needs to be modified to replace forward slashes with back slashes, or the file name needs to have it's back slashes replaced with forward slashes.

Note that Vim's :help autocmd-pattern mentions that 

> Note that for all systems the '/' character is used for path separator (even
> MS-DOS and OS/2).  This was done because the backslash is difficult to use
> in a pattern and to make the autocommands portable across different systems.

**Comment by jhamm** [comment]
PR #1776 resolves this.
