### ISSUE TITLE
\%# support in regex

### ISSUE THREAD

**Issue by wererogue** [jaredpar/VsVim#1780]
I'd be nice to be able to use `\%#` in regular expressions to grab the cursor position please
See [\%#](http://vimdoc.sourceforge.net/htmldoc/pattern.html#/%5C%25#)

**Comment by jaredpar** [comment]
Thanks for the report.

Unfortunately this is a feature that I can't take at this time.  My regex infrastructure is based on using .NET Regex under the hood.  They have no notion of cursor position and there is no way for me to translate the cursor position into a regex element.  Hence there is no way to do this without creating a full regex engine from scratch which is currently beyond the scope of this project.
