### ISSUE TITLE
Problem with substitution command

### ISSUE THREAD

**Issue by darkpotpot** [jaredpar/VsVim#1782]
Hi,

I have this line in my code (everything is on the same line)
`*(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*6) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*6+1) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*6+2) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*6+3) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*6+4) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*6+5) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*6+6) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*6+7) +
`

I want to replace *6 with *7 so I use the following command line:

> :s/\*6/\*7/g

In vim it works perfectly and the result is
`*(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*7) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*7+1) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*7+2) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*7+3) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*7+4) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*7+5) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*7+6) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit*7+7) +
`

But in vsvim I have the following result
`*(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit\*7) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit\*7+1) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit\*7+2) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit\*7+3) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit\*7+4) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit\*7+5) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit\*7+6) + *(l_pUI8_PtrOriginCurrent+l_I32_ScanlineSize8Bit\*7+7) +
`

An extra \ is added before the *

**Comment by jaredpar** [comment]
Thanks for the report.  I'll look into that.

**Comment by jaredpar** [comment]
What settings do you have in our _vimrc file?  By default the `*6` won't match the pattern `*6`.  There must be a setting that is allowing for that to happen.

**Comment by darkpotpot** [comment]
Indeed, something might be interfering. I removed every setting and, the issue is still here with the following command : 
`    :s/\*6/\*7/g
`

**Comment by jaredpar** [comment]
@darkpotpot can you share out your vimrc file?  It must be something in there.

**Comment by darkpotpot** [comment]
The latest test I did was without any vimrc file. I put "No vsvimrc or vimrc files" in the VimRc File Loading option. Or maybe I'm misunderstanding the option.

**Comment by jaredpar** [comment]
@darkpotpot gotcha.  I missed the use of \\ in the most recent repo before the 7.  I can repro the bug with that particular substitute pattern.
