### ISSUE TITLE
enter insert mode when exit of normal mode

### ISSUE THREAD

**Issue by chantisnake** [jaredpar/VsVim#1784]
When I am in insert mode and use a mouse to select a block of code, vsvim automatically enters visual mode, which is great.

But after I have done an operation, vsvim automatically goes back to insert mode, but I want it to stay in visual mode (which is what gvim does).

any way can I do this?

**Comment by jaredpar** [comment]
Thanks for filing. I'll take a look at this.

**Comment by vavill** [comment]
After select a block of code,then press "d" , it will replace whole block with a "d".

And when drag mouse form right to left , it will not select last character .

**Comment by chantisnake** [comment]
@vavill you issue looks like select mode...

**Comment by jaredpar** [comment]
> But after I have done an operation, vsvim automatically goes back to insert mode, but I want it to stay in visual mode (which is what gvim does).

What operation are you doing here?

**Comment by jaredpar** [comment]
Closing due to staleness
