### ISSUE TITLE
Shift-C and Shift-P don't write "C" and "P" when VsVim is disabled (with Ctrl-Shift-F12)

### ISSUE THREAD

**Issue by jtpio** [jaredpar/VsVim#1787]
Hi,

When I disable VsVim with Ctrl-Shift-F12 to give the keyboard to someone else, it becomes impossible to write the characters "C" and "P" using the Shift key.
- Shift-C and Shift-P do nothing
- However, it is possible to write "C" and "P" if the caps lock key is on.
- The other characters work fine.

It only happens when VsVim is disabled and for these two specific letters. In Vim Insert mode, everything is fine.

Tested on Visual Studio 2012.

**Comment by jhamm** [comment]
I think this is similar to #1654 and fixed in PR #1745.

**Comment by jtpio** [comment]
Yes it looks like the same issue.
I guess we just need to wait for the new release to get the fix.

**Comment by jaredpar** [comment]
@jtpio a new release was just added to the gallery.  You should be able to update to 2.1.0 and see the fix now.

**Comment by jtpio** [comment]
Grabbed the new update today and it now works.
Thanks for the fix!
