### ISSUE TITLE
Snippets are impaired with VsVim 2.1.0.0

### ISSUE THREAD

**Issue by cbates-** [jaredpar/VsVim#1789]
VS2015 Pro, Win10 x64

It appears that VS snippets behavior has been degraded after installing VsVim 2.1.0.0.
I have a snippet with two replaceable items.  I insert the snippet

>xdep\<Tab\>

and the 1st replaceable item is selected; I start typing and replace the item.
When I tab, the cursor now jumps into the 2nd replaceable item, but w/o selecting it -- this is the change in behavior.  Previously, when tabbing to each replaceable item the entire item would be selected, allowing me to type the replacement value.
I hope that description is clear enough....

**Comment by jaredpar** [comment]
Thanks for reporting this.  Are you able to share out this snippet so I can test it directly?  If not I can try and substitute in one of the standard snippets and see if I can replicate the behavior.  

Also: assuming this is C# code?

**Comment by cbates-** [comment]
Thanks for the reply.
Attached is the snippet, it's pretty simple.
Let me know there is any other help I can provide...
C. Bates

**Comment by jaredpar** [comment]
@cbates- the email reply didn't capture the snippet on Github.  Could you throw it up as a gist?

**Comment by cbates-** [comment]
Not that familiar with gist, hope this works....
https://gist.github.com/cbates-/7de750b693191bab49e4ed8f7eb17bda
C. Bates

**Comment by jaredpar** [comment]
That works.  Thanks!

On Mon, Jun 20, 2016 at 4:18 PM, cbates- <notifications@github.com> wrote:

> Not that familiar with gist, hope this works....
> https://gist.github.com/cbates-/7de750b693191bab49e4ed8f7eb17bda
> C. Bates
>
> On Mon, Jun 20, 2016 at 7:08 PM, Jared Parsons <notifications@github.com>
> wrote:
>
> > @cbates- <https://github.com/cbates-> the email reply didn't capture the
> > snippet on Github. Could you throw it up as a gist?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/jaredpar/VsVim/issues/1789#issuecomment-227296502>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABWN-XNztyOMU1uzSsOlGnuOk2x1EpR5ks5qNx1jgaJpZM4I52dF
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/jaredpar/VsVim/issues/1789#issuecomment-227298303>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAI-Fxrx-l5Azgi13zDiwCbvoMYtpljtks5qNx_WgaJpZM4I52dF>
> .
>



-- 
Jared Parsons
http://blog.paranoidcoding.com/
http://twitter.com/jaredpar

**Comment by jaredpar** [comment]
Thanks for providing the snippet.  I was able to track down the issue here and just submitted a fix.  It will be included in the next build of VsVim.  If you're looking to get it sooner, once the AppVeyor build completes you can grab the latest from vsixgallery.com.
