### ISSUE TITLE
double click word in normal mode does not expands to last letter

### ISSUE THREAD

**Issue by xuboying** [jaredpar/VsVim#1792]
VS 2013 VC++
vsvim 2.1.0.0
See gif for details

![screenshot9](https://cloud.githubusercontent.com/assets/5218237/16263596/c2e7561e-38a7-11e6-9cd2-96cccfb69f93.gif)

**Comment by jaredpar** [comment]
Thanks for reporting.  I was able to reproduce this issue.  It effects selections at the end of the line when certain vim options are set.  Should be fixed now in source.

**Comment by xuboying** [comment]
Thanks!!
