### ISSUE TITLE
typing certain characters in Normal mode causes them to be inserted

### ISSUE THREAD

**Issue by jankner** [jaredpar/VsVim#1793]
Some characters get inserted in the document when you type them in Normal mode. These are the characters I've discovered: ¤ ¨ £ € §  ´

**Comment by jaredpar** [comment]
Interesting.  Can you tell me how you type these?  In particular what keyboard you are using?

**Comment by mwinterb** [comment]
Oh boy, a tiny part of my childhood comes in handy! ¤ is typed with Alt+0164 (numpad for all of those, holding down Alt the entire time, then release). Character Map includes the keystrokes for several others, a random sampling hasn't gotten a single non-insert, except for the "letter" characters. I don't know enough about keyboards and input to say if the Alt+ mechanism is reported the same to an application as with actually typing those on a real keyboard, though, so this info may not be 100% helpful.

**Comment by jankner** [comment]
I used a Swedish keyboard to type those characters, but the Alt-number method has the same result. For example ¤ is typed as Shift-4, and § is typed using the key left of the 1 key.

**Comment by jkadg** [comment]
On a german keyboard one can insert € bei typing AltGr-E. VsVim inserts €, but doesn't change to insert mode at all.

**Comment by jaredpar** [comment]
Thanks.  I will try that out and see if I can repro the problem.

**Comment by ricksladkey** [comment]
I was able to reproduce this to enter into the buffer in insert or normal mode with a US keyboard using the Alt+0164 technique described by @mwinterb. I'll take a look into the issue.
