### ISSUE TITLE
Ex commands with range not working

### ISSUE THREAD

**Issue by jkadg** [jaredpar/VsVim#1794]
Ex-commands with range-specifier
:_begin_,_end_ _command_
(such as
**:'a,'b >**
to right-shift a block of code)
give "Parse error"

**Comment by jaredpar** [comment]
Have you tried using a `\`` instead of `'`.  That shoud work for this immediately.

**Comment by jkadg** [comment]
It was only a sample. It makes no different how I descripe the begin- and/or end-address.
:.,.+5 >
or
:100,200 >
or
:1,$ >
or any other legal form of addressing doesn't work.
I always get "parse error".
I also tried `a,`b instead of 'a,'b - it made no difference.
The shift command is also only a sample - but its one I'd like to use more often...

**Comment by jaredpar** [comment]
Hmm, I'm not seeing any of this on my machine.  I just verified this is supported in code, tested it manually and everything worked as expected.  I think there is something specific to your setup that is amiss here.  Can you try running `:map` and seeing what the output is?  I wonder if there is a key binding that is causing this issue.  Lacking that can you post your vimrc somewhere I can view?

**Comment by jkadg** [comment]
:map without an argument does nothing (and shows nothing).

My .vsvimrc contains the following lines (except the last line, it is simply a copy of .vimrc):

:syntax on
se guioptions=gmrtTb
se showmode
se showmatch
se nowrap
se sidescroll=20
se ai aw tabstop=4 sw=4
se hlsearch
se vsvim_useeditordefaults

**Comment by jkadg** [comment]
I just figured out, that if I ommit the space between the address and the command, it works.

:.,.+5>
works

:.,.+5 >
fails.

(g)vi(m) handles both. I'll get used to the space-less form... ;-)

Many thanks for your efforts.

**Comment by DarylRoberts** [comment]
that's the thing the compter can tell the difference ,, ikjt may onlky be a space but it can alter EVERYTHING,,,, I was told by a computer expert that he didn't know what that code would do ,,, Hmmm expect he was

**Comment by jaredpar** [comment]
@jkadg ahh okay.  That seems to be the issue.  I never knew spaces were legal there.  I will let this issue track adding spaces to the parsing there.  That should be easy enough.
