### ISSUE TITLE
Cannot go at the end of the line when vsvim in disabled mode

### ISSUE THREAD

**Issue by darkpotpot** [jaredpar/VsVim#1795]
When I hit ctrl+shift+f12 in order to disable vsvim, I cannot go anymore at the end of the line. I can only go up to the last character. I didn't have this behavior with my older version.

**Comment by allender** [comment]
I believe that this issue is fixed.  See this closed bug report [here](https://github.com/jaredpar/VsVim/issues/1791):

**Comment by jaredpar** [comment]
@allender is correct, this is a known bug.  It's been fixed now and will be included in the next update.  Probably going to release it later today.  There were a series of bugs here and I want to make sure I have them all fixed before I release an update.

**Comment by darkpotpot** [comment]
Oops, sorry I didn't saw the issue was already reported. I only looked at the "open issue" list, my bad.

**Comment by jaredpar** [comment]
@darkpotpot no problem.
