### ISSUE TITLE
detect vsvim in .vimrc file

### ISSUE THREAD

**Issue by iamkarlson** [jaredpar/VsVim#1796]
Hi, I have a plugin ( [incsearch](https://github.com/haya14busa/incsearch.vim) ). And this plugin require a special mapping for work.

```
"aditional mapping for incsearch
map /  <Plug>(incsearch-forward)
map ?  <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)
```

But VsVim proceeds this action as 

```
insert command
ncsearch-forward
```

How I can disable this behaviour or make this plugin works? 
Thanks

**Comment by jaredpar** [comment]
VsVim doesn't support arbitrary Vim plugins and is unlikely to work with `incsearch`.

**Comment by iamkarlson** [comment]
ok, but how I can detect that it's running in vsvim? I intend to exclude this mapping from .vimrc by 

```
if !has("vsvim")
    "aditional mapping for incsearch
   map /  <Plug>(incsearch-forward)
   map ?  <Plug>(incsearch-backward)
   map g/ <Plug>(incsearch-stay)
endif
```

**Comment by jkadg** [comment]
You could simply copy your **.vimrc** to **.vsvimrc** and omit the parts not working in VsVim.

**Comment by jaredpar** [comment]
That is the recommended practice.

**Comment by iamkarlson** [comment]
is copypaste recommended ? i haven't known that it can be recommended.

**Comment by jaredpar** [comment]
Generally I structure my files as follows:

1. .vimcommon: all my settings common to VsVim and gVim
2. .vsvimrc: runs `:source` on the common file
3. .vimrc: runs `:source` on the common file then does gVim specific work.

**Comment by iamkarlson** [comment]
Great, thanks! It's a better solution, I'll follow that.
