### ISSUE TITLE
Recommended way to make my own key-filtering extension compatible with VsVim?

### ISSUE THREAD

**Issue by spiralsam** [jaredpar/VsVim#1797]
Looking through the VsVim source a bit it seems like I need a silent "VsVim.SetDisabled" and "VsVim.SetEnabled" command to call into as opposed to "VsVim.ToggleEnabled", or make my own IExternalEditorAdapter but presumably I'd have to compile and run my VsVim for that.

I'm really just looking at temporarily disabling VsVim while my own action is in use, or otherwise creating some kind of exclusive keyboard input like a hidden modal dialog or something.

Have a preferred recommendation? Or this can just be a feature request to easily let arbitrary extensions reliably temporarily suspend or supersede VsVim. Thanks

**Comment by jaredpar** [comment]
This is actually pretty easy to add so I went ahead and submitted a PR to add them.
