### ISSUE TITLE
GoToDefinition should add a jumplist entry

### ISSUE THREAD

**Issue by rcorre** [jaredpar/VsVim#1798]
VsVim's jumplist woks nicely for some things, but not for GoToDefinition. This
means I have to remember to use `<c-o>` to return after searching, but `<c-->`
(the builtin VS shortcut) to return after `GoToDefinition`. It would be nice if
all of this was part of the `VsVim` jumplist.

Related: #1621

**Comment by jaredpar** [comment]
The jump list is integrated with the go to definition support:

https://github.com/jaredpar/VsVim/blob/master/Src/VimCore/CommonOperations.fs#L710

Go to definition is an odd command though given that it's implemented by each language in Visual Studio differently.  It often has unexpected behavior that I need to account for.  

What language are you using here?  Is the jump going between files?

**Comment by rcorre** [comment]
C#. Looks like it works for jumps in the same file, but not cross-file jumps

**Comment by rcorre** [comment]
C#. Looks like it works for jumps in the same file, but not cross-file jumps

**Comment by jaredpar** [comment]
This behavior is by vim design.  The jump list is separate per window.  This means that when `GoToDefinition` crosses files it's a new window with a new jump list.  Hence it <kbd>Ctrl-O</kbd> after the jump is going to the previous entry in the new window.  

From `:help jumplist`

> There is a separate jump list for each window.

**Comment by rcorre** [comment]
Argh, bummer. I wonder if there's a way to make `GoToDefinition` use the same window rather than open one of those weird pseudo-windows. You're right though, this isn't VsVim's fault.

**Comment by ricksladkey** [comment]
For the record @rcorre, there is a way, I use it all the time! Here is a stackoverflow question on the topic:

https://stackoverflow.com/questions/34437340/how-to-disable-peek-on-go-to-definition
