### ISSUE TITLE
Mouse selecting from right to left missing the last char.

### ISSUE THREAD

**Issue by xuboying** [jaredpar/VsVim#1801]
Version 2.1.1.0
VS: 2013 VC++
Mouse selecting from right to left missing the last char(most right char).

**Comment by jaredpar** [comment]
Thanks for reporting.  I will take a look at this.

**Comment by xuboying** [comment]
Thanks!

**Comment by slav** [comment]
This is also happening on VS 2015

**Comment by ricksladkey** [comment]
Unless I am misunderstanding something, I cannot currently reproduce this bug, with either `behave=mswin` or `behave=xterm`.

**Comment by ricksladkey** [comment]
I now understand this bug better and know that it was caused by a previous change that was reverted by PR #1829, which was merged, so this can be closed.
