### ISSUE TITLE
Tab completion for commands

### ISSUE THREAD

**Issue by vonhezhou** [jaredpar/VsVim#1806]
Been using the extension for quite some time now. Thanks for the great work. 
If I input ":cne" + tab, 
I expect vsvim to complete the command to ":cnext" or show some candidates just like vim does. 
But now it simply adds a tabstop instead, giving ":cne    ".
I wonder if you would like to implement the feature some time in the future.
Thanks for the great work again.

**Comment by jaredpar** [comment]
Thanks for the feedback!

I've considered adding tab completion here, and in several other cases.  The work is pretty straight forward there is just quite a bit of it to do.  It's something I'd like to do, I just need to find the 1-2 days to make it happen.

**Comment by vonhezhou** [comment]
great news, but no pressure.

**Comment by jaredpar** [comment]
Going to let #332 track the tab completion feature.
