### ISSUE TITLE
:registers doesn't show named registers

### ISSUE THREAD

**Issue by alarobric** [jaredpar/VsVim#1808]
When I type :registers I get the basic set of numbered registers, but not the named a-z registers, that I would expect to see in normal vim. Am I missing something or is this not supported yet?

![image](https://cloud.githubusercontent.com/assets/321603/16785453/045d6e8a-4843-11e6-8111-dce9108c556d.png)

**Comment by jaredpar** [comment]
Displaying of named register data is supported but only when there is something in the register.  If you explicitly copy a value into say `"c` does it show up?

**Comment by alarobric** [comment]
Nope. I can do `"cyw` for instance, then `:registers` will still just show the basic numbered registers. If I then `"cp` I can see the register is working, it's just not being displayed. Same thing with macros.

**Comment by jaredpar** [comment]
That's really strange.  It definitely shows for me and that logic isn't really complex.  It just gates on the register having a non-null value when displaying.  

Wonder if this is a simple UI issue.  Can you put your moues over the window, and use the scroll wheel to scroll it?  It's possible there is no scroll bar and the data is off screen.

**Comment by alarobric** [comment]
Yep that was it - the simple explanation. I don't suppose there's any way
to adjust the height of that popup window? There's a horizontal scrollbar
but no vertical one, and no way to adjust the size.

Sorry for the bother and thanks for the great tool.

**Comment by ricksladkey** [comment]
I gave it the old college try, but I could not figure out the WPF magic to get the pesky vertical scrollbar to appear automatically. In fact, I had considerable difficulty getting it to appear at all.

**Comment by ricksladkey** [comment]
It might also be helpful to change the description for this issue to "Command margin needs vertical scrollbar for multi-line content".
