### ISSUE TITLE
How to use 3V to select 3 lines?

### ISSUE THREAD

**Issue by frankyuan** [jaredpar/VsVim#1809]
How to select specify number lines in VSVim?

**Comment by jaredpar** [comment]
There is no command that I'm aware of in gVim that will do this.  It's possible I'm missing it though. 

In general putting a number before <kbd>V</kbd> causes all remaining lines to be selected.  To get specifically three lines selected I would perform <kbd>V2j</kbd>.

**Comment by frankyuan** [comment]
It worked, thanks!
