### ISSUE TITLE
Backspace does not work in document with VsVim disabled, or in C# Interactive window regardless of VsVim state

### ISSUE THREAD

**Issue by epscoe** [jaredpar/VsVim#1814]
I've been working with VsVim for just a few days, and noticed today that the backspace key does not work in the C# Interactive window. Delete still works, and Ctrl+Backspace still works, but I can't use Backspace to delete the single character left of the caret. The same is true of any file I'm trying to edit while VsVim is disabled. Re-enabling VsVim and entering Insert mode resolves the issue for documents, but not for other panes.

On investigation, it appears the issue also exists in a few other VS windows, including but not limited to F# Interactive, Command, and Package Manager Console. But some windows are fine: Team Explorer and all its sub-panes still accept Backspace normally.

I've tried disabling my .vimrc, and that didn't help (I haven't put much in there yet, so I didn't expect that to work anyway). I do have two backspace-related settings in there, for what it's worth:
- set backspace=indent,eol,start
- imap `<C-BS>` `<C-W>`

Thanks for a great product!

**Comment by jaredpar** [comment]
I'm not seeing that behavior locally.  I believe there is an issue here with how the keyboard is setup.  Can you do the following:

1. Open the Command Window in Visual Studio
2. Run: VsVim.DumpKeyboard
3. Open `%USERPROFILE%\AppData\Local\VsVim\keyboard.txt`
4. Paste the contents here

**Comment by epscoe** [comment]
Good catch, somehow the Edit.DeleteBackwards command has lost its keybinding. I didn't even realize that was possible. It seems unlikely that VsVim would be at fault if I'm the only person with the problem, but I'll try clearing my settings and reinstalling VsVim anyway to see if it happens again.

[keyboard.txt](https://github.com/jaredpar/VsVim/files/419366/keyboard.txt)

**Comment by simendsjo** [comment]
I had the same problem. I wasn't allowed to change the keybinding in VS, so I reset the keybindings, which brought it back.

**Comment by mqudsi** [comment]
There's a bug in VSVim somewhere. Just changing VSvim settings without making any changes to the keybinds can delete default VS keybindings.
