### ISSUE TITLE
dot-range shorthand not working

### ISSUE THREAD

**Issue by tjcertified** [jaredpar/VsVim#1816]
Minor issue. In Vim, for ranges in substitution, I can do the following:

```
:.,.5s/a/b    
```

and effectively change this and the next five lines. It is shorthand for:

```
:.,.+5s/a/b
```

which does work inside VsVim, and is a good workaround for now. Minor issue of additional '+', but I thought i would let you know about it. EDIT: I realized I left an 's' out of the second command, so I added it.

**Comment by jaredpar** [comment]
Thanks for reporting.  Did not know about that.  Will take a look at that.
