### ISSUE TITLE
support bookmark function

### ISSUE THREAD

**Issue by xuboying** [jaredpar/VsVim#1818]
Is it possible to support buildin bookmark function
like jump

Command     Description
]'  jump to next line with a lowercase mark
['  jump to previous line with a lowercase mark
]`jump to next lowercase mark
[`  jump to previous lowercase mark 

toggle might be a special key(limited supported)

**Comment by ricksladkey** [comment]
I understand all of this request except this line:

> toggle might be a special key(limited supported)

@xuboying Can you explain what you mean?
