### ISSUE TITLE
Joining lines of triple-slash comments doesn't remove slashes

### ISSUE THREAD

**Issue by albertdev** [jaredpar/VsVim#1821]
Assume the following documentation is present above a function and the cursor is on the `.` char surrounded by `|` marks:

```
        /// <summary>
        /// Returns the first digits of the number|.|
        /// The latter digits are the checksum.
        /// </summary>
```

Press `J` to join the two lines. In VsVim the result will be a line like this:

```
        /// Returns the first digits of the number.| | /// The latter digits are the checksum.
```

Expected result, taken from Vim:

```
        /// Returns the first digits of the number.| | The latter digits are the checksum.
```

Entering Insert mode and pressing Delete works as well because it's likely standard VS behavior, it's annoying though as it takes way more navigating and jumping through modes.

**Comment by jaredpar** [comment]
Do you know what mechanism in Vim causes the lines to be deleted?  It's usually not a standard vim behavior but instead something that can be configured whos default behavior just works in this way.  Usually i try and Implement the configuration as well.

**Comment by albertdev** [comment]
Ehr, sorry for that. I just got lazy and only showed the joined line(s) in the second and third example. The output of Vim is actually this:

```
        /// <summary>
        /// Returns the first digits of the number.| | The latter digits are the checksum.
        /// </summary>
```

As for configuration, I think this slashes-removing feature is related to the `comments` setting. In case of C# it gets set in `vim74\ftplugin\cs.vim`.

**Comment by albertdev** [comment]
Mind you, if you do want to go through with implementing the `comments` option then you would also need to look at the `o` and `O` normal mode commands and possible others. For these commands in particular, Vim will copy the "slashes" from the current line to the new line.

**Comment by jaredpar** [comment]
Sounds like this is coming from a plugin then. Plugins aren't supported by VsVim hence this behavior is operating as designed.

**Comment by albertdev** [comment]
@jaredpar I'm afraid there's a misunderstanding here.

[The 'comments' option](http://vimdoc.sourceforge.net/htmldoc/options.html#%27comments%27) and [format-comments feature](http://vimdoc.sourceforge.net/htmldoc/change.html#format-comments) are part of standard Vim. Joining lines / adding lines whilst formatting comments, ... is all part of Vim functionality.

The aforementioned "plugin" from Vim's standard distribution does nothing more than setting the right options / syntax. It's not even necessary to run it as-is when VsVim would contain the appropriate default `'comments'` value based on the current file's type.
