### ISSUE TITLE
Cannot understand supported feature keys: what does <C-w> mean?

### ISSUE THREAD

**Issue by aceperry** [jaredpar/VsVim#1822]
In the documentation, I see this under normal mode.  Does (left angle bracket)C-w(right angle bracket) mean a single control key press?  I have to write in the words angle bracket because this editor leaves it out.  I'm used to seeing a single letter 'C' for denoting the control key.  There are also other combinations like <C-w>(left angle bracket)C-l(right angle bracket).  (see: https://github.com/jaredpar/VsVim/wiki/Supported-Features)  I've never seen this kind of thing before.  I looked at some vi and vim keybindings  but can't find anything like this.  Any help would be appreciated.

**Comment by hpp3** [comment]
\<C-w\> means press ctrl and w.

**Comment by idealist1508** [comment]
You can find a complete information about this notation under http://vimdoc.sourceforge.net/htmldoc/intro.html#key-notation

**Comment by aceperry** [comment]
Thanks everyone.  I've never read the official docs too carefully.  Mostly used other sources to learn vi.
