### ISSUE TITLE
cannot vertical split command when cshtml

### ISSUE THREAD

**Issue by sinofseven** [jaredpar/VsVim#1826]
I use Visual Studio 2013 Professional.
when .cs file, I could use vertical split.
but when .cshtml I couldnot vertical split.

**Comment by jaredpar** [comment]
Are you unable to use Visual Studio vertical split at all or just through VsVim?

**Comment by sinofseven** [comment]
Sorry,  I don't know to use only Visual Studio vertical split.

**Comment by jaredpar** [comment]
Use the menu `Window -> Split`.  

VsVim internally just calls into the Visual Studio split functionality.  If it's not working in VsVim it's likely because Visual Studio itself doesn't support it in this scenario.
