### ISSUE TITLE
The command `dd` will overwrite the `0` register, which does not appear in vim

### ISSUE THREAD

**Issue by haolly** [jaredpar/VsVim#1827]
See here http://stackoverflow.com/a/3651797/1831404

**Comment by jaredpar** [comment]
Thanks for reporting.  I will take a look at that.

**Comment by MirKml** [comment]
It seems that register 0 doesn't work at all.
When I try to yank some line with `yy`, go somewhere and type `"0p` for pasting from register 0, nothing is pasted.
It's true that I'm using `"0p` mostly after some delete operation e.g. `d`, `x` etc.

**Comment by idealist1508** [comment]
It seems to be a dublete to #1738

**Comment by haolly** [comment]
Is this fixed in version 2.1.2 ? @jaredpar 
I don't see it works in my vs2013

**Comment by jaredpar** [comment]
@haolly this is fixed in 2.2.0.  I published that release this AM.  If you update you should get it.

**Comment by haolly** [comment]
@jaredpar  the command `p` is OK, but the capital  `P` is not
