### ISSUE TITLE
VsVim doesn't indent as Visul Studio behaves.

### ISSUE THREAD

**Issue by Inori** [jaredpar/VsVim#1828]
VsVim behavior:
![error](https://cloud.githubusercontent.com/assets/6732524/18508568/3a49573e-7aa7-11e6-931b-a142d87d7984.gif)
Operations:
shift+v
j
d
kk
p

Visual Studio(or VAX) behavior:
![right](https://cloud.githubusercontent.com/assets/6732524/18508641/835dcb1c-7aa7-11e6-8a7f-5cea8744e76a.gif)
Operations:
mouse select lines
ctrl+x
mouse move cursor
ctrl+v

I have tried:
```
set vsvim_useeditordefaults
set vsvim_useeditorindent
```
but it makes no sence.

In Vim I can fix this using [vim-pasta](https://github.com/sickill/vim-pasta).
Using `nnoremap <leader>p p`[v`]=` seems doesn't work.
And any solutions?

**Comment by Inori** [comment]
Oh Sorry, It seems that it is the same issues as:
https://github.com/jaredpar/VsVim/issues/1151

**Comment by Inori** [comment]
It seems that ``[` and ``]`  is still not supported in version 2.1.1.0.

**Comment by jaredpar** [comment]
Thanks for taking the time to report this issue.

Unfortunately this isn't behavior I can really control here.  VsVim processes indenting by using a couple of services provided by Visual Studio.  The C/C++ language service doesn't fully implement these interfaces and hence gets different results when typing and when processed via extensions like VsVim. 

If C/C++ exposes the correct behavior, as is the case with other languages, then VsVim should start picking it up immediately.  Until then though there isn't much I can do about this bug 😦 .

**Comment by Inori** [comment]
Thank you for reply. I use the way  @anjdreas mentioned in #1151, pretty good.
