### ISSUE TITLE
DeleteLineSelection needs to be hardened 

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#1831]
The code is still not fully accounting for the possibility of other extensions further deleting text after the VsVim deletion:

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.&#x000D;&#x000A;Parameter name: position&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.SnapshotPoint..ctor(ITextSnapshot snapshot, Int32 position)&#x000D;&#x000A;   at &lt;StartupCode$Vim-Core&gt;.$CommandUtil.editSpan@668.Invoke(Unit unitVar0)&#x000D;&#x000A;   at Vim.UndoRedoOperations.EditWithUndoTransaction[b](String name, ITextView textView, FSharpFunc`2 action)&#x000D;&#x000A;   at Vim.UndoRedoOperations.Vim-IUndoRedoOperations-EditWithUndoTransaction[a](String name, ITextView textView, FSharpFunc`2 action)&#x000D;&#x000A;   at Vim.CommandUtil.DeleteLineSelection(Register register, VisualSpan visualSpan)&#x000D;&#x000A;   at Vim.CommandUtil.RunVisualCommand(VisualCommand command, CommandData data, VisualSpan visualSpan)&#x000D;&#x000A;   at Vim.CommandRunner.Run(KeyInput ki)&#x000D;&#x000A;   at Vim.CommandRunner.Vim-ICommandRunner-Run(KeyInput ki)&#x000D;&#x000A;   at Vim.Modes.Visual.VisualMode.Process(KeyInput ki)&#x000D;&#x000A;   at Vim.Modes.Visual.VisualMode.Vim-IMode-Process(KeyInput keyInput)&#x000D;&#x000A;   at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput)&#x000D;&#x000A;   at &lt;StartupCode$Vim-Core&gt;.$VimBuffer.processSet@453(VimBuffer x, FSharpRef`1 processResult, KeyInputSet keyInputSet)&#x000D;&#x000A;   at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet)&#x000D;&#x000A;   at Vim.VimBuffer.Process(KeyInput keyInput)&#x000D;&#x000A;   at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput)&#x000D;&#x000A;   at Vim.UI.Wpf.VimKeyProcessor.TryProcess(KeyInput keyInput)&#x000D;&#x000A;   at Vim.VisualStudio.Implementation.Misc.VsVimKeyProcessor.TryProcess(KeyInput keyInput)&#x000D;&#x000A;   at Vim.UI.Wpf.VimKeyProcessor.TextInput(TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c.&lt;DispatchTextInputEvents&gt;b__6_0(KeyProcessor p, TextCompositionEventArgs args)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.&lt;&gt;c__DisplayClass10_1`1.&lt;Dispatch&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by jcouv** [comment]
Thanks!
