### ISSUE TITLE
Feature request: `:sort` support

### ISSUE THREAD

**Issue by mjgpy3** [jaredpar/VsVim#1833]
First of all, excellent plugin! This is by far one of the best "spirit-of-vim" in a non-vim IDE tools out there. Hats off to you!

I'm wondering if there are any nuances or reasons why something like the `sort` command couldn't be implemented.

My typical usage for this command looks like (e.g. on `using` statements)
![vim-sort-usage-fin2](https://cloud.githubusercontent.com/assets/1709849/18727327/226aa1b2-8016-11e6-8bfd-b49ea2d88679.gif)

**Comment by jaredpar** [comment]
The `sort` command can be implemented.  It's just one of the items I haven't gotten around to yet 😦  

I believe there are some customizations that I couldn't implement because they are function based.  But the simple functionality seems doable.

**Comment by tyrellj** [comment]
Same as #601?

**Comment by efimov-denis** [comment]
Still isn't available in 2.3.0.0 version?

**Comment by efimov-denis** [comment]
Still isn't available in 2.3.0.0 version?

**Comment by jaredpar** [comment]
Looks like a dupe of #601
