### ISSUE TITLE
Keyboard preferences cleared every new session

### ISSUE THREAD

**Issue by DJMcMayhem** [jaredpar/VsVim#1835]
For some reason, all of my keyboard preferences (e.g. handle `<key>` with VsVim/Visual Studio) are cleared every time I close and reopen visual studio. For example, I'll go

```
Open Visual studio
tools --> Options --> VsVim --> Keyboard --> Handle all with VsVim --> OK
```

And it works fine. Then

```
Close visual studio
Reopen visual studio
<C-v> 
```

will paste, rather than starting a visual block. If I go back to keyboard options, all keyboard options are set to "Visual Studio".  

I am using visual studio 2015 on windows 7, with VsVim 2.1.1.0

**Comment by jaredpar** [comment]
This generally happens when you have more than one instance of Visual Studio running.  VS will pick one of the instances to be the winner for settings changes.  Hence anything you change in the other instances won't persist.  

Can you try closing all instances of VS, then open one instance, change the settings, close and see if persists then?

**Comment by DJMcMayhem** [comment]
@jaredpar Hmm, well I only had one instance open while it was happening initially, but I rebooted and now it's behaving strangely. When I reopen visual studio, the options say that every key is handled by visual studio, but all of my vim-like keybindings are there. If I hit "Handle all with visual studio", the vim-bindings still apply. 

Not a huge deal, since I prefer the vim bindings anyway, but strange nonetheless. Another thing I noticed is that hitting "Handle all with vsvim" will select every key combo *except* for `Ctrl-v`. If you like, I could raise another issue on this.

**Comment by jaredpar** [comment]
That is strange.  Can you open the command window and run:

> VsVim.DumpKeyboard

That will put a file into `%LOCALAPPDATA%\VsVim\Keyboard.txt`.  That will give me a better picture of what is going on with the keyboard settings.

**Comment by DJMcMayhem** [comment]
Sure. It's a pretty large file, so I've uploaded it to a gist [here](https://gist.github.com/DJMcMayhem/64af160b9c3326ea701d4342cf13a95c)

**Comment by jaredpar** [comment]
I think you may be hitting an issue with how Visual Studio sync's keyboard settings.  Do you use Visual Studio on multiple machines with the same account?

**Comment by jaredpar** [comment]
Closing due to staleness.
