### ISSUE TITLE
gg with long count jumps to top rather than bottom

### ISSUE THREAD

**Issue by rcorre** [jaredpar/VsVim#1837]
In vim, if you give `gg` a count larger than the number of lines in the file, it jumps to the bottom of the file. In vsvim, it jumps to the top.

**Comment by jaredpar** [comment]
Thanks for reporting.  I will take a look at that.

**Comment by jaredpar** [comment]
This was fixed by 2cd5e84cee0c6ef7e8b72e5adf2335faa6ae5785
