### ISSUE TITLE
When using command "cc" or "S", the current line is not indented while "o" indent the new line correctly?

### ISSUE THREAD

**Issue by xnsua** [jaredpar/VsVim#1838]

**Comment by jaredpar** [comment]
Do you have `autoindent` set?  That changes the behavior of the commands in question.

**Comment by epscoe** [comment]
I did some testing with all of the combinations of options I could think of (autoindent, vsvim_useeditorindent, and VS text editor intendation settings), and my best guess is that the original poster had "autoindent" off and "vsvim_useeditorindent" on. Setting "autoindent" does make VsVim behave like gVim for 'S' and 'cc' regardless of "vsvim_useeditorindent", which seems like it will answer the question.

I did notice one potential discrepancy in the following case:
- set vsvim_useeditorindent
- 'autoindent' off
- Visual Studio indenting setting for the current file type is "None" (I tested with a .cs and a .txt file).

In this case, VsVim behaves exactly as gVim would behave with "autoindent" on. Examples:

```
    First line

        'O'
        cursor starts in this line
        'o'
 Last line
```

```
    First line
  Second line
'O'
cursor starts in this line
'o'
```

I hope that helps.

**Comment by xnsua** [comment]
Sorry for not responding for long time Because I move to another project and forgot all about this. Today I try again And now I cannot reproduce the problem. I believe some 'vimrc' file I do not notice cause this problem, thank everyone and I appreciate @epscoe 's effort.

**Comment by denis-reichelt** [comment]
I had the same problem and setting autoindent in my _vsvimrc file solved the problem for me.
I think you can close this issue.
