### ISSUE TITLE
Enter in command bar doesn't work

### ISSUE THREAD

**Issue by farzadmf** [jaredpar/VsVim#1840]
I don't know what's happened,
I was working with VsVim and everything was fine. Since yesterday, I notice this weird behavior that I go to command mode and I type a command, it treats it as if I have pressed Enter in the editor window, and it just opens a blank line in my code

**Comment by farzadmf** [comment]
It seems to be working fine now, I'll close this one and re-open if it happens again

**Comment by farzadmf** [comment]
Apparently, it has something to do with ReSharper. I don't know why because I have the exact same environment on both of my computers, but the issue only appears on one. If I suspend ReSharper, the issue goes away.
The thing is that sometimes the issue doesn't appear, so I don't know what is happening here.

**Comment by sonictk** [comment]
I am getting this same issue as well, and I have ReSharper installed too. Is there any way to force focus to the command bar when entering a command with VsVim?

**Comment by jaredpar** [comment]
Which version of R# do you have installed?

**Comment by Yax42** [comment]
During the last month I've been working on three different computers, and I've had this problem on every one of them. And I don't think I had Resharper on any of them (although I've been said that Visual Studio is slowly natively integrating features from Resharper).

**Comment by sonictk** [comment]
@jaredpar In Resharper > About, it says:

JetBrains ReSharper Ultimate 2016.2.2  Build 106.0.20160913.91321
dotCover 2016.2.20160913.94258
dotMemory 2016.2.20160913.94258
dotTrace 2016.2.20160913.94302
ReSharper C++ 2016.2.20160913.92511
TeamCity Add-in 2016.2.20160913.92511
ReSharper 2016.2.20160913.92608

**Comment by farzadmf** [comment]
I also have R# 2016, and it only happens on one of my computers, and unfortunately not always either!

**Comment by sonictk** [comment]
This issue is still present in VsVim 2.2.0.0 on VS 2015.

**Comment by ricksladkey** [comment]
The command margin now gets the focus (since 2.5.0 at least), so this bug should be resolved because the workaround suggested is now effectively performed automatically.
