### ISSUE TITLE
#j/#k Does not move desired count when at bottom/top of visible page

### ISSUE THREAD

**Issue by zolem** [jaredpar/VsVim#1844]
If you are on the bottom visible line and type `5j` then it will only move 1 line down instead of 5 as expected. Similarly if you are at the top visible line and type `5k` it will move up only 1 line instead of 5.

**Comment by jaredpar** [comment]
Thanks for reporting the issue.  I will take a look at this.

**Comment by chaitanyagurrapu** [comment]
Unable to reproduce this myself ...

![bugcapture](https://cloud.githubusercontent.com/assets/853059/19619505/7de89176-98ac-11e6-8a74-00f7953b054f.gif)

**Comment by zolem** [comment]
@chaitanyagurrapu What do you use to screen capture? I can record mine and Ill post it for you to see.

**Comment by chaitanyagurrapu** [comment]
@zolem I used Licecap http://www.cockos.com/licecap/ 
Open source, free etc.

**Comment by jaredpar** [comment]
I also can't reproduce this behavior and have multiple tests which test exactly for this.  Closing for now unless we can track down a stable repro.

**Comment by zolem** [comment]
![jkerror](https://cloud.githubusercontent.com/assets/7129911/24922012/0205c1b2-1eaa-11e7-904b-de36ec51479d.gif)

This still happens for me in 2017

**Comment by zolem** [comment]
I actually managed to fix this and I know what the problem is.

The culprit is this line in the .vsvimrc
```vimL
" Treat long lines as break lines (useful when moving around in them)
noremap j gj
noremap k gk
```

In vim this still works as expected.
