### ISSUE TITLE
Escaped sequences don't work for "execute"

### ISSUE THREAD

**Issue by bradphelan** [jaredpar/VsVim#1845]
![image](https://cloud.githubusercontent.com/assets/17650/19064484/f1dc35ea-8a0d-11e6-99d9-f1eb8448d362.png)

generates

![image](https://cloud.githubusercontent.com/assets/17650/19064499/068cfe20-8a0e-11e6-9cf6-b953aa5a9cca.png)

rather than actually executing carriage returns and escape key presses.

**Comment by jaredpar** [comment]
Interesting.  I didn't realize that was a feature.  Will adjust for it.

**Comment by bradphelan** [comment]
Thanks :)
