### ISSUE TITLE
Suggestion: Have Keyboard Options Dialog Show the VsVim & Visual Studio Functionality Side by Side

### ISSUE THREAD

**Issue by eddieparker** [jaredpar/VsVim#1847]
Right now the Keyboard dialog looks like this:

[Keystroke] Handled by [VsVim|VisualStudio]

If you click on the drop down you get to see what the VS keyboard shortcut you're replacing is, which is nice.

What I'd like however is to have two more columns to the right of this, with the text of the Visual Studio shortcut there, and the next column for the vim functionality you'd get.  It would make it easier at a glance to see what vsvim is replacing.

My use case is that for some reason Visual Studio keeps forgetting my keyboard shortcuts.  My 'solution' is to go to VS's options and 'reset' to the default scheme, then go back to VSVim, and say "Handle all with VSVim", and deselect the few that I want to keep with visual studio (CTRL-Home, Shift-Alt-O, CTRL-SHIFT-C, etc).  Would be nice to scan quickly versus clicking to select each one.

**Comment by jaredpar** [comment]
Thanks for the suggestion here.

> What I'd like however is to have two more columns to the right of this, with the text of the Visual Studio shortcut there, and the next column for the vim functionality you'd get.

This is not generally solvable though.  Keys in Vim alone don't represent commands, instead they have to be taken into context.  In particular what mode they operate in.  For instance <kbd>k</kbd> has one action in insert mode and another in normal.  It's unclear which would get displayed in this mode.

Furthermore this particular dialog actually takes into account key mappings.  Hence keys which inherently don't have any meaning can show up here.  There is no good display to add other than "custom mapping".

As for the VS display.  That can generally be added but not always.  There are plenty of keyboard combos that don't have any text associated with them.  😦

**Comment by eddieparker** [comment]
Fair points.  I personally would be happy even with the VS key combos that *do* exist.  I normally find I have to flip through them all to see if I'm losing a behaviour I care about (CTRL-ALT-L, CTRL-ALT-W), so even that would be a time savings.

Alternatively, if VS ever managed to sync my keyboard shortcuts amongst my machines, this would be a one-time setup. :)

**Comment by jaredpar** [comment]
Considered this, and a couple of other proposed designs. Decided to keep it as is for now. I can't find a design I'm truly happy with here.
