### ISSUE TITLE
How to remap <C-r> to another shortcut?

### ISSUE THREAD

**Issue by farzadmf** [jaredpar/VsVim#1848]
My question is maybe more related to Vim than VsVim, but I would appreciate if you guys let me know how I can remap <C-r> to something else so that I can paste registers. <C-r> is used a lot in Visual Studio's refactoring shortcuts, and that's the reason I need to change it.
Of course I'm assuming that <C-r> then "register-name" is supported. Is it true? I searched the issues, and I think it should be supported, right?

**Comment by jaredpar** [comment]
Can you give a bit more context about this?

> How I can remap to something else so that I can paste registers

I'm not entirely sure what is meant by this.  Can you try elaborating a bit?

**Comment by farzadmf** [comment]
Sorry if my explanation was not enough.
In Vim, when in insert mode, you can type `CTRL + R`, and then the name of the register you want to paste (instead of pressing `ESC` to go to normal mode and paste the register...)
But, in Visual Studio, and more specifically ReSharper, `CTRL + R` is used for refactoring commands (e.g., `CTRL + R, R` for renaming. I wanted to be able to paste registers in insert mode using another shortcut

**Comment by mpsyco** [comment]
I have the same problem here, it is quite annoying not to be able to paste while in insert mode.

**Comment by sqlkoala** [comment]
You can put this line to your vsvimrc
`inoremap <M-r> <C-r>`
Then you can paste from registers by  Alt+r  then register char. Alt (or Meta) is the key left from space (on my keyboard :D )

**Comment by Trepidimous** [comment]
VsVim can't seem to find my "map.vsvimrc" file no matter where I try to put it.
"C:\Users\[username]\AppData\Local\VsVim"
"C:\Users\dhahnert"

I'm using windows 10 and Visual Studio 2013

**Comment by ricksladkey** [comment]
This is not a bug per se, just a question about how to map alternate keybindings when it is desirable to have a critical key set to "handled by Visual Studio". The suggestion made by @sqlkoala resolves the issue.

**Comment by farzadmf** [comment]
Yes @ricksladkey you're right. Personally, I added `inoremap <C-Y> <C-r>` (following the suggestion by @sqlkoala ), so I'll close the issue as I got my answer

**Comment by listobject** [comment]
> This is not a bug per se, just a question about how to map alternate keybindings when it is desirable to have a critical key set to "handled by Visual Studio". The suggestion made by @sqlkoala resolves the issue.





https://stackdev.space/questions/what-is-the-best-way-to-combine-certain-names-using-the-paste-function
