### ISSUE TITLE
Can VsVim support `[ and `] ?

### ISSUE THREAD

**Issue by chizhangsysu** [jaredpar/VsVim#1849]
Very often, I have the need to re-select the text I #just pasted: http://stackoverflow.com/questions/4312664/is-there-a-vim-command-to-select-pasted-text

In vim this can be done by ``[V`]`, where:
``[`  jumps to the start of the last edited paragraph,
``]`  jumps to the end instead.

Is it possible that VsVim can also support that in a short future?

**Comment by jaredpar** [comment]
Thanks for the suggestion.  This is a pretty reasonable feature.  I will look into it.

**Comment by ricksladkey** [comment]
This feature was implemented in PR #2238 and so this issue can be closed.
