### ISSUE TITLE
Cursor column not being preserved after first jump and subsequent motion.

### ISSUE THREAD

**Issue by chaitanyagurrapu** [jaredpar/VsVim#1854]
In Vim, say you are in a certain column in a line, and press gg or G to go to the bottom or top of the file and that causes your column to change (because the line is too short). When you get back to the original line (or any other line that can support the column position) by using a motion command (j, k, 2G etc.), the caret is set to the original column position. This doesn't seem to be the case in VsVim. 

![vimversion](https://cloud.githubusercontent.com/assets/853059/19645924/86cf5f60-9a3a-11e6-91bf-3ca8895edc3d.gif)
![vsversion](https://cloud.githubusercontent.com/assets/853059/19646057/1c47f764-9a3b-11e6-9b11-642b4fd9ecb5.gif)

**Comment by jaredpar** [comment]
Thanks for reporting.  Sounds like I don't have that motion set to track the caret column.  Should be an easy fix.
