### ISSUE TITLE
imap jj <Esc> interferes with intellisense

### ISSUE THREAD

**Issue by 333fred** [jaredpar/VsVim#1855]
Mapping `jj` to escape in insert mode interferes with intellisense. If you attempt to tab complete (seems to work when hitting enter, it's just tab) after typing the start of an identifier, where you've typed up to `j` (`proj`, for example), a tab is inserted, instead of the highlighted prediction.

**Comment by jaredpar** [comment]
Hmm.  I thought the replay mechanism hit the intellisene hook but it appears ti doesn't.

**Comment by Rantanen** [comment]
Can confirm in a way. For me neither `tab` or `enter` work properly unless I wait for the mapping to timeout and `j` to appear on screen.

Another related issue seems to be disappearing intellisense prompt.

Typing `pro` provides intellisense for `pro*`, typing the `j` doesn't change anything as the `j` doesn't appear yet; but typing `e` will insert both `je` to the buffer, which for some reason makes the whole intellisense prompt disappear for me at least.

**Comment by jaredpar** [comment]
Dug into this a bit today and confirmed VsVim is sending the right data to Visual Studio here.  The gory details of how this plays out is as follows from the perspective of the IDE:

1. QueryStatus TypeChar j
1. QueryStatus Tab
1. Exec TypeChar j
1. Exec Tab

Normally the IDE would see the QueryStatus and Exec paired together for each event instead of spread out like this.  This seems to be confusing the IDE a bit.  At step 3 the IDE prints out the following diagnostics:

> Entered completion command handler for typechar.
> no completion session yet and this is NOT a trigger char, we won't have completion.

Following up with the IDE team to see if there is a way that I can make this work.

**Comment by jasonmalinowski** [comment]
@jaredpar: where is that string coming from? git grep says it's not in Roslyn, at least not in what we shipped in 2017 RC.

**Comment by jaredpar** [comment]
@jasonmalinowski no idea.  I had hoped it was Roslyn.  Like you I grepped our current sources and couldn't see this string anywhere.  This test was run against VS 2015 though so it's possible it's a diagnostic we've since deleted.

**Comment by jasonmalinowski** [comment]
Ah, I guess it is a removal. My bad for not using `git log -G"this is NOT a trigger char"`. This was removed in dotnet/roslyn@521299574bb08eae65c4085305bbea67c5a4c7de. It was added in dotnet/roslyn@b18139a6cfd812a280245da25b0bff9143ae76d8 but it doesn't say why.

**Comment by jaredpar** [comment]
Thanks for tracking that down @jasonmalinowski.  It turns out that message was a bit of a red herring.  But seeing it's location did clue me into where the real problem was ... VsVim's command handling code.   Got the fix working locally.  Will push a bit later.
