### ISSUE TITLE
Extension not available in Visual Studio "15" Preview 5?

### ISSUE THREAD

**Issue by simonbuchan** [jaredpar/VsVim#1856]
Though I can't see anyone else mention it, it seems the extensions list is heavily filtered for Preview 5 (released Oct. 5), probably to do with the VSIXv3 stuff mentioned [here](https://www.visualstudio.com/news/releasenotes/vs15-relnotes#vside) under "New Extensibility Format".

I'm dieing here without Vim in my life 😄, so if you could confirm that this isn't just me and that you're aware of the change? If it is a VSIXv3 thing, the release notes sound like they don't have the tooling out yet :(

**Comment by jaredpar** [comment]
Thanks for reporting.  I am aware of this change but still trying to figure out what is going on.  The extension is labeled for Dev15 and it's been installed just fine there.  It seems like a recent change caused all Dev15 based extensions that weren't built with Dev15 to be filtered out of the gallery.  There is no functional reason for this change (ext works just fine).  

I may have to temporarily release a Dev15 specific version to unblock people.

**Comment by jflam** [comment]
+1 on a Dev15 specific version, please! So hard showing off R Tools for Visual Studio to folks when I can barely type using the CUA key bindings ... I'll buy you lunch! :)

**Comment by simonbuchan** [comment]
Found this http://stackoverflow.com/a/40058387/20135 which describes how to get a VSIXv3, not sure if it's related to why the extension doesn't show up at all though :(

**Comment by cbates-** [comment]
VsVim Dev 15
https://marketplace.visualstudio.com/items?itemName=JaredParMSFT.VsVimDev15

**Comment by jaredpar** [comment]
This is available now on VS 2017.
