### ISSUE TITLE
Find backwards does not find matches that include the immediately preceding character

### ISSUE THREAD

**Issue by epscoe** [jaredpar/VsVim#1857]
Suppose I have the following line in my file:

```
var value = 5;
```

and the cursor is on the 'l' (middle character of "value"). If I type "?va<Enter>", the cursor will now be on the first character of the line, not the first character of the second word (the same test in gVim does place the cursor on the first character of the second word). If by coincidence the search text appears exactly once in the file (only in the current line), then VsVim will wrap around and find it (as expected). Searching forward ('/') also works as expected.

In case this seems like a silly thing to want to do, here's my explanation for how I encountered the issue through normal usage. Vim's default movements for (, ), {, and } don't usually put me where I want to be, so I have remapped them to find the previous/next parens/braces in the file. Here's the snippet from my .vsvimrc:

```
" Redefine 'sentence' and 'paragraph' movements
nnoremap ( ?(<Enter>
nnoremap ) /)<Enter>
nnoremap { ?{<Enter>
nnoremap } /}<Enter>
```

This works pretty well, except in one case: moving the cursor to the '(' character of a "()" pair that occurs below the current cursor location. My instinct is to press ')' to find the second paren and then '(' to find the immediately preceding paren, but what actually happens is the second keypress moves the cursor to some other paren further back up the file.

**Comment by jaredpar** [comment]
Thanks for reporting. 

I agree that seems like a bug.  I verified that the behavior of gVim is to match here.  Will dig into this and see what's going on.

**Comment by jaredpar** [comment]
Dug into this a bit and it appears to be a bug in Visual Studio.  Under the hood VsVim uses the Visual Studio find service to do text based searching.  After debugging this a bit it appears the find service will fail during a reverse search when the following conditions are met:

- A reverse search is being performed.
- The end point of the found string is the start point of the search. 
- There is another match of the search earlier on the same line. 

Not a lot I can do about this in VsVim.  I'm going to bring this up with the Visual Studio team and ask them for a fix here.
