### ISSUE TITLE
Reopen Configure Key Bindings

### ISSUE THREAD

**Issue by tltjr** [jaredpar/VsVim#1859]
Apologies if this is the wrong venue for this question, but I couldn't find an answer anywhere. Is there a way to reopen the dialog to configure conflicting key-bindings? I accidentally left Visual Studio to handle CTRL+V and it's quite painful.

**Comment by cbates-** [comment]
From the Command window:
> VsVim.Options

Or, Tools -> Options -> VsVim -> Keyboard

**Comment by tltjr** [comment]
You're a life saver. Thank you!
