### ISSUE TITLE
can vsvim support visual studio 2017?

### ISSUE THREAD

**Issue by FishThirteen** [jaredpar/VsVim#1862]

**Comment by jaredpar** [comment]
There is a version published for VS 2017 now.  Happy Vimming!

**Comment by rivanov2** [comment]
@jaredpar Where is this version published? I've tried to install from the extensions and updates, and to compile from source. Both fail to install on VS 2017 RC.

**Comment by cbates-** [comment]
Search the Visual Studio Marketplace for VsVim Dev15 .

**Comment by cbates-** [comment]
@rivanov2 Search the Visual Studio Marketplace for VsVim Dev15 .

**Comment by mmaguigan** [comment]
This does not seem to be working. I installed it and yet...

![image](https://cloud.githubusercontent.com/assets/6901070/20952038/84c0491c-bbf7-11e6-8afd-69a5a50f275f.png)

if I try to install it again, it says it's already installed :(

![image](https://cloud.githubusercontent.com/assets/6901070/20952016/62e644cc-bbf7-11e6-9462-b0c5c262573a.png)

**Comment by Borluse** [comment]
I've got vs17 version installed, but have only two keyboard bindings  in the options. The very important command gt doesn't work either...

**Comment by jaredpar** [comment]
@Borluse the gt command missing is a known issue.  It will be fixed in one of the updates coming out over the next few weeks.

**Comment by etodd** [comment]
@jaredpar any word on the gt command?

**Comment by Borluse** [comment]
the missing gt is the only reason that keeps me from using VS2017.....

**Comment by jaredpar** [comment]
Hoping to have time this weekend to fix.  This issue is tracking the work. 

https://github.com/jaredpar/VsVim/issues/1931
