### ISSUE TITLE
:w is not the same as File->Save ?

### ISSUE THREAD

**Issue by cbates-** [jaredpar/VsVim#1864]
I have installed Trailing Whitespace Visualizer extension.  It has an option to clean whitespace when the file is saved.  However, it is not activated when I use ":w", but it is activated when I use File->Save.
Not sure if this a VsVim issue, or a Trailing Whitespace Visualizer issue.

(I just noticed that TWV is not activated when my extension saves a file....  TWV must watch for a Save event at a level 'above' where my extension is saving the file.)

**Comment by jaredpar** [comment]
I took a look at the source for that extension.  It looks like it's keying on the "Save" command being sent to the Visual Studio command system.  VsVim essentially hooks in one layer lower by just saving the buffer (this is what happens once the "Save" command is executed).  

I'm going to open a discussion on the white space repo about this.

**Comment by jaredpar** [comment]
On second thought, I think Mads has the right of it here.  It would hook in a lot better to the system if I used the Save command route.

**Comment by cbates-** [comment]
@jaredpar Fwiw, I used the File->SaveAll and File->SaveSelectedItems where I could, and it works as desired with TWV.
