### ISSUE TITLE
Always use the block caret cursor, even in insert mode

### ISSUE THREAD

**Issue by sonictk** [jaredpar/VsVim#1867]
I just started using VsVim, so forgive me if this feature already exists, but I couldn't find it.
I would like to be able to always use the block caret cursor, even in insert mode, instead of it switching to the I-Beam cursor instead. Is it possible to do so in VsVim?

Thanks!

**Comment by jaredpar** [comment]
There is no way to do this at the moment.  Is there a similar feature for vim / gVim?  If so it would be fairly easy to implement.

**Comment by sonictk** [comment]
@jaredpar I'm not sure that there is a way to do this for gVim on Windows; but on Linux it follows whatever I have set in the terminal (I never use gVim anyway, and I use cmder on Windows which already has support for a block cursor).

Thanks for looking into it, though! I'll poke my vim friends and see if anyone knows of a way to force this in vim!
