### ISSUE TITLE
in insert mode error

### ISSUE THREAD

**Issue by harry890829** [jaredpar/VsVim#1868]
os:win10
version:vs community 2015 14.0.25431.01 update3

when i use backspace in insert mode, the word what I want to delete is still there and 'neocomplcache#smart_close_popup().""' is inserted at the cursor.
Using enter is also error, "CleverCr()" appeared.

I don't why, but when I uninstall vsvim, backspace and enter is ok.

**Comment by jaredpar** [comment]
Sorry you are seeing that.  

It sounds like you are using a vimrc file that maps backspace to a function call.  VsVim is picking up that mapping and failing to execute the function.  Can you try defining a `_vsvimrc` file in your home directory or disable loading `_vimrc` files in the option page?  That should fix the issue.

**Comment by harry890829** [comment]
Thank you very much. It is helpful.
I missed the _vimrc.
