### ISSUE TITLE
:marks doesn't always display global bookmarks

### ISSUE THREAD

**Issue by cbates-** [jaredpar/VsVim#1872]
Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 D14REL
VsVim 2.1.2.0
Marks created via "m-A", "m-D", etc. don't always appear in list of marks.
It looks like only the global marks for the current buffer are listed.
gVim lists all global marks, regardless of buffer.

For example, I have marks 'A', 'D', and 'T' set.
Jump to mark 'T': 'T
:marks
mark line  col file/text
 '     39    0 C:\work\scratch.txt
 T     38    0 C:\work\scratch.txt
 "      1    0 C:\work\scratch.txt
 ^     40    0 C:\work\scratch.txt
 .     39   43 C:\work\scratch.txt
 <      2    0 C:\work\scratch.txt
 >      3   27 C:\work\scratch.txt

Jump to mark 'A': 'A
:marks
mark line  col file/text
 '    424   28 C:\Users\Char...
 A    424   28 C:\Users\Char...
 "     69    0 C:\Users\Charl...

**Comment by jaredpar** [comment]
Thanks for reporting.  Will take a look at this.
