### ISSUE TITLE
ESC and Intellisense

### ISSUE THREAD

**Issue by gri6507** [jaredpar/VsVim#1873]
This seems to have already been discussed in Issue #325, but it seems that in the end that issue was closed without resolution due to old version of VisualStudio difficulties. I wonder if this can be reconsidered given the current 2015 or 2017 versions of Visual Studio.

To recap the problem, when I am in INSERT mode and I start typing, Intellisense pops up a window that, if I don't want to choose any suggestion, I naturally dismiss with ESC. However, that takes me out of INSERT mode.

**Comment by jaredpar** [comment]
This behavior is "By Design".  There was discussion very early on in VsVim about which behavior should occur here.  The overwhelming majority of feedback was to do the current behavior.
