### ISSUE TITLE
Cannot use Dot "." in the Visual Studio search box

### ISSUE THREAD

**Issue by Mehradzie** [jaredpar/VsVim#1875]
When I press _Ctrl+F_ and start using the integrated search functionality in Atmel Studio (which is really a rebadged VS), I can start typing for the search phrase, however if the phrase includes a Dot "." in it, the dot from vim takes over and repeats the last action on the editor rather than typing "." in the search box.

e.g.
I want to search for "radio.sleep( )" in the code. 
1. I press Ctrl+F to bring the search box.
2. Start typing "radio"
3. The moment I want to type the dot after radio "radio." no "." gets typed in the search box, and the editor say keeps adding a new line if that was the latest thing I have done on the editor for example. 

Anybody experiencing the same issue?

BTW, I already use the / for searching in the editor however the integrated search has it's own place so please consider that I am aware of the / search which is really a jump functionality in VIM.

**Comment by ricksladkey** [comment]
The mystery here is that if the buffer were mistaken being handled by VsVim, it would be in normal mode, and then *all* the letters in `radio` (for example) would also be normal vim commands.  And yet, the letters do *not* seem to invoke their corresponding vim normal commands.
