### ISSUE TITLE
VsVim crashes after updating to 2.1.2.0 / Where to find previous build?

### ISSUE THREAD

**Issue by jrao** [jaredpar/VsVim#1876]
I updated VsVim this morning to version 2.1.2.0 and got this error:

![vsvim-error](https://cloud.githubusercontent.com/assets/945039/20840946/f7c9dfca-b87f-11e6-987e-24eea19b25f9.png)

I removed my _vimrc and _gvimrc files but that had no effect on the error.

I'd like to revert to a previous version until this issue can be fixed but the dropbox link on the wiki seems to be broken: https://github.com/jaredpar/VsVim/wiki/faq#where-can-i-get-older-drops

**Comment by jaredpar** [comment]
Sorry that you hit that issue.

Not sure why you can't access that drop box link.  I just verified that it is working.  In any case though here is a different link to the most recent drop:

> https://vsvim.blob.core.windows.net/drops/VsVim-2.1.1.0.vsix

This is the first report I've seen of a crash though.  Can you post the contents of the specified log file for me to take a look at?  Just search for VsVim in it and there should be a stack trace of the exception.  That should be enough to let me know what the error is. 

Curious: are you running Visual Studio 2010?

**Comment by jaredpar** [comment]
Hmm, looks like permissions might be off on that blob container.  Looking at it.

**Comment by jaredpar** [comment]
Link should be fixed now.

**Comment by jrao** [comment]
Yes, I'm running Visual Studio 2012. Here's a link to the activity log: https://gist.github.com/jrao/78eec3c43bac679ca3f5a70caa720849

**Comment by jrao** [comment]
Looks like dropbox is blocked on my work network. Thanks for the alternate link.

**Comment by jrao** [comment]
Thanks again - just installed the 2.1.1.0 version and it's working correctly.

**Comment by jaredpar** [comment]
Thanks for posting the log contents.  That gave me some idea of what is going on here.  

Unfortunately it's a bit baffling.  It's a MEF composition error.  That should either happen 100% of the time or never.  This build's been installed on thousands of machines successfully now.  Your machine seems to be an outlier for some reason.  

What other extensions do you have installed?  I wonder if there is a conflict there that I need to be aware of.

**Comment by jrao** [comment]
The only extensions that I have are
- Microsoft ASP.NET and Web Tools
- NuGet Package Manager
- Visual Studio Extensions for Windows Library for JavaScript
- VsVim

**Comment by csy9** [comment]
Hey, I encountered the same issue and found a temporary workaround that might be able to help you.

* Close visual studio. 
* Win+r, regedit. 
* Go to Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Lsa\FipsAlgorithmPolicy
* Double click 'Enabled', set to 0.

Hope this helps in the meantime. Here are the errors on my ActivityLog from startup:

  <entry>
    <record>649</record>
    <time>2016/12/05 15:21:00.272</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.PerformLayout(SnapshotPoint trackingPoint)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>
  <entry>
    <record>650</record>
    <time>2016/12/05 15:21:00.693</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.PerformLayout(SnapshotPoint trackingPoint)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.InterTextAdornmentSupport.Implementation.InterLineAdornmentManager.OnBatchedTagsChanged(Object sender, BatchedTagsChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)</description>
  </entry>
