### ISSUE TITLE
#^d/#^u should be limited to screen size

### ISSUE THREAD

**Issue by laktak** [jaredpar/VsVim#1887]
Although it does not appear to be documented, when you do 1000^d or 1000^u in vim it will not scroll more than one screen.

This is a workaround because ^f/^b will not put the cursor on the first/last line on the first/last page.

Could you make VsVim scroll the same amount?

(I tried to `set scroll=36` in .vimrc but VsVim would not use that option either, only when entered via `:`, I guess it's overwritten after vimrc is loaded).

VS 2015, latest VsVim from Marketplace

**Comment by jaredpar** [comment]
Thanks for reporting. 

> Although it does not appear to be documented

A frequently problem with vim features 😦 

> when you do 1000^d or 1000^u in vim it will not scroll more than one screen.

Can you clarify what you mean by screen here?  If I use 1000^d in my vim window it happily scrolls up many increments of the current view port size.  Not quite sure what screen means here.

**Comment by laktak** [comment]
Well, if Vim shows 40 lines and I press `^d` I end up on line 21 (starting on line 1). If I go back to line 1 and do 1000^d I'm on line 41 (not line 1000). That's mostly similar to how page up/down works in Windows.

Tested with `vim -u NONE` on Mac/Linux/Windows.

I also found the page that I got this tip from http://vimrc-dissection.blogspot.ie/2009/02/fixing-pageup-and-pagedown.html (see update 2)

**Comment by jaredpar** [comment]
Okay it looks like <kbd>Ctrl-D</kbd> and the other scroll commands like <kbd>Shift-Down</kbd> and <kbd>PageDown</kbd> process the count argument differently.  The documentation for count and <kbd>Ctrl-D</kbd> seems completely wrong though.  Will have to experiment a bit with this.  At a glance it seems that count doesn't really affect <kbd>Ctrl-D</kbd> at all.

**Comment by laktak** [comment]
Btw, I tried to find a workaround using VS functions but this does not appear to work either (not work means it does not appear to do anything)

```
noremap K :vsc Edit.PageUp<CR>
noremap J :vsc Edit.PageDown<CR>
```

Strangely `noremap K :vsc Edit.ScrollPageUp<CR>` did work though that's not what I need.

**Comment by sqlkoala** [comment]
If `<C-f> and <C-b>` is what you want, take a look here:
https://github.com/jaredpar/VsVim/issues/2002
I posted a workaround for this problem.

**Comment by ricksladkey** [comment]
I've fixed `<C-f>`, `<C-b>`, `<C-u>`, and `<C-d>` to work exactly like vim (including the window size limiting and obeying the `startofline` setting) in PR #2223. Furthermore, if you don't like how page up/down work in vim (as in the referenced blog), the suggested technique (e.g. `map <silent> <PageUp> 1000<C-U>`) should also work.
