### ISSUE TITLE
Maybe support the ctrl+6 for switching between buffers like vim?

### ISSUE THREAD

**Issue by lorry-lee** [jaredpar/VsVim#1890]
That would be a very convinent way to switch to and back without spliting window i think.

**Comment by jaredpar** [comment]
Thanks for the feedback.  I will look into it. 

Features like buffer switching though tend to be difficult in Visual Studio.  The core vim infrastructure I have supports the idea.  But Visual Studio itself doesn't really support re-purposing existing windows with new buffers.  Instead it has to open new ones.
