### ISSUE TITLE
modifies key bindings but not reflected on UI

### ISSUE THREAD

**Issue by Jimmy-Z** [jaredpar/VsVim#1894]
close this if it's vscode.

**Comment by jaredpar** [comment]
Can you give some more detail here?  I'm not sure what UI you're referring to here in Visual Studio.

**Comment by Jimmy-Z** [comment]
like in the menu
![image](https://cloud.githubusercontent.com/assets/85773/21581952/65a938ce-d081-11e6-9d3a-f6d819daae81.png)
or the command line
![image](https://cloud.githubusercontent.com/assets/85773/21581957/9079d4a0-d081-11e6-918b-707ea95eae0f.png)
Ctrl-T is not working anymore but still shown

**Comment by Jimmy-Z** [comment]
sorry, I just realized this is not vscodevim, that's humiliating...

**Comment by jaredpar** [comment]
No worries.  It's happened a few times :smile:
