### ISSUE TITLE
Calling VsVim.SetMode programatically can cause popup error window

### ISSUE THREAD

**Issue by cbates-** [jaredpar/VsVim#1896]
- My current document is a class diagram
- In the command window I execute:
  >VsVim.SetMode Normal
- Error message: "Could not detect an active vim bufferThe operation could not be completed. Unspecified error"

If I try to execute the same command from within my extension via DTE.ExecuteCommand (the class diagram is the current window/buffer):
_dte.ExecuteCommand("VsVim.SetMode", "Normal");

A dialog pops up:
![image](https://cloud.githubusercontent.com/assets/1412601/21690493/8703118e-d342-11e6-971c-385ef05ad197.png)

Is there any way to suppress this?
Thanks --

**Comment by jaredpar** [comment]
Hmm, I'm not sure why that dialog is popping up.  It's certainly not anything that I'm doing.  It must be originating from within Visual Studio itself.  I'm unsure how that could be suppressed then.

**Comment by cbates-** [comment]
Ok.  The message in the popup is almost identical to the one in the command window, and if I don't invoke the vsvim.setmode command the popup doesn't appear, so I thought vsvim might be involved.
Thanks.
