### ISSUE TITLE
Integration with neovim

### ISSUE THREAD

**Issue by Swoorup** [jaredpar/VsVim#1899]
Are there any plans to integrate and use neovim as a backend instead?

**Comment by jaredpar** [comment]
There are no plans at this time.  

I looked into this a while back, as did a few other developers familiar with VsVim, and it didn't seem like it provided quite the type of hooks we need.  VsVim actually integrates very deeply into the VS editor infrastructure, both providing and consuming information.  This is required to have the seamless integration into the VS editing experience.  

Additionally there are a number of low level vim concepts that just don't have the right mappings for a true vim engine.  Buffers in particular don't have a real equivalent in VS.  

If anyone has a good plan for this I'd be interested in reading it.  But at this time it doesn't really seem feasible.
