### ISSUE TITLE
`P` and `p` only paste on the first line of a block selection

### ISSUE THREAD

**Issue by mfrischknecht** [jaredpar/VsVim#1900]
Steps to reproduce:

Given the Text:

```
test

foobar 1
foobar 2
foobar 3
```

- Move the cursor to `test` and yank it (e.g. `y i W`)
- Move the cursor to the first `foobar`
- Block-select all `foobar` occurrences (e.g. `0 C-v j j e`)
- Try to paste the yanked `test` to each line (`p`)

In vim, one would end up with all three occurences of `foobar` replaced by `test`, i.e.:
(tested using [vim.js](https://coolwanglu.github.io/vim.js/emterpreter/vim.html))
```
test

test 1
test 2
test 3
```

In Visual Studio, only the first line in the block selection gets replaced, the others are simply deleted:
(tested using both VS2015 and VS2010 w/ VsVim 2.2.0.0)
```
test

test 1
 2
 3
```

**Comment by farzadmf** [comment]
I tried with gvim, and it behaves the same as VsVim.

Also, it may not be the place, but one thing I like in GVIM is that, in this example, when we yank "test" (e.g., using `y i w`) and the cursor is in the middle of the word, then after the yank, the cursor moves to the beginning of the word, but this doesn't happen in VsVim

**Comment by mfrischknecht** [comment]
Funny, I didn't get that on my system. I recorded the test here: https://youtu.be/o8FHKilOTt4 (apologies for the music; I was listening to a podcast and my mic picked it up).

As you see, at least for my machine, GVim produces the expected result. Same goes for Neovim. Have you used a specific version of GVim? I've done a fresh installation from the Arch repo (v 8.0.0170-1).
