### ISSUE TITLE
Cursor visual clue when yanking

### ISSUE THREAD

**Issue by farzadmf** [jaredpar/VsVim#1903]
Suppose that we have the following and the cursor is on **b** in the brackets:
```
MethodCall(a, b, c);
```

Now we want to yank what's in the brackets into the `a` register, using `"ayi(`.
* In Gvim, when we do this, as soon as we press `y`, the cursor changes to a box with half the height, and stays like that until we press `(`. At this point, the cursor's height goes back to normal, and it jumps to the beginning character inside the brackets (`a` in this example)
* In VsVim, cursor's height changes to half when we press `y`, but it goes back to its original height as soon as we press `i`. Also, after we finish the keystrokes (i.e., after we press `(`), the cursor stays where it was (on `b`) instead of jumping to the beginning character inside the brackets

I think Gvim's cursor behavior provides a better visual clue to what's happening.

**Comment by jaredpar** [comment]
That seems like a bug.  The intent is to have the half cursor for the entire time here.

**Comment by farzadmf** [comment]
And also, the jump to the beginning character is also very useful, if implemented
