### ISSUE TITLE
Support using registry character for vi command

### ISSUE THREAD

**Issue by tgaldi** [jaredpar/VsVim#1906]
Hi,

I'm trying to use
 
`:nnoremap<leader>t vy:execute "normal! vi<c-r><c-w> "<CR>`

> vy - copy character into registry, execute vi[character]

to visually select everything within the enclosing character. This kind of binding works in vi/vim but not in VsVim.

**Comment by jaredpar** [comment]
Can you point to some documents about how `vy` should work here?  It seems like it should go to Visual Charactor mode and yank a single character (which works in VsVim).

**Comment by tgaldi** [comment]
Vy works correctly but using vi with the yanked character does not. 

So if I used vy on a ( and then tried to use vi with the character in the registry it should highlight everything between the opening and closing ().

The macro I posted will make a single command to do this with any enclosing characters.

**Comment by jaredpar** [comment]
Closing as I still can't find documentation on <kbd>vy</kbd>. If you can provide a link to the documentation here, or the right `:help` command to execute, would be happy to look into this.
