### ISSUE TITLE
Can't <enter> in command mode if line is triple-slash commented

### ISSUE THREAD

**Issue by MattRWallace** [jaredpar/VsVim#1910]
I'm using visual studio 2015 and noticed intermittent annoying behavior trying to save changes.  I narrowed it down to when I was on a line that started with a triple slash comment, I do not see this when the line is only double slashed.

When I type a command that moves the cursor to the prompt after hitting enter instead of executing the command it acts like I was in insert mode and inserts a newline.

**Comment by jaredpar** [comment]
This looks like a dupe of #1470.
