### ISSUE TITLE
Same key mapping for different modes not independant

### ISSUE THREAD

**Issue by franckspike** [jaredpar/VsVim#1911]
in .vsvimrc
```
nnoremap €W     f(%/{<CR>wvi{<vi{Dpbv%b%b"wD
vnoremap €W     D"wPvf(%/{<CR>%=bPvi{>
```
end up incorrectly only listed (by :map) as
`v    €W f(%/{<CR>wvi{<lt>vi{Dpbv%b%b"wD`

and then,
the execution of the normal mapping does not work (seems to end just before the %),
the execution of the visual mapping works though

if I manually do
`:nnoremap €W     f(%/{<CR>wvi{<vi{Dpbv%b%b"wD`
then it works (and still is badly listed the same by :map)

To try this mapping do
```
if (condition)
{
  code
}
```
put cursor on "if", execute the normal mapping,
then visual "code" and execute the visual mapping

**Comment by jaredpar** [comment]
Can you give a bit more information here?  I'm not sure what the problem is here.  The maps are separated (and fairly heavily tested).

**Comment by franckspike** [comment]
(sorry I wanted to update earlier but couldn't)
