### ISSUE TITLE
gd stopped working

### ISSUE THREAD

**Issue by PiotrPerak** [jaredpar/VsVim#1913]
I really love using `gd` instead of `F12` but it stopped working in VS2015.  It fires `goto next usage`.

Is it sth wrong with my configuration? This is new laptop.

**Comment by jaredpar** [comment]
What language are you using <kbd>gd</kbd> in?

**Comment by PiotrPerak** [comment]
C#

**Comment by haolly** [comment]
me too, In my vs 2013, `gd` shows next usage of `xxx` ,  which is a function call

**Comment by jaredpar** [comment]
Sorry but Im unable to reproduce this bug. Tried a number of times.
