### ISSUE TITLE
Anyword completion request 

### ISSUE THREAD

**Issue by samsu611** [jaredpar/VsVim#1914]
Hi great plugin but could you implement any word completion which is done like by CTRL+N and CTRL+P.

**Comment by theprash** [comment]
Have you gone into VsVim settings (within the main VS settings) and given control of those key combinations to VsVim?

**Comment by samsu611** [comment]
Sorry, but how do I do that exactly?

**Comment by theprash** [comment]
In Tools > Options:

![image](https://cloud.githubusercontent.com/assets/1362490/22853899/86b3eee0-f059-11e6-973a-7e066854f54e.png)

**Comment by samsu611** [comment]
Wow, this works! My only caveat is that the intelisense window appears but that isn't something major to be hung upon so I'll get over it  . Thank you theprash. 🥇
