### ISSUE TITLE
deleting visual selection with D doesn't delete the full line

### ISSUE THREAD

**Issue by kitwestneat** [jaredpar/VsVim#1915]
Sorry if this has already been reported, but in vsvim the D key behaves like x when there is a selection. In regular vim though, it deletes the full start and end lines of the visual selection.

For example, given this text where the brackets indicate a visual selection:
hell[man's
lma]o world

In vim (and vsvim), hitting x would leave you:
hello world

However in vim, D would erase everything. Is it possible to get that behavior in vsvim?

Thanks.

**Comment by jaredpar** [comment]
I just checked VsVim and I'm seeing the proper behavior for <kbd>D</kbd> in Visual character mode.  It does a linewise deletion of the selected region.

It's possible a bad key mapping is causing the difference here.  Can you check and see if <kbd>D</kbd> is mapped in your active session to values you weren't expecting?

**Comment by kitwestneat** [comment]
The problem was on my end, sorry for the confusion and thanks for your help.
