### ISSUE TITLE
Feature to enable debug output

### ISSUE THREAD

**Issue by vincpa** [jaredpar/VsVim#1916]
I would love to see a debug feature which writes to a log file so at times when vsvim isn't working correctly there is some diagnosic info available.

At least once a day vsvim stops working and I need to restart Vs. Perhaps there's an issue with another plugin? Not sure but it would be a good excuse for me to open my first pull request ☺️

**Comment by jaredpar** [comment]
Hmm, this shouldn't be happening at all.  Can you be more specific about what happens when VsVim isn't working?  

There are logging capabilities inside the code base.  It's just not enabled by default in the released code.  Would be relatively simple to add an option to do so.

**Comment by vincpa** [comment]
Sometimes Yanking and pasting just ceases to work or moving around, such as 2T<char> just doesn't work and the cursor just blinks. Other times, the arrow keys fail to move around the screen. Sometimes closing the active window makes VsVim work again, others it's a full restart.

Executing a vsvim command to dump some sort of state information might be able to help narrow down the problem.

I wish I could tell you more, like some steps to reproduce, but with lots of plugins loaded into VS and background processes firing off, who knows what the cause is :)
