### ISSUE TITLE
Tools -> VsVim Set mode ?

### ISSUE THREAD

**Issue by cbates-** [jaredpar/VsVim#1917]
Win10, VS 2015 Pro, VsVim 2.2.0.0
Why does VsVim install a "VsVim Set mode" menu item on the Tools menu?
When clicked, a message box pops up:
<--------------------------------------
Microsoft Visual Studio

The operation could not be completed. The parameter is incorrect.

OK
-------------------------------------->
I uninstalled VsVim and restarted VS 2015 - the menu item was not there.
I reinstalled VsVim and restarted VS 2015 - the menu item is on the Tools menu.

**Comment by jaredpar** [comment]
This seems to be an issue processing the VSCT file.  There is a command VsVim registers called SetMode.  But it's also specified as not having any UI hence this should not happen.  

Will ask around and see if there is a way to force this part of VS to reset and re-process the file.

**Comment by cbates-** [comment]
Weird.  I uninstalled an extension, but it still seems like VS2015 is trying to use it.  
Related to the VSCT file?  Who knows?

**Comment by aaron-meyers** [comment]
I'm having the same issue with VS2017 on a new machine.

Jared, feel free to reach me at MSFT if you'd like more repro info (alias ameyers).

**Comment by mitsukuri** [comment]
Same issue here, VS2017 (15.1.26403.7)

**Comment by ChannelOne** [comment]
Same issue, VS2017, Win10
