### ISSUE TITLE
Would it be possible to implement navigation through Intelisense with J and K?

### ISSUE THREAD

**Issue by PiotrPerak** [jaredpar/VsVim#1918]
It's the only time when I have to move my hand to arrow keys.

**Comment by chizran** [comment]
You can set custom keybindings for Edit.LineUp and Edit.LineDown in Visual Studio under Environment > Keyboard.  I use Alt - J and Alt  - K. The same binding is used for navigating through the Intellisense menu.

**Comment by PiotrPerak** [comment]
Wow! I didn't think I can remap this in VS. Thanks a lot!

**Comment by farzadmf** [comment]
Great to know. Thanks @chizran
