### ISSUE TITLE
Help testing VsVim setup changes

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#1925]
Support for Visual Studio 2017 is being [merged into master](https://github.com/jaredpar/VsVim/pull/1924) now.  The work here is larger than typically needed for a new version of Visual Studio because I had to migrate to the 2.0 version of VSIX.  That's a significant change to the setup process.

In theory this should be a no-op for users.  In practice though I like to get as much verification as possible for installation changes.  But properly covering this requires machines with all possible combinations of Visual Studio 2012 through 2017.  Not easy for a single developer.  Hence I wanted to give ethusiastic developers a change to help out here and let me know if the following VSIX installs + runs fine for them. 

- [VsVim 2.2.1](https://vsvim.blob.core.windows.net/drops/VsVim-2.2.1.0-beta1.vsix)

The combination of installations verified is listed below.  Please let me know if there are others I can add to this list:

- [x] VS 2017 + 2015
- [x] VS 2017
- [x] VS 2015
- [x] VS 2013
- [x] VS 2012

Note: Visual Studio 2010 is explicitly **not** supported anymore on the master branch and standard releases.  The changes to installation for Visual Studio 2017 make it impossible to continue producing a single VSIX that works on all Visual Studio versions.  Rather than juggle multiple VSIX and gallery pages I decided to drop support for 2010 in the main tree.  I will release an extension, tentatively named "VsVim Legacy", which is the equivalent of the 2.2.0 release.  Hence 2010 developers can continue to use that version.

**Comment by Chris-E-J-Ellis** [comment]
Works for me with VS 2013 - 12.0.21005.1 REL
Success when upgrading from existing release version.
Success when uninstalling/re-installing this version.
Thanks.

**Comment by allender** [comment]
Upgrade and fresh install on 2015 work without issue.

**Comment by jaredpar** [comment]
Thanks @Chris-E-J-Ellis and @allender

**Comment by Chris-E-J-Ellis** [comment]
Also works on my other PC VS Pro 2012 -  11.061219.00 Update 5 + VS Pro 2015 - 14.0.25123.00 Update 2
Upgrade and uninstalling/re-installing all successful, barring the minor cold sweat when opening VS without VsVim installed.

**Comment by jaredpar** [comment]
@Chris-E-J-Ellis thanks again!

**Comment by jaredpar** [comment]
Got all of the major VS releases covered now.  Thanks everyone for helping out!
