### ISSUE TITLE
Dot completion woes

### ISSUE THREAD

**Issue by ssmith73** [jaredpar/VsVim#1926]
Great work - i use this plugin everyday - apologies if this has been mentioned before.

Dot '.' repeat does not work for me if i use intellisence completion on the previous command (the command i want to repeat), it only completes what i actually typed, rather than the completed form. Is this something i'm doing badly or is it a known issue?

**Comment by jaredpar** [comment]
Thanks for reporting. Closing as a dupe of #664.
