### ISSUE TITLE
vsvim 2.2 : "behave mswin" not active in vs community edition 2015 without _vsvimrc

### ISSUE THREAD

**Issue by n3wjack** [jaredpar/VsVim#1927]
From what I recall VsVim behaves as a Windows Vim instance as long as you don't have a _vsvimrc file setup with Visual Studio. I noticed that at work where I created such a file to store some custom keybindings and suddenly my VsVim started going into visual mode where it didn't before.

Recently I setup VsVim on VS community edition 2015 on my home laptop and there the visual mode weirdness started right away. When I entered <ESC>:behave mswin all was fine.

So I ended up creating an _vsvimrc file which currently only contains the behave mswin command so it won't act up, but it would be handy if it would just behave like a windows Vim by default.
Since VsVim is a Visual Studio plugin which only runs on Windows, I don't see the point of not having "behave mswin" set as a default (as gVim on Windows also does). 
But I'm probably missing history here.

**Comment by jaredpar** [comment]
> So I ended up creating an _vsvimrc file which currently only contains the behave mswin command so it won't act up, but it would be handy if it would just behave like a windows Vim by default.

I agree that's a reasonable position.  Unfortunately VsVim originated with the present behavior of acting like normal Vim.  By the time I got around to properly implementing the `behave mswin` support VsVim had many thousand users.  Changing the default behavior at that point would be a fairly large breaking change and disrupt a number of users.  Hence I've decided to keep the current default.

**Comment by n3wjack** [comment]
Strange. I thought the default was "behave mswin" before. I can't remember having to create a _vsvimrc file before to force it to mswin behavior. It's only on new installs I'm seeing this.
Well, something to keep in mind for the future then. :)
