### ISSUE TITLE
Release Notes need updating for v2.3.0.0

### ISSUE THREAD

**Issue by ericmutta** [jaredpar/VsVim#1930]
Visual Studio just told me there is an update for VsVim (I currently have 2.2.0.0) but it appears the [release notes](https://github.com/jaredpar/VsVim/blob/master/Documentation/release-notes.md) in the documentation folder have not been updated to say what's new!

**Comment by jaredpar** [comment]
Thanks for the ping.  Will get these updated. 

Sadly nothing fancy: just VS 2017 support.  Will update when i get a few bug fixes out ove the weekend.

**Comment by ericmutta** [comment]
Many thanks for your continuing effort with this plugin, it is truly a life-saver!
