### ISSUE TITLE
gd doesn't seem to work on 2017

### ISSUE THREAD

**Issue by keithn** [jaredpar/VsVim#1931]
So I have 2015 and 2017 installed side my side, both with VsVim,  gd works fine in 2015, but nothing seems to happen in 2017.    Both using the same C# project

**Comment by shmup** [comment]
I can verify the same behavior. Clean install of VS2017 and a clean install of VsVim with no additional extensions. No `gd` behavior.

**Comment by jaredpar** [comment]
This behavior is known for VS 2017.   Hopefully have time to clean that up over the weekend.
