### ISSUE TITLE
Feature Request: Allow commands when text editor is not open.

### ISSUE THREAD

**Issue by zolem** [jaredpar/VsVim#1933]
Use Case:
All my files are closed and I want to open a file without using my mouse. I currently have \<leader\>o set to :vsc Edit.GoToFile<cr>

Of course this does not work when a file is not open because vim is not capturing anything. I was curious if it was possible to set a command to work globally like this? Sure would be great for me. Thanks!

**Comment by jaredpar** [comment]
Hmm, I'll have to think about that.  The command window today is based on being an editor widget essentially.  Lacking an editor I'd have to open up a new widget to run the commands.

**Comment by jalexandretoledo** [comment]
Maybe a solution for that would also help to implement navigation in the Solution Explorer?

**Comment by ricksladkey** [comment]
The design of Visual Studio requires a text editor window in order for VsVim to receive keystrokes that would be processed as normal commands. In fact, VsVim isn't even loaded in the situation you describe, so I am closing this issue as it is not currently possible.

You can however, using Visual Studio's keyboard mechanism to bind any keystroke to, e.g. `Edit.GoToFile`, you can use the Visual Studio menu to avoid the keyboard, or you can use my favorite `Ctrl+Comma` to open any file in the solution.
