### ISSUE TITLE
Search for tab broken

### ISSUE THREAD

**Issue by jnothstine** [jaredpar/VsVim#1937]
I have Visual Studio 2017.  VsVim 2.3.0.0.

When I search for the tab character by entering / and then tab, it tabs out of the search area and back into my file.

Same thing happens if I try something like this:
:%s/sometihing/{the tab}/g

When I hit the tab key, it tabs out of that area.  This used to work correctly.

**Comment by jaredpar** [comment]
> When I hit the tab key, it tabs out of that area. This used to work correctly.

What behavior did you used to get here?

**Comment by jnothstine** [comment]
The old behavior was that I could search for a tab or replace one:

:%s/[insert spaces here]/[insert tab here/g

Would replace the spaces with tabs.  Now, the tab causes it to go to the source editor.

/[insert tab here]andAnotherWordHere

Would search for andAnotherWordHere preceded by a tab.  Now, the tab moves me into the editor.

**Comment by jalexandretoledo** [comment]
Although a TAB works in GVim, I'm not sure if it ever worked with VsVim (it didn't work with VS2013+VsVim-2.2.529). 

Anyway, I always use \t to indicate a TAB:
 
  %s/\t/something/g

or 

  %s/\t\+/\t/g

This works on GVim and also in VsVim.

**Comment by jnothstine** [comment]
Weird, I used it all the time.  Never had problems with it until the recent changes.

**Comment by ricksladkey** [comment]
It used to work in VsVim because the command margin didn't used to get the focus when you were entering a command.  All keystroke were handled by and forwarded from the text view that initiated the command or search.  I think I know how to fix this and if so I'll submit a PR.
