### ISSUE TITLE
Atmel Studio 7 support

### ISSUE THREAD

**Issue by charon00** [jaredpar/VsVim#1939]
Hello, does VsVim work with Atmel Studio 7 (built on VS2015, I believe)?

If not, any chance this could be implemented?

If so, how do I go about installing it?  I tried downloading VsVim.vsix from the Visual Studio Marketplace and double-clicking it, but an error message appears that says it is not installable on any currently installed products.

Thanks!

**Comment by jaredpar** [comment]
Looks like I just need to add the appropriate InstallationTarget

``` xml
<InstallationTarget Id="AtmelStudio" Version="7.0" />
```

That should unblock AtmelStudio support.

**Comment by jaredpar** [comment]
Grab the latest from here and it should work

http://vsixgallery.com/extension/VsVim.Microsoft.e214908b-0458-4ae2-a583-4310f29687c3/
