### ISSUE TITLE
Indenting in Visual Block mode only increases indentation

### ISSUE THREAD

**Issue by arijoon** [jaredpar/VsVim#1940]
In visual block mode (Ctrl-Q) 

 - **Current Behavior**: pressing '>' or '<' will both add indentation (move right). 
 - **Expected behavior**:  Pressing '>' adds indentation and '<' removes indentation (modes left)

**Comment by sqlkoala** [comment]
I checked the behavior and vsvim acts as described.
But there is visual line mode, where >  and < work as expected.
@arijoon is there a case where one has to use visual block?

**Comment by jaredpar** [comment]
Looks like a dupe of #1453

**Comment by arijoon** [comment]
@sqlkoala I don't exactly remember why I was doing this in visual block and not visual line, nevertheless it's best if the feature is always working as expected. (doubt this is a high priority item)
