### ISSUE TITLE
Parse error for :if statement

### ISSUE THREAD

**Issue by iamkarlson** [jaredpar/VsVim#1942]
I have the following statement for switching highlight search on and off:

`nnoremap <c-c> :if (hlstate%2 == 0) \| nohlsearch \| else \| set hlsearch \| endif \| let hlstate=hlstate+1<cr>
`

But vsvim gives me an parse error when I press CTRL+C.

I suppose the problem is in `\|` symbols or the **if** statement just is not implemented yet

**Comment by jaredpar** [comment]
Closing as full vim script support is no longer a goal of the project

https://github.com/jaredpar/VsVim/blob/master/Documentation/Project%20Goals.md
