### ISSUE TITLE
Cannot disable telemetry

### ISSUE THREAD

**Issue by abhijat** [jaredpar/VsVim#1943]
I cannot disable telemetry via the Tools -> Options -> VsVim -> Telemetry toggle. I set this value to false, but when I inspect the value again after clicking on OK, the value shows up as True again. I have tried this on two separate installations of VS 2015, professional as well as community. 

It is still True after a restart of Visual Studio as well.

**Comment by jaredpar** [comment]
Huh.  Not sure why that setting isn't sticking.  Let me look into that.

**Comment by jaredpar** [comment]
This should be fixed now.
