### ISSUE TITLE
VS2017 - Switching view/moving of tabs doesn't seem to be working

### ISSUE THREAD

**Issue by connador** [jaredpar/VsVim#1944]
'gt', ':tabm -2', ':tabn 2' (etc) don't seem to do switch or move tabs, though VsVim is working otherwise (arrow keys, x, gg, GG, search and replace, etc.)

Additionally, the VsVim Setmode option displays an error (see attachment below)

I couldn't find anything specifically mentioning this in the issues (unless I completely missed it), so I wonder if maybe I have something configured incorrectly. I've attached my configuration for clarity, please let me know if there's anything else I can supply to help

![bindings_one](https://cloud.githubusercontent.com/assets/696702/24787228/104f6fca-1b1c-11e7-9274-08678620911b.PNG)
![bindings_two](https://cloud.githubusercontent.com/assets/696702/24787229/104f7eac-1b1c-11e7-8c26-3d48f210b999.PNG)
![options](https://cloud.githubusercontent.com/assets/696702/24787231/105058b8-1b1c-11e7-8f2f-c2d34e63867a.PNG)
![setmode](https://cloud.githubusercontent.com/assets/696702/24787230/104fd046-1b1c-11e7-92d5-7d9480cdefe8.PNG)

**Comment by zolem** [comment]
having issues with switching tabs also

**Comment by petitp00** [comment]
I'm having the same issues as well

**Comment by Zundrium** [comment]
Same here. Using Visual Studio 2017.

**Comment by jaredpar** [comment]
This should be fixed now in the 2.4.0 release.
