### ISSUE TITLE
VS2017 Ctrl+N not handled

### ISSUE THREAD

**Issue by darkpotpot** [jaredpar/VsVim#1947]
Hi,

I have VSVim installed for both Visual Studio 2015 and 2017. 

In 2015, I can see in VsVim/Keyboard option if I want to handle Ctrl+N with VsVim or Visual Studio. Handling it with vim works well and I have the autocomplete feature.

In 2017, I can't see this combinaison of key in the VsVim/Keyboard option and the autocomplete feature is not working.

Regards

Julien

**Comment by darkpotpot** [comment]
Hm, in fact it seems a lot of combinaison are missing in the VsVim/Keyboard option.

For exemple, ctrl+c is also not listed anymore. It works as expected in vim mode, but if I disable vsvim with ctrl+shift+f12, I can't copy text with ctrl+c like I would do witout vsvim mode in visual studio 2015

**Comment by darkpotpot** [comment]
This time I had an error windows when doing ctrl+n, asking me to check the log. Here is the error, in case of any help

> System.InvalidOperationException: Cannot Match. The session is dismissed. at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Match() at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start() at Vim.UI.Wpf.Implementation.WordCompletion.WordCompletionSessionFactoryService.Vim.IWordCompletionSessionFactoryService.CreateWordCompletionSession(ITextView textView, SnapshotSpan wordSpan, IEnumerable`1 wordCollection, Boolean isForward) at Vim.Modes.Insert.InsertMode.StartWordCompletionSession(Boolean isForward) at Vim.Modes.Insert.InsertMode.ProcessWordCompletionNext(KeyInput keyInput) at Vim.Modes.Insert.InsertMode.Process(KeyInput keyInput) at Vim.Modes.Insert.InsertMode.Vim-IMode-Process(KeyInput keyInput) at Vim.VimBuffer.ProcessOneKeyInput(KeyInput keyInput) at <StartupCode$Vim-Core>.$VimBuffer.processSet@485(VimBuffer x, FSharpRef`1 processResult, KeyInputSet keyInputSet) at Vim.VimBuffer.ProcessCore(KeyInputSet keyInputSet) at Vim.VimBuffer.Process(KeyInput keyInput) at Vim.VimBuffer.Vim-IVimBuffer-Process(KeyInput keyInput) at Vim.UI.Wpf.VimKeyProcessor.TryProcess(KeyInput keyInput) at Vim.VisualStudio.Implementation.Misc.VsVimKeyProcessor.TryProcess(KeyInput keyInput) at Vim.UI.Wpf.VimKeyProcessor.TextInput(TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c.<DispatchTextInputEvents>b__6_0(KeyProcessor p, TextCompositionEventArgs args) at Microsoft.VisualStudio.Text.Editor.Implementation.KeyProcessorDispatcher.<>c__DisplayClass10_1`1.<Dispatch>b__0() at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by agouwin** [comment]
@darkpotpot i can't even do ctrl+shift+f12 in Version 1.13.1 (1.13.1) + vsvim v0.9.0?

**Comment by darkpotpot** [comment]
Hm, I figured out why ctrl+c or ctrl+v were missing. They weren't defined anymore in Visual Studio Keyboard shortcut for Edit.Copy and Edit.Paste. I suppose now it uses the default windows combination key. 
If I add ctrl+c and ctrl+v for Edit.Copy and Edit.Paste, disabling vsvim with ctrl+shift+f12 makes the copy/paste shortcut works. If it's not defined, I cannot copy/paste when I disable vsvim.

**Comment by sqlkoala** [comment]
I noticed the same. After switching from vs2015 to VS2017, some key combinations are not displayed under tools->vsvim->keyboard.  (inkl Ctrl+c, Ctrl+n)
Must be because they are not used in vs2017. But for me, autocomplete via Ctrl+n works in vsvim.
