### ISSUE TITLE
`cw` and related commands should trigger intellisense

### ISSUE THREAD

**Issue by 333fred** [jaredpar/VsVim#1948]
If I have the "Show completion list after a character is deleted" setting checked, and I trigger a delete and replace like `cw`, I'd like for the intellisense prompt to be triggered. Relevant setting:

![image](https://cloud.githubusercontent.com/assets/2371880/25544483/7ff6e714-2c0f-11e7-9190-813449f785b2.png)

**Comment by jaredpar** [comment]
Unfortunately there isn't a lot I can do here.  The VS infrastructure doesn't have a way of arbitrarily triggering Intellisense.  It can only be incidentally triggered by other actions such as a key stroke. 

If someone from say Roslyn wanted to add this.  Then it's possible that I could hook into it.  But at this time there really isn't a way.
