### ISSUE TITLE
Retain highlight after indenting. 

### ISSUE THREAD

**Issue by Tombert** [jaredpar/VsVim#1950]
When I need to block-indent, I usually use `V` to select the line, and then use `j` or `k` to select the lines I care about, and complete it with `>`.  

The problem is that that only indents a single level, after which the highlight disappears.  Is there a mechanism in which I can retain the highlight so that I may indent multiple levels without having to reselect?

**Comment by farzadmf** [comment]
Normally, pressing `.` (dot) after such an action will repeat your action on your previous selection. I think that should work fine if your only intent is to repeat the last action (indenting)

**Comment by Tombert** [comment]
I feel silly for not thinking of this myself.  Thank you!
