### ISSUE TITLE
AtmelStudio versioning

### ISSUE THREAD

**Issue by RobinCutshaw** [jaredpar/VsVim#1953]
I downloaded the latest vsvim extension from the visual studio site and it fails to install saying that it doesn't support AtmelStudio.  It does claim to be version 2.3.0 which is the latest version in the github master manifest (which claims to support AtmelStudio 7).  Does the version need a bump?

Also, the version of vsvim in the Atmel Gallery is old and does not support version 7.

Any possibility of including the compiled extension in the master tree once there is a version bump?  This would be helpful to AtmelStudio users that don't have visual studio to compile from source.

Robin

**Comment by jaredpar** [comment]
Atmel Studio version 7.0 is supported in the master branch.  I just haven't published a version to the Visual Studio gallery that has this yet.  I'm planning on doing an update over the weekend which will include this.  

In the mean time you should be able to grab a build off of VsixGallery and it will have this change

http://vsixgallery.com/extension/VsVim.Microsoft.e214908b-0458-4ae2-a583-4310f29687c3/
