### ISSUE TITLE
The substitution command shouldn't require the `.` when substituting from the current line.

### ISSUE THREAD

**Issue by pushkin-** [jaredpar/VsVim#1958]
Currently, substituting from the current line requires a `.`: `:.,5s/...`

But from my [experience](http://www.vim.org/download.php) (couldn't verify this [here](http://vim.wikia.com/wiki/Ranges)), you should be able to omit the `.`:

`:,5s/...` will perform the substitution from the current line to line 5.

**Comment by jaredpar** [comment]
Yeah that looks like a bug.  Should be easy enough to fix.

**Comment by chaitanyagurrapu** [comment]
Yay! Happy to see the "Easy" label being used in vsvim. I keep looking for ways to contribute more to the project and this was the missing piece. Well ... this and my lack of F# knowledge, visual studio development knowledge and time really. ;-)

**Comment by ricksladkey** [comment]
Ha, ha, harder than it looked!

The default for `s` (`substitute`) was already the current line. The reported bug is related to an empty line specifier before or after a `,` (or before or after a `;`).

Previously, any line specifier followed by just a `,` referred to just that line but it should refer to that line through the current line. In other words, the default line specifier after a `,` is `.`.

Previously, `,` alone or `,` followed any line specifier produced a parse error, but it should refer to either just the current line or the current line through the specified line. In other words, the default line specifier after a `,` is also `.'.
