### ISSUE TITLE
CTRL+W, CTRL+L Not working in specific circumstances

### ISSUE THREAD

**Issue by thismat** [jaredpar/VsVim#1960]
Okay this is oddly specific, I was reluctant to even submit it as an issue.

VsVim Version:  2.4.0.0
Visual Studio Version: 2015
Resharper 2015 Installed

If you have a 2 pane vertical tab group, and a `.sql` file on the left, `CTRL+W,CTRL+L` will not swap you to the right. However if you open up a `.cs` or `.config` or I assume a number of other file in the left hand tab group, everything works fine.

Now, if you make it 3 tab groups vertically split and put the `.sql` file in the middle, `CTRL+W,CTRL+L` will move you left one group, to the edge. The opposite direction. 

I've only had it happen when editing `.sql` files, I am unsure if it's an issue with more types that don't have native document auto-formatting in Visual Studio or not.

EDIT: For Resharper, forgot about that.

My `_vsvimrc`:

```
" 
" Make things nice
"
set hlsearch
set clipboard=unname
set incsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set number


"
" VIM Specific
"

" map ; to :
map ; :

" map jj to escape
imap jj 

" map leader from , to space
let mapleader = "\<Space>"

" Breakpoints
map bp :vsc Debug.ToggleBreakpoint<CR>

"Navigation
nnoremap <Leader>, :vsc Edit.NavigateTo<CR>
nnoremap <Leader>g :vsc Edit.GotoDefinition<CR>
nnoremap <Leader>f :vsc Edit.FindAllReferences<CR>
nnoremap <Leader>e :vsc View.ErrorList<CR>

" Split Navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Tab Management
nnoremap <Leader>t :vsc Window.NewVerticalTabGroup<CR>
nnoremap <Leader>r :vsc Window.MoveToPreviousTabGroup<CR>
nnoremap <Leader>y :vsc Window.MoveToNextTabGroup<CR>

" Building
map bs :vsc Build.BuildSolution<CR>
map bc :vsc Build.CleanSolution<CR>
map <Leader>b :vsc Build.BuildSelection<CR>

" UI Hotkeys
map sl :vsc View.SolutionExplorer<CR>
nnoremap <Leader>. View.SolutionExplorer<CR>
```

**Comment by ricksladkey** [comment]
It's hard for me to try to repro this specific use case, but I'm fairly sure that on the head of master for VsVim this bug is fixed. The old method only worked for a specific set of circumstances and the new method should work for any window physically to the right of the cursor in the current window.

**Comment by ricksladkey** [comment]
Closing this issue because I believe it is fixed.
