### ISSUE TITLE
BUG: Dot command does not repeat autocompleted text.

### ISSUE THREAD

**Issue by ericmutta** [jaredpar/VsVim#1962]
The dot command is a handy way to make repetitive changes in code because it repeats what you did last. I usually use it like this:

1. Switch to edit mode (e.g by pressing 'cw' to change a word).
2. Type part of an identifier name (e.g 'Debug.A').
3. When Intellisense pops up press Tab to complete (e.g Debug.Assert).
4. Exit edit mode and go back to command mode (I press 'Esc' for this).
5. Move one line down and press dot to repeat edits made by step 2 and 3.

Doing the above, the dot command at step 5 repeats only the text explicitly typed in step 2 (i.e 'Debug.A') and ignores the extra text entered by autocomplete (i.e the letters 'ssert' to form the full 'Debug.Assert').

I am reporting this as a bug because gVim does the correct thing even if you use its autocompletion feature (i.e the dot command repeats all text, whether it was typed manually or inserted via autocomplete).

@jaredpar let me know if you can reproduce or if you need further clarification...and as always, thanks for your efforts on this extension, for me there is no Visual Studio without VsVim!

**Comment by ericmutta** [comment]
@jaredpar any word on this?

**Comment by jaredpar** [comment]
Sorry missed this.

Know there are issues here when the typed text and completed text differ in case. Should work otherwise though. Will look into it.

**Comment by ericmutta** [comment]
> Know there are issues here when the typed text and completed text differ in case.
That's interesting...I tested `Debug.writel` which is autocompleted to `Debug.WriteLine` and sure enough the dot command doesn't behave as expected. However if I create another method named `writeline` with that casing, then `writel` is autocompleted to `writeline` and the dot command repeats the edit and autocomplete just fine.

So looks like you've discovered the reason and I see you've planned a fix for milestone 2.4.1. Thanks @jaredpar I really appreciate your continued efforts on this superb extension!

**Comment by ericmutta** [comment]
(Not sure how closing issues works in this case, I suppose I leave it open and you actually close it when done?)

**Comment by ericmutta** [comment]
Hi @jaredpar I am using VsVim 2.4.1.0 and it appears this problem has been fixed. The dot command works like a charm! Much appreciated!
