### ISSUE TITLE
Control-P Word Completion?

### ISSUE THREAD

**Issue by dman777** [jaredpar/VsVim#1968]
First of all, thank you for this plug in.... it is a life saver!!!!!! 

Is there a ctrl-p word completion available? It's not working for me...instead I get the windows printer box. Wasn't sure if I was doing something incorrect.

**Comment by jaredpar** [comment]
Word completion is a supported feature. Sounds though like <kbd>Cntr+P</kbd> is still bound to a VS command. Have you checked to in the VsVim options that this is bound to VsVim?

**Comment by jaredpar** [comment]
Closing due to staleness.
