### ISSUE TITLE
Should VsVim be enabled on F# Interactive mode?

### ISSUE THREAD

**Issue by YellowOnion** [jaredpar/VsVim#1970]
F# Interactive is both broken and using VsVim, I assume VsVim is breaking some assumptions about  how the repl works as it is functionally useless.

**Comment by jaredpar** [comment]
Hmm, in general I try and disable VsVim in repl windows. Fixed the F# interactive window before. Not sure what changed though.

Short term though you can use Ctrl+Alt+F12 to disable it in that window.

**Comment by jaredpar** [comment]
Looked into this. The problem is F# is labeling this window essentially as a vanilla text document instead of an interactive buffer. VsVim won't install itself into any interactive buffer. 

Going to work with F# here to get this buffer to have the correct Interactive role.
