### ISSUE TITLE
Cannot enter '.' in breakpoint action logging dialog

### ISSUE THREAD

**Issue by RobinCutshaw** [jaredpar/VsVim#1971]
While debugging an issue in AtmelStudio 7, the '.' character is intercepted by VsVim and the last action is duplicated when trying to enter the '.' in the "log a message to Output Window" dialog in the breakpoint Action section.  As a result, you cannot enter structure members to print out.

**Comment by jaredpar** [comment]
Which window are you seeing this behavior in?

Sorry, not very familiar with Atmel Studio.

**Comment by RobinCutshaw** [comment]
Atmel Studio uses Visual Studio as its base.  When debugging a target, you click on the line you want to break at, select the gear icon to enter conditions or actions.  Under actions, you have the option to enter a string to output to the debug console (including variables).  You can enter text there as long as you don't enter a '.' (where VsVim will intercept and repeat the last command).

**Comment by loosche** [comment]
Happens to me in Visual Studio 2015 as well. I think it's been an issue since they started putting the Conditional box in the middle of the screen.

Steps
1. Add a break point to a line of code in the text editor
2. Right click on the red dot and select "Conditions..."
3. Type 'struct.member' into the text box provided (doesn't have to exist, even just typing period works)
4. Can't type period
5. Disable VsVim (Ctrl+Shift+F12)
6. Now I can type period in the text box

Expected: I can type the period character
Actual: Visual Studio plays an audio bell instead of typing period.

**Comment by eddieparker** [comment]
I have the same issue in VS with the same dialog in "Actions" as well as "Conditions".  A work around is that the period from the num key pad works (... but I keep forgetting about it until I've erased a bunch of stuff by accident. :)), in case that helps anyone.

**Comment by jaredpar** [comment]
I tried to reproduce this for a bit and was unable to. Tried both the action and condition inputs and both worked just fine. Can anyone reproduce this on recent builds?

**Comment by eddieparker** [comment]
Yes, still repros for me.  Dunno if it's a combo of my plugins?  Here's my system info if it helps:

Microsoft Visual Studio Professional 2017 
Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual C++ 2017   00369-60000-00001-AA347
Microsoft Visual C++ 2017

Add New File   3.5
The fastest and easiest way to add new files to any project - including files that start with a dot

ASP.NET and Web Tools 2017   15.0.40511.0
ASP.NET and Web Tools 2017

BuildVision   2.1.1.157
Building process visualization.

C# Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CustomizeVSWindowTitle 3   1.0
Information about my package

Entrian Inline Watch   1.0.8
Entrian Inline Watch: Shows the values of variables inline in your source code as you debug.

Entrian Source Search 1.7.14   1.7.14
Instant full-text search for your source code.

IncludeToolbox Extension   0.2
Tools around C/C++ #includes

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Smart Commandline Arguments Extension   2.0.4
A Visual Studio Extension which aims to provide a better UI to manage your command line arguments. For additional information, visit https://github.com/MBulli/SmartCommandlineArgs

Syntax Highlighting Pack   2.8.133
Adds syntax highlighting and snippet support for a wide variety of programming languages such as Clojure, Go, Jade, Lua, Swift, Ruby and many more...

Visual Assist   
For more information about Visual Assist, see the Whole Tomato Software website at http://www.WholeTomato.com. Copyright (c) 1997-2018 Whole Tomato Software, Inc.

Visual Basic Tools   2.8.2-beta6-62916-08. Commit Hash: 2ad4aabc7a9dada097e54e544ebba48ab1c05074
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Unity   3.7.0.1
Visual Studio Tools for Unity

VSColorOutput   2.5.1
Color output for build and debug windows - http://mike-ward.net/vscoloroutput

VsVim   2.5.0.0
VsVim is a Vim emulator for Visual Studio

Windows Machine Learning Generator Extension   1.0
Windows Machine Learning Visual Studio Extension Detailed Info

**Comment by eddieparker** [comment]
[ConsoleApplication1.zip](https://github.com/jaredpar/VsVim/files/2082031/ConsoleApplication1.zip)

I've also attached a sample application that exhibits it with the above plugins.

**Comment by ricksladkey** [comment]
The essential element appears to be Visual Assist and the offending code in VsVim appears to be doing exactly what the bug reports.

From: `Src\VsVimShared\Implementation\VisualAssist\VisualAssistKeyProcessor.cs`:

```C#
        public override void PreviewKeyDown(KeyEventArgs args)
        {
            VimTrace.TraceInfo("VisualAssistKeyProcessor::PreviewKeyDown {0} {1}", args.Key, args.KeyboardDevice.Modifiers);

            if (_vimBuffer.ModeKind == ModeKind.Normal && args.Key == Key.OemPeriod && args.KeyboardDevice.Modifiers == ModifierKeys.None)
            {
                // Visual Assist in general won't process any keys when we are in normal mode because we have 
                // the caret hidden.  However it appears they check for the caret hidden on a timer or some
                // form of delay.  This is provable by editting some text in insert mode then quickly hitting
                // Escape followed by '.'.  If this happens fast enough they will process the '.' directly 
                // instead of letting the key stroke go through.   This will cause a '.' to appear in the code
                // instead of a repeat action.  
                //
                // Experimentation shows that they only do this processing for a subset of keys including
                // '.'.  Letter keys and the like don't have this behavior so we let them go through
                // normal processing.  In the future though we may find more keys that need this exception
                _vimBuffer.Process(KeyInputUtil.CharToKeyInput('.'));
                args.Handled = true;
            }
```
