### ISSUE TITLE
Navigating to an uppercase mark placed in a closed file does not reopen file

### ISSUE THREAD

**Issue by halter73** [jaredpar/VsVim#1972]
VS 2017 15.3.0 Preview 3.0 [26621.2.d15rel]
VsVim 2.4.1.0

**Note:** In the repro below, marks behave as I would expect until after A.txt's tab is closed.

### Repro steps:

1. Create an uppercase mark `mA` in A.txt
2. Close A.txt's tab
3. Navigate to uppercase mark `'A` from another file.

### Expected behavior:

A.txt is reopened in a new tab, and the cursor is placed at the start of the marked line.

### Actual behavior:

Navigating to the the mark fails. VsVim shows a "Mark not set" status.

Even after A.txt is manually reopened, attempting to navigate to `'A` from another tab continues to fail with a "Mark not set" status. This was even true for tabs I successfully was able to do this from prior to closing A.txt.

### Other Strangeness

After A.txt is manually reopened, attempting to navigate to `'A` from A.txt's newly opened tab mostly succeeds. The weird part is that `'A` will now put the cursor the middle of the line precisely where the mark was set like I would expect `` `A`` to do instead of putting the cursor at the start of the line. `` `A`` continues to work as expected, but only from A.txt's tab.

**Comment by cbates-** [comment]
This might be related to an issue I reported some time ago --
Typing :marks only shows a global mark if you issue the marks command in the buffer that has the global mark.
- set mark A in A.txt.  :marks shows A.
- make B.txt current.  :marks does not show A.

**Comment by jaredpar** [comment]
Interesting. Global marks are stored globally so I wouldn't expect that type of bug. Will dig into.
