### ISSUE TITLE
VsVim Not Entering Insert after Refactor Start

### ISSUE THREAD

**Issue by 333fred** [jaredpar/VsVim#1974]
As the bug title says. After I hit `CTRL+R, CTRL+R` to enter refactor mode, VsVim does not enter  external edit detected mode, and enters visual mode instead. This only appears to be reproing on the latest builds of d15prerel at the moment, though I'm sure Int Preview will be affected eventually.

**Comment by jaredpar** [comment]
Sounds like Roslyn changed the refactor interface. I use dark, dark magic (aka reflection) to detect and manipulate Rosyln refactoring since there isn't a public API. If it changes it can break my detection.

**Comment by 333fred** [comment]
Update: this only seems to reproing on VB for me right now. C# appears to be working correctly.

**Comment by jaredpar** [comment]
Seems to be fixed now.

**Comment by 333fred** [comment]
Still repros on intpreview for me @jaredpar

**Comment by 333fred** [comment]
This seems to only be affecting VB at the moment.
