### ISSUE TITLE
Relative line number yanking from command line is not working.

### ISSUE THREAD

**Issue by bayantt** [jaredpar/VsVim#1976]
Only absolute line number yanking (or any operation) is working from command line, doing `-10,-6co.`, visual studio shows error dialog saying invalid line number.

**Comment by sqlkoala** [comment]
Hi,
it does work with one little "catch". Apparently you have to put a "." at least at the end of the range. Like so:
`-6,.-5 co +5
`
or in your example
`-10,.-6co.`
It's not 100% vim compatible of course, but (IMO) this is a small glitch I can work around.
