### ISSUE TITLE
Atmel Studio 7 with Visual Studio 2017

### ISSUE THREAD

**Issue by ChazNunz32** [jaredpar/VsVim#1977]
If Visual Studio 2017 is installed, and VsVim is added as an extension.
Then install Atmel Studio 7.   
If the downloaded installer for VsVim is re-run, it will not install in Atmel Studio 7.  In fact, I have not been able to install VsVim in Atmel Studio in this setup.  Previously was working.

The message "The extension is already installed to all applicable products." is displayed when the VsVim installer is run.

**Comment by jaredpar** [comment]
This should be fixed now via 55078dbe5b6ec59a286844c70ab6e79427a9ab2f
