### ISSUE TITLE
Backspace, Enter key won't work after sometimes

### ISSUE THREAD

**Issue by wongjiahau** [jaredpar/VsVim#1979]
- I'm not really sure how to replicate this issue, but it is very frustrating to me 
- After sometimes of using VsVim, when I went into INSERT mode, Backspace and Enter won't work as expected, I expect Backspace to delete a character and Enter to goto the next line 
- But actual behavior is, when Backspace is pressed, a '\r' character is inserted, which is not displayed in the editor, same goes for Enter key, a '\n' will be inserted but the cursor won't go to the next line
- However, I manage to resolve this issue everytime by going [Tools > Options > VsVim > Keyboard] then click on [Handle all with Visual Studio], then click on [OK] button. (But I need to wait at least one minute for it to resolve) 
- Therefore, can I know is this a bug or that I had accidentally went into some unknown mode?

**Comment by jaredpar** [comment]
Do you normally run gVim on this computer? If so it's possible there is a key mapping from your .vimrc file that VsVim is picking up and not able to fully execute. Can you run `:map` and see if it prints out any mappings around Enter and Backspace?

**Comment by wongjiahau** [comment]
@jaredpar Thanks for the reply, I ran the command, and I did not see any mappings around Enter and Backspace. I suspect that this problem is due to Resharper, but I'm still not able to reproduce the bug with a proper step. I will inform you when I found an exact steps to reproduce this error.

**Comment by wongjiahau** [comment]
@jaredpar I had found out that this issue is actually caused by Visual Studio itself, and to fix it just press [Alt + Enter] and this problem will be fixed.

Please refer to [this StackOverflow issue](https://stackoverflow.com/questions/10786257/backspace-doesnt-work-in-visual-studio) for more information.
