### ISSUE TITLE
Could not disable VsVIM in visual studio 2015 windows server 2008

### ISSUE THREAD

**Issue by Celthi** [jaredpar/VsVim#1981]
I have to disable vsvim when a coworker come to my computer as [this](https://github.com/jaredpar/VsVim/issues/740) is saying.

But I cann't disable VsVim through ctrl + shift F12. When I type ctrl+ shift + F12, the VS just change the focus into the Find Symbol Results windows.

I have try to let the VsVim to handle the ctrl + shift +F12 key, or VS to handle. But neither works.

I only can disable the VsVIM through the tools extension option and restart VS.

Any help is appreciated.

**Comment by jaredpar** [comment]
Sounds like <kbd>Ctrl+Shift+F12</kdg> is bound to another Visual Studio command. Can you try removing the key binding from that command. At that point VsVim will recognize the key again.

**Comment by Celthi** [comment]
Just now I tried with removing the keybinding for  `Ctrl+Shift+F12` from that command, which is show.findSymbol. But it still doesn't work. I have tried to let VsVim to handle `Ctrl+Shift+F12` and plus restart.

**Comment by Celthi** [comment]
It works, thanks. And great thanks for the VsVim.

**Comment by jaredpar** [comment]
Glad that worked!
