### ISSUE TITLE
mark does not work as {address} for  the ex copy command

### ISSUE THREAD

**Issue by Plotnus** [jaredpar/VsVim#1982]
I have two files, A, and B.
I wanted to copy an include from file B to File A.
I received an "Invalid address" error when using global marks referencing a different file.

For example:
  marked the line in file A with mA.
  go to file B and entered
  :5 co 'A
  if it repros you will get the result "Invalid address"

Note: I am running visual assist on vs2015

**Comment by jaredpar** [comment]
Didn't realize you could do that. Will look into implementing it.

**Comment by Plotnus** [comment]
Thanks jared. I really appreciate the work you've done
