### ISSUE TITLE
After substitute in selection and destroying selection I'm in command mode (VS2013/VS2015)

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#1987]
Hi,

If I select text with (e.g.) with `"Shift+V"` and start a substitution `":'<,'>s/…/…/"`, the selection is active at the end.
"Canceling" the selection by hitting `"Esc"` opens the command prompt `":"` and I need an additional hit on escape to get back to the text.

Can you please test, if you can reproduce and fix it?

Best regards,

Martin

**Comment by BigDub** [comment]
I experience this issue as well. It is rather annoying.
