### ISSUE TITLE
gd Command not really working [SOLVED]

### ISSUE THREAD

**Issue by wongjiahau** [jaredpar/VsVim#1994]
## Summary
The gd command (Go to method definition command) is not really working 

## Steps to reproduce
1. Move cursor under a method name. 
2. Press gd. 

## Expected 
Open the file where the method is located and move cursor to the method name.

## Actual 
The file where the method is located actually opened, but the focus is not moved to that file. Instead, Resharper show up a 'Go to next usage of XXX' popup. 
![image](https://user-images.githubusercontent.com/23183656/30087562-011864be-92d4-11e7-9ce2-33423a8e9240.png)

## Environment
1. Visual Studio 2017
2. Reshaper is turned on

**Comment by adrianjord** [comment]
I seem to be having the same issue when trying to map to `:vsc Edit.GoToDefinition<CR>` in my `.vsvimrc`

**Comment by jaredpar** [comment]
I think that ReSharper is likely the issue here. The `gd` command is implemented by calling into the Edit.GoToDefinition command. Guessing that ReSharper is getting in the way somehow here.

**Comment by adrianjord** [comment]
@jaredpar You are right, in the ReSharper options there is an option under 'Search & Navigation' called "Enable 'Smart go to declaration'". When unchecked, GoToDefinition works as expected. It's odd that it's called 'Smart go to declaration' when it doesn't affect GoToDeclaration, just GoToDefinition.

![image](https://user-images.githubusercontent.com/3665200/31078315-381b3702-a747-11e7-8618-2117fc8c7f60.png)

**Comment by wongjiahau** [comment]
@adrianjord Thank you! 
[Issue solved]
