### ISSUE TITLE
Repeat last colon command [Feature-Request]

### ISSUE THREAD

**Issue by wongjiahau** [jaredpar/VsVim#1995]
Based on the Vim [wikia](http://vim.wikia.com/wiki/Repeat_last_colon_command), the last executed colon command (Ex command) can be repeated by using `@:` , and further repeat can be done with `@@`.  
One useful usage is when I want to repeat the last substitute command, say `:s/old/new` .

**Comment by mletterle** [comment]
Duplicate of #1115
