### ISSUE TITLE
Toggle comment command

### ISSUE THREAD

**Issue by fiveNinePlusR** [jaredpar/VsVim#1998]
Is there a way to toggle comments in a selected region? seems silly to have to explicitly comment or uncomment a selection instead of just toggling the comment status based on the first line of the selection being commented or not.

**Comment by wongjiahau** [comment]
@fiveNinePlusR This is not implemented in the standard Vim because different language have different commenting scheme, however it is possible to bind VsVim commands to Visual Studio toggle comment command.

**Comment by fiveNinePlusR** [comment]
Thanks. I had to find another extension to do this actually because there is no built in method.

https://marketplace.visualstudio.com/items?itemName=munyabe.ToggleComment

**Comment by wongjiahau** [comment]
@fiveNinePlusR I think you can still leave this opened, because this can be possibly implemented into VsVim.

**Comment by wongjiahau** [comment]
The code here may helps this implementation.
https://github.com/munyabe/ToggleComment/blob/master/ToggleComment/ToggleCommentCommand.cs

**Comment by jaredpar** [comment]
Closing as this doesn't appear to be core vim functionality that needs to be replicated.

**Comment by wongjiahau** [comment]
@jaredpar Nonetheless, VSCodeVim did implement this feature, check it out [HERE](https://github.com/VSCodeVim/Vim#vim-commentary)

**Comment by asfaltboy** [comment]
Although VsCodeVim did implement it, using an external vim plugin as inspiration, it doesn't necesserily mean VsVim should... different maintainers, different audiences, different amount of contributors.

That said, I personally found that the [aforementioned][1] [ToggleComment][2] extension works well. I'm hoping we can use it withing vsvim with the help of a custom binding. I got the following binding to work:

    :nmap gc :vsc Edit.ToggleComment<CR>

But, unfortunately, could not toggle multiple lines with visual mode ... would the mapping be different in this case?

[1]: https://github.com/jaredpar/VsVim/issues/1998#issuecomment-328672183
[2]: https://marketplace.visualstudio.com/items?itemName=munyabe.ToggleComment

**Comment by tobarja** [comment]
I know this is old, but for any weary vim'ers who stumble this way, you can do this in visual mode as well:

```
:vmap gc :vsc Edit.ToggleComment<CR>
```

Now, if we could work out that `Ctrl-/` issue. :( 

I still don't know the difference between `map` and `noremap`, so I can't comment on that.

**Comment by kozie** [comment]
@tobarja Thanks for the heads up tho ;)

i found [this explanation](https://stackoverflow.com/questions/3776117/what-is-the-difference-between-the-remap-noremap-nnoremap-and-vnoremap-mapping) which describes just what the noremap does :)

Cheers!

**Comment by moinessim** [comment]
Hey there, thanks for the guidance in this subject.
Just an update...

`ToggleComment` command is `ToogleLineComment`  in the current version 1.8 of [ToggleComment](https://marketplace.visualstudio.com/items?itemName=munyabe.ToggleComment).

So new mappings would be:

For normal mode: `:nmap gc :vsc Edit.ToggleLineComment<CR>`
For visual mode: `:vmap gc :vsc Edit.ToggleLineComment<CR>`
