### ISSUE TITLE
PageDown and PageUp operation doesn't position cursor correctly VS2017, VsVim2.4.1.0

### ISSUE THREAD

**Issue by gwojan** [jaredpar/VsVim#2002]
I finally upgraded to Visual Studio 2017 Professional and noticed that ```PageDown``` operations do not position the cursor at the top of the window like gvim. I have bound ```PageDown``` to ```space``` as well as ```Ctrl+f```.

```PageDown``` operations result in the cursor being positioned at the bottom of the Window and ```PageUp``` leave the cursor at the top of the window. This is exactly the opposite of gvim/vim.

**Comment by sqlkoala** [comment]
You could create mappings in vimrc that combine PageDown/Up with another command (which move the cursor to the first/last line). Thats H and L. 

nnoremap <C-f> <C-f>H
nnoremap <C-b> <C-b>L
Or with  space
nnoremap <Space> <C-f>H

**Comment by gwojan** [comment]
@sqlkoala Thanks! That's a decent workaround for the time being, however, the behavior isn't quite exactly like vim's once you get to the end of the buffer.
