### ISSUE TITLE
Page forward/back implemented?

### ISSUE THREAD

**Issue by BentChainRing** [jaredpar/VsVim#2004]
I noticed that Control f and Control b (page forward, page back) does not seem to be implemented? At least it was not seen on the supported features list. 

This does conflict with VS 'find' and VS ' function break point ' But this is one of those features which I'd rather have the Vim functionality override the VS keys.

(using Win 10, VS community 2017, latest VsVim ext.)

**Comment by jalexandretoledo** [comment]
You can choose which keys will be handled by VS and which will be handled by VsVim; just go to Tools / Options / VsVim / Keyboard and make your choices.

**Comment by jaredpar** [comment]
@jalexandretoledo is correct. This is implemented, you just need to ask VS to let VsVim win here.
