### ISSUE TITLE
VsVim does not work when peeking definition (decompiled files)

### ISSUE THREAD

**Issue by adrianjord** [jaredpar/VsVim#2005]
When peeking a definition, none of VsVim's functionality carries over to the mini-buffer that spawns.

**Comment by jaredpar** [comment]
What version of VS are u seeing this in? This has def worked in the past.

**Comment by adrianjord** [comment]
Visual Studio 2017 Professional

**Comment by adrianjord** [comment]
Just an update, it appears the most recent update of 2017 (15.4.1) has fixed this issue.

**Comment by adrianjord** [comment]
I'm reopening this ticket as I've just found out that VsVim does not work when peeking decompiled files.

**Comment by jaredpar** [comment]
Turns out the peek definition window is created differently for metadata and non-metadata scenarios. Just needed to adjust the key processor provider to deal with the metadata scenario.
