### ISSUE TITLE
qall behavior unexpected

### ISSUE THREAD

**Issue by BigDub** [jaredpar/VsVim#2007]
Normally in vim if you execute qall it will close everything down. In visual studio I would expect it to close all open documents, but not visual studio itself, which it currently does. Maybe this is just me though.

**Comment by wongjiahau** [comment]
I had this issue as well.

**Comment by jaredpar** [comment]
The default behavior for `qall` in vim is to close all docs and shutdown vim. VsVim is just implementing that behavior.

**Comment by BigDub** [comment]
That is reasonable, but at the same time vim doesn't exist outside of an open document and boots up in a fraction of a second. MSVS can be open without having a document open and can take longer than a minute to boot up and several times longer to parse all the files in a large solution.
The command q, or quit, means to close the current document.
The command qa, or quit all, means to close all the documents.
In vim closing all the documents means closing vim.
In MSVS closing all the documents does not mean closing MSVS.
In vim if I only have one document open and I `:q` it closes the document, which also means closing vim.
In MSVS if I only have one document open and I `:q` it closes that document, which does not close all of MSVS. This is what I expect to happen.
When I input `:qall` I expect the behavior of `:q` to be applied to all documents.
I would argue that in closing all documents and also closing MSVS the qall implementation in VSVim does not implement the vim behavior for qall.

If anyone else is reading along annoyed by the qall implementation, the fastest way I have found to do this without needing to reach for the mouse is to do `:tabo` which closes all tabs but the open one, then `:q` the last tab. Since VSVim has not implemented | or tabdo these have to be issued as two separate commands.

**Comment by tommy-hansen** [comment]
Agree with @BigDub 100%. 

This is my least favorite thing about VsVim, that once in a while I'll forget I'm not in VSCode and close Visual Studio with a `:qa`. VSCodeVim/vim made the `:qa` functional discrepancy leap in VSCode and it seems fine. It works exactly as you'd expect in an application that has other notions of what "open" means (= project, not file). 

VimR on Mac also stays open, following Mac app standard behavior over Vim. 

I vote to reconsider ;-).

**Comment by imagest** [comment]
Another vote to reconsider. Vim works as a text editor, and "closing" means closing the currently open document. You would expect ":qall" to close the _vim_, not the terminal.

VS Code does this, IdeaVim(JetBrain's own) does this, and atom's vim emulator does this. VsVim is the only mainstream "vim emulator" that breaks the expectation. Even if it "makes sense" for the developer, this breaks the workflow for engineers who habitually use "qall" to close vim. At the very least, could you create an option to change the behavior?

This is one of the reasons I switched to Rider, by the way.
