### ISSUE TITLE
Cursor move slow when using key h, j, k, l. vsVim 2.4.1.0 and Visual Studio 2017

### ISSUE THREAD

**Issue by cathy02** [jaredpar/VsVim#2008]
Ever since installed Visual Studio 2017 and vsVim, the cursor movements using h, j, k, l are very slow. Can't even hold down these keys for a continuous movement.

**Comment by jaredpar** [comment]
Think this may be due to interactions with other extensions. Can u tell me what else you have installed here?

**Comment by cathy02** [comment]
Thanks for your help. I tried to uninstall extensions for Redgate and everything sees to work fine now.

By the way, is there a way to list all the extensions installed? I have so many extensions installed and the interface from VS2017 is not good to get just the name of the extensions.
