### ISSUE TITLE
VsVim not expanding tabs

### ISSUE THREAD

**Issue by Sk37ch** [jaredpar/VsVim#2015]
I've noticed that VsVim is no longer seems to be recognizing expandtab from my vimrc.

I have in my vimrc:
    set expandtab
    set tabstop=4
    set shiftwidth=4

Works as expected in vim (4 spaces are inserted when I press tab in insert mode). But in VS 2017 I'm getting tab characters still. Setting tabs to map to spaces in VS options ( Tools -> Options -> Text Editor -> Tabs) fixes the issue. 

I don't recall having to do this in the past. Is this the expected behaviour or a bug?

**Comment by jaredpar** [comment]
Can you run `:set` and confirm that the `expandtab` setting is correct? Want to make sure first there isn't an issue loading up the vimrc file.

**Comment by Sk37ch** [comment]
Looks like there is a issue loading my vimrc. Setting expandtab in the editor works.
My vimrc is in c:\users\myname 

I tried 
:vimrc
and
:vimrcpaths
But get 'parse error'. 

'VimRc File Loading' in options is set to 'vsvimrc or vimrc files'

**Comment by jaredpar** [comment]
Sorry for the delay here. I've been tied down in a lot of fire drills lately. 😦 

Can you share out your vimrc file for me? Having it locally I should be able to work out what the issue is.

**Comment by Sk37ch** [comment]
I tracked it down to being an issue with pathogen in my vimrc. Forgot to update here.

**Comment by marcel-landman** [comment]
@alsepkow any chance you could give a little more detail how you fixed this? I have the same problem.
