### ISSUE TITLE
VsVim support for The Welkin Suite

### ISSUE THREAD

**Issue by aSooker** [jaredpar/VsVim#2021]
Hello,

is it possible to add support for The Welkin Suite since it's essentially Visual Studio 2013?

Their guide on installing extensions is the manual way of installing them:
https://welkinsuite.com/blog/visual-studio-extensions-salesforce-development/

But I still get errors after doing that:
[ActivityLog.xml.txt](https://github.com/jaredpar/VsVim/files/1441111/ActivityLog.xml.txt)

Thank you and best regards,
Robert

**Comment by jaredpar** [comment]
Looking through the log I found this error:

> Could not load file or assembly 'Microsoft.VisualStudio.ComponentModelHost, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

That indicates that that one of the following is going wrong:

1. That particular SKU of VS isn't shipping a couple of core components
1. The binding redirects are incorrect

Can you post the contents of the main application .config file? That will have all the binding redirects listed and we can rule out which is the problem.

**Comment by aSooker** [comment]
here is the config:

[TheWelkinSuite.exe.config.txt](https://github.com/jaredpar/VsVim/files/1445372/TheWelkinSuite.exe.config.txt)

**Comment by jaredpar** [comment]
Looks like the binding redirects aren't correct in this application. I would expect to see this entry included (with slightly different version numbers)

``` xml
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.VisualStudio.ComponentModelHost" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
          <bindingRedirect oldVersion="2.0.0.0-14.0.0.0" newVersion="15.0.0.0"/>
        </dependentAssembly>
```

The number of binding redirects here should actually be quite large. This is something they'd need to correct on their side unfortunately. I can't do much if the core components won't load correctly.

**Comment by aSooker** [comment]
I wrote to their support and will update this issue when I get an answer.

Thank you so far :)

**Comment by aSooker** [comment]
Ok I received a new config from there support that fixed this issue and now the VsVim plugin works correctly.

This fix will be in upcoming releases of the welkin suite.
Here is the new config in the meantime:
[TheWelkinSuite.exe.config.txt](https://github.com/jaredpar/VsVim/files/1512842/TheWelkinSuite.exe.config.txt)

**Comment by jaredpar** [comment]
Glad that this worked out!
