### ISSUE TITLE
Is if support implemented?

### ISSUE THREAD

**Issue by mqudsi** [jaredpar/VsVim#2023]
This one is perplexing me a bit, as the simple test case isn't working and yet the response it returns indicates that VsVim _does_ have some understanding of the VimL if block concept..

```vim
:if 1 | echo "hello" | endif
```

But VsVim prints the following:
```
Unmatched Conditional Block
```

**Comment by jaredpar** [comment]
The `if` support is very limited in VsVim. I essentially tailored it to support the various vimrc files users sent me. 

I looked into deeper support here but eventually decided against it. VimScript is a full fledged language and it gets pretty in depth really fast. I'm interested in fixing specific bugs here but full `if` support isn't a goal at this time.
