### ISSUE TITLE
`==` moves down a line

### ISSUE THREAD

**Issue by mqudsi** [jaredpar/VsVim#2024]
In regular vim, positioning the cursor in the middle of the first line in the following:

```
Hello, world!
Goodbye!
```

and then pressing `==` will reformat the line and move the cursor to the start of the line, but remain on the same line. In VsVim, the same command will reformat the line and move the cursor to the next line.

**Comment by jaredpar** [comment]
Can you point me to the documentation for `==`? I'm not familiar with this command. Need to read a bit more about it to see waht it would take to implement.

I tried `:help ==` but that goes to the change version. Didn't seem like what you were referencing here.

**Comment by jaredpar** [comment]
Closing due to staleness.

**Comment by mqudsi** [comment]
Oh my, I apologize! I must have missed the notification for this or else dismissed it with some others that didn't require my feedback!

If you're still open to it, `=` is the re-indent command and `==`, like many other single character commands when repeated twice without any selection, acts as if the current line were selected and then kicks in (in this case reindenting only the current line).

http://vim.wikia.com/wiki/Fix_indentation

**Comment by jaredpar** [comment]
@mqudsi no problem. Thanks for the pointer to the docs here.
