### ISSUE TITLE
Not formating code after paste

### ISSUE THREAD

**Issue by cbmek** [jaredpar/VsVim#2027]
If I copy paste part of code using VisualStudio's `Ctrl^C + Ctrl^V`, it formats the code (indents, spaces etc.). But when I use VsVim's `yank/delete + paste` it doesn't format and usually indent of the first line is broken.
Is there a way to force VsVim to format code on paste, or is there some other fast way to format code after paste?

**Comment by jaredpar** [comment]
Thanks for the feedback!

This behavior is "by design". The underlying vim commands don't format and hence when using them with VsVim it does not paste either.

If there is a equivalent "after paste" behavior in vim I'd be interested in adding it. But lacking that this is the designed behavior.

**Comment by dominicpalmer** [comment]
For those who stumbled across this issue looking for VSVim formatting on paste, I managed to get it working by invoking the Visual Studio command `Edit.FormatDocument` after pasting. Simply place this remap in your VSVim .vimrc:

`nnoremap p p | :vsc Edit.FormatDocument<CR>`

**Comment by tahir-hassan** [comment]
If you want to do it on paste using Control-v in insert mode, you can add the following to your `.vsvimrc`:

```
inoremap <silent> <C-v> <C-v><ESC>:vsc Edit.FormatDocument<CR>a
```
