### ISSUE TITLE
VsVim erases all information in the status bar

### ISSUE THREAD

**Issue by markonius** [jaredpar/VsVim#2028]
When VsVim is set to use the status bar instead of the command margin, no other information can be displayed there.  
It would be great if VsVim wouldn't overwrite the status bar when in normal mode.

**Comment by jaredpar** [comment]
Can you give an example of a scenario where you wanted to see text in the status bar that was being erased? 

There are cases today when normal mode does populate the status bar in gVim. For example when doing a yank to a register the summary of the yank is displayed. Do you expect that to work in VsVim?

**Comment by markonius** [comment]
https://imgur.com/a/ViUQB  
You can see the error message being displayed for a single frame before getting overwritten by VsVim.

**Comment by jaredpar** [comment]
Based on the GIF it sounds like what you want is for VsVim to not arbitrarily clear the status bar? The original report was much more general: don't overwrite in normal mode

**Comment by markonius** [comment]
Well yes. Sorry for not being clear enoguh.

**Comment by jaredpar** [comment]
No problem. Understand the problem now and agree it should be fixed.

**Comment by markonius** [comment]
Thank you!
