### ISSUE TITLE
Autoindentation after typing "a"

### ISSUE THREAD

**Issue by MaxLevs** [jaredpar/VsVim#2034]
For example, there is such a code:
![screenshot_9](https://user-images.githubusercontent.com/11697304/33406199-7c2fb514-d5b7-11e7-9bdc-6371e420b061.png)

Above and under the cursor indents in 2 tab. I want the current line to be indented to 3 tabs after entering "a", but to achieve this I have to type "a[tab][tab][tab]".

Result:
![screenshot_10](https://user-images.githubusercontent.com/11697304/33406210-83698b70-d5b7-11e7-9055-c6a5c8ae4d1d.png)

**Comment by jaredpar** [comment]
This is behavior the same in VsVim as it does in gVim. The <kbd>a</kbd> command in normal just starts insert mode after the cursor. It doesn't do any indentation work.
