### ISSUE TITLE
Character classes in very magic pattern not working

### ISSUE THREAD

**Issue by sqlkoala** [jaredpar/VsVim#2036]
Hi Jared,
I think character classes in very magic pattern are not working.
This was first reported here:
https://github.com/jaredpar/VsVim/issues/1238
for the special case \d. But I think it's not working in general. I have prepared a small example in vim and vsvim (2.4.1.0). Vim works as expected.

```
the pattern "\v\d\d+" should match the next two lines. it doesn't. instead it matches the line with dd
123
456
dd
the pattern "\v\w\s\w" should match 'o b' in 'foo bar'. it does not.
foo bar
```
I dont know how big of an issue this is, I stumbled over it when I wanted to learn and really use pattern in vsim. I wanted to map / to /\v and use "very magic" as default pattern, because having to escape many of the special chars ( like (,),|  )  makes the pattern awful to read. But pattern without character classes is also very uncomfortable.

Still, VsVim is an awsome extension, Thank you a lot for this.

**Comment by jaredpar** [comment]
Thanks for reporting. Will take a look at that.

**Comment by sqlkoala** [comment]
Thanks for fixing this so fast. I just dl'ed the build and played around with it. Now I can work through Jeff Friedl's book and turn myself to a text editing magician (hopefully ;-)
