### ISSUE TITLE
alt-key with numeric key input 0-9 ignored in vsvim

### ISSUE THREAD

**Issue by juliuszint** [jaredpar/VsVim#2037]
Hi,

#### Expected Behaviour
The keymapping `imap <M-7> {` inserts the `{` character into the textbuffer.

#### Observed Behaviour
Numerics from 0-9 with the alt modifier pressed are ignored in Visual Studio 2017.

#### Debugging efforts
In the standalone VimApp, shipped as part of the sourcecode, everything works as expected. Meanwhile in the Visual Studio extension the keystroke gets dismissed because text input must be routed trough Visual Studio first.

    // In insert mode we don't want text input going directly to VsVim.  Text input must
    // be routed through Visual Studio and IOleCommandTarget in order to get intellisense
    // properly hooked up.  Not handling it in this KeyProcessor will eventually cause
    // it to be routed through IOleCommandTarget if it's input
    //
    // The Visual Studio KeyProcessor won't pass along control characters that are less than
    // or equal to 0x1f so we have to handle them here 

    if (VimBuffer.ModeKind.IsAnyInsert() &&
       !VimBuffer.CanProcessAsCommand(keyInput) &&
       (int)keyInput.Char > 0x1f)
    {
        return false;
    }

#### Possible Solution
If there is no character generated from a keystroke, skip this check.

**Comment by jaredpar** [comment]
Thanks for reporting. This is a known issue #806.

Visual Studio has special handling for Alt keys that make it extremely difficult for VsVim to intercept properly. That is why you see the behavior working in the stand alone app but not in Visual Studio. The underlying logic is there but the ability to reliably capture Alt in Visual Studio is tricky.
