### ISSUE TITLE
Is it possible to reload .vsvimrc without restarting Visual Studio?

### ISSUE THREAD

**Issue by wangzq** [jaredpar/VsVim#2040]

**Comment by jaredpar** [comment]
Is there a way to do this in vim / gVim?

**Comment by wangzq** [comment]
I believe it is `:source ~/.vimrc` to reload the vimrc in vim.

**Comment by jaredpar** [comment]
That should work in VsVim today. Is it giving you an error when you run that command?

**Comment by wangzq** [comment]
Ah yes, it already works, not sure why I didn't try that earlier; sorry for the spam.
