### ISSUE TITLE
:q does not close popup preview window

### ISSUE THREAD

**Issue by pizza2code** [jaredpar/VsVim#2046]
`:q` does not close popup preview windows.

To get a popup preview in a Visual C++ project, add a method to a .cpp file without declaring it in the header.  Save the file, and you should see the Quick Action lightbulb come up.  Hover over it and select the "Create declaration ..." option.  The header file will appear in a popup preview window.

**Comment by jaredpar** [comment]
Let me look into that.

**Comment by jaredpar** [comment]
There are two issues here:

- When executing `:q` on a dirty window the error message is not displayed in the command margin.
- When executing `:q` on a peek definition window it cannot be closed.

**Comment by dvygolov** [comment]
Ok, the peek window closes but the main window doesn't get focus back!

**Comment by pizza2code** [comment]
The original issue (`:q` not closing peek definition windows) has re-appeared in Visual Studio 2019, unfortunately.

Using the latest VsVim 2.6.0.

**Comment by jaredpar** [comment]
@pizza2code this will be fixed in 2.7.0 for VS2019
