### ISSUE TITLE
Does VsVim support column mode?

### ISSUE THREAD

**Issue by jack2gs** [jaredpar/VsVim#2047]
Hi,

Could someone tell me if VsVim support column edit mode or not please?

Thanks,
Jack

**Comment by sqlkoala** [comment]
Hi,
yes it does. You active it using Ctrl+v or Ctrl+q.
In Vstudio, you need to go to Tools -> Options ->VsVim -> keyboard
and check that these keys are handled by vsvim.
One last detail: right now, "only" insert at begin using I is supported.

**Comment by jack2gs** [comment]
cool. thanks man.
