### ISSUE TITLE
Announcement: Repo Cleanup

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#2049]
Been picking up work on VsVim again recently after taking some time off last year. Needed a bit of a break after doing all the necessary work to make everything work on VS 2017. 

Before picking up work again though I think I need to spend a bit of time getting issues in order. I haven't been as diligent as I should in managing them and have let too many linger. I've also failed to clearly outline goals for the project which lead to some confusion in a number of issues. Sorry about that. 

Today I submitted [a documentation PR](https://github.com/jaredpar/VsVim/pull/2048) that helps with setting expectations and outlining project goals. Over the next few weeks I'm going to be looking through the issue backlog and bringing them inline with this documentation. 

Wanted to have an issue to announce this as it's likely to affect the majority of issues currently open on the repo. Will be keeping this open until I complete my cleanup efforts. 

Apologies in advance if it seems like I'm somewhat arbitrary closing issues, or changing course on particular feature. The [goals document](https://github.com/jaredpar/VsVim/blob/master/Documentation/Project%20Goals.md) though represents my current thinking on goals and I'm trying to align on this for now. Please push back where you feel strongly. 

Current Status:

- [Tracking Query](https://github.com/jaredpar/VsVim/issues?page=2&q=is%3Aissue+is%3Aopen+-milestone%3AUnscheduled&utf8=%E2%9C%93)
- Page 2 (going backwards) 

Began with 410+ issues open. Trying to get to ~200

**Comment by sqlkoala** [comment]
Hi Jared,
I set up and started to use vsvim extensivly in the last months, so I have quite good knowledge what it supports and what's not supported. If you want, I could do some grunt work and browse the issues to find ones that can be closed.

**Comment by jaredpar** [comment]
@sqlkoala would be appreciative of help here.

**Comment by sqlkoala** [comment]
I went through the first 8 pages; after that most issues are label bug/feature request.

This is what I found:

These are issues where the feature is implemented:
https://github.com/jaredpar/VsVim/issues/780
https://github.com/jaredpar/VsVim/issues/2004
https://github.com/jaredpar/VsVim/issues/1989
(seems like "user error". the feature (running macros repeatedly works)
https://github.com/jaredpar/VsVim/issues/1968
https://github.com/jaredpar/VsVim/issues/1947

These could be regarded as small glitches/easy to work around and be closed or seen as low prio:
https://github.com/jaredpar/VsVim/issues/1976
https://github.com/jaredpar/VsVim/issues/1940
https://github.com/jaredpar/VsVim/issues/1928
https://github.com/jaredpar/VsVim/issues/2002

Very user specific issues (with mappings) that don't indicate a general problem (imho):
https://github.com/jaredpar/VsVim/issues/1824
https://github.com/jaredpar/VsVim/issues/1848
https://github.com/jaredpar/VsVim/issues/1722

**Comment by jaredpar** [comment]
@sqlkoala thanks! Will work through those once I can get VS up and running again 😄

**Comment by jaredpar** [comment]
Closing as I've completed the cleanup now. Goal was to get down to ~200 bugs. Ended up with 227 under consideration (didn't count unscheduled milestone). Still a lot but more approachable than when I started. Hopefully I can stay clean going forward. 

Thanks for the helpful hints on a number of issues @sqlkoala!
