### ISSUE TITLE
On lines with only spaces or tabs, mapping jk to <esc> moves cursor to start of line

### ISSUE THREAD

**Issue by BlueInt32** [jaredpar/VsVim#2050]
This issue seems to be very similar to [this one](https://github.com/jaredpar/VsVim/issues/1673) but the ending position is different and it occurs only on empty lines.

I reduced my _vsvimrc file to a single line and set the config to "only vsvimrc":
`inoremap jk <esc>`

Now when the cursor is in an empty line at some level of indentation(e.g. 2 tabs or 8 spaces), when I hit `jk` (but unexpectedly also when I hit `esc` directly) , it puts the cursor at the column 0 (just like hitting `0`).

[Gif showing the behavior](https://gfycat.com/BoringSilkyDunnart)

Removing the mapping of `jk` resolves the issue, i.e. the cursor is placed one space left to where the insert cursor was. It's gVim's behavior. **Edit** : my mistake, the issue remains even without any mapping.

**Comment by BlueInt32** [comment]
My mistake, the issue remains even without any mapping. 
Apparently, this issue is related to Visual Studio's behavior regarding autoformatting.
Whenever a newline is created, VS automatically puts the cursor at the correct indentation without creating any real tabs nor spaces. Then as soon as a character is inserted, the virtual space indentation is replaced with actual spaces or tabs. This seems to be just as if the visual studio's setting "Enable virtual space" was temporarily activated to prevent any unnecessary spaces/tabs to be inserted. On the other hand, if no character is entered, the line ends up to being completely empty, thus VsVim puts the cursor at column 0 (no other choice).

**Comment by jaredpar** [comment]
@BlueInt32 good sleuthing there. That is indeed what is happening here. 

This behavior though is behaving as designed. VsVim will defer to Visual Studio when it come to formatting and newline behavior (as it also does for features like Intellisense).
