### ISSUE TITLE
C-e does not work, while C-y works as expected

### ISSUE THREAD

**Issue by cbates-** [jaredpar/VsVim#2051]
VS 2015 Pro, VsVim 2.4.1
Tools -> Customize -> Keyboard...

Ctrl-e is assigned to:
InteractiveConsole.ExecuteInInteractive

Ctrl-y is assigned to nothing.

Is there a way to get the Vim behavior for Ctrl-e?

Thanks --

**Comment by sqlkoala** [comment]
I think you need to let VsVim handle this input.
Goto Options -> Vsvim -> keyboard -> ctrl+Y.
Pick: handled by vsvim.

**Comment by cbates-** [comment]
@sqlkoala Thanks.
I was going to write: "Neither Ctrl+E or Ctrl+Y are listed in Tools->Options->VsVim->Keyboard."
But then I noticed the "Include All Scopes" checkbox; that revealed Ctrl+E, and now it works as desired.

**Comment by cbates-** [comment]
VS Pro 2015 Update 3
VsVim 2.5
Both Ctrl-e and Ctrl-y are working as expected.

**Comment by sgrassie** [comment]
I'm not sure what happened, but it's working now :scream: 

I did install the [beta v2.6](https://github.com/jaredpar/VsVim/wiki/FAQ#how-can-i-install-a-build-with-the-latest-sources)

**Comment by yavorski** [comment]
In VS 2022 

* `Ctrl+e` is not working
* `Ctrl-y` is working as expected

"Handled by VsVim" is check/selected.
