### ISSUE TITLE
ctrl-m doesn't work in command line.

### ISSUE THREAD

**Issue by millionbonus** [jaredpar/VsVim#2059]
VS2015
VsVim 2.5.0.0

Since updated to VsVim 2.5.0.0
`ctrl-m` doesn't work in command line.
Now I have to press `:w<enter>` to save file instead of `:w<ctrl-m>` (which is work fine before).

**Comment by jaredpar** [comment]
Didn't realize this was a feature. How is <kbd>Ctrl-M</kbd> intended to work here?

**Comment by millionbonus** [comment]
`ctrl-m` can be an alternative to `enter` in vim (or bash).
Some people ues `ctrl-m` to keep their finger at position of middle of keyboard as much as possible.

Before VsVim 2.5.0.0, I can use `ctrl-m` without any problem. In edit mode, it insert a newline. In command bar, it submit an `enter`. Now I can only use `ctrl-m` in edit mode.
