### ISSUE TITLE
In command mode, ctrl-r, 0 register is not working

### ISSUE THREAD

**Issue by JungHyeonSub** [jaredpar/VsVim#2068]
I searched related to issues. 
I found this bug was already fixed #1252 .

But when I test ctrl-r, 0 in command mode, it is still not working.
Which option do I need to change , or else what am I wrong?

I checked :register and the result is as below:.
--- Registers ---
"+   asdf
"0   auto-style1

I tested in Visual Studio 2013 and vsvim v2.5.

**Comment by jaredpar** [comment]
No option should be needed here. This should be working (as I use it very often). 

Did you just start seeing this issue? What version of VsVim do you have installed?

**Comment by JungHyeonSub** [comment]
VsVim version is 2.5 , Visual Studio is 2013 Community.

![image](https://user-images.githubusercontent.com/7709807/35380042-75cac37e-01fb-11e8-8c5c-a449e5fab0bd.png)

**Comment by jaredpar** [comment]
Yeah this does seem to be broken. I missed earlier that it was in command mode.

**Comment by chaitanyagurrapu** [comment]
Looking forward to a release with this fix. I thought I had gone crazy. Been hunting around resharper/vs keyboard mappings to find the problem. But until then, the c register for all things! All command mode things anyway.
