### ISSUE TITLE
Reselecting after undo-ing visual block deletion selects incorrect range

### ISSUE THREAD

**Issue by philipmat** [jaredpar/VsVim#2079]
Given the following text.

```
1foo test foo
2foo test foo
3foo test foo
4foo test foo
```
1. `Shift-v`, `j` to select the first two lines
2. `d` to delete them (cursor is not on *3foo* line)
3. `u` to undo (cursor is now on *1foo* line)
4. `gv` to re-establish previous selection

=> lines 3 & 4 are selected
Expected: lines 1 & 2 to be selected.

**Comment by jaredpar** [comment]
Thanks for reporting!

Looks like the vim behavior is more interesting than originally expected.

**Comment by philipmat** [comment]
My memory may be faulty, but I seem to remember this used to work. It was a bit surprising because vsvim does restore the cursor position at step 3.

Anyway, it seem vim keeps the visual start marker and mode anchored to the lines and only adjusts them if you delete lines above, but it does so weirdly.

I would honestly be happy if vsvim fixed just this one issue. Adjusting while deleting lines above is the cherry on top.

Just to document using 1-5foo lines, starting at L1 C1

## Scenario 0 - if lines above get deleted vim adjusts selection marker
`j`, `<S-v>`, `j` (lines 2-3 get selected), `d`, `u`, `k`, `dd` (line 1 gets deleted), `gv` => lines *2-3foo* get selected

## Scenario 1 - `gv` right after delete only selects one line (surprise)
`<S-v>`, `j`, `d`, `gv` => *3foo* line gets selected. Would've expected it to select *3-4foo*

## Scenario 2 - `gv` seems to remember previous selections?
`j`, `<S-v>`, `j`, `d`, `j`, `<S-v>` (select line 5foo), `<Esc>`, `u`, `gv` => lines *2-3foo* selected. Would've expect vim to select the last selection which in my mind was line *5foo*.

**Comment by ricksladkey** [comment]
Oh drat, I just noticed that @jaredpar self-assigned this.
