### ISSUE TITLE
vit, vat and cit sometimes behave incorrectly inside HTML tags

### ISSUE THREAD

**Issue by ivarboms** [jaredpar/VsVim#2081]
The behavior of **vit**, **vat** and **cit** seems to be dependent on the character the cursor is currently on top of.

```html
<div>
a

</div>
```

If the cursor is on the _a_, **vit** and **vat** work correctly. If the cursor is on the empty line below the _a_, **vit** selects the same as what **vat** is meant to select (this also happens when the cursor is on the tag), while **vat** selects the empty line only.
**cit** always leaves an empty line inside the tag, regardless of cursor position (even on the tag).
**dit** seems to always work correctly.

Vim 8.0 implements this correctly.
I'm using VsVim 2.5 with VS2017.

**Comment by ricksladkey** [comment]
This bug similarly affects `vi(`, `va(`, and other text blocks.
