### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by chaitanyagurrapu** [jaredpar/VsVim#2082]
Hi,
I have the latest code from master. The code seems to compile fine. I tried setting "VimApp" as start up project and running it. I get a "Unable to run your project. The "RunCommand" property is not defined" error.

I am using visual studio 2017 community edition with latest updates and installed with the visual studio extension development option checked.

I am running on windows 10.

**Comment by jaredpar** [comment]
@cbates is correct:, that is how you setup the VS extension for debugging.

**Comment by chaitanyagurrapu** [comment]
Thanks. Screenshot below is what I had to do launch the second, sandboxed version of visual studio to do a full launch. Minor differences, but seems to work.

I haven't looked at the project in a while, but didn't the VimApp project use to be a mock, stand alone, wpf host for the VimCore functionality? Without having to launch the full second version of visual studio? I am looking at MainWindow.xaml in the VimApp project and I can see the UI for the mock app. See second screenshot.

![image](https://user-images.githubusercontent.com/853059/36589746-22527504-18d8-11e8-865f-d6f01338b865.png)

![image](https://user-images.githubusercontent.com/853059/36589822-62f5e87a-18d8-11e8-82aa-3be6f49cbba2.png)

**Comment by chaitanyagurrapu** [comment]
@cbates- ? @jaredpar ?
