### ISSUE TITLE
Support for Dark skin

### ISSUE THREAD

**Issue by BlackMajic** [jaredpar/VsVim#2084]
Using VS2013, switching to the dark theme has the command bar remain with a light background colour.
![image](https://user-images.githubusercontent.com/313210/37541707-f8b88db8-2931-11e8-9039-7532df46fae6.png)

**Comment by BlackMajic** [comment]
I found the following values worked well for my colour scheme.

Tools > Options > VsVim > Defaults
![image](https://user-images.githubusercontent.com/313210/37938038-3b4face2-312a-11e8-80b1-b5a4765ad907.png)

**Comment by educriado** [comment]
Thanks, this looks good with my color scheme as well.
