### ISSUE TITLE
Feature Request: option to persist registers

### ISSUE THREAD

**Issue by EnCey** [jaredpar/VsVim#2087]
**Use case:** I frequently store short-lived "snippets" in named registers, like a `// TODO #31: ` comment when I'm working on issue 31. Named registers are great for this because they make it easy to remember what's what (e.g. "t for "Todo"). 

However, after restarting Visual Studio I must fill my registers anew. Restarts are often forced upon users (updates, extensions, crashes).

**Feature:** add an option to VsVim to persist register contents so they "survive" Visual Studio restarts. 
For example, the existing `.vsvimrc` might be used for this.

**Comment by ricksladkey** [comment]
This is already supposed to be working.  The registers are persisted in the file `%LOCALAPPDATA%\VsVim\vimdata.json`.

Can you check whether that file is present on your system and whether it is updated when Visual Studio is closed?

Related to #1726 and fd2e7a32453d3dbc5bad9ce04dc9d550be2ce309

**Comment by EnCey** [comment]
I don't have a `VsVim` folder in `%LOCALAPPDATA%` – do I have to enable something in settings?

**Comment by ricksladkey** [comment]
@EnCey It looks VsVim attempts to create that folder automatically, but doesn't check for failure:

```f#
    member x.SaveSessionData() =
        _fileSystem.CreateDirectory (x.GetSessionDataDirectory()) |> ignore
        x.SaveSessionDataCore (x.GetSessionDataFilePath())
```
Can you try to create it yourself and then re-open and re-close Visual Studio? Then check if `vimdata.json` is properly saved. That experiment might help uncover what the problem is.

**Comment by EnCey** [comment]
Nope, doesn't help sadly. I tried both to create just the directory and then even the file, but nothing was written to it. In both cases I opened Visual Studio, copied something to a register and typed around a bit before closing it again.

Don't know what could be causing this; version of the extension is 2.5.0.0, Visual Studio is started in elevated mode. I have a `.vsvimrc` in `%userprofile%` but don't think any of it should affect this. Any of the extension's settings in Visual Studio perhaps?

**Comment by EnCey** [comment]
Hmm, I tried to verify your theory and have no idea what just went down:
![image](https://user-images.githubusercontent.com/1894528/41522497-79d2fe18-72d6-11e8-8572-7016c6d095c1.png)

Upon hitting the "Ok" button in the Tools ↦ Options menu (no changes made) Visual Studio hung for a while and my PC fans went crazy – but the `vimdata.json` was created after closing VS.

Register contents were not loaded on next VS start, not even when I entered the VsVim options menu again. But the 40-odd seconds hang was there again. Dunno if this is an issue or not.

Can I test your fix somehow or will it be released soon?

**Comment by ricksladkey** [comment]
@EnCey Well, that's discouraging! But maybe it's some progress, because we at least managed to get VsVim to save the session data.

Here is how you can use the latest VsVim build if you are willing to try:

https://github.com/jaredpar/VsVim/wiki/FAQ#how-can-i-install-a-build-with-the-latest-sources

Looks like there is a build that includes the PR that closed this issue:

http://vsixgallery.com/extension/VsVim.Microsoft.e214908b-0458-4ae2-a583-4310f29687c3/
