### ISSUE TITLE
Better handling of Ctrl+R Ctrl+R

### ISSUE THREAD

**Issue by mqudsi** [jaredpar/VsVim#2088]
Ctrl+R Ctrl+R is the default trigger for the Visual Studio "rename all references" tool, which highlights the word in question and then waits for the text to be renamed and the `enter` key to be pressed upon which it'll rename all instances of the word in question to the new name.

There are several issues with VsVim that render the experience subpar, here are some suggestions:
* Ctrl+R Ctrl+R should result in the word being highlighted and the editor placed in Insert mode (and making sure that the highlight of the symbol at the cursor is correctly reflected)
* `Enter` after Ctrl+R Ctrl+r should be passed through to Visual Studio and not interpreted by VsVim

**Comment by jaredpar** [comment]
VsVim is designed to allow for both of those actions. When a refactoring operation is detected VsVim will enter External Edit mode and remain there until the refactoring is complete. External Edit is similar to Insert except it doesn't have any commands hence everything, including <kbd>Enter</kbd> goes to Visual Studio.

What version of Visual Studio are you using?

**Comment by mqudsi** [comment]
This is weird, on one PC that is indeed the case (after rename triggered the text is selected and VsVim is in insert mode, pressing enter at any point applies the change), but on my main dev PC the text is selected but VsVim is in normal mode and pressing enter passes through to the editor (not the inline rename symbol dialog); there I have to press `c` to `c`hange highlighted text then use `ctrl+a` (the key accelerator for the `a`pply button in the rename dialog). 

Any ideas?

**Comment by jaredpar** [comment]
Are you using Parallels (Windows on a Mac) in either of the cases? Prob sounds like an odd question but I've seen this type of behavior there before.

**Comment by nosu** [comment]
I have the same issue as @mqudsi . 
When I press `Ctrl + R`, it seems VsVim doesn't enter External Edit mode but still in Normal Mode, and I see the error message below. 
> Unexpected undo / redo event. Falling back to Visual Studio undo

I tried to uninstall/reinstall VsVim, but nothing changed.

**Comment by jaredpar** [comment]
@nosu do you have any other extensions installed or are you just using VS standard refactoring here? If so what language / construct are you doing the refactoring operation on?

**Comment by nosu** [comment]
@jaredpar I don't use any other extensions which can override VS standard refactoring such as ReSharper. 

I created a simple .NET console app and captured the operation.
![vsvim_rename](https://user-images.githubusercontent.com/1146140/43950201-a066ba4c-9cca-11e8-8add-e07f84e90e0f.gif)

Here's the repro steps:
- Move cursor to `sampleVar`
- Press `Ctrl + R` -> Nothing happens
- Press `Ctrl + R` again -> VS rename panel is shown, but VsVim is still in normal mode. The error message is shown in the white message bar. Can move cursor by pressing `h` or `l`
- Press `Esc` -> `i` to switch Insert mode
- Press `Alt + A` to finish renaming operation

Environment: 
- Windows 10 Pro 17134.167 (Japanese)
- Visual Studio Enterprise 15.7.6 (Japanese)

**Comment by nosu** [comment]
Thank you @jaredpar !
