### ISSUE TITLE
Macros don't capture all events

### ISSUE THREAD

**Issue by mqudsi** [jaredpar/VsVim#2089]
I know this one is a bit tough since it relies on events well outside of VsVim's control, but I have a few suggestions to make macros in VsVim work more intuitively.

The core problem is that VsVim does not register auto-created content, i.e. if braces, parentheses, semicolons, etc. generated automatically with Intellisense (no custom providers or anything severely obtrusive like ReSharper installed) are not "seen" by VsVim, and therefore are not reproduced in the resulting macro - but keystrokes interacting with these objects (including removing them) _are_ seen and saved by VsVim.

Here's a good example, starting with the following code:

```csharp
public class Class1
{
    public int foo;
    public int bar;
}
```

Now let's say I want to create a macro to change these from fields to properties. I put the cursor on the `foo` declaration and press `qq` to begin recording a macro `q` to do just that. 

`$` to go to the end of the line, followed by `s{` to replace the `;` with an opening brace aaaaaand Visual Studio magically inserted a closing `}` to make my life easier. The macro is already ruined, since it is unaware of the insertion of that character. In _this_ case, I can "force" it to work by hitting `Esc` then `D` to clear to the end of the line, then `A` to append - since I'm working on the end of the line only, I can safely keep doing this to delete autogenerated content, and when replaying the macro on another line there is nothing past that point that I need to protect so it's OK to keep doing that. But if I were making a change in the middle of the line, for example, then that won't cut it.

Suggestions:
* While in macro mode scan for changes to the line content while in insert mode and treat them as the input, rather than relying on key presses (again, only in insert mode so it should be "safe")
* Less ideally, if in macro mode, disable all automatic code generation/intellisense/completions

**Comment by jaredpar** [comment]
> While in macro mode scan for changes to the line content while in insert mode and treat them as the input, rather than relying on key presses (again, only in insert mode so it should be "safe")

Unfortunately this isn't really doable. Macros are very literally done by capturing and replaying the exact set of key strokes that happen during recording. No context about what is happening is part of the recording. You can actually see how literal this is by recording a few macros and then using `:reg` to see how the text is recorded. Trying to interlace edits, which are unpredictable, with the key strokes is pretty unweildy. 

> Less ideally, if in macro mode, disable all automatic code generation/intellisense/completions

This is the approach that I took with VsVim. It's disabled by default because the experience is a bit jarring to developers who want to mix the features. To enable it go to Tools -> Options -> VsVim and change macro recording to clean.

**Comment by mqudsi** [comment]
Thanks, I didn't know about that feature - it certainly addresses my needs.

I know a few programs that are integrated with (neo)vim backend and in insert mode they switch from reading keys to reading the contents of the line and interpreting that as the equivalent keystrokes (basically "char added" vs "char removed"), but I don't know if that is possible with the Visual Studio extension API.
