### ISSUE TITLE
Option to globally share unnamed register?

### ISSUE THREAD

**Issue by mqudsi** [jaredpar/VsVim#2090]
Would you be open to using a shared buffer for the unnamed register, such that a `y` operation in one VS instance running VsVim can be followed by a `p` in another instance of Visual Studio?

**Comment by jaredpar** [comment]
Is there a particular gVim feature you're trying to emulate here? 

VsVim does support using the unnamed register as the global clipboard.

**Comment by jaredpar** [comment]
Is that a feature that neovim supports? It's not the default in gVim (or supported that I know). Generally when I do features I try to emulate the existing behavior as close as possible. Want to get a better idea of the semantics here.

**Comment by ricksladkey** [comment]
The `:set clipboard=unnamed` option does exactly what is being requested, albeit in a slightly more general way. So this issue can be closed as already implemented.

**Comment by ricksladkey** [comment]
@mqudsi The unnamed register will only use the clipboard if you use the setting.

To test it out, type `:set clipboard=unamed<CR>` in both Visual Studio instances. Then yank a line (for example) in one Visual Studio with `yy` and paste it in another Visual Studio with `p`.

**Comment by ricksladkey** [comment]
BTW, this technique also works between VsVim and vim.

**Comment by mqudsi** [comment]
Thanks, @ricksladkey. 

But that means that it can't be used alongside the system clipboard, right?

**Comment by mqudsi** [comment]
@ricksladkey Right. But the `"` register is set aside for the unnamed clipboard, so it should be possible to use `"*y` to copy to the system clipboard and `""y` to copy to the unnamed clipboard, no?

**Comment by mqudsi** [comment]
Ok but that isn’t shared across instances, though.

**Comment by ricksladkey** [comment]
@mqudsi You are teasing me now! Not unless you use `:set clipboard=unamed`. :-)
