### ISSUE TITLE
CTRL+W family of movements not working

### ISSUE THREAD

**Issue by mvittiglio** [jaredpar/VsVim#2093]
I'm sorry if this is the wrong place to put a question but I've seen varying posts on this topic and can't say for certain if it's supposed to work or otherwise. I'm running VS Community 2017 with the latest (as of today) version of VsVim but CTRL+W CTRL+W/hjkl and such do not work. This this a known bug or simply an unsupported matter?

**Comment by jaredpar** [comment]
The j and k versions should definitely be working whenever you invoke a split screen operation (using the options under the Window menu). Can you describe a bit more the setup where this isn't working?

**Comment by mvittiglio** [comment]
I'm currently developing in C++ under Visual Studio 2017 Community Edition. When I have two tabs side by side or even a top/bottom split none of the CTRL+W family commands to move around work. I've recorded this behavior and uploaded it here: https://youtu.be/18w8LHvfioI

So I guess that left/right view-port support is not a possibility? :-(

**Comment by jaredpar** [comment]
The left / right view port works but has a less definitive implementation. It's more convention than a defined relationship than the top / bottom split. Let me see if I can reproduce that.

**Comment by mvittiglio** [comment]
Jared,
Thank you so much for your support on the left/right movement stuff. Is there any reason why the whole "up/down" matter isn't working?

Sincerely,
Mike

**Comment by sqlkoala** [comment]
Hi Michael,
about <C-w>h/l: these vim commands are mapped to these VS-commands (AFAIK)
Window.PreviousDocumentWindow,  Window.NextDocumentWindow
However, Previous and Next don't always work as left and right. It works (for me) with 2 open documents, not more.
Up/Down in a split works reliable for me. From the video it looks like you have some "two-chord" mappings in visual studio, that start with Ctrl+w, like Ctrl+k, Ctrl+w -> Bookmark Window (but starting with w). In these cases, VsVim can't "capture" the two chords correctly, I think.

**Comment by jaredpar** [comment]
> Is there any reason why the whole "up/down" matter isn't working?

Still looking into this. Haven't been able to reproduce it yet.

**Comment by ricksladkey** [comment]
This can be closed as the `<C-w>` key binding was not being handled by VsVim, as @sqlkoala uncovered. The keys can be made to work by one or more of:

- Using the "Include all scopes" option to find the offending chorded `<C-w>` bindings
- Marking `<C-w>` as "handled by VsVim"
- Manually removing all `<C-w>` key bindings

**Comment by ricksladkey** [comment]
@sqlkoala Actually, the left/right motions are now handled by enumerating all top level document windows and comparing the coordinates of their left margin.

**Comment by mvittiglio** [comment]
@ricksladkey Can confirm; things are working now. Thanks everyone!

**Comment by sqlkoala** [comment]
Thanks, @ricksladkey for the last two comments, I could improve my setup with them.
