### ISSUE TITLE
VsVim prints escape character like <Esc> on screen from mapped macro

### ISSUE THREAD

**Issue by zikhan** [jaredpar/VsVim#2094]
I've been using vsvim on different computers for a while now, and this is the first time I've run into this issue.

Here's a snippet from my .vimrc file:
![image](https://user-images.githubusercontent.com/8488326/38783135-e8c37374-40c3-11e8-9ef0-0fd79375659f.png)

When I use this .vimrc file with vim/gvim, pressing `;` in normal mode will append ; to the end of the line and return to normal mode. However, when I use `;` in vsvim, I get this:
![image](https://user-images.githubusercontent.com/8488326/38783151-3b250f9c-40c4-11e8-9e98-4a4c88b2ea9e.png)
And I remain in Insert mode.

Any ideas why vsvim would output the literal <Esc> string?

Edit: I have changed the Macro string to `A;<Esc>` as well and it didn't help.

**Comment by jaredpar** [comment]
Will have to look into that. My first guess is that `^[` was being misinterpreted but your edit of using `<Esc>` goes against that.

Can you post the actual text snippet of the .vimrc instead of the picture? Want to make sure I have the exact text here to look at.

**Comment by zikhan** [comment]
I've zipped both files one with <Esc> and the esc character.

[vimrc.zip](https://github.com/jaredpar/VsVim/files/1916169/vimrc.zip)

**Comment by zikhan** [comment]
I don't know if this helps, but when I record the register in vsvim, the macro in register q works.

Here's what I see in the registers:
```
"a   A;<Esc>
"q   A;
```

**Comment by sqlkoala** [comment]
I think you could do it without a macro, like this.
```
nnoremap ; A;<Esc>
nnoremap ; mqA;<Esc>`q
```
the  second variant uses the mark q to bring the cursor back.

**Comment by ricksladkey** [comment]
@sqlkoala One might want to add `:delm q<CR>` to your second macro to prevent `q` from cluttering up the indicator margin in my upcoming mark glyphs PR!

**Comment by ricksladkey** [comment]
@zikhan The mystery is solved because we *assumed* that the value of the `a` register was the macro that was being run. Instead, it was loading session data from a json file from your previous editing session *after* the rc file was loaded and so the actual contents of the `a` register were whatever they were in the previous session, presumably when you were experimenting interactively.
