### ISSUE TITLE
Undo replaces file content

### ISSUE THREAD

**Issue by Diadlo** [jaredpar/VsVim#2095]
##### Brief Description

OS: Arch Linux
Visual Studio Code about:
```
Version 1.22.2
Commit 3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
Date 2018-04-12T16:34:44.222Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```
VsVim version: v0.11.4

Reproducible: Always

##### Steps to reproduce

1. Open document A
2. Open document B
3. Made some change
4. Save and close B
5. Open B again
6. Press 'u'

##### Observed Behavior

Content of document B will be replaced on content of A

##### Expected Behavior

Undo change from 3. or nothing

**Comment by Diadlo** [comment]
Sorry, wrong repo

**Comment by Diadlo** [comment]
Is this project same with https://github.com/VSCodeVim/Vim/ ?
If so, issue relevant too

**Comment by jaredpar** [comment]
@Diadlo no this is a different project. This is the plugin for Visual Studio.
