### ISSUE TITLE
Cannot replace selected line with register content in visual line mode

### ISSUE THREAD

**Issue by mqudsi** [jaredpar/VsVim#2103]
While visual line mode supports normal `y` and `p` operations, it does not seem to work when attempting to paste from a register in visual line mode, the operation fails with an error beep.

i.e. given the following text:

```
foo
bar
```

1. Navigate to the first line, and key in `V"ay` to copy the line in visual line mode to register `a`. 
2. Navigate to the second line, and key in `V"ap` to attempt to replace the line with the contents of register `a`.

The operation fails.

**Comment by jaredpar** [comment]
I tested out and this seems to work just fine. In the repro you laid out the second line changed from "bar" to "foo" as I would expect it to do. What did you see happen here?

**Comment by mqudsi** [comment]
I hear an error ding and nothing changes.

If I use `"aP` instead of `"ap` however, it works. This only affects visual mode, otherwise they both work fine.

Nevermind: it's caused by my very minimal vsvimrc, which has the following:

```
" reformat on pasting over selected text
vnoremap p "_dPv`.=
```

**Comment by ricksladkey** [comment]
@mqudsi Thanks for digging into this!
