### ISSUE TITLE
Ctrl-D in insert mode inserts new line?

### ISSUE THREAD

**Issue by eddieparker** [jaredpar/VsVim#2116]
I'm trying to use Ctrl-D in insert mode to 'unindent' but instead it's giving me a new line.  

I'm running vsvim 2.5.0.0, on Visual Studio 2017.

**Comment by jaredpar** [comment]
Have you set VsVim to handle the Ctrl-D shortcut? By default that is mapped to actions in Visual Studio. To confirm check the conflicting keys dialog:

- Tools -> Options
- VsVim 
- Keyboard

**Comment by eddieparker** [comment]
Ah; you're totally right.  VS was handling it, not vsvim.  Good catch - apologies.
