### ISSUE TITLE
Use previous recorded macro during macro recording will freeze VS.

### ISSUE THREAD

**Issue by lorry-lee** [jaredpar/VsVim#2119]

**Comment by ricksladkey** [comment]
Although I cannot reproduce a hang using a previously recorded macro during macro recording, I confirm that it does not work correctly.

### Repro

- Record a macro into register `a` to delete a word: `qadwq`
- Record a macro into register `b` to replay macro `a`: `qb@aq`

### Results

- Actual contents of register `a`: `dw`
- Actual contents of register `b`: `@dwa`
- Expected contents of register `b`: `@a`
