### ISSUE TITLE
Prevent temp files or alter directory for temp files when saving with :w

### ISSUE THREAD

**Issue by lycandroid** [jaredpar/VsVim#2142]
I work on a web project which has code in the App_Code folder.  I notice that when I edit a file in App_Code in visual studio (2017) and use :w to save there is a significant delay and also sometimes it shows a message:

    VsVim 2.5.0.0 likely caused n seconds of unresponsiveness

If I use CTRL-S to save then no delay.

I'm fairly sure this is happening because temp files are written to App_Code when using :w causing visual studio to rebuild something or other (intellisense?).   For example when editing a file xxx.cs I see temp files created (and then deleted):

    u22ookwy.wzr~
    xxx.cs~RF22b7aadb.TMP

Is there a way of telling vsvim either to not write the temp files or to put them in a different location?

I tried vimrc settings:

    set nobackup
    set nowritebackup
    set noswapfile

But no effect (and I checked it was using my vimrc file using the :set vimrc command).  I don't think they are standard vim files anyway - maybe something vsvim does itself?

**Comment by jaredpar** [comment]
>  also sometimes it shows a message:

This will be going away in one of the upcoming versions of Visual Studio. The code that produces this is trying to ensure that typing remains responsive in Visual Studio. It does this by measuring the amount of time every extension takes to process a key in the editor. 

This logic is operating under the assumption though that key strokes are meant to be processed as simple edits. It doesn't hold up for extensions like VsVim where key strokes also represents commands. They are going to be adjusting the heuristics in the future versions to no longer incorrectly flag VsVim. 

> I'm fairly sure this is happening because temp files are written to App_Code when using :w causing visual studio to rebuild something or other (intellisense?). 

Are these being written when you use `<Ctrl-S>`? VsVim essentially implements `:w` by calling the same Save function. I wouldn't expect any additional work to be happening here.
