### ISSUE TITLE
ci( yi( di( etc does not work if parenthesis contains a string literal with a "("

### ISSUE THREAD

**Issue by danpett** [jaredpar/VsVim#2159]
Trying to use vi( or any _i( combination inside a parenthesis containing a "(" inside a string literal does not work, for example trying to copy the statement in the if () does not work:

`if ("hello".IndexOf('(') == 0)`

**Comment by ricksladkey** [comment]
I am a longtime vi user but am only now learning about text objects in vim.  Great concept!

Anyway, ordinary brace matching `%` has the same problem. I'll take a look at this.
