### ISSUE TITLE
`:'<,'>s/.../...` alters the active visual selection (if in line-based visual mode)

### ISSUE THREAD

**Issue by mfrischknecht** [jaredpar/VsVim#2174]
If line-based visual selections are used to search/replace specific patterns, the completion of the command alters the selection, making it impossible to re-select the originally selected region using `gv`.

Say we are starting with the following text:

```
foo, bar, bar
bar, foo, bar
bar, bar, foo
```

We can then select the whole file using `ggVG` (using a diff to visualize the selection, lines with `+` are selected):

```diff
+ foo, bar, bar
+ bar, foo, bar
+ bar, bar, foo
```

After that we can run a substition command on the whole selection by running `:'<,'>s/foo/baz/g`. In 'real' vim, the selection would be cleared after the command, resulting just in the modified text. Running `gv` after that would then automatically re-select the same text as before. This comes in very handy if one wants to make multiple substitution changes to the same region.

VsVim, on the other hand, remains in visual mode after the command has run, but the selection is altered: Only the last line is still selected:

```diff
  baz, bar, bar
  bar, baz, bar
+ bar, bar, baz
```

If the selection is canceled (`<ESC>`), `gv` will then re-select just this one line. I experimented a bit with this effect, and it seems like only line-based selection is affected; selections using `v` or `C-v` result in the correct behavior on my setup. Also, it seems like the line left after the substitution depends on the cursor position: Selecting backward (`GVgg`) or swapping the position after the selection (`ggVGo`) before substituting results in the *first* line being selected. The behavior doesn't seem to be dependent on whether the command succeeded or not (`:'<,'>s/bla/blubb/g` yields the same result).

**Comment by ricksladkey** [comment]
This is a duplicate of issue #2120 and is already fixed by PR #2121.

**Comment by mfrischknecht** [comment]
My bad, sorry for the duplicate. I hadn't looked for closed issues. I'll close this one then.

**Comment by ricksladkey** [comment]
@mfrischknecht It's not always easy to find similar issues; better to file a new issue if you can't find any!
