### ISSUE TITLE
Setting notimeout is not respected

### ISSUE THREAD

**Issue by dhmgit** [jaredpar/VsVim#2180]
Setting notimeout does not prevent partially typed commands from timing out.  In contrast, Vim will wait indefinitely for a command to be completed.

This may be naive given my lack of experience with the codebase, but simply adding a return in KeyMappingTimeoutHandler.OnKeyInputBuffered seems to fix the issue for me.  Also, a nearby comment seems to indicate that this was the original intent.

```
if (!globalSettings.Timeout)
{
     _timer.Stop();
    return; // added
}
```

**Comment by ricksladkey** [comment]
This is fixed and can be closed! Thanks, @dhmgit
