### ISSUE TITLE
Implement the 'showcmd' feature

### ISSUE THREAD

**Issue by dhmgit** [jaredpar/VsVim#2181]
When the 'showcmd' setting is on in Vim, the last line of the screen shows partially typed commands and other context information.

http://vimdoc.sourceforge.net/htmldoc/options.html#'showcmd'

I find this feature very helpful, so I've implemented it in my VsVim fork for my own use.  I've never submitted a PR, so I'm adding this feature request as a first step.  If this project is open to new contributors, I'd like to submit my work for review.

Thanks to everyone who has contributed to this project for greatly enhancing my VS editing experience.  VsVim is awesome!

**Comment by ricksladkey** [comment]
I don't speak for the project, but I can say that I am simply an enthusiastic user, like you, who wants to give back to a project that is important to me. I definitely think you should submit a PR for review.

**Comment by jaredpar** [comment]
>  If this project is open to new contributors, I'd like to submit my work for review.

Absolutely open to contributions :smile:
