### ISSUE TITLE
Cursor Blinking between block and line

### ISSUE THREAD

**Issue by 333fred** [jaredpar/VsVim#2195]
In the latest dogfood builds of VS, the cursor is blinking between block cursor and line cursor in normal and visual modes. Approximate visual steps of what's happening:

1. Cursor blinks out, as is standard cursor behavior
2. Cursor blinks in as a line, instead of a block
3. Cursor becomes a block, a couple hundred milliseconds later. Long enough to be noticeable but otherwise very quick
4. GoTo 1

Best I was able to get as a screen record, it's pretty quick: https://i.gyazo.com/75cebee055705ad178320a9fd727b041.mp4

**Comment by ricksladkey** [comment]
Having been in the block caret code recently, the only way I can see this happening is if `ITextView.Caret.IsHidden` isn't being respected by the editor subsystem.

**Comment by ricksladkey** [comment]
Or if something else immediately unhides the caret after VsVim hides it..

**Comment by 333fred** [comment]
Very possible, as this is an internal build of VS. I'll debug with Jared when he gets back from his current vacation.

**Comment by jaredpar** [comment]
Yeah I updated my internal build and this immediately started happening. I will try and track this down.

**Comment by ricksladkey** [comment]
@jaredpar Sorry, block caret is right up my alley, but I can't help you with this one.  :-)

**Comment by jaredpar** [comment]
@ricksladkey no problem. @333fred and I took a look at this today and I think I identified the problem. The refactored the caret UI code a bit in Preview 3 and it looks like they simply broke the behavior around `ITextCaret.IsHidden`. They are tracking the issue and attempting a fix in Preview 4. 

Keeping this open until we verify the fix. 

https://devdiv.visualstudio.com/DevDiv/_workitems/edit/627142

**Comment by AmadeusW** [comment]
@grabalon is aware of it and fixed it for 15.8 preview 4 ^

**Comment by jaredpar** [comment]
@AmadeusW just saw that as well. Waiting for a preview 4 build to verify. Will close this once I do.

**Comment by 333fred** [comment]
Confirmed that this is fixed. Thanks @AmadeusW and @grabalon

**Comment by jaredpar** [comment]
Indeed thank you all for fixing this.
