### ISSUE TITLE
Visual block starts expanding right when I highlight down

### ISSUE THREAD

**Issue by agocke** [jaredpar/VsVim#2196]
Repro:

Go into visual block mode in IntPreview. Use "j" to start selecting down. Instead of selecting just one column, it starts selecting a bunch of columns to the right as well.

**Comment by jaredpar** [comment]
That's not good. Sounds like the editor changed in some way here.

**Comment by ricksladkey** [comment]
Closing this as obsolete because Visual Studio 2019 preview is out and the bug has not been reported.
