### ISSUE TITLE
visual block selection and pasting doesn't work correctly

### ISSUE THREAD

**Issue by keithn** [jaredpar/VsVim#2231]
I came across https://code.joejag.com/2016/text-editing-kata.html

I was wanting to block select and paste the block beside itself , so using ctrl-v on the following...

```
Basic Price 
Discount
Sub total
Factory options
Dealer options
Fuel and mats
Road fund licence
Number plates and delivery
Registration fees
Sub total
Service plan
Autocare
Protect
VRI
Our Insurance
Sub total
Customer contribution
Part exchange value
Cash back
Settlement
Sub total
Credit card handling charge
Vat
Total to pay 
```                

it had a problem highlighting the block, it wouldn't let me cursor past the end of the line so I added some spaces padding the first and last line... I yanked the block and went to the end of the top line, then tried to p it.   It pasted the first line at the end of the line, but it then pasted the rest after the last line rather than side by side...

so I got 

```
Basic Price                   Basic Price                
Discount
Sub total
Factory options
Dealer options
Fuel and mats
Road fund licence
Number plates and delivery
Registration fees
Sub total
Service plan
Autocare
Protect
VRI
Our Insurance
Sub total
Customer contribution
Part exchange value
Cash back
Settlement
Sub total
Credit card handling charge
Vat
Total to pay               
Discount
Sub total
Factory options
Dealer options
Fuel and mats
Road fund licence
Number plates and delivery
Registration fees
Sub total
Service plan
Autocare
Protect
VRI
Our Insurance
Sub total
Customer contribution
Part exchange value
Cash back
Settlement
Sub total
Credit card handling charge
Vat
Total to pay                   
```

Rather than

```
Basic Price                   Basic Price                  
Discount                      Discount
Sub total                     Sub total
Factory options               Factory options
Dealer options                Dealer options
Fuel and mats                 Fuel and mats
Road fund licence             Road fund licence
Number plates and delivery    Number plates and delivery
Registration fees             Registration fees
Sub total                     Sub total
Service plan                  Service plan
Autocare                      Autocare
Protect                       Protect
VRI                           VRI
Our Insurance                 Our Insurance
Sub total                     Sub total
Customer contribution         Customer contribution
Part exchange value           Part exchange value
Cash back                     Cash back
Settlement                    Settlement
Sub total                     Sub total
Credit card handling charge   Credit card handling charge
Vat                           Vat
Total to pay                  Total to pay                  

```

However if i use visual studios block copy and paste it works as expected, and of course in gVim itself it works as expected without having to pad anything.

If I just used visual studios paste function on VsVims block selection it doesn't seem to be copied as a block and doesn't paste ok

**Comment by ricksladkey** [comment]
If vim acts, the way you say it acts, I suspect that your vim has at least `:set virtualedit=block` set. Can you check `:set virtualedit?` in the vim you are testing?

In VsVim, even if you try to use `:set virtualedit=block`, VsVim still does not allow the cursor to move into virtual space. So that is problem number one.

In my testing, yanking a visual block selection and putting it does actually do a block put, but VsVim improperly adds the padding to the beginning of short lines instead of the end. That is problem number two. I cannot reproduce the symptoms you describe that it appears as though VsVim is doing a non-block put.

Here is VsVim with `:set virtualedit=` using padding (represented by underscore):

```
abc___
x
def___
```
Typing `<C-v>jj$y` and then `$p` results in:

```
abc___abc___
_____xx
def___def___
```
But is should be:

```
abc___abc___
x_____x
def___def___
```

**Comment by ricksladkey** [comment]
BTW, here is a vim "one-liner" for that puzzle:

```
:%s;^\(.*\)$;<dt runat="server" id="dt\1">\1</dt>\r<dd runat="server" id="dd\1"></dd>\r
```

**Comment by ricksladkey** [comment]
This issue is tracking the "padding" problem: #1165.

**Comment by keithn** [comment]
the vim oneliner doesn't titlecase and remove spaces for the id.....   that's why I was block copying, first making things titlecased and copying the non title cased text next to it, then doing a similar regex that took those and created the final transform

**Comment by keithn** [comment]
trying to replicate  your smaller example....  I got different results...  mine ended up looking like

abc___abc___
x
def___
x
def___

**Comment by ricksladkey** [comment]
@keithn Back to the drawing board for my vim oneliner!

The "put" symptoms you describe are what would happen if it were just a "normal" (non-block) put. The test that I did was with the head of master and with VsVim 2.5.0.0 (the current version in the Visual Studio gallery). I can't explain why it's not doing a block put.

Here's a different test for block put as a sanity check:

```
abc def
ghi jkl
```

Using the commands `<C-v>jwyP` should give:

```
abc abc def
ghi ghi jkl
```

If this doesn't work correctly, the different symptoms might help clarify what is going on.
