### ISSUE TITLE
Error while trying to run in Visual Studio - The "RunCommand" property is not defined.

### ISSUE THREAD

**Issue by hacksoi** [jaredpar/VsVim#2256]
I cloned the repository, opened the solution, and tried running the VimApp project. The issue is that I get the following error:

![error](https://user-images.githubusercontent.com/22923652/42720824-ec72902a-86e3-11e8-9245-5d8a724ce837.PNG)

Anyone else experiencing this issue, or know what it means? There doesn't seem to be much info about it on the internet...

I'm using Visual Studio Version 15.7.5

**Comment by ricksladkey** [comment]
I ran into this problem too. Although there may be a better way to fix it, the setting that leads to the error is  "Launch -> Project".

Here are the settings I use:

![image](https://user-images.githubusercontent.com/2680524/42720993-2bf52a84-8700-11e8-896d-374959098d06.png)

Beware that this "hard codes" the Debug version, so if you make changes and build the Release version, you become very confused very quickly! Speaking from experience...

**Comment by hacksoi** [comment]
Works for me, thanks!
