### ISSUE TITLE
After '$', further 'j'/'k' motions don't always track end-of-line

### ISSUE THREAD

**Issue by ricksladkey** [jaredpar/VsVim#2261]
I did not know that vim had this feature, but after a `$` motion, further `j`/`k` motions should track the end-of-line. This features seems to be implemented in VsVim, but it fairly easy to get it to misbehave. For example, in this buffer:

```
cat
fish
horse
```

After issuing `$` on the `cat` line, `j` to the next line does land on the `h` of `fish` but `j` again puts the cursor on the `s` in `horse` rather than on the `e`.

**Comment by jaredpar** [comment]
Interesting. This does appear to be tied specifically to `$` here. I tried a few other motions to get to the end of the "cat" line and none of them had this behavior.
