### ISSUE TITLE
Can't exit command mode via Ctrl+C

### ISSUE THREAD

**Issue by hacksoi** [jaredpar/VsVim#2292]
In gvim I can exit command mode via Ctrl+C!

**Comment by oufu99** [comment]
manybe you can define a script let it exit command mode

**Comment by adrianjord** [comment]
This works just fine. Go to `Tools > Options > VsVim > Keyboard` and find `Ctrl+C` and change it to Handled by `VsVim`

**Comment by ricksladkey** [comment]
@adrianjord This might have worked in a prior version, but it definitely does not work in VsVim 2.5.0.0. In any case, it is fixed in PR #2295, which is likely to be merged shortly, and so it will be fixed in the next release of VsVim.

**Comment by adrianjord** [comment]
@ricksladkey I have VsVim on auto update and it is at 2.5.0.0. Everything works fine for me.
I'm on Visual Studio 2017 15.7.3 and ReSharper Ultimate 2018.1.3

**Comment by ricksladkey** [comment]
@adrianjord Interesting! It's true that `<C-c>` works to exit from insert mode, but I just triple checked and typing `:<C-c>` leaves the focus on the command margin waiting for more input. The only way to exit command mode in VsVim 2.5.0.0 is with `<Enter>`, `<Esc>` or `<BS>`. And I always have all keys (including `<C-c>`) set as "handled by VsVim". So I can't explain why it works for you and not for me or @hacksoi.

**Comment by adrianjord** [comment]
@ricksladkey Ah, I'm sorry. I misread the title of the ticket. I was thinking of exiting insert mode with <C-c>, not the command margin.
