### ISSUE TITLE
Implement z keybindings for scrolling

### ISSUE THREAD

**Issue by adrianjord** [jaredpar/VsVim#2308]
Key Chords can often block the use of Ctrl based movement even with VsVim handling certain keybindings. There are also no Ctrl bindings for scroll horizontally.

Would love to see z bindings implements for scrolling as per the docs found at http://vimdoc.sourceforge.net/htmldoc/scroll.html

If there is any way I can help, I'd love to contribute.

**Comment by ricksladkey** [comment]
@adrianjord This is definitely doable as your first contribution to VsVim. Wire up the keybindings, 
 create new `NormalCommands`, and implement them in `CommandUtil.fs` using the Visual Studio API function [ScrollViewportHorizontallyByPixels](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.text.editor.iviewscroller.scrollviewporthorizontallybypixels?view=visualstudiosdk-2017).

**Comment by ricksladkey** [comment]
However, I should mention, this issue is a duplicate of #1139, and so this issue can be closed letting that one stay open.

**Comment by adrianjord** [comment]
Okay, I'll close this ticket and give it a shot.
