### ISSUE TITLE
Support special marks '(apostrophe) and `(backtick) + []

### ISSUE THREAD

**Issue by cmaughan** [jaredpar/VsVim#2311]
Special marks `[ and '[, '], `] do not work.  These jump you to the beginning and end of the last pasted text.

**Comment by jaredpar** [comment]
Thanks for reporting. This is fixed and will be in the next VS release. 

Dupe against #1151

**Comment by cmaughan** [comment]
Awesome news, thanks :)

**Comment by cmaughan** [comment]
I just tried this and it seems like it is reversed....
backtick should take me to the column, but it takes me to the beginning of the line. 
apostrophe does what I'd expect backtick to do.....
