### ISSUE TITLE
Yanking and pasting is not working in command mode.

### ISSUE THREAD

**Issue by bayantt** [jaredpar/VsVim#2339]
Earlier, I used to yank word from the text file and while trying to replace it I used to run `:%s` command and pasting the word there with `ctrl + r` `0`. But now I am unable to paste the word which I yanked from the text file using the same command in command mode.

**Comment by ricksladkey** [comment]
Thank you for taking the time to report a bug! You are right that this worked prior to VsVim 2.5.0 and no longer works in the released version. This bug was previously reported in issue #2068 and was fixed in PR #2150 and will be included in the next version of VsVim.
