### ISSUE TITLE
Column insert in visual block ignores empty lines

### ISSUE THREAD

**Issue by tsreyb** [jaredpar/VsVim#2342]
> Note: In this issue I use the term 'empty line' rather than 'blank line' to differentiate between a line with truly nothing (an empty line) and a line that contains only one or more whitespace characters (a blank line). This issue pertains *only* to empty lines

When inserting text across multiple lines in visual block mode, empty lines do not get the inserted text.

EXAMPLE

From the top of the code fragment below I follow this sequence..

1.     Ctrl-Q
2.     (reposition cursor to the end of the fragment)
3.     "I# " _(without quotes)_

Original code fragment..

```
for (x=1; x<=10; ++x) {

  do something
  do something else

  do another thing
  print results
}
```

becomes..

```
# for (x=1; x<=10; ++x) {

#   do something
#   do something else

#   do another thing
#   print results

# }
```

What I expect (and how vim 8.1 behaves) is this..

```
# for (x=1; x<=10; ++x) {
#
#   do something
#   do something else
#
#   do another thing
#   print results
#
# }
```

Reasons this issue matters are..

1. Behavior is different than gvim (v8.1 on windows)

2. Prevents subsequent navigations to the start or end of the block using '{' and '}' from working efficiently (each press of { or } only navigates as far as the next empty line)

3. The resultant code it is less visually appealing.

**Comment by jaredpar** [comment]
> Note: In this issue I use the term 'empty line' rather than 'blank line' to differentiate between a line with truly nothing (an empty line) and a line that contains only one or more whitespace characters (a blank line). This issue pertains only to empty lines

Thanks for the extra info here. This lines up with the terminology we use as well. 

> What I expect (and how vim 8.1 behaves) is this..

Verified this is a bug on current master. Will try and get this fixed for the next release.

**Comment by tsreyb** [comment]
Wow lightning quick response! Look forward to the fix. Thanks!
