### ISSUE TITLE
Surrogate pair spaces

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#2344]
The spacing logic for surrogate pairs appears to be incorrect. For symbols like `\U0001F47D` (👽) vim appears to treat them as accounting for two spaces, not one. Consider the following buffer (make sure to `:set enc=utf-8`):

```
dog
👽👽👽👽👽👽
cat
```

Now starting at the beginning and type `llj` this will put you on the second alien not the third. That indicates that vim believes the first alien occupies two spaces. If it believes it occupied one then it would have tracked to the first alien. The same is true if you use `lllj`. 

To fix this need to research a bit how Vim assigns space counts to these characters. It could be as simple as surrogate pairs occupy two spaces. Doubt it's that easy. It doesn't seem to be due to some unicode category that I can tell. 

There is another twist though to consider: block insert. Take the same repro sample above, starting at the beginning and type: `l<C-Q>jjI#<Esc>`. That will leave you with the following

```
d#ogs
#👽👽👽👽👽👽
t#rees
```

That behavior suggests that when a spaces count in block insert "splits" a surrogate pair the insert should go before the pair, not after. This is different that wide characters in the BMP plane. These also count for two spaces but when a block insert "splits" a wide character it's converted to spaces then the spaces are split. This is another scenario that I need to dig into a bit more to understand the full implications.

This came from digging into PR feedback on #2343

**Comment by ricksladkey** [comment]
These are the best references I could find:

https://news.ycombinator.com/item?id=11963781

For example, the extraterrestrial alien emoji is listed in this official Unicode list as "East Asian Wide" (W):

https://www.unicode.org/Public/UCD/latest/ucd/EastAsianWidth.txt

**Comment by jaredpar** [comment]
Thanks. I think that should be enough to get this going. Really two issues here: 

1. Update the width logic to account for Unicode 9
1. Update the block insert logic to handle splitting of surrogate pairs to not convert into spaces. 

For (2) I still don't have a concrete understanding of how Vim makes this decision. I may need to go dig through their source a bit better to understand what the distinction is.

**Comment by jaredpar** [comment]
The logic seems to be simply that a block insert never starts in the middle of a multibyte character. Instead it always moves to the front for that given row.
