### ISSUE TITLE
"o" to create a new line does not respect the previous line indentation

### ISSUE THREAD

**Issue by Mehradzie** [jaredpar/VsVim#2345]
I have recently moved to a new PC _(Windows 10_),  with a new installation of the same Atmel Studio _(v7.0.1931_) and installed the latest VsVim plug-in (_v2.5.0.0_) on it.

The issue I am noticing is that when I press <kbd>o</kbd> or <kbd>O</kbd> key, the current indentation is not respected. I have quickly hopped into my previous machine (_Windows 10, VsVim v2.1.488_) and tested the same line of code in there and it works as expected.
For example pressing <kbd>o</kbd> on the `SignalQuality,` line takes me to the start of the line not the indented line right under S in Signal.

```
enum Commands
{
	SignalQuality,
	NetRegStat
};
```
If I switch to the edit mode and press the <kbd>Enter</kbd> key to create a new line, Visual Studio puts me in the correct indentation. I have also tried `set autoindent` which did not have any effect on the issue.

My current VsVim settings are as follows.
![vsvim](https://user-images.githubusercontent.com/7462584/44496906-0c94b400-a6ba-11e8-89c8-9134f3c94811.JPG)

**Comment by jaredpar** [comment]
Thanks for reporting this!

The indentation of VsVim is primarily based on the services provided by Visual / Atmel Studio and they tend to be language specific. What language are you using in Atmel Studio and is it the same language that you're using in Visual Studio?

**Comment by Mehradzie** [comment]
Oh, Good point. Totally forgot about that. Even though I have installed Visual Studio on the new PC I still haven't had a chance to even open it but I would normally do C#.

In Atmel Studio that I am seeing the issue, I am developing in C.

**Comment by jaredpar** [comment]
That explains the behavior. The C language service doesn't implement formatting services hence when VsVim calls into them they essentially do nothing. The C# language service though has a fairly robust implementation and hence indentation works as you'd generally expect.

**Comment by Mehradzie** [comment]
As I mentioned in the description of the issue, the indenting was working perfectly fine in the older version I was using. That was also C.

**Comment by ricksladkey** [comment]
In my testing with VsVim 2.5.0 and a new C console project, the `autoindent` setting doesn't seem to matter, only the C/C++ Language Service tab settings:

![image](https://user-images.githubusercontent.com/2680524/44505875-b00da680-a671-11e8-9788-42787bc14802.png)

This might be affected by `:set vsvim_useeditordefaults`. In any case, I recently developed a large C software project in VsVim 2.5.0 and the editor indent with `o` and `O` was working for me, so it *can* work.

**Comment by Mehradzie** [comment]
From my testing when I go to the new line, rather than the number of the tabs to make the indent, I only have the same number of spaces. Say if my new line would need two tabs to be aligned to the previous line, after the <kbd>o</kbd> I only get two spaces 😲

**Comment by Mehradzie** [comment]
Changin the Indenting option from **Smart** to **Block** under **Options > Text Editor > GCC** fixed the issue for me. Thanks for the help guys.
