### ISSUE TITLE
F2 - rename yields inconsistent results

### ISSUE THREAD

**Issue by pimbrouwers** [jaredpar/VsVim#2363]
First off Jared, thank you very much for all of your and the other contributors effort's here. This is truly a wicked extension.

I've noticed that since installing the extension that the builtin `F2` rename functionality is a little wonky. The primary symptom is as follows:

Upon enabling rename mode, the VsVim bar indicates "Unexpected undo/redo event. Falling back to Visual Studio undo". This leaves you hung in rename mode, forcing you to `ESC` the error message and `i` into insert mode to make your changes.

My setup:
- Visual Studio 2017 v15.8.1
- VsVim handling all binding in all contexts (except Ctrl + M for Code Maid)

I propose, if possible, that F2 should enable rename mode as it does. Once rename is enabled, the user should be place into insert mode at which point `Enter` should commit the changes and `ESC` revert.

**Comment by ricksladkey** [comment]
There has been some work on rename recently, see issue #2088 and PR #2340. So it is possible that this is fixed at the head of master. If you want to test the latest pre-release version of VsVim, you can try it out here:

[VsVim in the Open Vsix Gallery](http://vsixgallery.com/extension/VsVim.Microsoft.e214908b-0458-4ae2-a583-4310f29687c3/)

**Comment by ricksladkey** [comment]
Based on other issues, I believe this particular problem with `F2` has been fixed in VsVim 2.6.0 and so I am closing this issue. See related issue #2427.
