### ISSUE TITLE
Keyword Local Completion support? (ctrl-x ctrl-p)

### ISSUE THREAD

**Issue by muchcharles** [jaredpar/VsVim#2364]
Is there an equivalent of this in VsVim?  In standard vim it completes the current word based on searching backwards for previous words in the current document.

**Comment by jaredpar** [comment]
VsVim has has support for <kbd>ctrl-p</kbd>. How is this version different?

**Comment by muchcharles** [comment]
Ah that works the same!  I've just always used ctrl-x ctrl-p but looks like there isn't any difference.  ctrl-x is prefix for several different completion modes.

**Comment by ricksladkey** [comment]
The `<C-x>` flavor of this command is part of "insert mode completion" and is already covered by the older issue #1171, so I am closing this one.
