### ISSUE TITLE
How to use functions like strftime in _vimrc file

### ISSUE THREAD

**Issue by mchalkley** [jaredpar/VsVim#2365]
On other implementations of Vim that I've used on Windows, I've been able to remap a key sequence to get the current date & time in the form of a timestamp, using the following, for example:

nnoremap TS a<C-R>=strftime('%Y-%m-%d %H:%M:%S')<CR>

The above mapping actually inserts the string "strftime('%Y-%m-%d %H:%M:%S')" into a new line.  Obviously, I don't know how to use the function in VsVim, but I wasn't able to find anything that seemed applicable in a few minutes of Googling...

**Comment by ricksladkey** [comment]
In the current version of VsVim (not yet released) you can use filters to run an external program:

```
!!/cygwin/bin/date "+%Y-%m-%d %H:%M:%S"<CR>
```

which replaces the current line with the formatted date and time. You can perform some pre/post steps to simulate inserting the text at the caret position, e.g.:

```
nnoremap TS i<CR><CR><Esc>k!!/cygwin/bin/date "+%Y-%m-%d %H:%M:%S"<CR>kJJ
```

**Comment by ricksladkey** [comment]
Because full vim-script is not a project goal and because we have a workaround, I'm going to close this issue.
