### ISSUE TITLE
The 2.6.0 release

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#2373]
There has been a **ton** of good stuff added since 2.5.0 and high time it was shipped to customers. I've tried to carve off a release a few times now but I've either been stopped due to a bug fix I wanted to slip in or because an enticing PR showed up. 

Trying to get disciplined now and get a release out the door. Going to use the 2.6.0 milestone to track work that needs to be done for this release and create 2.7.0 to put other items. Will likely create a 2.6.0 branch so that 2.7.0 work can continue unimpeded. 

Looking through the issues in 2.6.0 these are the ones I think are critical to get in. Let me know if there are any others you think are needed. Will update the milestones this weekend to match this issue.

- #2372: need to get options page done for new UI
- #2341: I need to either get a solid repro for this or resolve the bug
- #2249: this would block VS2015 installation if it's still present

The staging branch will be used for 2.6.0 stabilization / release.

**Comment by ricksladkey** [comment]
I'm totally psyched for a new release. I'm taking a look at #2372.

**Comment by ricksladkey** [comment]
@jaredpar OK, it looks like all the items in the short list are complete. Let me know if there is anything I can do to help with the release!

**Comment by jaredpar** [comment]
I think we are ready to go. Plan is to release Tuesday. Didn't release over the weekend because travel meant I wouldn't have been able to do any trouble shooting if problems came up.

**Comment by jaredpar** [comment]
It is done, happy Vimming everyone!

**Comment by kkorus** [comment]
Hooray! hooray! 🎉🎉🎉🎉🎉 😂
