### ISSUE TITLE
Cannot navigate to the symbol under caret

### ISSUE THREAD

**Issue by rickythefox** [jaredpar/VsVim#2382]
Navigation using Ctrl-click does not work with VsVim v2.6.1221 and VS 2017 v15.8.7. Disabling VsVim fixes the issue. This works in VsVim v2.5.0.

![image](https://user-images.githubusercontent.com/1675955/46880093-c0423680-ce15-11e8-9d57-d2ba0bbdb635.png)

![image](https://user-images.githubusercontent.com/1675955/46880287-3f376f00-ce16-11e8-8571-c1ee2e854fbc.png)

**Comment by ricksladkey** [comment]
Interesting. It actually does go to the definition, but it goes to the definition the caret is on, not where the mouse cursor is clicked.  The workaround is to simple click first to move the caret.

I'll take a look at fixing this.

**Comment by rickythefox** [comment]
@ricksladkey the fix works, however when Resharper is installed it sometimes jumps to definition and then immediately jumps onwards somewhere unrelated. Maybe checking for resharper and then executing the Resharper action 'ReSharper.ReSharper_GotoDeclaration<CR>' would fix this?

**Comment by ricksladkey** [comment]
@rickythefox I recommend modifying your binding as follows:

```
:map <C-LeftMouse> <LeftMouse>:vsc Resharper.Resharper_GotoImplementation<CR>
```

otherwise it will go to the definition of the word under the caret rather than the mouse.
