### ISSUE TITLE
ISmartTagBroker usage in Dev16

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#2387]
The `ISmartTagBroker` type is being deleted in Dev16. This means all of the uses need to move to a VS specific assembly. The current uses are preventing VsVim from loading entirely in Dev16 builds. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.language.intellisense.ismarttagbroker?view=visualstudiosdk-2017

**Comment by ricksladkey** [comment]
Is this issue fixed by PR #2388, which has been merged?

**Comment by jaredpar** [comment]
Yes it is.
