### ISSUE TITLE
Remove VS2012 and VS2013 support

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#2399]
Now that VS2017 is nearly complete and focus is shifting to VS2019 I've been evaluating what all versions of VS should VsVim be targeting for support. After some discussion with others decided to make VS2015 the minimum supported version. The advantages it has:

1. AsyncPackage is supported
1. The official SDK is on NuGet
1. Light bulbs exist (the replacement for smart tags)
1. My, recently deleted, telemetry suggests the majority of developers are already here.

**Update**: Link to version of VsVim that supports specifically 2012 and 2013: https://marketplace.visualstudio.com/items?itemName=JaredParMSFT.VsVim2012and2013

**Comment by eviltobz** [comment]
will the last compatible version still be downloadable and obvious if you're using an older version of studio? it'd be terrible to have to do some maintenance on some old code, needing an old version of studio, and suddenly find that pressing a key directly correlated to the character appearing in the editor. ick! ;)

**Comment by jaredpar** [comment]
>will the last compatible version still be downloadable and obvious if you're using an older version of studio? 

Yes. When I removed VS2010 support I published a special version of the extension that only listed 2010 as supported. Hence VS2010 users will forever see that, and only that, when they look for it. I would do the same for VS2012 and VS2013.
