### ISSUE TITLE
Join Line Command Shift-j doesn't do anything

### ISSUE THREAD

**Issue by GaryFurash** [jaredpar/VsVim#2413]
Is join implemented some other way?

**Comment by ricksladkey** [comment]
Joining lines is definitely working for me and has been implemented for a very long time and offhand I cannot think of a reason why it might not be working for you.

**Comment by jaredpar** [comment]
This is definitely implemented. If it's not working the most likely issue is that VsVim mis- processed your vimrc file and has created a bad mapping. Can you run `:set` and see if the <kbd>J<kbd> command is incorrectly mapped?

**Comment by GaryFurash** [comment]
will do thanks!

**Comment by ricksladkey** [comment]
@GaryFurash I think @jaredpar means the `:map` command.

**Comment by jaredpar** [comment]
Doh! Yes I meant the `:map` command. 😦
