### ISSUE TITLE
normal mode across all files

### ISSUE THREAD

**Issue by 00bins** [jaredpar/VsVim#2416]
Not necessarily an issue but would it be possible (or is it already) to have normal mode be global across all files? At the moment it seems to be a per window setting.

Thanks
Rob

**Comment by jaredpar** [comment]
VsVim works this way because it's how gVim works as well. Is there a way to enable a global mode setting in gVim that we should consider emulating?

**Comment by 00bins** [comment]
ah sorry I didn't realize that - I mostly use vim in a console if not vsvim. I'll check
Thanks
Rob

**Comment by 00bins** [comment]
Ok so running gvim with split windows each window is either in insert mode, or normal mode. If I go to insert mode, all windows are then in insert mode. If I go to normal mode all windows are in normal mode.
I didn't set anything special to do that - it just did it naturally.

**Comment by jaredpar** [comment]
Hmm. I see that as well. It does seem the mode is sync'd in all places though, not just for all views for a given buffer. 

The behavior seems more complex though. Consider that if you open two files each in a separate tab, enter visual character mode in one of them and then use the mouse to switch to the other file. The new file will be in normal mode, not visual mode. Switch back and the first file is normal as well. 

That seems to indicate there are two possible ways this is implemented in vim: 

1. There is one global mode for an instance of vim. 
1. Each view has it's own mode but when a file gets focused it attempts to take on the mode of the previously focused file. In some cases it cannot do this and reverts to normal mode instead. 

I think that (1) is unlikely and that (2) is more plausible. Need to experiment a bit more though and see if I can reason out the behavior here.

**Comment by ricksladkey** [comment]
I can see both sides of this issue. I have often been surprised to return to some buffer and start typing normal commands only to see them literally inserted because I incidentally switched away from it while it was in insert mode. However the ability to have selections in unfocused buffers is a fairly central feature of the Visual Studio editor model and VsVim currently supports this.

**Comment by 00bins** [comment]
There's also this https://vi.stackexchange.com/questions/6463/have-different-tabs-windows-remembering-their-mode so it would appear to be 1) which is the normal way (*pun*)
What do you mean by
"However the ability to have selections in unfocused buffers is a fairly central feature of the Visual Studio editor model" ?
cheers
Rob

**Comment by ricksladkey** [comment]
@00bins In Visual Studio (and in VsVim) you can create a selection in one document (e.g. double-clicking on a word), switch to another document, and then switch back to the first document. In that case, the word will still be selected.

**Comment by 00bins** [comment]
I see what you mean. I don't think I'd ever noticed nor relied on that feature.
I've remapped Ctrl-Tab to make vsvim behave like gVim now anyway 

cheers
Rob

**Comment by 00bins** [comment]
My alt-tab mapping doesn't really work the way I'd like so if there's a way to make vsvim more vim like wrt to this I'd be happy - switching tabs (which I don't really use since they're not the same in vs) or windows always maintains the current mode (unless it's a selection)

**Comment by 00bins** [comment]
apparently this does what I want 

autocmd BufEnter * stopinsert 

but not in vsvim ;(

**Comment by ricksladkey** [comment]
Well, since `autocmd` isimplemented, but `stopinsert` is not, this issue is now a very reasonable feature request to implement the `stopinsert` command.

**Comment by 00bins** [comment]
hmm except 
src/vimcore/autocommandrunner.fs -

/// VimBufferCreated is the closest event we have for BufEnter.
    member x.OnVimBufferCreated (vimBuffer: IVimBuffer) =
        // TODO: BufEnter should really be raised every time the text buffer gets edit
        // focus.  Hard to detect that in WPF / VS though because keyboard focus is very
        // different than edit focus.  For now just raise it once here.

so it may not be that easy

**Comment by cbates-** [comment]
> apparently this does what I want
> 
> autocmd BufEnter * stopinsert
> 
> but not in vsvim ;(

I never want to be in Insert mode when switching to a different window.  This line in _vsvimrc seems to do what I want:
au BufWinLeave * call feedkeys("\<C-\>\<C-n>")

Maybe this too:
	au FocusLost,TabLeave * call feedkeys("\<C-\>\<C-n>")

**Comment by 00bins** [comment]
Thanks - I will try that. I suppose ctrl-tabbing to another window  is not the vim way.  I should probably remap ctrl-tab and force myself to unlearn years of visual studio / windows muscle memory. Or not, if your vimrc tips work ! 

cheers
Rob
