### ISSUE TITLE
markers margin

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#2419]
I really like the new way to visualize markers - even not knowing enough about the markers to understand all the visualized markers and how to use them efficitently.

Sincerely the drawn markers collide with VS "markers" for breakpoints, bookmarks and tasks:

- ![breakpoint on VsVim markers](https://user-images.githubusercontent.com/525700/48482447-f9a10400-e810-11e8-8ccd-e843f1ba3b70.png)
- ![bookmark on VsVim marker](https://user-images.githubusercontent.com/525700/48482476-10dff180-e811-11e8-8299-d4074bd06769.png)
- ![task on VsVim marker](https://user-images.githubusercontent.com/525700/48482537-3ff66300-e811-11e8-86b4-f72a1ad03f86.png)

Is there a chance to make it a bit "cleaner"?

Thanks in advance!

**Comment by ricksladkey** [comment]
The VsVim mark glyphs could be shown "below" (in the z-order) the other glyphs, rather than above them. Is that what you are suggesting?
