### ISSUE TITLE
Parameter name: span was out of range of valid values [vs2015/2.6.0.0] 

### ISSUE THREAD

**Issue by obaterspok** [jaredpar/VsVim#2422]
I started getting daily error messages after updating to 2.6.0.0.
I just triggered it by pressing ESC
------
[Microsoft Visual Studio]
Specified argument was out of the range of valid values.
Parameter name: span
----------
I believe it usually pops up when pressing ESC and it's always 'span'.

Unfortunately I can't reliably reproduce it. Any hints on how I can provide better information? (log files, etc)

-- john

**Comment by ricksladkey** [comment]
The fact that you know what the exception is and what the exception message surprises me. The most common situation is a message box saying something to the effect that an "error occurred" and that more information can be found in the activity log.

So first, if you could post a screenshot of the actual dialog you get, that could be useful. And if you have an activity log, it might contain a complete stack trace of the exception. If you don't have an activity log, you might need to enable it as [described here](https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-the-activity-log?view=vs-2017),

**Comment by obaterspok** [comment]
Hi Rick,

I found the exception in the ActivityLog so I'd guess the screenshot would be of little use (but it really looked like my textual representation with "Micro... Studio" as title bar):

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: span
   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(ITextSnapshot snapshot, Span span)
   at Vim.Modes.Insert.TextChangeTracker.get_EffectiveChange()
   at Vim.Modes.Insert.TextChangeTracker.Vim-Modes-Insert-ITextChangeTracker-get_EffectiveChange()
   at Vim.Modes.Insert.InsertMode.OnCaretPositionChanged(CaretPositionChangedEventArgs args)
   at &lt;StartupCode$Vim-Core&gt;.$Modes_Insert_InsertMode.-ctor@295-31.Invoke(CaretPositionChangedEventArgs args)
   at Microsoft.FSharp.Control.CommonExtensions.SubscribeToObservable@2172.System-IObserver`1-OnNext(T value)
   at Microsoft.FSharp.Control.ObservableModule.succeed@2704[TResult](IObserver`1 observer, FSharpOption`1 _arg1)
   at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.h@349.Invoke(Object _arg1, TArgs args)
   at &lt;StartupCode$Vim-Core&gt;.$Modes_Insert_InsertMode.-ctor@293-35.Invoke(Object delegateArg0, CaretPositionChangedEventArgs delegateArg1)
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)

**Comment by ricksladkey** [comment]
Thanks, the stack trace helps a lot. This indicates that the tracking for the "active region" is get munged up. Looking at the code, the area is rife for mistakes and corner cases. Having a repro would help to solve the underlying bug. Nevertheless, adding bullet-proofing to the code would at least prevent exceptions bubbling up to the user.

**Comment by ricksladkey** [comment]
OK, some progress on this item.

The current code only handles text changes consisting of a single change. I saw this limitation elsewhere and thought that multiple changes were supported but only in theory. Well, it turns out multiple changes in a single text change are definitely possible, but it depends on the language service or extension making those changes.

The short answer is, in order to be robust, the maintenance of the "active region" definitely needs to support multiple changes per text change event. This however is trickier than it sounds so I'm going methodically.  [Here](https://docs.microsoft.com/en-us/visualstudio/extensibility/inside-the-editor?view=vs-2017#textmodel) is a good reference on the text change event and its data structures.

**Comment by obaterspok** [comment]
![image](https://user-images.githubusercontent.com/5311823/48892725-ff18d280-ee3e-11e8-99fb-5486892e0571.png)

I'd say this was pretty close to my textual description :)

**Comment by Mark-Sims** [comment]
Was there ever any resolution here? I run into this error periodically (seems to be related to pasting, as mentioned - Shift+Insert, or Ctrl+v) and am forced to restart Visual Studio.

**Comment by ricksladkey** [comment]
@Mark-Sims PR #2426 was merged and it was intended to resolve the stated problem. The fix will be included in the next version of VsVim. If you want to test the fix before the next version of VsVim is released, you can search for VsVim in the [Open VSIX Gallery](http://vsixgallery.com/).
