### ISSUE TITLE
Clipboard for VsVim not synced with Visual Studio

### ISSUE THREAD

**Issue by seltzy** [jaredpar/VsVim#2423]
This is a nice extension. Makes using VS a little more tolerable for me. Thanks for making it!

If I do `Ctrl-C` and then press `p`, it instead pastes the last thing copied via `y`. Likewise, If I use `y` to copy and then do `Ctrl-V` I get the last thing I copied with `Ctrl-C`. This is infuriating behavior. Is there anything that can be done about this?

I'm using VS2015.

Thanks! :)

**Comment by ricksladkey** [comment]
It is not the default behavior (for compatibility with vim/gvim), but VsVim supports what you want with the setting:

```
:set clipboard=unnamed
```

Type this out to test it and then put it into your rc file (e.g. `~/.vsvimrc`) if you like it.

**Comment by ricksladkey** [comment]
Closing this issue as answered.
