### ISSUE TITLE
What the setting Hide Marks Value

### ISSUE THREAD

**Issue by NoDocCat** [jaredpar/VsVim#2425]
I want hide marks on margin.
But i don't know the setting's value
In new version, I want have some prompt
Thanks

**Comment by ricksladkey** [comment]
The value of `vsvim_hidemarks` is a string consisting of the mark characters you don't want to be displayed in the glyph margin.

#### Examples

- Don't hide any marks: `:set vsvim_hidemarks=`
- Hide only special marks: `:set vsvim_hidemarks=<>[]^.'`
- Hide all local marks: `:set vsvim_hidemarks=<>[]^.'abcdefghijklmnopqrstuvwxyz`
- Hide all marks: `:set vsvim_hidemarks=<>[]^.'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ`

**Comment by ricksladkey** [comment]
In fact, I only gave the `vsvim_hidemarks` setting light testing and in fact it doesn't perfectly react to "live" changes. Marks which were previously not hidden and that are present don't become hidden, instead they "become stuck" at their current positions.

**Comment by NoDocCat** [comment]
Thank you for your answer.
And, i suggest set a special value to "Hide all marks"

**Comment by ericmutta** [comment]
In case someone else like me lands here when looking for the meaning of each of the marks, here are the Vim docs: https://vim.fandom.com/wiki/Using_marks#Special_marks
