### ISSUE TITLE
Command Mode should respect words

### ISSUE THREAD

**Issue by Wagk** [jaredpar/VsVim#2428]
Assuming an input like:

`/Namespace::something`
`?Namespace::something`
`:Namespace::something`

pressing `C-w` to kill a word should result in:

`/Namespace::`
`?Namespace::`
`:Namespace::`

Currently it results in:

`/`
`?`
`:`

**Comment by ricksladkey** [comment]
The `<C-w>` command in command mode was added in PR #2241. Do you want to look at this, @dhmgit?

**Comment by dhmgit** [comment]
@ricksladkey, yes I can probably take a look at this within the next couple of days.  IIRC, the WPF assembly didn't have access to the internal F# implementation for chunking up words, so implemented a simplified version.  I'll take another look to see if there's any reason the F# implementation can't be exposed as a public utility.
