### ISSUE TITLE
Searching with /, then pressing Ctrl-A and typing FOO inserts /O/O/F

### ISSUE THREAD

**Issue by tankorsmash** [jaredpar/VsVim#2456]
To reproduce on VS2013 (and Resharper++, if relevant)

1. `/`
2. `<C-A>`
3. `FOO`

Results in `/O/O/F`, and searches for O, instead of FOO as expected.

`C-A` sends the cursor to the front of the line in command mode,  but when searching, it goes before the `/`.

**Comment by ricksladkey** [comment]
I can reproduce this with VS2019 at the head of master.
