### ISSUE TITLE
Echoing environment variables

### ISSUE THREAD

**Issue by gregshields** [jaredpar/VsVim#2458]
I could swear that in previous versions of VsVim I was able to echo environment variables like so:
:echo $HOME
:echo $VIM

I believe I have the most current release installed (2.6.0.0), at least according to the "Extensions and Updates" window in Visual Studio.

I've also tried this:
:echo %HOME%
:echo %VIM%

Both syntaxes return "Parse error".

Please forgive me if I'm missing something obvious. I did try to peruse Kazark's old implEcho branch, and that just brought up more questions in my mind.

**Comment by ricksladkey** [comment]
It's true that `:echo $HOME` should work because it works in vim.

In the current version of VsVim, you can use the shell to do echoing. For example:

```
:!echo %HOME%
```
produces (for me):

```
C:\Users\jrs
```

**Comment by gregshields** [comment]
Ah, very crafty! Thank you, Rick.

This usage of ! to invoke a shell is unfamiliar territory for me. Can you point me to some documentation of that?
