### ISSUE TITLE
Integration with TwinCAT 3

### ISSUE THREAD

**Issue by maximbendiks** [jaredpar/VsVim#2468]
TwinCAT 3 is an extension for Visual Studio for programming industrial PLCs which you can freely download at https://beckhoff.de/default.asp?download/tc3-download-xae.htm?id=1948695119487514. It seems that they implemented the text editor completely by themselves, so VsVim is not working out of the box. When I change the editor to Source Code (Text) Editor VsVim is working. Unfortunately I need to use the TwinCAT PLC Editor because it is creating in the background a xml file but with the PLC Editor it looks like I am editing a plain text file.
Did anyone try it before? Can I somehow force VsVim to work in this other Editor or is it a completely new API? What would the first steps be to check if it is even possible to make it work? I'd be happy to contribute but am completely new to VS extensions. 
My Versions: VS 2015 Community + TwinCAT 3.1.4022.27 + Windows 7 Pro x64 + VsVim 2.6.0.0

**Comment by jaredpar** [comment]
Unfortunately I don't have any experience with this product. Do we know if they're using the standard editor or not? You mentioned they may not be. If that's the case then VsVim won't work, it's pretty tied to the VS editor APIs. 

> What would the first steps be to check if it is even possible to make it work?

Mostly just need to see if they're using the VS editor API or not. Is there a way to download their extension without buying the product? If I can see the extension I can figure this out pretty fast if this is the case.

**Comment by maximbendiks** [comment]
It is definitely not the standard editor. So I guess you can close this issue.
But they have an API called Automation Interface. It seems to be quiet easy to create a simple extension as a middleware between the VS editor and the back-end of TwinCAT. So I think I will go with that.

**Comment by RGrabichler** [comment]
@ascaron37 , you made any progress in this matter?

**Comment by ascaron37** [comment]
> @ascaron37 , you made any progress in this matter?

No, sorry.

**Comment by piratecarrot** [comment]
Perhaps it would be possible to create a temporary file, which is a raw structured text document, and then subsequent file saves would update the backing XML file.

This is a tool to convert between the proprietary XML and plain ST files.
https://github.com/Zeugwerk/Plaincat
