### ISSUE TITLE
Detecting 2017 vs 2019 in vsvimrc

### ISSUE THREAD

**Issue by keithn** [jaredpar/VsVim#2469]
Annoylingly, all my mappings to resharper functionality don't work in 2019 as there is a "Extensions" prefix,  but 2019 and 2017 are loading the same file, can I conditionally distingush which version I'm dealing with / have different files load depending on version?

**Comment by ricksladkey** [comment]
You should be able to say:

```
if $VisualStudioVersion == "15.0"
```

But this doesn't currently work environment variables don't work in expressions yet and binary equality does not yet correctly handle string values.

**Comment by keithn** [comment]
I like that.... Yes! .... but no :)
