### ISSUE TITLE
Always disabled when restart VS2015

### ISSUE THREAD

**Issue by truelixin** [jaredpar/VsVim#2475]
Everytime I restart VS2015, VsVim seems disabled, and I have to open "Extensions and Updates", and enable it, and restart VS, and then this time VsVim is enabled to be used.
But next time I close VS and restart it, VsVim disabled. I have to repeat those operations.

**Comment by ricksladkey** [comment]
@truelixin, can you see if the problem is the same problem of duplicate extensions as discussed in this general issue related to extensions?

https://github.com/madskristensen/BundlerMinifier/issues/214

**Comment by truelixin** [comment]
Ah, it worked! Thanks a lot! @ricksladkey
