### ISSUE TITLE
CTRL+A in blockwise-visual mode increments numbers not in selection

### ISSUE THREAD

**Issue by jazzdelightsme** [jaredpar/VsVim#2501]
Suppose you have text like the following:

```
 1  This is the first thing. Here's a number: 99.

 2 This is the second thing.
   Here is another number 123.

 3 This is the last thing.
```

1. Enter blockwise-visual mode (<kbd>ctrl+v</kbd>) and select only the numbers on the left ("1", "2", and "3"), leaving the rest of the text unselected.
2. Now use <kbd>ctrl+a</kbd> to increment the numbers (so now the items in the list should be numbered "2", "3", "4").

**Expected result:**
*Only* the numbers on the left should be incremented.

**Actual result:**
*All* the numbers (including other numbers in the text, like "99" and "123") are incremented--even those not covered by the blockwise-visual selection.

*And as always: thank you for such an awesome plugin!*

**Comment by ricksladkey** [comment]
In my testing with the head of master, only the second number is incremented. But that is definitely a difference from vim. I'll take a look at fixing this.
