### ISSUE TITLE
Visual Studio 2019 always Display "Welcome to Vim"

### ISSUE THREAD

**Issue by TKumadaki** [jaredpar/VsVim#2506]
My Visual Studio 2019 always shows "Welcome to Vim" when opened with the editor.
On the other hand, Visual Studio 2017 has not seen this message.

I dug into this difference a bit.
The order of initialization processing is different between Vs2017 and Vs2019.

Vs 2019
1. Vim.SetupInitialMode()
2. Vim.SetupInitialMode.runInit()
3. CommandMarginController.Connect()

Vs 2017
1. Vim.SetupInitialMode()
2. CommandMarginController.Connect()
3. Vim.SetupInitialMode.runInit()

When `runInit` is performed, VsVim switches the mode from 'UninitializedMode' to 'NormalMode'.
Vs 2017 catches this event and updates the command margin to blank.
Vs 2019 does not catch this event.

I am not troubled by this problem.
The behavior of Vs2019 looks like the original intention.
I just wanted to point out the difference.
If maintainer judge that it has no problem, please close this.

**Comment by ricksladkey** [comment]
I noticed this too, although I have seen "Welcome to Vim" in the past. However, I believe the intention is to tell the user "Welcome to Vim" just once, but now with VS2019 when you load a solution with many open documents, or when you open any new document, or open a new peek window, all the windows always say "Welcome to Vim", whereas vim itself is silent when opening a new file.

**Comment by TKumadaki** [comment]
>  I believe the intention is to tell the user "Welcome to Vim" just once

I agree with your opinion.
I wondered if I should do the same as Vim.
For now, I changed it to display the message only once.
