### ISSUE TITLE
gq doesn't format text

### ISSUE THREAD

**Issue by loosche** [jaredpar/VsVim#333]
If you select a set of rows and press 'gq' the text isn't formatted into properly sized lines. In vim the width for the command is based on the 'textwidth' variable.

**Comment by ctnieves** [comment]
This feature would  be very helpful.

**Comment by mqudsi** [comment]
Is it too simplistic to just map gq to `:vsc Edit.FormatSelection` and have Visual Studio worry about the formatting? Can VsVim simply forward the value of `tw` to the matching Visual Studio formatting option for the current document?

**Comment by ricksladkey** [comment]
@mqudsi That kind of formatting (code formatting) is already support using `=`. This kind of formatting (wrapping and indenting text and comments) is not yet implemented.

**Comment by ricksladkey** [comment]
I have a preliminary version of this working. I'll submit a PR when it is finished.

**Comment by Kazark** [comment]
@ricksladkey you are the :bomb:

**Comment by mqudsi** [comment]
@martin-braun did you read #2274? `gq` is implemented (in a limited capacity).

**Comment by martin-braun** [comment]
@mqudsi Missed that, but not working for me. I simply mapped Edit.FormatDocument or so on Visual Studio. Sorry about that comment, though.
