### ISSUE TITLE
Relative line numbers

### ISSUE THREAD

**Issue by thelamb** [jaredpar/VsVim#375]
In Vim7.3 it's possible to enable relative line numbers. I haven't found a plugin for Visual  Studio that does the same, I guess without VsVim it is not really useful.

However, if at all possible, I would really like to see this included in VsVim.

Also, an important missing movement for me is d/  - I often find it faster to use d/ when removing a few words.

Thanks, awesome job in general!

**Comment by jaredpar** [comment]
Closing as the relative line number extension is a suitable option here.

**Comment by Samelandslaget** [comment]
Unfortunately, the extension does not work with Visual Studio 2019.

**Comment by ricksladkey** [comment]
@Samelandslaget The master branch of VsVim does include native support (not requiring an extension) for relative line numbers. The feature was added in #2571. You can use the nightly builds or wait for the next release of VsVim, which may be out shortly.
