### ISSUE TITLE
More information in the VsVim status/command bar

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#408]
I would be glad to have more information in the status/command bar like VIM has.

As example ... deleting, yanking, pasting a range of lines gives as response of the action information about the count of lines the action worked on - "4dd" has as response "4 fewer lines", like "4yyp" tells "4 more lines".

**Comment by joshcameron** [comment]
I second this request. It's the number one thing I find missing from VsVim compared to vim in my workflows. I'll cut and paste some code from one place to another and now I need to indent it, but I don't know how many lines I've just pasted. I'm getting pretty good at guessing, or doing the arithmetic on the line numbers, but it would be much easier if VsVim would just tell me how many lines I've just affected. Thanks!

**Comment by jaredpar** [comment]
@joshcameron yeah not sure how this request got lost for so long.  It's relatively easy to add in.

**Comment by ricksladkey** [comment]
This feature was implemented in PR #2238.
