### ISSUE TITLE
Incorrect vimrc file handling

### ISSUE THREAD

**Issue by eyeofhell** [jaredpar/VsVim#411]
Hello. If i add folowing line to my vimrc file, the "a" key in normal mode will not put vim into insert mode. Instead, it will go into command mode and write ":let" in command line :(.

nmap <M-a> :let g_nFontSize -= 1<CR>:exec ':set guifont=DejaVu\ Sans\ Mono:h' . g_nFontSize<CR>:echo g_nFontSize<CR>

**Comment by jaredpar** [comment]
This problem has been tackled on a couple of levels now:

1. Many more types of key mappings are now supported.
2. VsVim is much better about issuing errors for unsupported mappings. 
3. Any errors which come about while running the `_vsvimrc` are displayed in the IDE.
