### ISSUE TITLE
A kind of help document is needed, telling what parts of VIM are supported ...

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#453]
Hi,

working with VsVim I got a good impression, because I could work with most of my used "commands".
But sometimes it shows up, that (ex) commands are not implemented (yet).

Is it possible to integrate a kind of help, telling what hotkeys, (ex) commands are implemented/supported?

And could this be combined with a kind of plan for the future showing what will be implemented/supported in the near future?

Best regards,

Martin

**Comment by jaredpar** [comment]
Added a [Supported Features](https://github.com/jaredpar/VsVim/blob/master/Documentation/Supported%20Features.md) document
