### ISSUE TITLE
Executed macro produces different results than identical manual keystrokes

### ISSUE THREAD

**Issue by kalebpederson** [jaredpar/VsVim#547]
This seems like a likely R# integration issue.

Given the following function with too many arguments, I may decide to reformat so I'll position the cursor at the beginning of the line the function is declared on and then do something like this to manually drop the arguments onto separate lines: `f,a<CR><ESC>`, `f,a<CR><ESC>`, ...

```
public class SomeClass
{
    public void SomeFunction(string arg1, string arg2, string arg3, string arg4, string arg5)
    {
    }
}
```

The result when manually performed is the following:

```
public class SomeClass
{
    public void SomeFunction(
        string arg1,
        string arg2,
        string arg3,
        string arg4,
        string arg5)
    {
    }
}
```

But if instead I record a macro: `qaf,a<CR><ESC>q` and then execute `4@a` on that same line I get the following:

```
public class SomeClass
{
    public void SomeFunction(
 string arg1,
 string arg2,
 string arg3,
 string arg4,
 string arg5)
    {
    }
}
```

**Comment by jaredpar** [comment]
Recent builds of VsVim have a solution for this: clean macro recording.   This is an option available in the options page:

- Tools -> Options -> VsVim 
- Vim Edit Behavior -> Clean Macro Recording

When set to True this will disable a lot of Visual Studio features that interfere with Macro Recording: intellisense, brace matching, etc ...  Hence the recording session for a macro and the associated playback should be idental and very clean.

The warning for this feature is the same as the use case: when recording a macro Intellisense will stop working.  😦  

I personally accidentally record macros all the time.  I've gone back and forth in enabling this feature.  But when enabled it does result in cleaner macro playback.
