### ISSUE TITLE
Undo doesn't take into account external edits

### ISSUE THREAD

**Issue by kalebpederson** [jaredpar/VsVim#549]
This is likely a R# integration issue.

Given the following line in the middle of a function somewhere:

```
        Assert.AreEqual(Some.Value, Other.Value);
```

With the cursor on the line above I can drop `Other.Value` onto the following line with some indentation using: `^f,a<CR><ESC>`. But, if I then decide I didn't want it on the following line, executing undo (via `u`) results in the `Other.Value` being dedented. It takes two `u`'s to undo the actual operation.

**Comment by ricksladkey** [comment]
This bug was fixed in PR #2106 and so this issue can be closed.
