### ISSUE TITLE
Block command-to-VS passthrough in command line mode

### ISSUE THREAD

**Issue by kalebpederson** [jaredpar/VsVim#552]
Although I'm uncertain, I think it might make sense to block any passthrough to visual studio when we're in command line mode.  For example:

Finding and replacing: `:%s/<C-R>a/substitute/g`
Going to beginning of line to fix a typo: `:ste ts=4 sw=4<C-B>`
Navigating between words: `:set ts=4 sw=4 sts=2<C-Left>`

I can't think of any examples where I would really wanted VS to interpret something when I'm in command-line mode.

**Comment by jaredpar** [comment]
This issue seems to be long fixed now that command line mode is its own edit control.  It essentially blocks all pass through to Visual Studio except for a few special cases.
