### ISSUE TITLE
o/O not indenting properly in XAML files

### ISSUE THREAD

**Issue by kongo2002** [jaredpar/VsVim#557]
Hi,
I just discovered that `o` and `O` normal commands don't indent correctly in XAML

```
<Button Grid.Column="1"
        Content="Cancel"
        IsCancel="True"
```

Pressing `o` on the 'IsCancel' line results in the following:

```
<Button Grid.Column="1"
        Content="Cancel"
        IsCancel="True"
<CURSOR>
```

Expected result:

```
<Button Grid.Column="1"
        Content="Cancel"
        IsCancel="True"
        <CURSOR>
```

Pressing `<Return>` in insert mode works just fine.

Cheers,
Gregor

**Comment by ricksladkey** [comment]
This works correctly at the head of master and so this issue can be closed.

**Comment by ricksladkey** [comment]
The behavior and settings are somewhat complicated. Here is a summary of the essential factors for indenting with `o` and `O`:

| `vsvim_useeditorindent` | `autoindent` | Language Service Indent | Indent? |
| --- | --- | --- | --- |
| set | - | Block or Smart | yes |
| set | - | None | no |
| unset | set | - | yes |
| unset | unset | - | no |

In my testing with the XAML Language Service and VS2017, block indenting is not different from smart indenting.
