### ISSUE TITLE
Feature Request: Extend markers functionality to be closer to VIM

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#575]
Using in VIM `:help markers` tells a lot about the functionality of marks/markers in VIM.
Some of them I never used, some of them I didn't miss, because I already forgot them again, some of them I really miss in VsVim.

Some functionality worth porting IMHO:
1. Uppercase markers being persistent, causing, if used, the opening of the remembered file and a jump to the remembered location 
2. Special _markers_ like:
   - changes `'[`, `']`, `'.`, `'^`
   - positions `''` (needs a jump list recallable with :jumps), `'"`, `['`, `]'`

And all `'` things are useful with `, too!

**Comment by ricksladkey** [comment]
The marks `'[` and `']` are still unimplemented, but issue #1151 is tracking that. I think the spirit of this request has been fulfilled and it can be closed.
