### ISSUE TITLE
Add support for :sort

### ISSUE THREAD

**Issue by kalebpederson** [jaredpar/VsVim#601]
I was trying to sort a list of constants and noticed that `:sort` is still needed.

**Comment by gibwar** [comment]
Also bumping in hopes this could get prioritized at some point, this request is over 5 years old!

**Comment by funonly** [comment]
Does closed mean "Will not implement"? 

I still would love to see this feature

**Comment by jaredpar** [comment]
@funonly this issue is still active. There was a duplicate of this issue closed but the main issue is still active.

**Comment by ricksladkey** [comment]
FYI, I'm working on the issue. I have sorting with or without reverse ordering and the ignore case sort option (`[i]`) working. I'll submit a PR when I get a little bit further. The full vim sort command is remarkably rich and I don't know if I have the stamina to implement all of the variants.

https://github.com/ricksladkey/VsVim/tree/sort-command

**Comment by Kazark** [comment]
@ricksladkey I would be excited to see even a basic version of this implemented.

**Comment by ricksladkey** [comment]
@Kazark Got the whole thing working, I think!
