### ISSUE TITLE
Changing lines with the caret (e.g. "j" or cursor down) lets the caret jump, if the lines contain different count of tabulators

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#603]
An example (good) - between the variable types and the name of the variables is in each line one tabulator:

```
const Type* pObject  = __super::operator[](ii);
const char* pcszPath = "<unknown path>";
```

If you place the cursor/caret onto the assignment operator of the first line and use "j" to go to the next line, than the caret stays onto the assignment operator.

An example (bad):

```
const ExampleType*  pObject  = __super::operator[](ii); // between "ExampleType*" and "pObject" is one tabulator
const char*     pcszPath = "<unknown path>"; // between "char*" and "pcszPath" are two tabulators
```

If you place the cursor/caret onto the assignment operator of the first line and use "j" to go to the next line, than the caret suddenly is onto the "k" of "unknown". So it jumps 7 characters to the right.

This is really annoying going through lines to modify them.

(Both examples are align the right way in Visual Studio (ts = 4, sw = 8), even if github displays them misaligned.)

**Comment by chaitanyagurrapu** [comment]
Is this related to https://github.com/jaredpar/VsVim/issues/1854? If so, perhaps this can be closed as well.

**Comment by jaredpar** [comment]
@chaitanyagurrapu i will check.  This should be fixed by now but will at least add a test.
