### ISSUE TITLE
Add support for CTRL-W, CTRL-W

### ISSUE THREAD

**Issue by jaredpar** [jaredpar/VsVim#625]
Move to next window

**Comment by knatten** [comment]
@ciwchris You say "'CTRL-W, j' and 'CTRL-W, k' are currently implemented.", should I expect those to work in 2.0.1.0? What do they do? I would expect them to move focus between horizontal tab groups, but they don't seem to do anything.

Anyway, <C-w>h / <C-w>l is my most wanted feature for VsVim.

**Comment by ciwchris** [comment]
@knatten yes, they provide movement between horizontally split windows. I'm currently using version 2.0.1.0 and they are functioning. `CTRL-W j` will move to the window below the current window and `CTRL-W k` will move to the window above the current window. [Window move cursor](http://vimdoc.sourceforge.net/htmldoc/windows.html#window-move-cursor)

**Comment by knatten** [comment]
@ciwchris Sorry for the very late reply, I forgot all about this. On my computer, `Ctrl-w h` and `Ctrl-w l` *does* move between vertically split tab groups, but `Ctrl-w j` and `Ctrl-w k` *does not* move between horizontally split tab groups.
I'm using Visual Studio 2013 Update 4 on Windows 10, and VsVim 2.0.1.0.

**Comment by ciwchris** [comment]
@knatten Interesting, you are correct. I guess I never create a "New Tab Group" and instead always split the current window. I expect `:new` and `:vnew` would create a "New Tab Group", but since they are not supported I split the window with `:sp` and `:vs` and then use the new window to open whatever file I'm interested in.

**Comment by knatten** [comment]
In summary, `Ctrl+w [hjkl]`
- works for windows opened with `:vs`
- works for windows opened with `:sp`
- does not work for  "new horizontal tab group"

And finally a weird thing, for "new vertical tab group", `Ctrl+l` always works, but `Ctrl+h` only sometimes works.

**Comment by Plotnus** [comment]
Any plans to add support for moving windows?
Ctrl+w [HJKL]

**Comment by zahillmtu** [comment]
I selected VsVim for using Ctrl+W but Visual Studio is still attempting to capture it, any ideas for how I can fix this?

**Comment by ricksladkey** [comment]
@zahillmtu Here is a guide to troubleshooting keyboard problems like that:

https://github.com/jaredpar/VsVim/wiki/Troubleshooting-the-Keyboard
