### ISSUE TITLE
== doesn't update the screen

### ISSUE THREAD

**Issue by philippos** [jaredpar/VsVim#680]
While other indent command combinations like =j  =k  =% immediately change the indent, the == doesn't update the screen until another key is pressed. But then you see that command itself had been executed, the change just hasn't been shown. This problem arises independent of whether you give the == a count or not.

Additionally, after = commands, the cursor is moved one line down. So for example, when you are on an opening brace and press =%, the cursor is in the line after the closing brace after the command instead of the line itself.

Thank you, Philipp (win7, vs10, vsvim 1.1).

**Comment by ricksladkey** [comment]
This works correctly at the head of master and so this issue can be closed.
