### ISSUE TITLE
Undoing "C<Return>{<Return>}<Return>" needs undoing sub actions

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#722]
After the failure repeating `C<Return>{<Return>}<Return>` ([#721](https://github.com/jaredpar/VsVim/issues/721)) I wanted to undo the whole failed action, but I had to undo each "keystroke".

But I have problems repeating this behavior, which should be solved since a few versions.

**Comment by jaredpar** [comment]
Undo is functioning correctly here now.
