### ISSUE TITLE
Would like support for \@=buffer replacments

### ISSUE THREAD

**Issue by PlaidShirtPat** [jaredpar/VsVim#736]
I recently ran into an issue where I was creating a macro that needed to replace text with text that was in a buffer. Looking through the vim documentation, there is the ability to do this with the following command: :s/textToReplace/\@=a/ where a is the buffer that the text is stored in. Would this be a possible feature to implement? It seems to me that it would be relatively trivial to implement, but I am not the developer.

**Comment by ricksladkey** [comment]
This is documented in my recent vim by `:help :s\=`.
