### ISSUE TITLE
Buffers

### ISSUE THREAD

**Issue by prat0088** [jaredpar/VsVim#743]
Support for navigating between tabs would be swell:

:bn
:bp
:b Loa*.cs<tab>

**Comment by wererogue** [comment]
+1 :)

**Comment by austincrft** [comment]
I'd also like to see `:bd` implemented.

I think these should have a higher priority. VS Tabs have more in common with Vim Buffers than Vim Tabs.

**Comment by ricksladkey** [comment]
This is a duplicate of issue #612 and can be closed.

**Comment by nbergen** [comment]
#612 is closed, and this is the tracking issue per https://github.com/jaredpar/VsVim/issues/993#issuecomment-354666604
