### ISSUE TITLE
Could the block caret observe both fore and background color

### ISSUE THREAD

**Issue by philipmat** [jaredpar/VsVim#749]
It seems the setting for "VsVim Block Caret" only observes the Foreground color and uses that as "background" color.
Would it be possible to make it observe both FG and BG colors?

For example, given the following settings:
- VsVim Block Caret : FG = Blue, BG = Yellow and 
- Normal Text : FG = Red, BG = Black

I would like the caret to blink OFF: Red on Black (this happens), ON: Blue on Yellow (this doesn't happen - the caret is Red on Blue).

**Comment by Mpdreamz** [comment]
+1 would love this so that the caret cursor doesn't change depending on what symbol you are over.
