### ISSUE TITLE
few things i like in vim and cannot make it work in vsvim

### ISSUE THREAD

**Issue by yetanotherdeveloper** [jaredpar/VsVim#755]
Hi,

My wish list:

1) "[{" -- going to beginning of block of code we are in,  would be useful element.
2)  ".,/pattern s/^/\/\//gc" - VSVIM claims that it cannot be done eg. adding C++ comment in a each line up to pattern

I really appreciate work you have done, so I my life with Visual Studio + windows is not that dark and sad as it used to be.

All the best

**Comment by jaredpar** [comment]
Looking through some older issues.  Both of these are implemented in the latest release.  Sorry for the delay in updating this.
