### ISSUE TITLE
":normal" command not implemented?

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#780]
I tried to append to bunch of lines `\n\` using the "new" global command:

```
:'<,'>global/[^\\]$/normal A\n\
```

But the result is a parser error in the "command line".

In VIM no problem to be used.

And yes - in VIM no global command needed, `:'<,'>normal A\n\` sufficient for correctly selected lines.

**Comment by jaredpar** [comment]
This is implemented now.
