### ISSUE TITLE
Always jump to beginning of match

### ISSUE THREAD

**Issue by tkellogg** [jaredpar/VsVim#789]
When doing jumping operations like `%`, the cursor always ends up at the beginning of the matched span. However, in VsVim it ends up at the end of the span. This can be inconvenient if you're used to Vim's behavior.

This is partly due to how VsVim implements `CommonOperations.MoveCaretToMotionResult`, however it's much more complicated than just fixing that one member. For instance, `MotionUtil.MatchingToken` returns a large span between the current `caret.Position` and matching token inclusive. There's probably dozens of other places like that. Due to the breaking nature of the fix, this should probably be targeted for v2.0

**Comment by ricksladkey** [comment]
It's quite possible this issue has been resolved, but it's not clear which operations this issue is saying are incorrect. Unless it is expanded with concrete failures, it should probably be closed as already implemented.
