### ISSUE TITLE
Implement (or increase) the 'path' option for gf

### ISSUE THREAD

**Issue by Banger** [jaredpar/VsVim#826]
It seems the 'path' is hardcoded to the local project (or solution) file.  This works for 50% of our header files.  The other 50% are in specific header folders.
Thus, arguably, the default path in VSVim should be a concatenation of the projects' Include Directories, with the local directory as is.

**Comment by garethstokes** [comment]
I think this would be nice as a shortcut to visual studios "go to definition" feature
