### ISSUE TITLE
Support `%` and `#` special characters in the command line

### ISSUE THREAD

**Issue by m0tive** [jaredpar/VsVim#869]
VsVim doesn't replace `%` with the current filename. This really useful when wanting to open the current file in another editor (eg `:! gvim %`).

Filename modifiers like `%:h` and `%:r` would also be good.

http://vimdoc.sourceforge.net/htmldoc/cmdline.html#cmdline-special

**Comment by ricksladkey** [comment]
This feature was implemented in PR #2229.
