### ISSUE TITLE
Support running multiple commands at once

### ISSUE THREAD

**Issue by philipmat** [jaredpar/VsVim#898]
The pipeline is a command separator in Vim that allows one to execute multiple commands on a single line:

```
:vsc Edit.RemoveAndSort | wq
```

Would run the _Edit (-> IntelliSense -> Organize Usings) -> Remove and Sort_ command then write and quite the tab.

**Comment by WillemMali** [comment]
Could this issue get some love?

It'd be really useful for doing multiple text transformations (i.e. multiple replaces) on files, especially when paired with `.` to repeat the command.
