### ISSUE TITLE
Normal mode cursor is black in VS11 dark theme

### ISSUE THREAD

**Issue by tkellogg** [jaredpar/VsVim#935]
I know there are some issues logged related to this, however I think this is a real bug now that VS11 ships with a standard dark theme.

==== Problem

The background is very dark (near black) and the VsVim normal mode cursor is black. This makes it a headache to see the cursor (and dark themes are supposed to be easier on the eyes).

==== Reproduce
1. Install VS11 RC \w VsVim
2. Go to Tools -> Options -> Environment -> General
3. Set `Color Theme` to "Dark"
4. Hit OK and notice cursor is black.
5. Enter insert mode and notice that cursor is near-white
6. Disable VsVim and hit the "Ins" key to go into insert mode and get a similar blocky cursor as VsVim's normal mode. The cursor is near-white, but looks more greyish - quite a nice shade for a dark theme.

==== Possible solution

Perhaps we can reuse the same cursor color setting from VS for VsVim? This would take care of all theme problems. I don't know if that's possible though.

**Comment by jeremyiverson** [comment]
When testing the current stable version on VS2013 and VS2015, I see the color options have moved to Tools - Options - VsVim - Defaults - Item Colors. This works fine on VS 2013, but in VS 2015 the colors are all black and any changes do not stick.

I'll echo the comments about how great the extension is; what a joy!

**Comment by jeremyiverson** [comment]
Here is a quick for anybody else having problems getting colors to save: 

1. Exit Visual Studio
2. In the registry, delete all the items under HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0\FontsAndColors\Cache
3. Restart Visual Studio. The VsVim color options should now be avaiable and working.

There is an old thread discussing this problem, which may be of interest.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/54064c52-727d-4015-af70-c72e44d116a7/vs2012-fontandcolors-text-editor-category-for-language-service-colors?forum=vsx

**Comment by jaredpar** [comment]
@jeremyiverson unfortunately there is a bug in VS 2015 that is affecting all VSIX which have `Font and Color` information.  It's hit F# power tools, R#, viasfora, etc ...  The VS team is aware of the bug and is planning on fixing it for RC (pretty sure, if not RTM).
