### ISSUE TITLE
Using / to search for a term that doesn't exist can result in incorrect file scrolling

### ISSUE THREAD

**Issue by Arkazon** [jaredpar/VsVim#941]
Open a file that doesn't fit on one screen and use / to search for a term, the start of the term needs to exist but not in the visible region so that the search scrolls to make the partial term visible.  When you continue typing so that the search term no longer exists, the view should be returned to it's original position, in vsvim however it is returned such that the cursor is at the top or bottom of the view depending on where the partial term was found in the file.

Example:
- Enable incsearch
- Create a file the doesn't fit in the window
- Add a line like "searchtest" at the bottom (make sure that "searchtest" doesn't appear elsewhere in the file)
- Scroll so that you can't see the "searchtest" line
- Move the cursor so that it is a few lines from the top of the visible part of the file
- Type /searchtestsajkdbasfawf  (end part doesn't matter so long as it doesn't exist)
- View will have been moved so that the cursor is at the top of the screen, in gVim it would have been returned to it's original position with the cursor a few lines from the top (as setup in step 5)

Note: While typing this issue I've noticed that searching for a term that is not visible then hitting escape to cancel the search also results in the same bug.

Note 2: I frequently hit this as searching for arbitrary terms is a good way of clearing the search and thus removing any highlights, every so often I end up with my random key presses finding something that isn't visible and then my view gets moved when I didn't intend it to.

**Comment by jaredpar** [comment]
This should be fixed now.
