### ISSUE TITLE
C-U and C-D should maintain cursor position in window

### ISSUE THREAD

**Issue by philipmat** [jaredpar/VsVim#945]
Unlike C-B and C-F, C-U and C-D are supposed to move the cursor with the content so that it essentially maintains the same position. The [help text](http://vimdoc.sourceforge.net/htmldoc/scroll.html#CTRL-D) is a bit obtuse, but the behavior can be easily observed.

> Scroll window Downwards in the buffer. [...] 
>   The cursor is moved the same number of
>   lines down in the file [...]

To reproduce, choose a multi-page text file. Press M to move the cursor into the middle of the text. Press C-D - in Vim the cursor remains in the middle of the window; in VsVim it stays with the actual line and thus moves to the top of the window.

**Comment by jaredpar** [comment]
Going through some old issues.  This is fixed in the latest release.  Need to make sure `startofline` is not set and it will work.  Sorry for delay in updating this issue.
