### ISSUE TITLE
Implement smart formatting of comments

### ISSUE THREAD

**Issue by hollasch** [jaredpar/VsVim#970]
I suppose that this is a backburner sort of item, but I really miss the smart formatting in Vim. For example, entering text in a // comment will not only wrap the line, but will also prepend the line with the appropriate comment syntax. It's also really handy when changing a paragraph comment, as you can use 'gqap' to reflow and recomment the entire paragraph.

Perhaps a limited solution (like gqap, or just insert-mode wrapping) is feasible.

**Comment by jcredland** [comment]
This would be amazing.
:)

**Comment by ricksladkey** [comment]
The `gq` half of this request was implemented in PR #2274.

**Comment by ricksladkey** [comment]
The other half of this request is the `c`, `r` and `o` options of `formatoptions` (see vim `:help fo-table`).

**Comment by ricksladkey** [comment]
It turns out this is a duplicate of the older issue #573.
