### ISSUE TITLE
Cannot change color of cursor line?

### ISSUE THREAD

**Issue by cliechty** [jaredpar/VsVim#974]
I just updated to 1.3.1.1 the other day and I cannot find a way  to change the color of the cursor line. I like a dark theme and the current cursor line color makes it impossible to use. As you can see from the screen grab bellow you cannot read most of the text on the current line.

![ScreenGrab](http://home.comcast.net/~cliechty/cursorline.png)

Is there a way to change the color?

**Comment by jaredpar** [comment]
Closing as this issue doesn't exist in VS2012 and above and VS2010 support is no longer under active development.
