### ISSUE TITLE
Indenting inside brackets

### ISSUE THREAD

**Issue by dracan** [jaredpar/VsVim#981]
If I do ">i}", then it also indents the brackets. As far as I'm aware, it should indent everything inside the brackets but not the actual brackets.

I'm using VS2012 Professional with VsVim 1.3.1.3.

**Comment by ricksladkey** [comment]
This works correctly at the head of master and so this issue can be closed.

**Comment by dracan** [comment]
Thanks @ricksladkey - I've just tried this in the current released version and this works there too - so will close. I'd forgotten that `>i}` even did that in Vi due to stopping using it due to this issue! Will have to get that back into the habit of using that one again 😄
