### ISSUE TITLE
changing a block selection containing tabulators fails

### ISSUE THREAD

**Issue by MartinL0815** [jaredpar/VsVim#992]
Having ...

```
virtual bool        funcA(...);
virtual bool        funcB(...);
virtual bool        funcC(...);
```

... selecting the whitespace between `bool` and `/func[ABC]/`, which is a tabulator ...
... using `c` to change the selected block by using the `<tab>` key the 3 lines change to ...

```
virtual bool    funcA(...);
virtual bool        funcB(...);
virtual bool        funcC(...);
```

... where the first line contains (as expected) 4 spaces, while second and third line again (unexpectedly) contain a tabulator.

Changing a "table" with lines containing different counts of tabulators with a block selection is currently impossible.

This issue is related to the problem, that repeating an action replacing a tabulator by using the `<tab>` key, causing insertion of 4 spaces, causes the insertion of a tabulator, instead of inserting again 4 spaces.

**Comment by ricksladkey** [comment]
This works correctly at the head of master and so this issue can be closed.
